### ISSUE TITLE
Feature Request: more output data types

### ISSUE THREAD

**Issue by tobsecret** [sdparekh/zUMIs#1]
Would it be possible to add some additional output data types for the expression matrix?
Just outputting them as a csv or tsv would be nice.
Thanks!

**Comment by sdparekh** [comment]
Sure. I added a feature to save full data with three feature types with read counts and UMI counts (total 6 count tables) as a tab delimited text files. However, saving all the tables with the given downsampling list would create many more text files in the output folder. I added an explanation on how to use the object saved in sn.dgecounts.rds to save the count matrix that is required.
