### ISSUE TITLE
Trouble finding the EC2 image for zUMIs

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#10]
Dear zUMIs team,

looks like you are developing a great tool here, which I'd love to use. Unfortunately I can't find the EC2 AMI in the manner described under https://github.com/sdparekh/zUMIs/wiki/Amazon-EC2-instances. Does it still exist?

Best Max

**Comment by cziegenhain** [comment]
Dear Max,

Sorry I recently updated the zUMIs AMI and had accidentally set it to private. It should be available again now.
Let me know if you have any further questions.

Best,
Christoph
