### ISSUE TITLE
No error No resultes

### ISSUE THREAD

**Issue by haiyun0799** [sdparekh/zUMIs#100]
I try to use zUMIs to running the test datasets.
it is finished in seconds, I did not get any error, and I can not see any results ?

 You provided these parameters:
 YAML file:	test.yaml
 zUMIs directory:		/home/hgan/tools/zUMIs/
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   20
 zUMIs version 2.2.3

**Comment by cziegenhain** [comment]
Hi,

We would need to see your exact command, yaml file and any messages to standard out to be able to help you. 

Best,
Christoph

**Comment by haiyun0799** [comment]
[hgan@nodecn210 test_data]$ pwd
/home/hgan/tools/zUMIs/test_data
[hgan@nodecn210 test_data]$ ../zUMIs-master.sh -y test.yaml 
------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------


 You provided these parameters:
 YAML file:	test.yaml
 zUMIs directory:		/research/rgs01/home/clusterHome/hgan/tools/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   20
 zUMIs version 2.2.3 





test.yaml file:

project: test
sequence_files:
  file1:
    name: /research/rgs01/home/clusterHome/hgan/tools/zUMIs/test_data/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /research/rgs01/home/clusterHome/hgan/tools/zUMIs/test_data/cDNAread_HEK.1mio.fq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /research/rgs01/home/clusterHome/hgan/tools/zUMIs/test_data/reference/hg38_chr22/
  GTF_file: /research/rgs01/home/clusterHome/hgan/tools/zUMIs/test_data/reference/GRCh38.84.chr22.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /research/rgs01/home/clusterHome/hgan/tools/zUMIs/test_data/output
num_threads: 1
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
ke_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /research/rgs01/home/clusterHome/hgan/tools/zUMIs

**Comment by cziegenhain** [comment]
Hi,

Your YAML file is malformatted, likely in several places.
First there seem to be unmatched quotes near `additional_STAR_params`. Next, you seem to have duplicate keys like `which_Stage`.

Please fix these and try again. 
Best,
C

**Comment by haiyun0799** [comment]
Thanks, you are right.
the yaml is make by zUMIs-config_shiny.R in windows Rstudio, I think that is the issues.
