### ISSUE TITLE
Memory consumption in fqfilter_v2.pl 

### ISSUE THREAD

**Issue by JesperGrud** [sdparekh/zUMIs#101]
Hi,

I have run into an issue where memory consumption is off the charts for fqfilter_v2.pl. The issue is independent of memory limits in the configuration files. It is a gradual build up over time as the script processes the files, building up by approximately 1Gb of RAM per 20s or so processing time - it seems the script is saving something in memory rather than flushing to disk prior to reaching the specified memory limit. I tried playing around with some parameters for ulimit, but i ended up just breaking the pipe with that. 

Any ideas?

Thanks in advance,
Jesper

**Comment by cziegenhain** [comment]
Hey Jesper,

Yes that is actually a problem I just noted too! We are checking.
Likely you'll be safe when downgrading to version 2.2 https://github.com/sdparekh/zUMIs/releases/tag/zUMIs2.2 

Sorry for the inconvenience, will keep you posted!

Best,
Christoph

**Comment by cziegenhain** [comment]
Hi,

Sorry for the delay. I just pushed a fix that that removed the problematic line.
It should solve your issue, let me know if it works.

Best,
Christoph

**Comment by cziegenhain** [comment]
I guess this worked for you as it did for us, so I am closing this issue.

**Comment by JesperGrud** [comment]
Hi,

We reverted to an older version as you suggusted, which allowed us to run the analysis. I havn't tried your fix yet, but im sure that if it fixes the problem on your end, it also does on mine.

Thanks,
Jesper

Få Outlook til Android<https://aka.ms/ghei36>




On Sun, Mar 3, 2019 at 11:06 AM +0100, "cziegenhain" <notifications@github.com<mailto:notifications@github.com>> wrote:


I guess this worked for you as it did for us, so I am closing this issue.

**Comment by cziegenhain** [comment]
Alright great! Let us know if we can help again in the future.
