### ISSUE TITLE
It creates so many temporary files by pigz which easily exceed my cluster quota.

### ISSUE THREAD

**Issue by AlfredShawn** [sdparekh/zUMIs#107]
Hi,

I am testing to run zUMIs for my scRNAseq fastq files (32X2Gb, 10X Genome). Everything looks good when running. However, during the running, it generates millions of temporary small fastq.gz files under zUMIs_output/.tmpMerge folder which cause the exceed of quota. It's not an efficient way by write/read so many files for merging. Is it caused by some inappropriate setting in yaml file? (like num_threads: 16; mem_limit: 200)

Thanks,

Yu

**Comment by cziegenhain** [comment]
Hi Yu,

If you could share the YAML file you have used that would be useful for us to check.
In principle using 16 threads should create 16 temporary files for parallel filtering.

I am not sure what you mean by 32X2Gb fastq files, could you explain that?

**Comment by AlfredShawn** [comment]
Hi Cziegenhain,

It means paired end fastq files, each single one is 32Gb size.

I think the reason could be the mem_limit setting. I should use 200G rather than 200. Is that right?

Yu

**Comment by AlfredShawn** [comment]
Sorry for forgetting the yaml file.

Yu

From: Wang, Yu [mailto:yu.wang.2@vumc.org]
Sent: Thursday, March 7, 2019 10:25 AM
To: sdparekh/zUMIs <reply@reply.github.com>; sdparekh/zUMIs <zUMIs@noreply.github.com>
Cc: Yu Wang <yu.wang.2@vanderbilt.edu>; Author <author@noreply.github.com>
Subject: RE: [sdparekh/zUMIs] It creates so many temporary files by pigz which easily exceed my cluster quota. (#107)

Hi Cziegenhain,

It means paired end fastq files, each single one is 32Gb size.

I think the reason could be the mem_limit setting. I should use 200G rather than 200. Is that right?

Yu

**Comment by cziegenhain** [comment]
Hi Yu,

No the memory setting as an integer should be correct.
The YAML file didnt make it, try uploading it with a .txt file ending (GitHub is a bit particular there)

**Comment by AlfredShawn** [comment]
Hi Cziegenhain,

I changed the .yaml to .txt and set mem_limit as null. It still doesn't work. Should I set "base_definition"? I keep it null to let zUMIs detect BC and transcripts length by itself. 

Yu

**Comment by cziegenhain** [comment]
Hi Yu,

You were supposed to upload the yaml file with a .txt ending here in GitHub so I can see what you are doing.
base_definition is not optional but mandatory. How do you suppose zUMIs can guess where your barcode or cDNA is located?

**Comment by AlfredShawn** [comment]
I thought you can open it in attachment since I reply you by email. Sorry for the misleading. But I set the base_definition based on my fastq files. It still act the same way. Here is the yaml file.
[2853SR1.yaml.txt](https://github.com/sdparekh/zUMIs/files/2943194/2853SR1.yaml.txt)

**Comment by cziegenhain** [comment]
Hi,

It seems like your YAML file is quite malformatted. You have many odd indentations and line breaks that I would expect to disturb the run.
Check back with the [provided example](https://github.com/sdparekh/zUMIs/blob/master/zUMIs.yaml) or use the [Shiny application](http://shiny.bio.lmu.de:3838/zUMIs-config/) we are providing!
