### ISSUE TITLE
counting error of SPLIT-seq

### ISSUE THREAD

**Issue by dingxm** [sdparekh/zUMIs#108]
Thanks for generate the great tool. We are using zUMI for split-seq analysis.
It has been successful in our small data set( 10M reads). 
This time we used another medium size data set(50M reads). we got below error,
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
[bam_sort_core] merging from 0 files and 4 in-memory blocks...
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/Data_analysis/CORE_Analysis/sc_seq/new_seq/mm10/zUMIs_output/expression/split_test_mm10.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

below is the yaml and log file.

project: split_hg
sequence_files:
  file1:
    name: /data/Data_analysis/CORE_Analysis/sc_seq/new_seq/pooling38-GTAGTCGT_HY7GCCCXY_L5_1.fq.gz
    base_definition: cDNA(1-63)
  file2:
    name: /data/Data_analysis/CORE_Analysis/sc_seq/new_seq/pooling38-GTAGTCGT_HY7GCCCXY_L5_2.fq.gz
    base_definition:
      - UMI(1-10)
      - BC(11-18,49-56,87-94)
reference:
  STAR_index: /data/Data_analysis/ref/star_hg38
  GTF_file: /data/Data_analysis/ref/Homo_sapiens/UCSC/hg38/Annotation/Archives/archive-2015-08-14-08-18-15/Genes/genes.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/Data_analysis/CORE_Analysis/sc_seq/new_seq
num_threads: 8
mem_limit: 50
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 300
counting_opts:
  introns: yes
  downsampling: '10000,20000,30000,40000,50000,60000,70000,80000,90000,100000'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering

samtools_exec: /home/lixadmin/local/bin/samtools
pigz_exec: /data/tools/pigz-2.4/pigz
STAR_exec: /data/tools/STAR-2.5.4b/bin/Linux_x86_64/STAR
zUMIs_directory: /data/tools/zUMIs
read_layout: SE

log files

You provided these parameters:
 YAML file:	new_seq/yaml_hs
 zUMIs directory:		/data/tools/zUMIs
 STAR executable		/data/tools/STAR-2.5.4b/bin/Linux_x86_64/STAR
 samtools executable		/home/lixadmin/local/bin/samtools
 pigz executable		/data/tools/pigz-2.4/pigz
 Rscript executable		/usr/bin/Rscript
 RAM limit:   50
 zUMIs version 2.3.0b 

Filtering...
Mapping...
Mar 06 22:02:20 ..... started STAR run
Mar 06 22:02:21 ..... loading genome
Mar 06 22:03:22 ..... processing annotations GTF
Mar 06 22:03:27 ..... inserting junctions into the genome indices
Mar 06 22:05:38 ..... started mapping
Mar 06 22:13:59 ..... finished successfully
Counting...
[1] "2019-03-06 22:14:07 PST"
[1] "82852 barcodes detected."
[1] " reads were assigned to barcodes that do not correspond to intact cells."
[1] "2.25e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/data/Data_analysis/ref/Homo_sapiens/UCSC/hg38/Annotation/Archives/archive-2015-08-14-08-18-15/Genes/genes.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S split_hg.filtered.tagged.Aligned.out.bam       ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid36171 ...         ||
||    Features : 268548                                                       ||
||    Meta-features : 20728                                                   ||
||    Chromosomes/contigs : 255                                               ||
||                                                                            ||
|| Process BAM file split_hg.filtered.tagged.Aligned.out.bam...               ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 46943167                                             ||
||    Successfully assigned alignments : 5819827 (12.4%)                      ||
||    Running time : 0.47 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.2

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S split_hg.filtered.tagged.Aligned.out.bam       ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid36171 ...         ||
||    Features : 258411                                                       ||
||    Meta-features : 16041                                                   ||
||    Chromosomes/contigs : 244                                               ||
||                                                                            ||
|| Process BAM file split_hg.filtered.tagged.Aligned.out.bam...               ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 46943167                                             ||
||    Successfully assigned alignments : 9982705 (21.3%)                      ||
||    Running time : 0.47 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Warning! None of the barcodes had enough reads for the following requested downsampling:"
[1] "30000"  "40000"  "50000"  "60000"  "70000"  "80000"  "90000"  "100000"
[1] "Here are the detected subsampling options:"
[1] "10000" "20000"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 82852 barcodes in this chunk..."
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-03-06 22:29:43 PST"

**Comment by cziegenhain** [comment]
Hey,

Sorry for the slow answer and that you are running into problems.
I don't presume that the increased number of reads is the issue here, as 50 M is still relatively low (I have tested zUMIs up to ~4 billion reads).

On the first glance it also doesn't seem like you have done anything wrong here, I suspect something odd happens with this specific dataset that we havent handled in zUMIs. The easiest for troubleshooting would be if you could share your data with us, if possible (eg. Google Drive, Dropbox, etc). Either your input fastq or the `.BCstats.txt` + `.filtered.tagged.Aligned.out.bam` would be great.

Best,
Christoph

**Comment by dingxm** [comment]
Sorry for the delay of response.  The problem is caused by the subsampling. when using "20000" for subsampling, actually no barcode has more than 20000 reads. 
So we got this error assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Changed the subsampling options will solve the problem.

**Comment by cziegenhain** [comment]
Hi,
Thanks for the update and good to hear that it works. 
This is odd because this specific case is handled explicitly in zUMIs. As you can see in your log it had also correctly discarded the other downsampling depths higher than 20000.

In order for us to make this more robust, would you mind still sharing your *.BCstats.txt with us?

Anyways I'll close this issue now. 

Best,
Christoph
