### ISSUE TITLE
[question] 10x cDNA read length

### ISSUE THREAD

**Issue by gokceneraslan** [sdparekh/zUMIs#109]
On the wiki page cDNA range for 10x files is given as (1-97). I was wondering why it's 97 and not 98, given that read length is typically 98nt.

**Comment by cziegenhain** [comment]
Hi, 

There is no particular reason - I would just use however many cycles I can squeeze out of a particular sequencing kit. All read lengths you would have should be supported equally in zUMIs  :)

**Comment by cziegenhain** [comment]
Closing here, but let me know if you have further questions!

**Comment by gokceneraslan** [comment]
Thanks!
