### ISSUE TITLE
Error: length(values) == length(cluster) is not TRUE

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#11]
Dear zUMIs team,

I am testing your pipeline using your EC2 AMI. It works well with the example data set. However when using my own fastq files from a DroNc-seq run it stops with the following message:

> Initialising 16 core cluster.
> Error: length(values) == length(cluster) is not TRUE
> In addition: Warning messages:
> 1: Removed 1 rows containing missing values (geom_vline). 
> 2: group_indices_.grouped_df ignores extra arguments 
> Execution halted

I am running the process on a 16 core machine and still got the same message when setting the p parameter of the pipeline to fewer cores. Also as a sidenote: I had to use absolute paths for the pipeline to function up to this point, which I thought was a resolved issue. So maybe the pipeline version in the AMI is not up to date?

I used the following command to run the pipeline:

`nohup bash /home/ec2-user/zUMIs/zUMIs-master.sh -f /home/ec2-user/mynuclei/FASTQ/HHDroNc01_R1.fastq.gz -r /home/ec2-user/mynuclei/FASTQ/HHDroNc01_R2.fastq.gz -c 1-12 -m 13-20 -l 76 -g /home/ec2-user/reference_genomes/mm10/STAR -a /home/ec2-user/reference_genomes/mm10/mm10.gtf -n ### -p 16 -o /home/ec2-user/mynuclei/mm10.alignout > /home/ec2-user/mynuclei/Output.txt &`

Please find the complete log file attached and thank you for your help.
[log.txt](https://github.com/sdparekh/zUMIs/files/1498300/log.txt)

**Comment by cziegenhain** [comment]
Hey Max,

indeed, zUMIs on the AMI was the v0.0.2 release, but didn't include some of the more recent bugfixes.

I created an updated AMI (ami-7e980d04).

If you want the newest scripts in your already set up instance, just run
`git clone https://github.com/sdparekh/zUMIs.git`

Also, please avoid using # or other special characters in your sample name (-n).

Let us know if you have any further questions.

Best,
Christoph

**Comment by MaxKman** [comment]
Hi Christoph, 
I only used the ### to censor the name of my experiment in the logfile. Sorry if this was unclear. I will try to run the updated pipeline. Was the issue I described a known problem in the past?

Best Max

**Comment by cziegenhain** [comment]
Ah okay no problem ;-) just wanted to make sure you don't run into issues with the #.
The issue you posted was a bug related to our estimation of cell barcodes that could crash depending on the distribution of reads among cell barcodes and should be fine with the most current version.
Best,
Christoph
