### ISSUE TITLE
MARS-seq / barcodes in fastq read header

### ISSUE THREAD

**Issue by kritikakarri** [sdparekh/zUMIs#110]
I have mars-seq single end samples that have already be processed in the following way: "Sequences with RMT of low quality (defined as RMT with minimum Phred score of less than 27) were filtered out. Pool-barcode and well-barcode-RMT were extracted from the first and second end of the read (respectively) and concatenated to the fastq header, delimited by a underscore i.e. POOL_BARCODE_WELL_BARCODE_RMT while "NNNNNN" was used as a place holders if plate barcode was not used. Reads were separated by POOL_BARCODE_WELL_BARCODE header data, allowing 1 sequencing error. This process created a single fastq file for each source well. the R2 sequences, used solely for barcode extraction, were not included." How can I  modify the input parameters in  zUMI  in order to process these single end fastq files and get a count tables?

**Comment by kritikakarri** [comment]
I have mars-seq single end samples that have already be processed in the following way: "Sequences with RMT of low quality (defined as RMT with minimum Phred score of less than 27) were filtered out. Pool-barcode and well-barcode-RMT were extracted from the first and second end of the read (respectively) and concatenated to the fastq header, delimited by a underscore i.e. POOL_BARCODE_WELL_BARCODE_RMT while "NNNNNN" was used as a place holders if plate barcode was not used. Reads were separated by POOL_BARCODE_WELL_BARCODE header data, allowing 1 sequencing error. This process created a single fastq file for each source well. the R2 sequences, used solely for barcode extraction, were not included." How can I modify the input parameters in zUMI in order to process these single end fastq files and get a count tables?

**Comment by JLTrincado** [comment]
Hi,

I have similar question. How did you solve this?

Thanks for your help.

**Comment by JLTrincado** [comment]
I see this was solved in here: #111
