### ISSUE TITLE
no sort.sam file

### ISSUE THREAD

**Issue by hmassalha** [sdparekh/zUMIs#112]
Hi all, 
I am using the zUMIs to map a bulk experiment prepared using mcSCRUBseq protocol. I have 3 pools (8 samples each). 2 pools worked fine and I got the count files. However, for some reason the 3rd pool is not finishing the process, even though when I looked in the 'Log.out' file, I found 'ALL DONE!' at the end of the file. when I looked at the type of the files that were generated at the end of the processing, I found out that there is no SAM file!

The server output says that there is a problem in opening some files which is weird, the first two pools worked fine. Any help/hint please. 

Here is the output file:
Resource usage summary:

    CPU time :                                   9329.00 sec.
    Max Memory :                                 28822 MB
    Average Memory :                             13247.33 MB
    Total Requested Memory :                     180000.00 MB
    Delta Memory :                               151178.00 MB
    Max Swap :                                   -
    Max Processes :                              7
    Max Threads :                                14
    Run time :                                   8842 sec.
    Turnaround time :                            8847 sec.

The output (if any) follows:

Your jobs will run on this machine. 

Make sure you have more than 25G RAM and 1 processors available. 

Your jobs will be started from filtering. 

 You provided these parameters:
 SLURM workload manager: no
 Summary Stats to produce:       yes
 Start the pipeline from:        filtering
 A custom mapped BAM:            NA
 Custom filtered FASTQ:          no
 Barcode read:                   /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AHT525BGX9_190326_telo_stroma_LGK_bulk_output/telo_stroma_lgk_bulk/telo_stroma_lgk_bulk_p3_S3_R1_001.fastq.gz
 cDNA read:                      /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AHT525BGX9_190326_telo_stroma_LGK_bulk_output/telo_stroma_lgk_bulk/telo_stroma_lgk_bulk_p3_S3_R2_001.fastq.gz
 Study/sample name:              telo_stroma_lgk_bulk_p3
 Output directory:               /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AHT525BGX9_190326_telo_stroma_LGK_bulk_output/telo_stroma_lgk_bulk/zUMI_strandS1
 Cell/sample barcode range:      1-6
 UMI barcode range:              7-16
 Retain cell with >=N reads:     100
 Genome directory:               /home/labs/shalev/NGS/indexes/GRCm38.84_STAR_zumi/
 GTF annotation file:            /home/labs/shalev/NGS/indexes/GRCm38.84/Mus_musculus.GRCm38.84.gtf
 Number of processors:           1
 Read length:                    66
 Strandedness:                   1
 Cell barcode Phred:             20
 UMI barcode Phred:              20
 # bases below phred in CellBC:  1
 # bases below phred in UMI:     1
 Hamming Distance (UMI): 0
 Hamming Distance (CellBC):      1
 Plate Barcode Read:      NA
 Plate Barcode range:     NA
 Barcodes:                       /home/labs/shalev/hassanm/.Documents/temp_OD/indexes/scrb_barcode_32.txt
 zUMIs directory:                /home/labs/shalev/hassanm/NGS/zUMI/zUMI006
 STAR executable         STAR
 samtools executable             samtools
 pigz executable         pigz
 Rscript executable              Rscript
 Additional STAR parameters:     
 STRT-seq data:                  no
 InDrops data:                   no
 Library read for InDrops:       NA
 Barcode read2(STRT-seq):        NA
 Barcode read2 range(STRT-seq):  0-0
 Bases(G) to trim(STRT-seq):     3
 Subsampling reads:              0 

 zUMIs version 0.0.6c 

Raw reads: 101007904 
Filtered reads: 71507942 

Make sure you have approximately 25059 Mb RAM availableMar 28 09:37:06 ..... started STAR run
Mar 28 09:37:06 ..... loading genome
Mar 28 09:37:29 ..... processing annotations GTF
Mar 28 09:37:36 ..... inserting junctions into the genome indices
Mar 28 09:41:23 ..... started 1st pass mapping
Mar 28 10:11:11 ..... finished 1st pass mapping
Mar 28 10:11:11 ..... inserting junctions into the genome indices
Mar 28 10:12:35 ..... started mapping
Mar 28 10:47:51 ..... finished successfully
[bam_sort_core] merging from 7 files and 1 in-memory blocks...
[E::hts_open_format] Failed to open file tmp.telo_stroma_lgk_bulk_p3.0000.bam
samtools sort: failed to create temporary file "tmp.telo_stroma_lgk_bulk_p3.0000.bam": File exists
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2019-03-28 11:12:23 IST"
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2019-03-28 11:12:32 IST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2019-03-28 11:13:21 IST"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/labs/shalev/hassanm/NGS/190326_NB551 ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : stranded                                         ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid166373 ...      ||
||    Features : 225068                                                       ||
||    Meta-features : 25257                                                   ||
||    Chromosomes/contigs : 38                                                ||
||                                                                            ||
|| Process BAM file /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AH ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 71507942                                                  ||
||    Successfully assigned reads : 7054029 (9.9%)                            ||
||    Running time : 1.97 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/labs/shalev/hassanm/NGS/190326_NB551 ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : stranded                                         ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid166373 ...      ||
||    Features : 710016                                                       ||
||    Meta-features : 42143                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AH ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 71507942                                                  ||
||    Successfully assigned reads : 38438831 (53.8%)                          ||
||    Running time : 2.05 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

Read 8.2% of 71507942 rows
Read 32.8% of 71507942 rows
Read 58.8% of 71507942 rows
Read 84.7% of 71507942 rows
Read 71507942 rows and 1 (of 1) columns from 0.773 GB file in 00:00:06
cut: /home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AHT525BGX9_190326_telo_stroma_LGK_bulk_output/telo_stroma_lgk_bulk/zUMI_strandS1/telo_stroma_lgk_bulk_p3.barcodelist.filtered.sort.sam: No such file or directory
Error in data.table::fread(paste("cut -f10 ", ubamfile, sep = ""), quote = "",  : 
  File is empty: /dev/shm/file289e5839c7e2
Calls: makeGEprofile -> <Anonymous>
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2019-03-28 11:17:41 IST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/labs/shalev/hassanm/NGS/190326_NB551168_0301_AHT525BGX9_190326_telo_stroma_LGK_bulk_output/telo_stroma_lgk_bulk/zUMI_strandS1/zUMIs_output/expression/telo_stroma_lgk_bulk_p3.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

Thanks, HM

**Comment by cziegenhain** [comment]
Hey,

In general I'd like to say it's a bit hard for us to keep supporting old versions of zUMIs.
What i see on first glance is that of course your samtools sort has a problem, and its visible in the log:
`samtools sort: failed to create temporary file "tmp.telo_stroma_lgk_bulk_p3.0000.bam": File exists`
So that means a temprary file with that name existed already and that lead samtools sort to fail. are you running several things in the same folder etc? In any case just removing this file and starting clean should be fine ideally.

Best,
Christoph

**Comment by hmassalha** [comment]
Hi Christoph, 
Thanks for your quick reply. I just asked the zUMIs to write the output in a new directory. Now it is working perfectly. 

I would like to move to the new version of zUMIs, but I didn't manage to run it using the YAML file. do you have a working example that I can try? 

Thanks a lot,
HM

**Comment by cziegenhain** [comment]
Hey,
Excellent that it worked out in the end!
Here is an example YAML file:
https://github.com/sdparekh/zUMIs/blob/master/ExampleData/Example.yaml

I'm closing for now but feel free to reply if you need another hint for the YAML files. 
Best
C
