### ISSUE TITLE
Yes/No in YAML file

### ISSUE THREAD

**Issue by tbeaux18** [sdparekh/zUMIs#116]
Hello,

I am working on automating a pipeline that will build the YAML file for kicking off the pipeline, however, I am having many issues with the yes/no dumping since YAML is super tricky with how it handles boolean operators such as yes/no/true/false/on/off. Does your pipeline still operate well with just True/False for the values or does it absolutely need the plain scalar yes/no values? 

Thanks. 

[EDIT]

Somehow I was able to find the correct code to change the global Resolver object for PyYAML, so now I can get yes/no to dump as a plain scalar.

However, just for reference, I would like to know if True/False would still be acceptable since most languages interpret yes/no in that way.

**Comment by tbeaux18** [comment]
Greetings again,

Somehow I was able to find the correct code to change the global Resolver object for PyYAML, so now I can get yes/no to dump as a plain scalar. 

However, just for reference, I would like to know if True/False would still be acceptable since most languages interpret yes/no in that way.

**Comment by cziegenhain** [comment]
Hi!

Sounds nice to automate the yaml creation! 
I am fairly confident that yes/true no/false work synonymous in zUMIs. The only setting that would really want "yes"  as such is the switch for creating statistics output. If you encounter a problem there let us know and we can try to make that more robust too.

Best,
Christoph

**Comment by tbeaux18** [comment]
Great thank you very much! I can close this issue. 

Thanks again!
Tim
