### ISSUE TITLE
Error on yaml file of the zUMIs 2.4.0

### ISSUE THREAD

**Issue by yxiao832** [sdparekh/zUMIs#117]
Hi zUMIs, 

I previously used zUMIs older version which run well. Thank you very much!

Now I'd like to add the hamming distance 1 to collapse BC, but I run into some issue in the newest version 2.4.0. I got error for yaml file and error in the log file says "Please check barcode list file path".

Does this mean I have to add whitelist for my barcode?

Here is my Yaml file 
project: zUMI_splitseq4102019
sequence_files:
  file1:
    name: /home/yxiao832/04062019Splitseq/452019Splitseq_R1_001.fq.gz
    base_definition: cDNA(1-66)
  file2:
    name: /home/yxiao832/04062019Splitseq/452019Splitseq_R2_001.fq.gz
    base_definition:
    - BC(11-18,49-56,87-93)
    - UMI(1-10)
reference:
  STAR_index: /home/yxiao832/index/STAR_index/mm10_STARindex_splitseq_NOGTF_ensemble
  GTF_file: /home/yxiao832/index/Ensemble_mm10/Mus_musculus.GRCm38.94.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/yxiao832/04062019Splitseq
num_threads: 12
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 10
  UMI_filter:
    num_bases: 1
    phred: 10
barcodes:
  barcode_num: ~
  barcode_file: ''
  automatic: 'yes'
  BarcodeBinning: 1
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

Thanks a lot!
Yang

**Comment by cziegenhain** [comment]
Hey Yang,

I assume you made the YAML file with the Rshiny application?
In that case sorry for the error, the barcode selection options didnt really get parsed as I wanted.

You don't need any barcode reference if you don't want to give it.
Please change the barcode related lines in the YAML file as follows:

barcode_file: ~
automatic: yes

Earlier today I updated the shiny application here on GitHub, hope that these issues don't reoccur then.

Best,
Christoph

**Comment by yxiao832** [comment]
Hi Christoph,
The new YAML file worked!
Thanks a lot!
Yang

**Comment by cziegenhain** [comment]
Thats nice to hear! 
Best,
C

**Comment by mbassalbioinformatics** [comment]
I just used the Shiny app and the same error occurred.  Manually updating the yaml lets things progress though.

**Comment by mbassalbioinformatics** [comment]
> Thats nice to hear!
> Best,
> C

I just used the Shiny app and the same error occurred.  Manually updating the yaml lets things progress though.
