### ISSUE TITLE
descriptive stats error 

### ISSUE THREAD

**Issue by hmassalha** [sdparekh/zUMIs#119]
Hi all, 
After I managed to run successfully the latest version of the zUMIs, I found the following lines in the output file: 

`
[1] "I am loading useful packages for plotting..."
[1] "2019-04-11 16:23:51 IDT"
Error in .guessPackageName(env) : 
  none of the objects in the source code could be found:  need to attach or specify the package
Calls: suppressMessages ... withCallingHandlers -> insertSource -> .guessPackageName
Execution halted
Thu Apr 11 16:23:53 IDT 2019
`

What would be missing to generated the stat file? (I am running mcSCRBseq data of bulk samples)

Thanks, HM

**Comment by cziegenhain** [comment]
You must be lacking a dependency package.
Please check:
https://github.com/sdparekh/zUMIs/wiki/Installation#r

**Comment by hmassalha** [comment]
Thanks for the quick reply, I will update when I have the results of the next run. Thanks, HM
