### ISSUE TITLE
data table error

### ISSUE THREAD

**Issue by drhee** [sdparekh/zUMIs#122]
Hi, I'm running indrops v3 data. Have been getting the following error (attached). Didn't look like anyone else had posted about this specific issue.

Also wondering what I should expect in the output when I run data with multiple library barcodes (does it separate out the libraries?). Seems like the library barcodes are showing up in the kept barcodes file and in the downsampling thresholds graph.

Thanks.

[39212968err.txt](https://github.com/sdparekh/zUMIs/files/3098413/39212968err.txt)

**Comment by cziegenhain** [comment]
Hi,

could you please send us your YAML, full output log (stderror & stdout) as well as the versions of dependencies you use (especially, R, STAR, Rsubread & data.table)

Best,
Christoph

**Comment by drhee** [comment]
Hi Christoph,

Thanks for taking a look. Here are the output files and info:

data.table 1.11.5
Rsubread 1.32.4
R 3.5.1-extra
STAR 2.7.0f
pigz 2.3.4
samtools 1.9


 



Best,

Dave

**Comment by cziegenhain** [comment]
Hi Dave,

your software seems up to date which is good, but I don't see any files attached.

Also for your question regarding library barcodes:
if you have defined both the cellbarcode and library barcode in your YAML, the final cell barcode used in zUMIs will be the unique combinations of that. Thus, your output should contain all cells correctly.

**Comment by drhee** [comment]
Not sure why they didn't attach before - 
[39266893err.txt](https://github.com/sdparekh/zUMIs/files/3104263/39266893err.txt)
[DKO1_April19yaml.txt](https://github.com/sdparekh/zUMIs/files/3104264/DKO1_April19yaml.txt)
[39266893out.txt](https://github.com/sdparekh/zUMIs/files/3104265/39266893out.txt)

**Comment by cziegenhain** [comment]
Hi Dave,

that looks great. Can you confirm that you get all expected output except the statistics output?
I see the problematic line in the code; there is an easy fix:
Can you please upgrade to at least v1.11.6 for data.table? 
I'll also push a little update later that makes this more agnostic to data.table version.

Thanks and best,
Christoph

**Comment by drhee** [comment]
Hi Christoph,

Great. Thanks for the quick response and the help.

Yes, I believe I'm getting everything out that should be there. I'll give it a go.

Best,

Dave

**Comment by drhee** [comment]
Everything looks good. Thanks again.

**Comment by cziegenhain** [comment]
Good to hear, thanks for the update!

**Comment by drhee** [comment]
Hi Christoph,

I updated to the most recent version (also updated data.table) and ran a larger dataset - ran into the following error:

Error in gforce(thisEnv, jsub, o__, f__, len__, irows) : 
  Internal error: Failed to allocate counts or TMP when assigning g in gforce
Calls: sumstatBAM -> [ -> [.data.table -> gforce
Execution halted

Everything is identical as before. Added the out and err below.

Thanks,

Dave

[39637778out.txt](https://github.com/sdparekh/zUMIs/files/3127667/39637778out.txt)
[39637778err.txt](https://github.com/sdparekh/zUMIs/files/3127668/39637778err.txt)

**Comment by cziegenhain** [comment]
Hi Dave,

I have encountered this too with a very big datasets, looking into this since yesterday. will keep you posted!

**Comment by cziegenhain** [comment]
As a sidenote: If you set a smaller RAM limit, zUMIs will try to break up the processing into several chunks of reads. That could prevent this data.table exception! Feel free to give it a go until I have coded a fix.

**Comment by cziegenhain** [comment]
Hi Dave,
I just pushed a new version of zUMIs to GitHub! 
Should take care of the error that you are seeing.
Best,
C

**Comment by drhee** [comment]
Great, I’ll give it a go. Thanks!

**Comment by drhee** [comment]
Hi Again,

Was wondering if you've ever seen this error?

"samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory"

Thanks,

Dave

**Comment by sdparekh** [comment]
Hi Dave,

I am not sure if you are using bioconda. It seems to have dependency issues. I could redirect you to this https://github.com/bioconda/bioconda-recipes/issues/12100

let me know if this does not help!

Best,
Swati

**Comment by cziegenhain** [comment]
Hi Dave,

If you're not on bioconda, I had a similar issue in samtools recently after updating some curl & libssh packages on my Ubuntu installation. Recompiling samtools fixed that for me!

Best,
C

**Comment by drhee** [comment]
Hi Swati and Christoph,
Thanks for the responses - I guess some things were updated on our cluster, which was the source of the problem. 

Best,

Dave
