### ISSUE TITLE
stops after alignment - “dgTMatrix” issue

### ISSUE THREAD

**Issue by cstrlln** [sdparekh/zUMIs#124]
Hi 
I run the example data without problem, but now while trying to run some of my data right after the alignment I get this:

\\===================== http://subread.sourceforge.net/ ======================//

sh: line 1:  3900 Killed                  samtools sort -n -O 'BAM' -@ 4 -m 6G -o $i $i.tmp
sh: line 1:  3901 Killed                  samtools sort -n -O 'BAM' -@ 4 -m 6G -o $i $i.tmp
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 4868 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted

**To Reproduce**
Thu May 16 23:09:58 EDT 2019
Filtering...
Thu May 16 23:53:34 EDT 2019
Mapping...
Fri May 17 00:34:00 EDT 2019
Counting...
[1] "2019-05-17 00:34:10 EDT"
[1] "4868 barcodes detected."
[1] "21278960 reads were assigned to barcodes that do not correspond to intact cells."
[1] "2e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/dir/FEB26_POOL1_KO_317_SI-GA-D1/KO_317_zUMIs.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S KO_317_zUMIs.filtered.tagged.Aligned.out.bam   ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid3517 ...          ||
||    Features : 435967                                                       ||
||    Meta-features : 47605                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file KO_317_zUMIs.filtered.tagged.Aligned.out.bam...           ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 127877442                                            ||
||    Successfully assigned alignments : 79290987 (62.0%)                     ||
||    Running time : 1.89 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S KO_317_zUMIs.filtered.tagged.Aligned.out.bam   ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid3517 ...          ||
||    Features : 238562                                                       ||
||    Meta-features : 28461                                                   ||
||    Chromosomes/contigs : 38                                                ||
||                                                                            ||
|| Process BAM file KO_317_zUMIs.filtered.tagged.Aligned.out.bam...           ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 127877442                                            ||
||    Successfully assigned alignments : 33728788 (26.4%)                     ||
||    Running time : 1.80 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

sh: line 1:  3900 Killed                  samtools sort -n -O 'BAM' -@ 4 -m 6G -o $i $i.tmp
sh: line 1:  3901 Killed                  samtools sort -n -O 'BAM' -@ 4 -m 6G -o $i $i.tmp
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 4868 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Fri May 17 00:40:56 EDT 2019
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-05-17 00:40:56 EDT"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dir/FEB26_POOL1_KO_317_SI-GA-D1/zUMIs_output/expression/KO_317_zUMIs.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Fri May 17 00:41:17 EDT 2019

**Desktop (please complete the following information):**
I'm runnin on a server with CentOS7.

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

Looks like samtools sort gets terminated.
Have you made sure that you have enough RAM available and there is enough disk space for samtools to write its temporary files?

**Comment by cstrlln** [comment]
Thanks for the fast response! I'll give it a try, how much RAM do you recommend?

**Comment by cziegenhain** [comment]
Depends on your server configuration & load! I'd say give at most half of the physical memory to avoid clashes with other processes.

**Comment by cstrlln** [comment]
It worked now! thanks for the advice.
Offtopic, do you have a specific way of reading the output into a single cell  experiment object?

**Comment by cziegenhain** [comment]
Excellent! 
I'd just read the zUMIs RDS file and create a single cell experiment object from the matrix you'd like to use (eg intron+exon). 
https://bioconductor.org/packages/devel/bioc/vignettes/SingleCellExperiment/inst/doc/intro.html
`sce <- SingleCellExperiment(assays = list(counts = counts))`
