### ISSUE TITLE
Did zUMIs finish properly? gives "notch went outside hinges. Try setting notch=FALSE" message and terminates

### ISSUE THREAD

**Issue by tom-snir** [sdparekh/zUMIs#13]
I am using the following syntex to run zUMIs:

bash $p/zUMIs-master.sh -f /private/zel/tom/mike3/LIB030951_GEN00110820_S1_L001_R1.fastq \
-r /private/zel/tom/mike3/LIB030951_GEN00110820_S1_L001_R2.fastq -p 16 -c 1-12 -m 13-20 -l 125 -n 30951 \
-g /private/zel/tom/STAR/GRCh38_Index_124_OvHng/ -a /private/zel/tom/STAR/gencode.v27.chr_patch_hapl_scaff.basic.annotation.gtf 

the run starts fine, the output up until I get the message I mentioned in the title is:

Make sure you have more than 29G RAM and 16 processors available.

Your jobs will be started from filtering.

 You provided these parameters:
 SLURM workload manager:        no
 Summary Stats to produce:      yes
 Start the pipeline from:       filtering
 Barcode read:                  /private/zel/tom/mike3/LIB030951_GEN00110820_S1_L001_R1.fastq
 cDNA read:                     /private/zel/tom/mike3/LIB030951_GEN00110820_S1_L001_R2.fastq
 Study/sample name:             30951
 Output directory:              /home/zel/tom/mike3
 Cell/sample barcode range:     1-12
 UMI barcode range:             13-20
 Genome directory:              /private/zel/tom/STAR/GRCh38_Index_124_OvHng/
 GTF annotation file:           /private/zel/tom/STAR/gencode.v27.chr_patch_hapl_scaff.basic.annotation.gtf
 Number of processors:          16
 Read length:                   125
 Strandedness:                  0
 Cell barcode Phred:            20
 UMI barcode Phred:             20
 # bases below phred in CellBC: 1
 # bases below phred in UMI:    1
 Barcodes:                      NA
 zUMIs directory:               /private/zel/tom/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 Additional STAR parameters:
 STRT-seq data:                 no
 Barcode read2(STRT-seq):       NA
 Barcode read2 range(STRT-seq): 0-0
 Bases(G) to trim(STRT-seq):    3
 Subsampling reads:             0

Raw reads: 158045
Filtered reads: 151739

Dec 07 12:09:06 ..... started STAR run
Dec 07 12:09:06 ..... loading genome
Dec 07 12:11:36 ..... processing annotations GTF
Dec 07 12:11:45 ..... inserting junctions into the genome indices
Dec 07 12:13:38 ..... started 1st pass mapping
Dec 07 12:13:54 ..... finished 1st pass mapping
Dec 07 12:13:55 ..... inserting junctions into the genome indices
Dec 07 12:16:13 ..... started mapping
Dec 07 12:16:57 ..... finished successfully
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-12-07 12:16:58 IST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-12-07 12:17:04 IST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
There were 17 warnings (use warnings() to see them)
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2017-12-07 12:18:12 IST"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/zel/tom/mike3/30951.aligned.sorted.b ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid4531 ...        ||
||    Features : 277399                                                       ||
||    Meta-features : 32340                                                   ||
||    Chromosomes/contigs : 343                                               ||
||                                                                            ||
|| Process BAM file /home/zel/tom/mike3/30951.aligned.sorted.bam.in...        ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 151739                                                    ||
||    Successfully assigned reads : 33204 (21.9%)                             ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/zel/tom/mike3/30951.aligned.sorted.b ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid4531 ...        ||
||    Features : 743602                                                       ||
||    Meta-features : 55470                                                   ||
||    Chromosomes/contigs : 374                                               ||
||                                                                            ||
|| Process BAM file /home/zel/tom/mike3/30951.aligned.sorted.bam.ex...        ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 151739                                                    ||
||    Successfully assigned reads : 64397 (42.4%)                             ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "18552 barcodes detected."
Initialising 16 core cluster.
[1] "I am subsampling between 1 and 10 reads per barcode."
Warning message:
group_indices_.grouped_df ignores extra arguments
[1] "18552 barcodes detected."
Initialising 16 core cluster.
[1] "I am subsampling between 1 and 10 reads per barcode."
Warning message:
group_indices_.grouped_df ignores extra arguments
[[1]]
[[1]][[1]]
NULL

[[1]][[2]]
NULL

[[2]]
[[2]][[1]]
NULL

[[2]][[2]]
NULL

[[3]]
[[3]][[1]]
NULL

[[3]][[2]]
NULL

[1] "2017-12-07 12:23:46 IST"
[1] "I am done!! Look what I produced.../home/zel/tom/mike3/zUMIs_output/"
            used   (Mb) gc trigger   (Mb)   max used   (Mb)
Ncells   4468649  238.7    9968622  532.4    9968622  532.4
Vcells 598223348 4564.1 1025940204 7827.4 1025939966 7827.4
[1] "I am loading useful packages..."
[1] "2017-12-07 12:23:48 IST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.
notch went outside hinges. Try setting notch=FALSE.

Can you please clarify if the run completed properly or not? I do see a "I am done!!" message previously.

**Comment by sdparekh** [comment]
Hi Tom,

Yes, zUMIs has finished successfully and you will see all the output files in zUMIs_output directory. zUMIs makes boxplots for number of genes and UMIs from your data using ggplot. This warning message is generated by ggplot when the confidence levels are going outside of the bounds in your boxplots. 

Best,
Swati
