### ISSUE TITLE
only filter and tag sequences

### ISSUE THREAD

**Issue by cstrlln** [sdparekh/zUMIs#130]
Hello,
I was wondering what would be the proper way to use zUMIs just for filtering and tagging sequences. Ultimately I would like to have original fastq sequences with barcode as name tag for downstream applications
I thought about retrieving this from the filtered.tagged.aligned.out bam file. When using bedtools to convert to fastq from bam the sequence is different (it's the aligned seq I guess?).
I suppose I could make a script to retrieve the info directly from the bam file but was wondering if you have dealt with a similar situation.
thanks for any advice.
####
e.g. head of bam file

NB501715:410:HJ5LVBGXB:1:11208:4378:13117	16	4	128999157	255	91M	*	0	0	TTGTGTCTGTCATTTGGCCACCGGGGACATGCTGAGAGCCATGGTAGCTTCTGGCTCAGAGCTAGGAAAAAAGCTGAAGGCGACAATGGAT	EEEEE6EEEEEEEEE<EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:89	nM:i:0	BC:Z:TTCGAAGTCACCAGGC	UB:Z:TACTCAGATTTT
NB501715:410:HJ5LVBGXB:1:11208:7195:13119	16	1	180573699	255	91M	*	0	0	CTTCTGGAAGGTGGGCCACTCCATCCGGCAGCCTGATGTTGAGGTGGATGGCTTCTCTGAGCTGCGCTGGGATGATCAGCAGAAGGTCAAG	EEEEEEEEEEEEEEEEEEEEEEEAAEEEAEEEEEEEEEEEEEEEEEEEEEEEEEE/EEEEEEEEEEEAEEEEEEEEEEEEEEEEEEAAAAA	NH:i:1	HI:i:1	AS:i:89	nM:i:0	BC:Z:CCACCTAAGCTAGGCA	UB:Z:TCATGGCTTTTT

###
head of bedtools generated fastq files

@NB501715:410:HJ5LVBGXB:1:11208:4378:13117
ATCCATTGTCGCCTTCAGCTTTTTTCCTAGCTCTGAGCCAGAAGCTACCATGGCTCTCAGCATGTCCCCGGTGGCCAAATGACAGACACAA
+
AAAAAEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE<EEEEEEEEE6EEEEE
@NB501715:410:HJ5LVBGXB:1:11208:7195:13119
CTTGACCTTCTGCTGATCATCCCAGCGCAGCTCAGAGAAGCCATCCACCTCAACATCAGGCTGCCGGATGGAGTGGCCCACCTTCCAGAAG
+
AAAAAEEEEEEEEEEEEEEEEEEAEEEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEAEEEAAEEEEEEEEEEEEEEEEEEEEEEE

## ~ desired out:
@Barcode_UMI
original_sequence... etc

**Comment by cziegenhain** [comment]
Hi,

We don't recommend using fastq files and misusing the readID line for BC/UMI information - hence zUMIs operates with tagged bam files.
Anyway, as you say STAR can reverse complement reads of course depending on the strand it maps to.

If you use a current version of zUMIs, you will also get a `.filtered.tagged.unmapped.bam` file which is exactly what you want I think!

**Comment by cstrlln** [comment]
thanks! I'll update zUMIs and give that a try

**Comment by cstrlln** [comment]
it looks like is something I can work with.

BTW, after updating zUMIs (I was in version 2.4.2 before) I got this error during the run:

[bam_sort_core] merging from 0 files and 4 in-memory blocks... 
[bam_sort_core] merging from 0 files and 4 in-memory blocks... 
[1] "Here are the detected subsampling options:" 
[1] "Automatic downsampling" [1] "Extracting reads from bam file(s)..." 
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 2954 barcodes in this chunk..." 
Error in if (molecule_map_flag == TRUE || opt$barcodes$demultiplex == : missing value where TRUE/FALSE needed Execution halted

but the run continued and did have a seemingly normal expression rds at the end, would there be any problem?

**Comment by cziegenhain** [comment]
Great!
The update also brought some new features that you didnt set in your yaml then - that is where theerror comes from. The run should be totally unaffected and I will remove this unnecessary complaint in the next update. 
Thanks!

I will close here for now, let me know if I can help furtherl.
