### ISSUE TITLE
The readspercell.pdf plots should not be barplots with log transforms 

### ISSUE THREAD

**Issue by knokknok** [sdparekh/zUMIs#133]
Please see the following discussion:
https://stackoverflow.com/questions/9502003/ggplot-scale-y-log10-issue

**Comment by cziegenhain** [comment]
Thanks for the link. The plot does seem to be messed up, I will note it for a future update.

**Comment by cziegenhain** [comment]
Forgot to close here - some time ago we removed this plot from output as it was superfluous.
