### ISSUE TITLE
BUG - printed line in .Rprofile breaks zUMIs

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#134]
Hi,

took me a bit to figure this one out. I didn't use zUMIs for a couple of month and then suddenly the pipeline kept failing with

> Filtering...
> couldn't open loaded for reading: No such file or directory
> couldn't open .Rprofile for reading: No such file or directory
> couldn't open from for reading: No such file or directory
> sh: 1: Syntax error: Unterminated quoted string
> sh: 1: Syntax error: "(" unexpected
> couldn't open loaded for reading: No such file or directory
> couldn't open .Rprofile for reading: No such file or directory
> couldn't open from for reading: No such file or directory
> couldn't open loaded for reading: No such file or directory
> couldn't open .Rprofile for reading: No such file or directory
> couldn't open from for reading: No such file or directory
> sh: 1: Syntax error: Unterminated quoted string
> sh: 1: Syntax error: Unterminated quoted string
> sh: 1: Syntax error: "(" unexpected
> sh: 1: Syntax error: "(" unexpected
> ...

Turns out it was the following line that I added to my .Rprofile that causes the issue:
`writeLines("loaded .Rprofile from /home/username")`

You might want to have a look at you code to see if this behaviour can be prevented.

Best Max

**Comment by cziegenhain** [comment]
I'm sure you understand that we can't foresee what users might store in their Rprofiles.
Also not sure what you are achieving with this - writeLines is used to write text output to a connection (eg file). Check if you wanted to use `print` instead.

Best,
Christoph

**Comment by MaxKman** [comment]
Hi,

you are right that writeLines may not be appropiate here but I ran into the same problem when using `print`. Other R scripts work fine within zUMIs with my .Rprofile so I found it weird that in this one case zUMIs is mistaking my R start message for a file location.  

Of course you can't forsee what users might do with their Rprofiles. One way around this could be to just place an .Rprofile into your working directory.

Best Max
