### ISSUE TITLE
Improvement request: Improve cell detection tresholding

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#137]
Dear zUMIs team,

thanks again for developing zUMIs. The following issue may be similar to what is explained here: https://github.com/sdparekh/zUMIs/issues/128

I noticed that for some of my samples the automatic cell detection, that zUMIs provides, seems to pick an unintuitive treshold.

Most of the time I get a treshold like this, which seems fine:
A)
![image](https://user-images.githubusercontent.com/30081989/63688935-f5c2f900-c808-11e9-9e1e-2bbae81ef80d.png)

However for some samples the tresholding looks like
B)
![image](https://user-images.githubusercontent.com/30081989/63689011-2145e380-c809-11e9-834d-8b6d2b2ecdd7.png)

or
C)
![image](https://user-images.githubusercontent.com/30081989/63689036-33278680-c809-11e9-8217-aef98b3cfcd4.png)

Whereas I don't really mind B, since the the additional low UMI barcodes will be discarded later on in quality control, I wonder if I don't loose some actual cells in situation C. 
A, B, C are all processed exactly the same way, using the same yaml template. I am running zUMIs 2.5.4 on GNU linux. Let me know if you need any additional information.

Best Max

**Comment by cziegenhain** [comment]
Hi Max,

Thanks for a very nice suggestion! I totally understand what you mean.
I just sat down with two example datasets that have unsatisfactory automatic barcode detection too.

My solution would be a detection sensitivity parameter on an arbitrary scale from 1 to 100.
The current default setting would equal to 50 as a good overall compromise.
Depending on the dataset one can then decrease the value to be less inclusive or increase the value to include more barcodes (see attached screenshot).

The implementation is ready but I should be running some tests before pushing to GitHub. 

Let me know if this makes sense or you have further suggestions on this!

![BCdetect 001](https://user-images.githubusercontent.com/16579427/63789841-757bc100-c8f8-11e9-92a1-086a5252febf.png)


Thanks and best,
Christoph

**Comment by MaxKman** [comment]
Yes, I think that would make sense in principal.  

What is happening under the hood here? I wonder if there is really no model out there that can accurately predict the knee of the right curve with one setting for both of these conditions. But haven't got any experience with how difficult a problem this is.

Best Max

**Comment by inesHellmann** [comment]
Hi Max,
we are using mclust to detect the knee. Mclust fits the observed density with k normal distributions, whereas we choose the cut-off to keep 99% of the kth normal distribution, i.e. the one with the largest mean. The second hump in your case C) looks a bit bimodal, so that you would want to keep cells that fall in the kth and the (k-1)th distribution. 
Best Ines

**Comment by cziegenhain** [comment]
Hi again,

Sorry for the holdup. after you asked about the detection algorithm we decided to look further into this. Ines has implemented the UIK (Unit Invariant Knee) method from the [inflection](https://cran.r-project.org/web/packages/inflection/index.html) R package. 
In our tests it seemed to be a bit more robust than the old mclust approach. 

I just pushed this updated to GitHub, would be great if you could give it a go and see how it works for you.

**Comment by MaxKman** [comment]
Hey,

that's great, thanks. Will try.

**Comment by MaxKman** [comment]
It fails with the following error:

> Error in uik(bccount$cellindex, bccount$cs/1000) : 
>   Method is not applicable for such a small vector. Please give at least a 5 numbers vector
> Calls: cellBC -> .cellBarcode_unknown -> .FindBCcut -> uik

Best Max

**Comment by inesHellmann** [comment]
Dear Max,
Thank for testing our new function. Can you please send me your 
.BCstats.txt file, then I will try to fix this problem.

Best, Ines

**Comment by MaxKman** [comment]
Dear Ines,

sorry for being unresponsive. I didn't have new files to run for a while so didn't really have the opportunity to test the improvement. I now processed a number of runs with zUMIs2.5.5. Unfortunately the automatic tresholding performed rather poorly for some of the samples. Here is an example:

![image](https://user-images.githubusercontent.com/30081989/68545281-cb2a1a80-03cb-11ea-9908-c80c8ab4fb8a.png)
![image](https://user-images.githubusercontent.com/30081989/68545278-c5ccd000-03cb-11ea-8064-3f006d910eb0.png)

These are 10X runs superloaded using cell hashing, so the expected cell numbers can be >> 20000 cells per run. I will send you a link to the corresponding .BCstats file via email.

Can you help me with a work around until the tresholding is improved? Is it possible to just process the top 50 000 barcodes? I tried to this using the following settings in my YAML file:

```
barcodes:
  barcode_num: 50000
  barcode_file: null
  automatic: no
  BarcodeBinning: 0
  nReadsperCell: 100
```

Here is the complete YAML file
[HASH-HH-OX-45-46-49-50_F.yaml.txt](https://github.com/sdparekh/zUMIs/files/3828528/HASH-HH-OX-45-46-49-50_F.yaml.txt)

zUMIs states
> [1] "Warning! The data contains fewer barcodes than requested so I will try to use top 100 cells!"
> [1] "294492306 reads were assigned to barcodes that do not correspond to intact cells."
> Mapping...

and then throws away most of the data. Is there a way around this?

Best Max

**Comment by cziegenhain** [comment]
Hi Max,

As you can see there is not really a knee that could have been found so in your case it's probably good to work with the manual number of cells.
I just pushed a slight modification with the following behavior: 
When requesting top n cells but less are present in the data, the pipeline will continue with all barcodes present instead of defaulting to top 100.

Honestly I think its not going to help you to collect barcodes with < 100 reads, so I would not recommend lowering that cutoff. I assume the `Error: negative length vectors are not allowed` is some downstream error of lots of nonsensical barcodes present

So please try again with the update.

Best

**Comment by MaxKman** [comment]
That's great. Thank you so much for the quick reaction. Yes, I agree about barcodes below 100 UMIs. I was only reducing that number to try to prevent the default to top 100 behaviour.

I try out the new version today and will let you know!

**Comment by MaxKman** [comment]
This seems to work (at least for the first sample I tried). Thanks very much for the quick help!

**Comment by cziegenhain** [comment]
Very nice to hear!
