### ISSUE TITLE
The usage of soft links for the input files does not work

### ISSUE THREAD

**Issue by rcosentino** [sdparekh/zUMIs#140]
Hi,

**Describe the bug**

I was getting the following error running zUMIs  :

```
Filtering...
bash: /PATH_TO_OUTPUT/zUMIs_output/.tmpMerge/_Tryp_SL_wt_SL_r2.fqASE_SL_scRNAseq_ALLzzzgijmq.gz: Remote I/O error
split: with FILE=/PATH_TO_OUTPUT/zUMIs_output/.tmpMerge/_Tryp_SL_wt_SL_r2.fqASE_SL_scRNAseq_ALLzzzgijmq, exit 1 from command: pigz -p 16 > $FILE.gz
bash: /PATH_TO_OUTPUT/zUMIs_output/.tmpMerge/_Tryp_SL_wt_SL_r1.fqASE_SL_scRNAseq_ALLzzzgjfbl.gz: Remote I/O error
split: with FILE=/PATH_TO_OUTPUT/zUMIs_output/.tmpMerge/_Tryp_SL_wt_SL_r1.fqASE_SL_scRNAseq_ALLzzzgjfbl, exit 1 from command: pigz -p 16 > $FILE.gz
...
```
Until I figured out that the problem was that zUMIs did not like that the paths, that I gave in the yaml file, were full paths to soft links pointing to the actual files, instead of the full paths to the files themselves... I don't know if this is a bug or if it is expected but It would be handy, for me at least, if we could use soft links as input or in the worse case,  know that I cannot be done :)

**Desktop (please complete the following information):**
 - OS: CentOS Linux 7 (Core)
 - zUMIs version: 2.4.5b

Best,

Raúl

**Comment by cziegenhain** [comment]
Hi Raul,

Sorry for the slow answer.
I think another zUMIs user has a fix for this. 
https://github.com/sdparekh/zUMIs/commit/41d118602e648d8564693759b7d71cf74e73b37e
Could you change that line in your zUMIs and try again?
Unfortunately I won't have time for testing myself soon.

Thanks,
Christoph

**Comment by rcosentino** [comment]
Hi Christoph,

Yes, that modification solve the issue.

Thanks,

Raúl
