### ISSUE TITLE
error during Subread counting step: "No features were loaded in format SAF"

### ISSUE THREAD

**Issue by rcosentino** [sdparekh/zUMIs#142]
Hi,

I am getting the following error when running zUMIs, and I don't know what the problem could be:
```
...
ERROR: no features were loaded in format SAF. The annotation format can be specified by the 'isGTFAnnotationFile' option.
The porgram has to terminate.
...
```

The "filtered.tagged.Aligned.out.bam" is not empty, so I guess the mapping step terminated correctly.

zUMIs version is 2.5.5
R version is 3.6
RSubread version is 1.32.4

Please, let me know if you need me to share with you the content of some output files or some other information..

Best,

Raúl

**Comment by cziegenhain** [comment]
Hi Raul,

I suspect something wrong with your GTF file for the gene annotation. Make sure its correctly formatted and you have the correct path set.
As usual, its always helpful to see the full YAML and standard error/output verbose of the pipeline.

Best
Christoph

**Comment by rcosentino** [comment]
you were right, there was something in wrong in my GFF file.

Thanks,

Raúl
