### ISSUE TITLE
fread cannot open file

### ISSUE THREAD

**Issue by Jachimdejonghe** [sdparekh/zUMIs#143]
**Describe the bug**
fread cannot open files, although I have installed all the dependencies, apart from ggrastr, which gave me an error

**To Reproduce**
yaml file:

project: indrop
sequence_files:
  file1:
    name: jdj1/dropest/indrop_R1.fastq.gz
    base_definition: cDNA(1-61)
  file2:
    name: jdj1/dropest/indrop_R2.fastq.gz
    base_definition: BC(1-8)
  file3:
    name: jdj1/dropest/indrop_R3.fastq.gz
    base_definition: BC(1-8)
  file4:
    name: jdj1/dropest/indrop_R4.fastq.gz
    base_definition:
    - BC(1-8)
    - UMI(9-14)
reference:
  STAR_index: jdj1/dropest/CellRanger/hg19_mm10_ERCC/STAR
  GTF_file: jdj1/dropest/CellRanger/hg19_mm10_ERCC/hg19_mm10.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: indrop_out
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: jdj1/zUMIs/zUMIs
read_layout: SE

standard output
 You provided these parameters:
 YAML file:     spindrop_real.yaml
 zUMIs directory:               jdj1/zUMIs/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   0
 zUMIs version 2.5.5

Fri 27 Sep 10:03:29 BST 2019
Filtering...
date: write error: Stale file handle
Error in data.table::fread(bccount_file) :
  File 'indrop_out/indrop.BCstats.txt' does not exist or is non-readable. getwd()=='jdj1/zUMIs/indrop_out'
Calls: cellBC -> <Anonymous>
Execution halted
zUMIs/zUMIs-master.sh: line 232: echo: write error: Stale file handle
[W::bam_merge_core2] No @HD tag found.

Additionally, the mapping  generates files but still I get freed errors:
date: write error: Stale file handle
Error in data.table::fread(bccount_file) :
  File 'indrop_out/indrop.BCstats.txt' does not exist or is non-readable. getwd()=='jdj1/zUMIs/indrop_out'
Calls: cellBC -> <Anonymous>
Execution halted
zUMIs/zUMIs-master.sh: line 232: echo: write error: Stale file handle
[W::bam_merge_core2] No @HD tag found.
date: write error: Stale file handle
zUMIs/zUMIs-master.sh: line 242: echo: write error: Stale file handle
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) :
  File 'indrop_out/zUMIs_output/indropkept_barcodes.txt' does not exist or is non-readable. getwd()=='jdj1/zUMIs/indrop_out'
Execution halted
date: write error: Stale file handle
zUMIs/zUMIs-master.sh: line 257: echo: write error: Stale file handle
Error in library(cowplot) : there is no package called ‘cowplot’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted
date: write error: Stale file handle

**Desktop (please complete the following information):**
Red Hat Enterprise Linux Server release 7.6

**Comment by cziegenhain** [comment]
Hi,

Please try to use full paths instead of relative paths for all file/folder fields in the YAML, that should fix the errors.

Best,
Christoph

**Comment by Jachimdejonghe** [comment]
Great thanks a lot, I don't know why I forgot to add the full path for the output as well. Works like a charm.

As a side-note. To demultiplex on R3 fastq files for indrops v3, do I have to put the project name as project: InDropsV3 for the demultiplexing to happen? Which part of the yaml file is parsed to recognise an indrops v3 format? Sorry I have seen your Protocol specific setup page but wasn't sure why my files weren't demultiplexed

**Comment by cziegenhain** [comment]
Awesome, great to hear that it solved the issue!

To clarify the last bit: The `project: ` setting is just an arbitrary label for output file names. 
All the handling of where cell barcode sequences should be extracted from happens in the `base_definition: ` sections for each input fastq file. So as long as you have the R3 fastq file in your YAML you will be fine.

Hope this helps!

Closing the issue for now but of course happy to take additional questions.

Best,
Christoph

**Comment by Jachimdejonghe** [comment]
Hi Christoph, thank you for this! But I am still unsure how the zUMIs can demultiplex indrops v3 samples based on library tags (R3), which is different from the cell barcodes (R1 and R2).

Aim happy to open another issue on this if necessary.

Thanks for developing such an amazing tool !

**Comment by cziegenhain** [comment]
No problem we can discuss here!
However many barcode files you give with the respective barcode ranges will be considered for demultiplexing. zUMIs simply concatenates all extracted barcode pieces to make one long barcode string that is unique per cell.
Imagine a cell in InDrops v3 has the following sequences:
cell barcode R1 = XXXXXXXX
cell barcode R2 = YYYYYYYY
library barcode R3 = ZZZZZZ
The cell barcode zUMIs considers will be XXXXXXXXYYYYYYYYZZZZZZ

**Comment by Jachimdejonghe** [comment]
Hi. Thanks. Yes I have seen that, but my question would be, is there something in zUMIs that can demultiplex on YYYYYYYY (to have all cells per sample)? Or should I manually do this on the rds file ?

Thanks!

**Comment by cziegenhain** [comment]
Ah i see, you just want the output to be separated by library barcode?
that is not implemented, so either run zUMIs for each lib BC or separate from the RDS file.

Best,
Christoph

**Comment by Jachimdejonghe** [comment]
great thank you Christoph :)
