### ISSUE TITLE
Error report of zUMIs

### ISSUE THREAD

**Issue by skytguuu** [sdparekh/zUMIs#147]
Hi,
Recently, I tried to use zUMIs to analyze my scRNA data. However,  I met a error report:
##################
Wed Oct 16 10:33:20 CST 2019
Filtering...
Wed Oct 16 10:57:20 CST 2019
Read 6007772 rows and 2 (of 2) columns from 0.097 GB file in 00:00:10
Error in uik(bccount$cellindex, bccount$cs/1000) :
  could not find function "uik"
Calls: cellBC -> .cellBarcode_unknown -> .FindBCcut
Execution halted
Mapping...
[1] "2019-10-16 10:57:39 CST"
[W::bam_merge_core2] No @HD tag found.
Wed Oct 16 11:45:48 CST 2019
Counting...
[1] "2019-10-16 11:46:05 CST"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) :
  File '/home/dell/mnt1/nieyongqiang/zUMIs_output/zUMIs_output/scRNA1kept_barcodes.txt' does not exist. Include one or more spaces to consider the input a system command.
Execution halted
Wed Oct 16 11:46:05 CST 2019
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-10-16 11:46:07 CST"
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  :
  File '/home/dell/mnt1/nieyongqiang/zUMIs_output/zUMIs_output/scRNA1kept_barcodes.txt' does not exist. Include one or more spaces to consider the input a system command.
Execution halted
Wed Oct 16 11:46:12 CST 2019
#######################
And this is my yaml file:
project: scRNA
sequence_files:
  file1:
    name: /home/dell/mnt1/nieyongqiang/NYQ-2cell_combined_R1.fastq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: /home/dell/mnt1/nieyongqiang/NYQ-2cell_combined_R2.fastq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /home/dell/softwares/tools/RNAseq/scRNA/zUMIs-master/STAR_nogtf_index
  GTF_file: /home/dell/Annotation/RNAseq_anno/mm10/Ref_mm10.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/dell/mnt1/nieyongqiang/zUMIs_output
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /home/dell/softwares/tools/RNAseq/scRNA/zUMIs-master
read_layout: SE
###############
I did not know what's happened?
Could you give me a hand?

Thank you!

**Comment by cziegenhain** [comment]
Hi!

Thanks for giving zUMIs a try!
It looks like you are missing the R package `inflection`. 
Could you double check if all the dependencies are properly installed: https://github.com/sdparekh/zUMIs/wiki/Installation#r 

Best,
Christoph

**Comment by skytguuu** [comment]
Hi,

Thanks for your prompt reply. I have checked the package "inflection", it was well installed. Also, other required package were installed .
#######
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.2 LTS

Matrix products: default
BLAS: /home/dell/softwares/anaconda2/lib/R/lib/libRblas.so
LAPACK: /home/dell/softwares/anaconda2/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=zh_CN.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=zh_CN.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=zh_CN.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] inflection_1.3   RevoUtils_10.0.8

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    parallel_3.4.3
#################
Thanks!

**Comment by skytguuu** [comment]
Hi,
I met another question about this tool. I tried use old version of "zUMIs" (version 2.5.0). It won't report above error, however, another error has been reported. 
########
-------------

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs

-------------


 You provided these parameters:
 YAML file:     /home/dell/mnt1/nieyongqiang/scRNA2.yaml
 zUMIs directory:               /home/dell/softwares/tools/RNAseq/scRNA/zUMIs-2.5.0
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   0
 zUMIs version 2.5.0


Wed Oct 16 20:41:30 CST 2019
Filtering...
Wed Oct 16 21:04:16 CST 2019
[1] "Warning! Adaptive BC selection gave < 10 cells so I will try to use the top 100 cells!"
[1] "1119587 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2019-10-16 21:04:27 CST"
[W::bam_merge_core2] No @HD tag found.
Wed Oct 16 22:00:25 CST 2019
Counting...
[1] "2019-10-16 22:00:42 CST"
[1] "2e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/dell/mnt1/nieyongqiang/test/scRNA1.final_annot.gtf"
Error in mutate_impl(.data, dots) :
  Cannot convert object to a function: [type=NULL; target=CLOSXP, SPECIALSXP, or BUILTINSXP].
Calls: .makeSAF ... <Anonymous> -> mutate.tbl_df -> mutate_impl -> .Call
In addition: Warning message:
The `printer` argument is deprecated as of rlang 0.3.0.
This warning is displayed once per session.
Execution halted
Wed Oct 16 22:02:01 CST 2019
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-10-16 22:02:02 CST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/dell/mnt1/nieyongqiang/test/zUMIs_output/expression/scRNA1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Wed Oct 16 22:02:07 CST 2019
################
I don't know what's happened?
Could you give me some advises?

Thanks!

**Comment by cziegenhain** [comment]
Hi,

It makes sense that the error `could not find function "uik"` goes away when you use an older version before we switched to the `inflection package`.
Often when users have problems with the R package dependencies it turns out that there are several R versions / environments around. 
For completeness: The last error message relates to loading/parsing your GTF file.

BEst,
Christoph
