### ISSUE TITLE
Output of unfiltered count matrix

### ISSUE THREAD

**Issue by OliInTheValley** [sdparekh/zUMIs#148]
Hi,

We've been using zUMIs succesfully in the past and really like the mapper.
However, I plan to conduct a preprocessing step on the resulting data to remove cell free mRNA (called ’soup’) from my datasets. mRNA from lysed cells floating around and being erroneously incorporated and sequenced, is a common problem in droplet technologies. Nevertheless, with packages like SoupX (https://github.com/constantAmateur/SoupX), one can use the information from empty droplets to calculate the degree of contamination and bioinformaticly remove it.
At the moment, zUMIs only provides the filtered count matrix dependent on the knee plot thing, but I assume it must be stored somewhere as a temporary file or output. 

Would it be possible to include an option to generate a mostly unfiltered count matrix in addition to the filtered one?

**Comment by sdparekh** [comment]
Hi, Good to know that you are happy with zUMIs.
Which option do you use for barcode detection? Do you use "Automatic" or do you provide the number of expected barcodes? Which droplet technology are you using? If you are using the "Automatic" barcode detection, does zUMIs give you many more than expected? 

Keeping millions of false barcodes will effectively slow down the assignment process. Hence, we take only the detected barcodes further down for generating count matrix. 

Please give me more details about your experiment and if possible, share the knee plot generated by zUMIs to discuss further and find the best solution for your needs.

Hint: I usually give 3-4times more than expected number of barcodes and filter downstream from the generated count matrix.

Best,
Swati
