### ISSUE TITLE
Another question when used zUMIs

### ISSUE THREAD

**Issue by zhangyj2017** [sdparekh/zUMIs#15]
Dear zUMIs developers
       When we used the newest version of zUMIs, we found it did not produce some important files such as umicounts.exons.txt in expression folder. This files is necessary for follow-up analysis. Is that something wrong in it?
Yous Sincerely
Johannes Zhang

**Comment by cziegenhain** [comment]
Hey,

Because writing out plain text files is rather inefficient, especially for large datasets, we have switched to storing count data in the sparseMatrix format. 
You can find all the count tables you are used to for downstream analysis in the *.dgecounts.rds file produced. 

Best,
Christoph
