### ISSUE TITLE
zUMIs output file is empty 

### ISSUE THREAD

**Issue by taniachavarria79** [sdparekh/zUMIs#150]
Hello,

we are working with RNA sequence data provide by the Helmut lab in LMU so we have three files: r1, r2 and i. Also we have the barcodes using by each sample in a txt file name Sample-info. When we run the zUMIs script we got the follow message and the stats and expression files are empty, plus it does not produce the demultiplex file.  We previously run zUMIs with your test data and works fine. 
Here I adjunct the message produce and the yaml file we are using in a text form because it does not support the yaml type. 
Thanks so much for your help,
Best,

Tania 

This is the message zUMIs produced:

You provided these parameters:
 YAML file: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun/zumis_test2.yaml
 zUMIs directory: /data/scratch/taniach/zUMIs
 STAR executable STAR
 samtools executable samtools
 pigz executable pigz
 Rscript executable Rscript
 RAM limit: 256
 zUMIs version 2.5.6b

Mon Dec 9 10:11:04 CET 2019
Filtering…
Mon Dec 9 10:46:37 CET 2019
[1] "Using intersection between automatic and whitelist.“
[1] "116 barcodes detected automatically.“
[1] "Keeping 0 Barcodes.“
[1] "428872587 reads were assigned to barcodes that do not correspond to intact cells.“
Mapping…
[1] "2019-12-09 10:46:42 CET“
[W::bam_merge_core2] No @HD tag found.
Mon Dec 9 11:44:43 CET 2019
Counting…
[1] "2019-12-09 11:44:49 CET“
[1] "1.152e+09 Reads per chunk“
Error in if (bccount[i]$n > maxR) { :
  missing value where TRUE/FALSE needed
Calls: splitRG
Execution halted
Mon Dec 9 11:44:49 CET 2019
Descriptive statistics…
[1] "I am loading useful packages for plotting…“
[1] "2019-12-09 11:44:50 CET“
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun2/zUMIs_output/expression/test.dgecounts.rds', probable reason 'No such file or directory‘
Execution halted
Mon Dec 9 11:44:51 CET 2019

### This is the yaml file information

project: Example_experiment
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_i1.fq.gz
    base_definition: BC(1-8)
  file2:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r1.fq.gz
    base_definition: 
    - BC(1-6)
    - UMI(7-16)
  file3:
    name:/data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r2.fq.gz 
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_all_genes_20170213.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun2
num_threads: 48
mem_limit: 256
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/Sample_info.txt 
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/zUMIs
read_layout: SE

[zumis_test2.txt](https://github.com/sdparekh/zUMIs/files/3944075/zumis_test2.txt)

**Comment by cziegenhain** [comment]
Hi,

As you can see from the verbose in the log, none of the barcodes you listed were found in the data. 
This is the relevant section from the log:

> [1] "Using intersection between automatic and whitelist.“
> [1] "116 barcodes detected automatically.“
> [1] "Keeping 0 Barcodes.“

You need to give the expected barcodes correctly and rerun.

Best,
Christoph

**Comment by taniachavarria79** [comment]
Hello,

Thanks for answers me back. I did run again zUMIs putting the option of automatically select the barcodes and again I do not have anything in my output expression and stats files. 
I do not know what could be wrong as I am submitting the files as we received from the Helmut lab and we are using an example of a yaml file they gave us. 
This is the new information I put in the yaml file:
project: Example_experiment
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_i1.fq.gz
    base_definition: BC(1-8)
  file2:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r1.fq.gz
    base_definition: 
    - BC(1-6)
    - UMI(7-16)
  file3:
    name:/data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r2.fq.gz 
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_all_genes_20170213.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun
num_threads: 48
mem_limit: 256
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: null
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
  demultiplex: yes
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/zUMIs
read_layout: SE


Thanks so much for your help

**Comment by cziegenhain** [comment]
Hi,

To be able to troubleshoot, it would be necessary to see the verbose printed out by zUMIs.
