### ISSUE TITLE
Error in setnames(x, value) : Can't assign 2 names to a 0 column data.table

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#154]
Hello, I tried to use zUMIs.

Thanks in Advance for your great help!

Yue

~$ bash ~/zUMIs/zUMIs-master.sh -y BC10_SRR7191904.yaml

You provided these parameters:
YAML file: BC10_SRR7191904.yaml
zUMIs directory: /home/li/zUMIs
STAR executable /home/li/STAR-2.6.0a/bin/Linux_x86_64/STAR
samtools executable samtools
pigz executable pigz
Rscript executable Rscript
RAM limit: 20
zUMIs version 2.5.6b

Mon Dec 16 21:36:16 EST 2019
Filtering...
sh: 1: Syntax error: Unterminated quoted string
sh: 1: Syntax error: Unterminated quoted string
Mon Dec 16 21:38:28 EST 2019
Error in setnames(x, value) : 
Can't assign 2 names to a 0 column data.table
Calls: cellBC -> names<- -> names<-.data.table -> setnames

**Comment by cziegenhain** [comment]
Hi,
for troubleshooting, you would need to send your YAML file too.
It seems there is a problem with your input though, because the fastq filtering had an issue.

**Comment by yueli711** [comment]
Hello, cziegenhain,

Thank you for our response!

The data set I used is GSM3148577.
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3148577

I have some problems in transfer the GSM3148577_BC10_TUMOR1_barcodes.tsv.gz file to the barcodes.fastq.gz which BC10_SRR7191904.yaml wanted.

Thank you again!

Yue 

[GSM3148577_BC10_TUMOR1_barcodes.tsv.gz](https://github.com/sdparekh/zUMIs/files/4017639/GSM3148577_BC10_TUMOR1_barcodes.tsv.gz)


[barcodes.fastq.gz](https://github.com/sdparekh/zUMIs/files/4017641/barcodes.fastq.gz)


[BC10_SRR7191904.zip](https://github.com/sdparekh/zUMIs/files/4017690/BC10_SRR7191904.zip)


`@4911
@SRR7191904.4911
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4912
@SRR7191904.4912
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4913
@SRR7191904.4913
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4914
@SRR7191904.4914
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4915
@SRR7191904.4915
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4916
@SRR7191904.4916
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4917
@SRR7191904.4917
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4918
@SRR7191904.4918
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4919
@SRR7191904.4919
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4920
@SRR7191904.4920
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4921
@SRR7191904.4921
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4922
@SRR7191904.4922
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4923
@SRR7191904.4923
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4924
@SRR7191904.4924
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4925
@SRR7191904.4925
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@4926
@SRR7191904.4926
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

Thu Jan  2 18:06:36 EST 2020
Error in uik(bccount$cellindex, bccount$cs/1000) : 
  Method is not applicable for such a small vector. Please give at least a 5 numbers vector
Calls: cellBC -> .cellBarcode_unknown -> .FindBCcut -> uik
Execution halted
Mapping...
[1] "2020-01-02 18:06:37 EST"
[W::bam_merge_core2] No @HD tag found.

EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile
SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
Jan 02 18:06:37 ...... FATAL ERROR, exiting
[main_samview] fail to read the header from "-".
Thu Jan  2 18:06:37 EST 2020
Counting...
[1] "2020-01-02 18:06:42 EST"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) : 
  File '/home/li/li01/zUMIs_output/BC10_SRR7191904.yamlkept_barcodes.txt' does not exist or is non-readable. getwd()=='/home/li/li01'
Execution halted
Thu Jan  2 18:06:42 EST 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-01-02 18:06:42 EST"
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/home/li/li01/zUMIs_output/BC10_SRR7191904.yamlkept_barcodes.txt' does not exist or is non-readable. getwd()=='/home/li/li01'
Execution halted
Thu Jan  2 18:06:43 EST 2020
`

**Comment by OliInTheValley** [comment]
Hi, 
was this issue solved? If so, how?

I have experienced a very similar problem. When running zUMIs with the automatic detection mode without setting a defined number of barcodes or providing a whitelist, it inexplicably caused an error in the filtering step:

> Thu Mar  5 01:37:50 PST 2020
> Filtering...
> Thu Mar  5 04:56:00 PST 2020
> [1] "89619 barcodes detected."
> [1] " reads were assigned to barcodes that do not correspond to intact cells."
> Error in setnames(x, value) : 
>   Can't assign 0 names to a 1 column data.table
> Calls: BCbin ... colnames<- -> names<- -> names<-.data.table -> setnames
> Execution halted

This does not cause the software to halt though. Instead, zUMIs continues with the mapping but fails in the counting step because it cannot find the XXkept_barcodes_binned.txt file (full zUMIs output attached). This has not happened in the past, and is not limited to this particular input file.  Running zUMIs with a given fixed number of BCs does not cause this error. YAML file is attached. 
Any help/suggestions would be greatly appreciated.

P.S.: .yaml file and slurmoutput usually do not end on .txt, I had to add that so I can upload them here.

[slurm-14447460.out.txt](https://github.com/sdparekh/zUMIs/files/4295014/slurm-14447460.out.txt)
[Yaml_call_OPL2_reg.yaml.txt](https://github.com/sdparekh/zUMIs/files/4295015/Yaml_call_OPL2_reg.yaml.txt)

**Comment by yueli711** [comment]
Hello, OlilnTheValley,

I played the code two months ago. I tried to download the new version and give your suggestion, but I also met many errors.

I only remember the barcoderead and the cDNA files should have the same ID, the ID should be identical. Also, these two files should have same lines, the length of these files should be the same. I have to use zip files.  Following are the demo data, they are all 4000000 lines.

I will message you if I have new progress.


```
li@Desktop-590-p0xxx:~/zUMIs-master_01_work$ wc -l demult_HEK_r1.1mio.fq 
4000000 demult_HEK_r1.1mio.fq
li@Desktop-590-p0xxx:~/zUMIs-master_01_work$ wc -l demult_HEK_r2.1mio.fq 
4000000 demult_HEK_r2.1mio.fq

```

Best,

Yue

**Comment by yueli711** [comment]
@OliInTheValley Hello, I worked very well in zUMIs-2.0 version.

I guess, but I am not sure. I still think is the id name.

Best,

yue

```
#output directory
out_dir: ./ #specify the full path to the output directory
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt")) : 
  File './/zUMIs_output/OC1_100kkept_barcodes_binned.txt' does not exist or is non-readable. getwd()=='/oak/stanford/scg/lab_twc/OHahn/data_proc
```

**Comment by cziegenhain** [comment]
Hi @OliInTheValley,

Sorry for the slow reply.
This looks like a problem when trying to do error correction on the barcode read.
Can you try again with a) the most current zUMIs version and b) BarcodeBinning: 0
