### ISSUE TITLE
EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#156]
Hello, 

I have problem in running zUMIs.

Thank you in advance for your great help!

Best,

Yue

[example01.yaml.zip](https://github.com/sdparekh/zUMIs/files/4028442/example01.yaml.zip)

[example01.fastq.gz](https://github.com/sdparekh/zUMIs/files/4028441/example01.fastq.gz)

`@756968
@ST-K00126:308:HFLYFBBXX:2:1105:4066:34811_TACTTACTCCTTCAAT_GTTCTGTAAG
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756969
@ST-K00126:308:HFLYFBBXX:2:1105:11698:34881_CCTACACGTTCCCGAG_AATTCGATAA
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756970
@ST-K00126:308:HFLYFBBXX:2:1105:6431:34899_AGCGTCGGTAAACACA_TAAGGCAGCG
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756971
@ST-K00126:308:HFLYFBBXX:2:1105:20821:34899_CACCTTGTCAGTTCGA_AGGGGTGCCC
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756972
@ST-K00126:308:HFLYFBBXX:2:1105:12784:34969_ACTGTCCCATATGGTC_AGAAAGCACC
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756973
@ST-K00126:308:HFLYFBBXX:2:1105:13098:34987_TACTTACTCCTTCAAT_CTAAACCTAT
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

@756974
@ST-K00126:308:HFLYFBBXX:2:1105:26656:34987_TTAGGCAAGATATACG_AGATATGGTT
ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order.

Mon Jan  6 19:50:41 EST 2020
[1] "41 barcodes detected."
[1] "2339535 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2020-01-06 19:50:43 EST"
[W::bam_merge_core2] No @HD tag found.

SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
Jan 06 19:50:43 ...... FATAL ERROR, exiting
[main_samview] fail to read the header from "-".
Mon Jan  6 19:50:50 EST 2020
Counting...
[1] "2020-01-06 19:50:54 EST"
[1] "9e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/li/li01/example01.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"
Error in normalizePath(files, mustWork = T) : 
  path[1]="/home/li/li01/example01.filtered.tagged.Aligned.out.bam": No such file or directory
Calls: .runFeatureCount -> featureCounts -> normalizePath
Execution halted
Mon Jan  6 19:50:56 EST 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-01-06 19:50:56 EST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/li/li01/zUMIs_output/expression/example01.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan  6 19:50:57 EST 2020
`

**Comment by cziegenhain** [comment]
Hi,

It seems that the read IDs in your two fastq files don't match
Please carefully check that `example01.fastq.gz` and `hgmm_100_R2_extracted.fastq.gz` are from the same experiment and the reads match.

Best,
Christoph

**Comment by yueli711** [comment]
Hello, Christoph,

Thank you so much for your suggestion! It works!

Thank you for developing so nice software!

Best,

Yue



[example04.yaml.gz](https://github.com/sdparekh/zUMIs/files/4032908/example04.yaml.gz)

**Comment by cziegenhain** [comment]
Glad to hear!
