### ISSUE TITLE
Adding custom parameters to FeatureCounts usage

### ISSUE THREAD

**Issue by skannan4** [sdparekh/zUMIs#157]
Would it be possible to have an option in the YAML file for additional or custom FeatureCounts parameters, similar to the current additional_STAR_params option? In particular, it may be helpful (well, for me at least) to have some more options for handling multimappers (for example, fractional counting or, in the particularly weird niche usage I have, counting every single mapping). Others may also find usage here if there are additional FeatureCounts parameters they want to include. Not sure how easily this works with the R implementation but figured I'd ask!

**Comment by cziegenhain** [comment]
Hi! That should certainly be possible. 
For now, I would refer you to change the following function controlling the featureCounts call in your local zUMIs installation: 
https://github.com/sdparekh/zUMIs/blob/master/runfeatureCountFUN.R#L76

**Comment by skannan4** [comment]
This worked fine for me, so I'm happy to close for now.
