### ISSUE TITLE
Error in (function (cl, name, valueClass)  : 

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#158]
Hello, cziegenhain,

Thank you for developing so nice software!

I have error in running the program.

Any hint or help will be appreciated!

Thank you!

Yue

```
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
```

**Comment by cziegenhain** [comment]
As always, I need at least the YAML and full verbose to troubleshoot.
