### ISSUE TITLE
Error in data.table::fread(samfile, na.strings = c(""), select = c(1,  :    Column number 4 (select[4]) is too large for this table, which only has 3 columns.

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#159]
Hello, sdparekh,

Thank you so much for developing so nice software!

I tried to use your new version: https://github.com/sdparekh/zUMIs.

Thank you in advance for your great help and really appreciated!

Best,

Yue

`$ bash ~/zUMIs-master/zUMIs-master.sh -y runExample.yaml`

`
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 50 barcodes in this chunk..."
`
`Error in data.table::fread(samfile, na.strings = c(""), select = c(1,  : `
`Column number 4 (select[4]) is too large for this table, which only has 3 columns.`
`Calls: reads2genes -> <Anonymous>`

[runExample.zip](https://github.com/sdparekh/zUMIs/files/4067036/runExample.zip)

**Comment by cziegenhain** [comment]
Yue,

Just so you know, we do want that users post their full verbose with the GitHub issue. Please remember for the future.

For the issue: I can reproduce it, must be something that I missed when coding up the latest updates.I'll push a fix ASAP

**Comment by cziegenhain** [comment]
A fix taking care of this is now pushed.
Feel free to reopen if you need further assistance.

**Comment by yueli711** [comment]
Hello, cziegenhain,

Thank you so much for your quick response!

I already add the command line.

Thank you again!

Yue

**Comment by yueli711** [comment]
Hello, cziegenhain,

May I ask where I ca find a fix taking care of this?

Thank yo again!

Best,

Yue

**Comment by cziegenhain** [comment]
Just type `git pull` within your zUMIs folder. It should fetch the latest update

**Comment by yueli711** [comment]
Hello, cziegenhain,

`~/zUMIs-2.6.0$ git pull`

`fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`
