### ISSUE TITLE
How to  convert sparseMatrix in .rds format to .txt format ?

### ISSUE THREAD

**Issue by zhangyj2017** [sdparekh/zUMIs#16]
Dear Swath
       Thanks very much for your response.
The new version zUMIS can only work when we re-install old version of rsubread package 1.26.0. We are learning to analysis sequencing data only a few months.So we also want to know how to  convert sparseMatrix in .rds format to .txt format. Thanks very much.
Sincerely
Johannes Zhang

**Comment by cziegenhain** [comment]
Please check the wiki page 
https://github.com/sdparekh/zUMIs/wiki/Output
