### ISSUE TITLE
Issues running zUMIs

### ISSUE THREAD

**Issue by taniachavarria79** [sdparekh/zUMIs#160]
Hello, 
Iam running zUMIS now with the option of detecting the barcodes automatically and I have this error: 

During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
 You provided these parameters:
 YAML file: /data/scratch/taniach/zumis_loba1.yaml
 zUMIs directory: /data/scratch/taniach/zUMIs
 STAR executable STAR
 samtools executable samtools
 pigz executable pigz
 Rscript executable Rscript
 RAM limit:   256
 zUMIs version 2.5.6b 

Thu Jan 16 14:27:31 CET 2020
Counting...
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
[1] "2020-01-16 14:27:38 CET"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) : 
  File '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun//zUMIs_output/Example_experimentkept_barcodes.txt' does not exist or is non-readable. getwd()=='/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun'
Execution halted
Thu Jan 16 14:27:38 CET 2020
Descriptive statistics...
During startup - Warning message:
Setting LC_CTYPE failed, using "C" 
[1] "I am loading useful packages for plotting..."
[1] "2020-01-16 14:27:38 CET"
Error in fread(gtf, select = 1:2, header = F) : 
  File '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun//Example_experiment.final_annot.gtf' does not exist or is non-readable. getwd()=='/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun'
Calls: getUserSeq -> fread
Execution halted
Thu Jan 16 14:27:39 CET 2020

This is the yaml file information
project: lobaria_experiment1
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth_1_i1.fq.gz
    base_definition: BC(1-8)
  file2:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth_1_r1.fq.gz
    base_definition: 
    - BC(1-6)
    - UMI(7-16)
  file3:
    name:/data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth_1_r2.fq.gz 
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index/
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_all_genes_20170213.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun/
num_threads: 48
mem_limit: 256
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: null 
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/zUMIs/
read_layout: SE

Thanks so much for your help

Best,

Tania

**Comment by cziegenhain** [comment]
Hi Tania,
this can either not be your full log or it is not the matching YAML information you posted.
 It seems like your zUMIs run starts with Counting where you have indicated that start should be in Filtering.
Please check back.

**Comment by taniachavarria79** [comment]
Hello, I already check the yaml folder and everything is fine I even change the stage to Counting and it keep giving me the same error. 
What do you mean that is not my full log?

Thanks so much

**Comment by cziegenhain** [comment]
I'm saying that your config file specifies Filtering as the start stage but the log  you posted starts at Counting. so all of what comes before is lacking and I can't troubleshoot your issue.

**Comment by taniachavarria79** [comment]
okay thanks I will double check if there is some issues with the installation
