### ISSUE TITLE
use a different mapper

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#161]
Hello, Christoph Ziegenhain,

Thank you so much for developing so nice software: zUIMs.
In your paper GigaScience, 7, 2018, 1-9
“Filtering and mapping”

"Furthermore, if the user wishes to use a different mapper, it is also possible to provide zUMIs with an aligned bam file instead of the fastq file with the cDNA sequence, with the sole requirement that only one mapping position per read is reported in the bam file."

If I want to use Rsubread (R package) mapper, what can I do? Following are the Rsubread mapping command.

Thank you in  advance and really appreciate any of your help!

Best,

Yue

[runExample.zip](https://github.com/sdparekh/zUMIs/files/4083765/runExample.zip)

`$ bash ~/zUMIs-master/zUMIs-master.sh -y runExample.yaml`

> library(Rsubread)
> ref <- system.file("extdata","reference.fa",package="Rsubread")
> buildindex(basename="reference_index",reference=ref)
> reads <- system.file("extdata","reads.txt.gz",package="Rsubread")
> align.stat <- align(index="reference_index",readfile1=reads,output_file="alignResults.BAM",phredOffset=a64)`
```

**Comment by cziegenhain** [comment]
Hi,

You are right that our paper talked about easily swapping out the mapper. This is however mainly true for [zUMIs version 1](https://github.com/sdparekh/zUMIs/tree/zUMIs-version1) which stored reads after filtering in fastq format. This version of zUMIs is no longer supported by us.

In the current version of zUMIs, you can still try to use a custom mapper as long as it fulfills:
- take input reads from an unmapped bam file
- retains tags for output bam file (eg cell barcode & UMI tags)
- one mapping per read

Practically, I would recommend to run zUMIs as usual first. This will give you the unmapped bam file: `<Project_name>.filtered.tagged.unmapped.bam`. You could then try to map this using whatever software and name the output `<Project_name>.filtered.tagged.Aligned.out.bam`. Then, resume zUMIs at the "Counting" stage and it should proceed with your custom mapped bam file.

Good luck,
Christoph

**Comment by yueli711** [comment]
Hello, cziegenhain,

Thank you so much for your quick response!

I already got the` <Project_name>.filtered.tagged.Aligned.out.bam`  by using Rsubread mapper.

How I can resume zUMIS at the "counting" stage?

I stuck this for almost one week, and really appreciate any of your great help!

And always, thank you in advance for any of your suggestions!

Best,

Yue 

`$ bash ~/zUMIs-master_runE_yli1/zUMIs-master_yli1.sh -y runE.yaml`


[zUMIs-master_runE_yli1.zip](https://github.com/sdparekh/zUMIs/files/4085228/zUMIs-master_runE_yli1.zip)

[runE.zip](https://github.com/sdparekh/zUMIs/files/4085235/runE.zip)

**Comment by cziegenhain** [comment]
Great! Then, in line 43 of your yaml, set:
`which_Stage: Counting` to start from that stage :)

**Comment by yueli711** [comment]
Hello, cziegenhain,

Thank you so much for your helpful suggestion!

I changed line43 of my yaml., set:  which_Stage: Counting, still got the error.

Really appreciate of your help, and thank you again!

Best,

Yue

`$ bash ~/zUMIs-master_runE_yli1/zUMIs-master_yli1.sh -y runE.yaml`

I changed the file checkyaml.R line 22-25, zUMIs-master.sh line 137 147, and zUMIs-mapping.R line 80.

[runE.zip](https://github.com/sdparekh/zUMIs/files/4087442/runE.zip)
[zUMIs-master_runE_yli1.zip](https://github.com/sdparekh/zUMIs/files/4087443/zUMIs-master_runE_yli1.zip)

**Comment by cziegenhain** [comment]
Hi Yue,

I didnt look at your code changes, but can you end the actual error message you are getting?

**Comment by yueli711** [comment]
Hello, cziegenhain,

Thank you so much for your message!

Thank you for your time and great help!

Best,

Yue
[zUMIs-master_runE_yli1.zip](https://github.com/sdparekh/zUMIs/files/4087713/zUMIs-master_runE_yli1.zip)
[runE.zip](https://github.com/sdparekh/zUMIs/files/4087714/runE.zip)

`bash ~/zUMIs-master_runE_yli1/zUMIs-master_yli1.sh -y runE.yaml`

` which_Stage:Counting`

`Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes.txt")) :`


`which_Stage: Filtering`


`[1] "Working on barcode chunk 1 out of 1"`
`[1] "Processing 43 barcodes in this chunk..."`
`Error in (function (cl, name, valueClass)  : `
`assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE`
`Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>`
`Execution halted`

**Comment by cziegenhain** [comment]
Sorry, we cannot support this issue further. We are just maintaining zUMIs in our freetime next to our actual research work.

You need to work on the code on your own for this particular request.

**Comment by yueli711** [comment]
Hello, cziegenhain,


Thank you again for your time and help!


Thank you!


Best,


Yue










At 2020-01-23 02:02:34, "cziegenhain" <notifications@github.com> wrote:

Sorry, we cannot support this issue further. We are just maintaining zUMIs in our freetime next to our actual research work.

You need to work on the code on your own for this particular request.

**Comment by yueli711** [comment]
Hello, cziegenhain,

Really appreciate your time and help!

Thank you!

Best,

Yue
