### ISSUE TITLE
only want the `<Project_name>.filtered.tagged.unmapped.bam

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#162]
Hello, cziegenhain,

Thank you so much for your time and great help!

Which command that can only output `<Project_name>.filtered.tagged.unmapped.bam`,not <Project_name>.filtered.tagged.Aligned.out.bam` together?

Thank you in advance and really appreciate any of your help!

Best,

Yue

**Comment by cziegenhain** [comment]
Hi Yue,

We have not built an option to run only the first parts of the pipeline and don't plan to. 
zUMIs is meant to be a one stop command from fastq to count tables.
