### ISSUE TITLE
demultiplex

### ISSUE THREAD

**Issue by taniachavarria79** [sdparekh/zUMIs#163]
Hello,

In which part of the yaml file I should include the option to demultiplex my samples.
Here is the yaml file:

project: lobaria_experiment1
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r1.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file3:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r2.fq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index/
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_all_genes_20170213.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun/
num_threads: 48
mem_limit: 256
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~ 
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/zUMIs/
read_layout: SE  

Thanks for your help

**Comment by cziegenhain** [comment]
Hi,

the demultiplex option should sit in the barcode section:
https://github.com/sdparekh/zUMIs/blob/master/zUMIs.yaml#L65

**Comment by taniachavarria79** [comment]
Thanks
