### ISSUE TITLE
Add functionality to collapse SPLiT-seq OdT/random hexamer barcodes

### ISSUE THREAD

**Issue by jeremymsimon** [sdparekh/zUMIs#166]
For SPLiT-seq, we often use both random hexamers and oligo-dT to amplify, but the net effect is that we'll have two different bc1 but identical bc2-bc3, all corresponding to the same cell. This is handled in the [Unofficial SPLiT-seq demultiplexing pipeline](https://github.com/paulranum11/SPLiT-Seq_demultiplexing) but would need to be done manually post hoc for zUMIs. 

It would be great if there were an option to perform this step early on in the zUMIs pipeline. There are a variety of quality-control reasons why it would be better to perform it _during_ rather than _after_ everything is completed (mainly if you filter for x reads or UMIs per cell, that filter would be applied before this collapsing step rather than after).

Is there a way this could be implemented? We know which barcodes correspond to random hexamers and which correspond to oligo-dT so it doesn't seem like it would be too terribly involved, however whether you manually supply or automatically detect the barcodes likely would have an influence.

Thanks!

**Comment by cziegenhain** [comment]
Hi!

Thanks for your suggestion! 
I think this is a very good feature, and we should also have this functionality for 10x Genomics users where there can be four i7 index sequences for the same cell.

Right now I am thinking it shouldn't be too hard and I would ask users to provide the barcodes belonging together in a text file, where each line corresponds to a cell with however many columns for however many barcodes that belong together with this cell.

Hopefully I can get around to this soon, but can't promise something specific at the moment.
I'll leave this issue open until I have coded something up!

Best,
Christoph

**Comment by jeremymsimon** [comment]
Sounds great- I wonder if it would make sense to roll into the step where you collapse by hamming distance so all the collapsing is happening in one go, but you would probably know best when to incorporate it. Keep us posted! Thanks!

**Comment by cziegenhain** [comment]
Implemented in zUMIs2.7.2, closing here.
