### ISSUE TITLE
running example dataset

### ISSUE THREAD

**Issue by ghalasz** [sdparekh/zUMIs#167]
Hi- thanks for creating this useful tool. I'm have a some trouble getting off the ground with the example dataset:

1) The online shiny tool doesn't load: http://shiny.bio.lmu.de:3838/zUMIs-config/.
2) It would be really helpful to have a ready-to-use yaml file for the example dataset. Is file2 in this case the barcodes file? Is the base definition for the first file -UMI(1-50)? I've tried a number of different ways, all yielding cryptic errors.

Thanks!

**Comment by cziegenhain** [comment]
Hi,

The shiny works for me but the server is uforunately not very fast. You can always of course run the shiny in your local computer using rstudio!

Check the yaml file for running the example dataset here:
https://github.com/sdparekh/zUMIs/blob/master/ExampleData/runExample.yaml

**Comment by ghalasz** [comment]
Thank you so much for the quick reply! The shiny has never loaded for me, and on my local machine complains about the lack of STAR, pigz, etc. (not insurmountable, obviously).

I completely missed the ExampleData directory- apologies! However, running it after pointing to my files, I get, e.g.:

sh: -c: line 0: syntax error near unexpected token `('
samtools view -Sb - > /home/gabor.halasz/zUMIs/example_from_wiki/barcoderead_HEK.1mio.fq.gz /home/gabor.halasz/zUMIs/example_from_wiki/cDNAread_HEK.1mio.fq.gz/zUMIs_output/.tmpMerge/BC(1-6);UMI(7-16) cDNA(1-50).Exampleaf.filtered.tagged.bam

(and so on). Should I open this as a separate issue?

**Comment by cziegenhain** [comment]
No its fine, we can try to troubleshoot this here!
It seems that your yaml file is lacking some line breaks in the right places, can you double check the file?
I have heard of people having issues with text file encoding after opening them on windows machines

Also feel free to upload the config file in here and I can have a look.

**Comment by ghalasz** [comment]
I've now re-created the yaml file using the shiny app on my local (Mac) machine, then uploaded the server and edited the paths with emacs to generate the attached file, i.e. no windows involvement. I get the same error as above. 
[runExample.yaml.txt](https://github.com/sdparekh/zUMIs/files/4178838/runExample.yaml.txt)
Thanks again!

**Comment by cziegenhain** [comment]
Sorry for the slow reply. 
Are you getting the same error message here?
Is there any other verbose from zUMIs? The more information you can give me would probably help to solve this cryptic error.

Your YAML file looks completely correct, just the STAR index should be `STAR_index: /home/gabor.halasz/programs/zUMIs/example_from_wiki/reference/hg38_chr22/` without the `SAindex`. (but that would not be the issue here)

**Comment by cziegenhain** [comment]
Seems like this issue has been inactive, closing.
Feel free to reopen if further help is required.
