### ISSUE TITLE
FATAL ERROR in reads input: quality string length is not equal to sequence length

### ISSUE THREAD

**Issue by GianlucaDuda** [sdparekh/zUMIs#168]
Hi, 

I'm using zUMI pipeline to analyze data coming from https://www.ncbi.nlm.nih.gov/pubmed/27345837. These are Illumina HiSeq 2500 single cell. I got this error several times:

"EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length"
and at the end is telling me:
"SOLUTION: fix your fastq file"

I tried to run a py script in order to get the same length and run again.. but did not work...here what I have done...

before the py script the fastq file looks like:
@SRR3472973.1 1 length=76
NGTGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN
then:
@SRR3472973.1 1 length=76
NGTGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

I tried to run fastq-dum with - F option to get the original header of the file.. but what I got here actually from the .sra file is 
"@SRR3472973.1 1 length=76"

could be the header, missing from the sra file? 

Thanks for your help
G.

**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

Please try to use the flags `--origfmt --defline-qual '+'` with fastq-dump, the SRA format is known to cause issues in zUMIs https://github.com/sdparekh/zUMIs/wiki/Reprocessing-of-public-data

**Comment by cziegenhain** [comment]
Let us know if you need further help.
