### ISSUE TITLE
Problems with zUMIs execution 

### ISSUE THREAD

**Issue by taniachavarria79** [sdparekh/zUMIs#170]
Hello,
We been trying to run zUMIs for a while with no luck, We know the program is well installed in our server as we ran the example data and everything was goo. Nonetheless, when we try to running with our data we encounter several issues.
This is the most recent one, we do not know how to fix it. We really appreciate if you can help us with this:

 You provided these parameters:
 YAML file: /data/scratch/taniach/lobaria_pulmonaria_experiment/lobaria1test_philipp1.yaml
 zUMIs directory: /data/scratch/taniach/zUMIs
 STAR executable STAR
 samtools executable samtools
 pigz executable pigz
 Rscript executable Rscript
 RAM limit:   256
 zUMIs version 2.5.6b

Thu Feb  6 15:04:59 CET 2020
Filtering...
Thu Feb  6 15:30:41 CET 2020
[1] "Using intersection between automatic and whitelist."
[1] "107 barcodes detected automatically."
[1] "Keeping 96 Barcodes."
[1] "17781865 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2020-02-06 15:30:43 CET"
[W::bam_merge_core2] No @HD tag found.
Thu Feb  6 16:30:32 CET 2020
Counting...
[1] "2020-02-06 16:30:38 CET"
[1] "1.152e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//lobaria_experiment1.final_annot.gtf"
Error: subscript contains NAs
Execution halted
Thu Feb  6 16:30:40 CET 2020
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-02-06 16:30:40 CET"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//zUMIs_output/expression/lobaria_experiment1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Feb  6 16:30:41 CET 2020

Here is the yaml file:

project: lobaria_experiment1
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r1.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file3:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r2.fq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index/
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_all_genes_20170213.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun/
num_threads: 48
mem_limit: 256
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~ 
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/zUMIs/
read_layout: SE  

Thanks for your help

**Comment by cziegenhain** [comment]
The error message sounds like your GTF format is broken or odd!

**Comment by taniachavarria79** [comment]
Hello thanks for your response,
Yes we know the problem is we do not have a really complete genome as is not a reference genome, there is many field missing because there is not information. So we need to know what fields need to be of the zUMIs program expect in the GTF file so we modified our GTF file according to what the program needs. We modified it a little bit and now we get this error: 
 
You provided these parameters:
 YAML file:	/data/scratch/taniach/lobaria_pulmonaria_experiment/lobaria1test_philipp1.yaml
 zUMIs directory:		/data/scratch/taniach/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   512
 zUMIs version 2.5.6b 


Thu Feb 20 12:04:53 CET 2020
Filtering...
Thu Feb 20 12:22:05 CET 2020
[1] "Using intersection between automatic and whitelist."
[1] "107 barcodes detected automatically."
[1] "Keeping 96 Barcodes."
[1] "17781865 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2020-02-20 12:22:08 CET"
Thu Feb 20 12:29:47 CET 2020
Counting...
[1] "2020-02-20 12:29:54 CET"
[1] "2e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//lobaria_experiment1.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S lobaria_experiment1.filtered.tagged.Aligne ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 64                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid48365 ...         ||
||    Features : 15607                                                        ||
||    Meta-features : 15254                                                   ||
||    Chromosomes/contigs : 1802                                              ||
||                                                                            ||
|| Process BAM file lobaria_experiment1.filtered.tagged.Aligned.out.bam...    ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 0                                                    ||
||    Successfully assigned alignments : 0                                    ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 96 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  :
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Thu Feb 20 12:30:01 CET 2020
Descriptive statistics...
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
[1] "I am loading useful packages for plotting..."
[1] "2020-02-20 12:30:01 CET"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//zUMIs_output/expression/lobaria_experiment1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Feb 20 12:30:02 CET 2020

**Comment by cziegenhain** [comment]
featureCounts reports no input reads - did you not check the STAR log to see what has happened in the mapping step?

**Comment by taniachavarria79** [comment]
where should I find that STAR log? is not in the output file, I already check all the folders that zUMIs produce with the star name as stargenome, starpass1, starttmp, and there is not STAR log on any of the files

**Comment by reslp** [comment]
Hi, 

I would like to join the conservation here. Together with @taniachavarria79 I try to get zumis to run on her data. First of all, thank you very much @cziegenhain for your help so far. I think you are right that there is a problem with the GTF file. I tried to get it to work but unfortunately it is unclear to us how the GTF file has to look so that it works with zumis. We don't have a good reference genome for our species so our GTF probably contains less information as that of a well-annotated genome would include. From what I saw it has to do with the transcript_id, but we have the transcript_id specified in the GTF file.

Here is a short segment of our GTF file:

```
scaffold_1	prediction	gene	2251	3133	0	-	.	gene_id gene_1; gene_name jgi.p|Lobpul1|1068649; portal_id Lobpul1; protein_id 1068649; transcript_id 1068705
scaffold_1	prediction	mRNA	2251	3133	.	-	.	gene_id mRNA_1; gene_name jgi.p|Lobpul1|1068649; Parent gene_1; protein_id 1068649; track FilteredModels2; transcript_id 1068705
scaffold_1	prediction	exon	2753	3133	.	-	.	gene_id exon_1_1; Parent mRNA_1
scaffold_1	prediction	CDS	2753	3133	.	-	0	gene_id CDS_1; Parent mRNA_1
scaffold_1	prediction	exon	2251	2682	.	-	.	gene_id exon_1_2; Parent mRNA_1
scaffold_1	prediction	CDS	2251	2682	.	-	0	gene_id CDS_1; Parent mRNA_1
scaffold_1	prediction	gene	10816	12540	0	+	.	gene_id gene_2; gene_name jgi.p|Lobpul1|1100134; portal_id Lobpul1; protein_id 1100134; transcript_id 1100190
scaffold_1	prediction	mRNA	10816	12540	.	+	.	gene_id mRNA_2; gene_name jgi.p|Lobpul1|1100134; Parent gene_2; protein_id 1100134; track FilteredModels2; transcript_id 1100190
scaffold_1	prediction	exon	10816	10942	.	+	.	gene_id exon_2_1; Parent mRNA_2
scaffold_1	prediction	CDS	10816	10942	.	+	0	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	exon	11248	11567	.	+	.	gene_id exon_2_2; Parent mRNA_2
scaffold_1	prediction	CDS	11248	11567	.	+	2	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	exon	11642	11709	.	+	.	gene_id exon_2_3; Parent mRNA_2
scaffold_1	prediction	CDS	11642	11709	.	+	0	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	exon	11764	11816	.	+	.	gene_id exon_2_4; Parent mRNA_2
scaffold_1	prediction	CDS	11764	11816	.	+	1	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	exon	11866	11895	.	+	.	gene_id exon_2_5; Parent mRNA_2
scaffold_1	prediction	CDS	11866	11895	.	+	2	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	exon	11943	12540	.	+	.	gene_id exon_2_6; Parent mRNA_2
scaffold_1	prediction	CDS	11943	12331	.	+	2	gene_id CDS_2; Parent mRNA_2
scaffold_1	prediction	three_prime_UTR	12332	12540	.	+	.	gene_id UTR3_2; Parent mRNA_2
scaffold_1	prediction	gene	30897	31319	0	+	.	gene_id gene_4; gene_name jgi.p|Lobpul1|1153414; portal_id Lobpul1; protein_id 1153414; transcript_id 1153470
scaffold_1	prediction	mRNA	30897	31319	.	+	.	gene_id mRNA_4; gene_name jgi.p|Lobpul1|1153414; Parent gene_4; protein_id 1153414; track FilteredModels2; transcript_id 1153470
scaffold_1	prediction	exon	30897	31319	.	+	.	gene_id exon_4_1; Parent mRNA_4
scaffold_1	prediction	CDS	30897	31319	.	+	0	gene_id CDS_4; Parent mRNA_4
scaffold_1	prediction	gene	33236	34816	0	-	.	gene_id gene_5; gene_name jgi.p|Lobpul1|1323312; portal_id Lobpul1; protein_id 1323312; transcript_id 1323368
scaffold_1	prediction	mRNA	33236	34816	.	-	.	gene_id mRNA_5; gene_name jgi.p|Lobpul1|1323312; Parent gene_5; protein_id 1323312; track FilteredModels2; transcript_id 1323368
```
I am not completely shure if this is the log file you are referring to, but it indicates that something is wrong with the transcript_id. Here is a small snippet of the file:
```
eb 20 12:22:17 ..... processing annotations GTF
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	2753	3133	.	-	.	gene_id exon_1_1; Parent mRNA_1
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	2251	2682	.	-	.	gene_id exon_1_2; Parent mRNA_1
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	10816	10942	.	+	.	gene_id exon_2_1; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	11248	11567	.	+	.	gene_id exon_2_2; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	11642	11709	.	+	.	gene_id exon_2_3; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	11764	11816	.	+	.	gene_id exon_2_4; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	11866	11895	.	+	.	gene_id exon_2_5; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	11943	12540	.	+	.	gene_id exon_2_6; Parent mRNA_2
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	30897	31319	.	+	.	gene_id exon_4_1; Parent mRNA_4
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	34173	34816	.	-	.	gene_id exon_5_1; Parent mRNA_5
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	33991	34114	.	-	.	gene_id exon_5_2; Parent mRNA_5
WARNING: while processing pGe.sjdbGTFfile=/data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf: no transcript_id for line:
scaffold_1	prediction	exon	33723	33937	.	-	.	gene_id exon_5_3; Parent mRNA_5
```
I am surprised that zumis seems to load the file correctly (it does not complain at the respective step). Here is what zumis outputs on screen:

```
ou provided these parameters:
 YAML file:	/data/scratch/taniach/lobaria_pulmonaria_experiment/lobaria1test_philipp1.yaml
 zUMIs directory:		/data/scratch/taniach/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   512
 zUMIs version 2.5.6b 


Thu Feb 20 12:04:53 CET 2020
Filtering...
Thu Feb 20 12:22:05 CET 2020
[1] "Using intersection between automatic and whitelist."
[1] "107 barcodes detected automatically."
[1] "Keeping 96 Barcodes."
[1] "17781865 reads were assigned to barcodes that do not correspond to intact cells."
Mapping...
[1] "2020-02-20 12:22:08 CET"
Thu Feb 20 12:29:47 CET 2020
Counting...
[1] "2020-02-20 12:29:54 CET"
[1] "2e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//lobaria_experiment1.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S lobaria_experiment1.filtered.tagged.Aligne ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 64                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid48365 ...         ||
||    Features : 15607                                                        ||
||    Meta-features : 15254                                                   ||
||    Chromosomes/contigs : 1802                                              ||
||                                                                            ||
|| Process BAM file lobaria_experiment1.filtered.tagged.Aligned.out.bam...    ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 0                                                    ||
||    Successfully assigned alignments : 0                                    ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 96 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  :
  assignment of an object of class "numeric" is not valid for @'Dim' in an object of class "dgTMatrix"; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Thu Feb 20 12:30:01 CET 2020
Descriptive statistics...
During startup - Warning message:
Setting LC_CTYPE failed, using "C"
[1] "I am loading useful packages for plotting..."
[1] "2020-02-20 12:30:01 CET"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp2//zUMIs_output/expression/lobaria_experiment1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Thu Feb 20 12:30:02 CET 2020
```

We are greatfull for any suggestion you may have to get this fixed.

kind regards,

Philipp

**Comment by sdparekh** [comment]
Hi, Can you share your mapping stats reported in the file suffix with *.Log.final.out and the first few lines of any of the featurecounts output bam. you can do `samtools view *.featureCounts.bam | head`. I just want to make sure if mapping went right. If possible redirect me to the link you dowloaded the gtf file.

**Comment by reslp** [comment]
Hi, thank you for your help. It seems there is indeed something wrong with the mapping. The bam file is empty, it seems all the reads are in the .tagged.unmapped.bam file.
We created the GTF file ourselves by converting it from a GFF file. If you want I can upload it into a Github repository for you to review it. We had to make some changes to it because there was another problem were zumis stopped with an error at the "Loading reference annotation" step. This was why we expected that there may still be something wrong with it.
Now seeing the empty BAM file, could it be that there is something wrong with the yaml file or the barcode list? 
I see this line in the output: "17781865 reads were assigned to barcodes that do not correspond to intact cells." Is this what you would expect or does it indicate a problem with the barcodes?
Also here is our yaml file, maybe there is a mistake there:

```
project: lobaria_experiment1
sequence_files:
  file1:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r1.fq.gz
    base_definition: 
      - BC(1-6)
      - UMI(7-16)
  file2:
    name: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/_Werth1_r2.fq.gz
    base_definition: cDNA(1-50)
reference:
  STAR_index: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_scotland_V1_STAR_index/
  GTF_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/star_index_scottland_genome/Lobpul1_GeneCatalog_zumis.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /data/scratch/taniach/lobaria_pulmonaria_experiment/zumis_testrun_philipp3/
num_threads: 80
mem_limit: 512
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /data/scratch/taniach/lobaria_pulmonaria_experiment/rawdata/Lobariatest1_BCs.txt
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: no
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /data/scratch/taniach/lobaria_pulmonaria_experiment/zUMIs-2.6.0
read_layout: SE
```
Again, thank you very much for your help!

all the best,

Philipp

**Comment by cziegenhain** [comment]
Hi,

For the GTF file we should wait for a reply from Swati, I'm not too familiar with those intricacies.

For the question of unassigned reads to barcodes:
This depends on the amount of total reads you have, I'd generally expect 5-10% loss or so.
But also I'd as default allow for a mismatch to the expectation 'BarcodeBinning: 1' or you could relax the read filtering criteria a bit. 

Best
Christoph

**Comment by reslp** [comment]
Hi Christoph,

many thanks for your reply. We have about 650 mio reads, so I guess the 17 mio are ok. I will try the BarcodeBinning: 1 missmatch setting now.

viele Grüße,
Philipp

**Comment by sdparekh** [comment]
Hi Philipp,
I see the problem of GFF to GTF conversion. STAR expects all the tags in "exon and CDS" fields. My first guess and suggestion is to add the tags you have in "gene" definition lines. Hopefully, that solves the issue otherwise feel free to contact us.
I have very limited time currently being on maternity leave but i will try to answer ASAP.

Best wishes,
Swati

**Comment by reslp** [comment]
Hi Swati,

thank you for your response and your help. I will look into this. I am sure I can write a small script to add the necessary fields to the GTF. I will report back if it works.

all the best,
Philipp

**Comment by reslp** [comment]
Hi again,

We got it to work. The problem was indeed the formatting of the GTF file (or more the GFF to GTF conversion). Many thanks for your help! If I may make a suggestion: It would be very helpful if the information how a GTF for zUMIs has to look like would be in the zUMIs documentation. Especially for non-model organisms and draft annotations this would be super helpful and save a lot of time. 

Many thanks again for your help!

best,
Philipp

**Comment by cziegenhain** [comment]
Hey Philipp,

great to hear that things are running now.
Can you tell me what was the key change for you that helped get the GTF into the right format?
