### ISSUE TITLE
conda-unpack: command not found

### ISSUE THREAD

**Issue by lihairi** [sdparekh/zUMIs#172]
When I tried to run example data, the following error happened and the program is halted.

zUMIs-master.sh: line 152: conda-unpack: command not found
Error: 
Execution halted

Where can I get package or program with "conda-unpack" command?

Thanks,

**Comment by cziegenhain** [comment]
Hi,

I'm currently out travelling with limited access to internet, but could you send:
your exact zUMIs command
info on your operating system
your YAML file

Best,
C

**Comment by cziegenhain** [comment]
Reopen here if you need further input!
