### ISSUE TITLE
Error in if (!inp$num_threads >= 1) { : argument is of length zero

### ISSUE THREAD

**Issue by yueli711** [sdparekh/zUMIs#173]
Hello, cziegenhain,

Thank you for developing so great software zUMIs.

I have error ` !inp$num_threads >= 1`, actually my `runExample.yaml `file `num_threads: 8`.

Please see attached file.

Thank you in advance for your great help!

Best,

Yue

```
li@Desktop-590-p0xxx:~$ bash ~/zUMIs-master/zUMIs-master.sh -y runExample.yaml 
Error in if (!inp$num_threads >= 1) { : argument is of length zero
Execution halted
/home/li/zUMIs-master/zUMIs-master.sh: line 165: [[: "Number: syntax error: operand expected (error token is ""Number")
tee: /.zUMIs_runlog.txt: Permission denied
[runExample.zip](https://github.com/sdparekh/zUMIs/files/4295709/runExample.zip)
[runExample.zip](https://github.com/sdparekh/zUMIs/files/4295711/runExample.zip)


```
[runExample.zip](https://github.com/sdparekh/zUMIs/files/4295714/runExample.zip)

**Comment by jeremymsimon** [comment]
Hi @yueli711 and @cziegenhain - do you know what the source of this error is? I'm helping a collaborator get zUMIs running on their compute cluster and am receiving the same error. But it is set as

`num_threads: 20`

**Comment by cziegenhain** [comment]
I haven't encountered this one, I could imagine that it happens when the YAML is not correctly formatted? E.g. if there is an extra space after the numbers?

**Comment by jeremymsimon** [comment]
Yes- for future users who end up here, the yaml was edited in a Windows text editor and therefore formatted with Windows/CRLF line endings. A quick `tr -d "\r" < yamlfile.yaml > yamlfile_new.yaml` fixed it and got everything running.

**Comment by cziegenhain** [comment]
ah great - thanks for the code snippet!
