### ISSUE TITLE
Loom file from umicounts has format issues

### ISSUE THREAD

**Issue by Jachimdejonghe** [sdparekh/zUMIs#175]
**Describe the bug**
Hi, I hope you are well! So I have installed loomR and velocyto and run zUMIs. When i try to read the file sample.umicount.inex.all.loom in scanpy it gives me the following error message :

adata = sc.read('sample.umicount.inex.all.loom', cache=True)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-f9553f3575ec> in <module>
----> 1 adata1 = sc.read('sample.umicount.inex.all.loom', cache=True)
      2 adata1.var_names_make_unique()
      3 
      4 
      5 adata1

~/anaconda3/envs/bam/lib/python3.7/site-packages/scanpy/readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    120             cache=cache,
    121             cache_compression=cache_compression,
--> 122             **kwargs,
    123         )
    124     # generate filename and read to dict

~/anaconda3/envs/bam/lib/python3.7/site-packages/scanpy/readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
    689         adata = _read_softgz(filename)
    690     elif ext == 'loom':
--> 691         adata = read_loom(filename=filename, **kwargs)
    692     else:
    693         raise ValueError(f'Unknown extension {ext}.')

~/anaconda3/envs/bam/lib/python3.7/site-packages/anndata/_io/read.py in read_loom(filename, sparse, cleanup, X_name, obs_names, obsm_names, var_names, varm_names, dtype, **kwargs)
    189     from loompy import connect
    190 
--> 191     with connect(filename, "r", **kwargs) as lc:
    192         if X_name not in lc.layers.keys():
    193             X_name = ""

~/anaconda3/envs/bam/lib/python3.7/site-packages/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1387                 Note: if validation is requested, an exception is raised if validation fails.
   1388 	"""
-> 1389         return LoomConnection(filename, mode, validate=validate)

~/anaconda3/envs/bam/lib/python3.7/site-packages/loompy/loompy.py in __init__(self, filename, mode, validate)
     80                         lv = loompy.LoomValidator()
     81                         if not lv.validate(filename):
---> 82                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{lv.version}'")
     83 
     84                 self._file = h5py.File(filename, mode)

ValueError: Row attribute 'gene_names' dtype object is not allowed
Column attribute 'cell_names' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
sample.umicount.inex.all.loom does not appead to be a valid Loom file according to Loom spec version '0.0.0'

whereas the sample.loom generated from Velocyto seems to run fine. Would you perhaps be able to let me know how you think I could load the inex.umicounts.loom file into Scanpy?

Additionally, I think it would be super useful to merge the generated UMIcounts loom (introns and exons) with the velocyto loom. To avoid complications from re-naming and merging matrices based on gene names when trying to merge both datasets. I would assume this will maybe take some time to write, but would be very useful.

As usual, thanks a lot for the help!

All the best,
Jo

**To Reproduce**
project: Proj
sequence_files:
file1:
name: /path/proj_R1.fastq.gz
base_definition: cDNA(1-61)
file2:
name: /path/proj_R2.fastq.gz
base_definition: BC(1-8)
file3:
name: /path/proj_R3.fastq.gz
base_definition: BC(1-8)
file4:
name: /path/proj_R4.fastq.gz
base_definition:
- BC(1-8)
- UMI(9-14)
reference:
STAR_index: /path/STARfull
GTF_file: /path/Mus_musculus.GRCm38.99.gtf
additional_STAR_params: ''
additional_files: ~
out_dir: /path/zumis/Out/Proj
num_threads: 8
mem_limit: 0
filter_cutoffs:
BC_filter:
num_bases: 1
phred: 20
UMI_filter:
num_bases: 1
phred: 20
barcodes:
barcode_num: ~
barcode_file: ~
automatic: yes
BarcodeBinning: 0
nReadsperCell: 100
counting_opts:
introns: yes
downsampling: '0'
strand: 0
Ham_Dist: 0
velocyto: yes
primaryHit: yes
twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /path/zumis/zUMIs
read_layout: SE

**Comment by cziegenhain** [comment]
Hi!

Sorry that this is not working as expected. I don't personally use the loom output much (and that shows)
I'll try to look at this asap

**Comment by cziegenhain** [comment]
Hi Jachim,
Sorry for the long delay.
I just had a look and i can read looms with `scanpy.read_loom()` just fine.
Is this maybe because you just used `read()` instead?

**Comment by Jachimdejonghe** [comment]
Hello, awesome! I wiped all my data so I can't double check.

I always used scanpy.read for loom files, and it worked, so I wonder what happened. I will close the issue.

**Comment by Jachimdejonghe** [comment]
Hello, just to mention I still encounter this error from above (I have the latest zUMIs and scanty installed). I wonder what could be happening:
ValueError                                Traceback (most recent call last)
<ipython-input-4-611ca86f3500> in <module>
----> 1 adata1 = sc.read("snRNA_10x_3_1.readcount.exon.downsampled_5000.loom")
      2 
      3 
      4 

~/opt/anaconda3/envs/poin/lib/python3.8/site-packages/scanpy/readwrite.py in read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, **kwargs)
    110     filename = Path(filename)  # allow passing strings
    111     if is_valid_filename(filename):
--> 112         return _read(
    113             filename,
    114             backed=backed,

~/opt/anaconda3/envs/poin/lib/python3.8/site-packages/scanpy/readwrite.py in _read(filename, backed, sheet, ext, delimiter, first_column_names, backup_url, cache, cache_compression, suppress_cache_warning, **kwargs)
    715         adata = _read_softgz(filename)
    716     elif ext == 'loom':
--> 717         adata = read_loom(filename=filename, **kwargs)
    718     else:
    719         raise ValueError(f'Unknown extension {ext}.')

~/opt/anaconda3/envs/poin/lib/python3.8/site-packages/anndata/_io/read.py in read_loom(filename, sparse, cleanup, X_name, obs_names, obsm_names, var_names, varm_names, dtype, **kwargs)
    189     from loompy import connect
    190 
--> 191     with connect(filename, "r", **kwargs) as lc:
    192         if X_name not in lc.layers.keys():
    193             X_name = ""

~/opt/anaconda3/envs/poin/lib/python3.8/site-packages/loompy/loompy.py in connect(filename, mode, validate, spec_version)
   1387                 Note: if validation is requested, an exception is raised if validation fails.
   1388 	"""
-> 1389         return LoomConnection(filename, mode, validate=validate)

~/opt/anaconda3/envs/poin/lib/python3.8/site-packages/loompy/loompy.py in __init__(self, filename, mode, validate)
     80                         lv = loompy.LoomValidator()
     81                         if not lv.validate(filename):
---> 82                                 raise ValueError("\n".join(lv.errors) + f"\n{filename} does not appead to be a valid Loom file according to Loom spec version '{lv.version}'")
     83 
     84                 self._file = h5py.File(filename, mode)

ValueError: Row attribute 'gene_names' dtype object is not allowed
Column attribute 'cell_names' dtype object is not allowed
For help, see http://linnarssonlab.org/loompy/format/
snRNA_10x_3_1.readcount.exon.downsampled_5000.loom does not appead to be a valid Loom file according to Loom spec version '0.0.0'

Thanks for the help!

**Comment by cziegenhain** [comment]
Hi!
Do you think it's possible to upload an example loom file so I can see what might be happening?

Best,
Christoph
