### ISSUE TITLE
zUMIs bug when mapping

### ISSUE THREAD

**Issue by ytang0831** [sdparekh/zUMIs#177]
**Describe the bug**
Hi I have 16 cells in one R1.fq and R2.fq, and I want to use zUMIs to split these 16 cells and do more single cell analysis.  I used the method of STAR index generate in WiKi usage to get my STAR index(my STAR version is 2.5.4b) without providing --sjdbOverhang and --sjdbGTFfiles
STAR --runMode genomeGenerate --runThreadN 16 --genomeDir mm10_STAR5idx_noGTF --limitGenomeGenerateRAM 111000000000 --genomeFastaFiles mm10.fa

And I do get 16 parent barcodes. While during mapping, I get the error --sjdbOverhang is not rigtht,so i use # to comment out this paremeter. Then go on,  I get wnt3a-rna-1.filtered.tagged.Aligned.out.bam (62kb),and wnt3a-rna-1.filtered.tagged.unmapped.bam(1.5Gb). That means something wrong when filtering and mapping, because when i use my method to split the fq files and do mapping with STAR, it can get some output although the alignment rate is low.

Log.std.out
Apr 14 14:10:37 ..... started STAR run
Apr 14 14:10:37 ..... loading genome
Apr 14 14:14:41 ..... processing annotations GTF
Apr 14 14:14:50 ..... inserting junctions into the genome indices

the tail of log.out
Processing sjdbGTFfile=/opt/database/gencode.mouse.v1.annotation.gtf, found:
		95495 transcripts
		677632 exons (non-collapsed)
		243332 collapsed junctions
Apr 14 14:14:50 ..... finished GTF processing
Apr 14 14:14:50   Loaded database junctions from the GTF file: /opt/database/gencode.mouse.v1.annotation.gtf: 243332 total junctions

WARNING: long repeat for junction # 139492 : chr3 93128497 93133185; left shift = 229; right shift = 255
WARNING: long repeat for junction # 162795 : chr5 11344881 11419828; left shift = 255; right shift = 27
WARNING: long repeat for junction # 207941 : chr7 148994101 148996209; left shift = 255; right shift = 255
WARNING: long repeat for junction # 238310 : chrX 83497260 83546166; left shift = 255; right shift = 168
Apr 14 14:14:50   Finished preparing junctions
Apr 14 14:14:50 ..... inserting junctions into the genome indices
Apr 14 14:21:18   Finished SA search: number of new junctions=243240, old junctions=0
Apr 14 14:22:04   Finished sorting SA indicesL nInd=97295638
Apr 14 14:23:00   Finished inserting junction indices
Apr 14 14:23:15   Finished SAi

My yaml file:
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: wnt3a-rna-1

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /opt/wnt3a-wnt1-RNA/wnt3a-wnt1-RNA_1.fq.gz #path to first file
    base_definition:
      - cDNA(57-150)
      - BC(1-22)
  file2:
    name: /opt/wnt3a-wnt1-RNA/wnt3a-wnt1-RNA_2.fq.gz #path to second file
    base_definition:
      - cDNA(58-150)
      - BC(1-23)

#reference genome setup
reference:
  STAR_index: /opt/database/STARindexmm9 #path to STAR genome index
  GTF_file: /opt/database/gencode.mouse.v1.annotation.gtf #path to gene annotation file in GTF format
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /opt/result1 #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 1 
mem_limit: 25 #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 20
    phred: 8
  UMI_filter:
    num_bases: 20
    phred: 8

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: 
  barcode_file: /opt/wntBC.txt 
  automatic: no #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: yes #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  write_ham: no #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths

#below, fqfilter will add a read_layout flag defining SE or PE
zUMIs_directory: /opt/zUMIs-master
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: /opt/STAR-2.5.4b/bin/Linux_x86_64/STAR
Rscript_exec: Rscript
read_layout: PE

**Desktop (please complete the following information):**
 - Ubantu
 - Version 18.0.4

Thanks!

**Comment by cziegenhain** [comment]
Hi,
Did you solve your issue?

Best,
Christoph

**Comment by ytang0831** [comment]
> Hi,
> Did you solve your issue?
> 
> Best,
> Christoph

Hi, I did some tests, and finally it turned out to be a hardware problem.
After I moved the software environment to the server, the problem was resolved
Thanks, Christoph, great software!

Now I have some other confusion. Since my server is not connected to the Internet, my results are annotated. Does zUMIs have annotation function? By the way, do you have any Suggestions for converting zumis results to Seurat objects？

Thanks a lot！

**Comment by cziegenhain** [comment]
Great to hear that the issue resolved and you like zUMIs!

What exactly do you mean with annotation, I'm not sure I understand.

To get the data into Seurat, a few simple steps should be sufficient:
Load zUMIs output count table object:
`dge  <- readRDS("project.dgecounts.rds")`
Then extract the quantification of your choice (depends on if you want exon, exon+intron or downsampling; [see also here](https://github.com/sdparekh/zUMIs/wiki/Output#structure-of-the-output-dgecounts-object-in-project_namedgecountsrds)):
`mat <- dge$umicount$exon$all`
With this you can create your Seurat object:
`CreateSeuratObject(counts = mat)`

**Comment by ytang0831** [comment]
I'm sorry for not making clear what annotation means. Now have the result with Ensemble ID, so I wonder if zUMIs have the function to convert Ensemble ID into Gene symbol ID?

**Comment by cziegenhain** [comment]
Ah I see! No, at the moment this is not part of the functionality.

Best,
Christoph

**Comment by ytang0831** [comment]
Thanks!  
I have cDNA in both R1 and R2 files. I did a test, split R1 and R2 separately and then do mapping, and the ratio was 70%. After splitting R1 and R2 at the same time , the ratio was reduced to 50% in both SE mode and PE mode. Is that normal?

**Comment by cziegenhain** [comment]
This is entirely dataset dependent.
It can be that your reads don't find compatible mappings as pairs. This would be more a question for the developers of STAR.
In zUMIs, there is no SE/PE mode, if you give cDNA definitions in both R1+R2, zUMIs will always consider this as PE. If you have only one cDNA defined in your config file it will be SE.

**Comment by cziegenhain** [comment]
Hi,

I added functionality to automatically provide the geneID to gene name mapping in the latest zUMIs update.
Thanks for the suggestion!

Best,
Christoph

**Comment by ytang0831** [comment]
@cziegenhain Thanks！
