### ISSUE TITLE
BUG Hamming distance throws a mclapply error

### ISSUE THREAD

**Issue by Jachimdejonghe** [sdparekh/zUMIs#179]
**Describe the bug**
Hello, I tried changing the hamming distance to 1 (Ham_Dist: 1). However this throws a mclapply error at me during the Counting phase, which is resolved when I put it back to 0.  Let me know if this error can be reproduced, or if it is just because I have a very long barcode or so :)

egistered S3 methods overwritten by 'ggplot2':

  method         from

  [.quosures     rlang

  c.quosures     rlang

  print.quosures rlang

Registered S3 methods overwritten by 'ggplot2':

  method         from

  [.quosures     rlang

  c.quosures     rlang

  print.quosures rlang

Error in mclapply(readsamples_list, function(x) ham_helper_fun(x), mc.cores = use_cores,  :

  'mc.cores' must be >= 1

Calls: umiCollapseHam -> mclapply

Execution halted

Loading required package: yaml

Loading required package: Matrix

Warning message:

package ‘hdf5r’ was built under R version 3.6.2

Error in gzfile(file, "rb") : cannot open the connection

Calls: rds_to_loom -> readRDS -> gzfile

In addition: Warning message:

In gzfile(file, "rb") :

  cannot open compressed file '/PATH/9h.dgecounts.rds', probable reason 'No such file or directory'

Execution halted

[E::hts_open_format] Failed to open file NA

samtools view: failed to open "NA" for reading: No such file or directory

Registered S3 methods overwritten by 'ggplot2':

  method         from

  [.quosures     rlang

  c.quosures     rlang

  print.quosures rlang

Error in gzfile(file, "rb") : cannot open the connection

Calls: readRDS -> gzfile

In addition: Warning message:

In gzfile(file, "rb") :

  cannot open compressed file '/PATH/9h.dgecounts.rds', probable reason 'No such file or directory'

Execution halted

zUMIs/zUMIs-master.sh: line 310: [: =: unary operator expected

**To Reproduce**

yaml file:

project: INDEXm
sequence_files:
  file1:
    name: /PATH/INDEXct_R1.fastq.gz
    base_definition: cDNA(1-61)
  file2:
    name: /PATH/INDEXct_R2.fastq.gz
    base_definition:
    - BC(1-32)
    - UMI(33-38)
reference:
  STAR_index: /PATH/STAR_m93_60
  GTF_file: /PATH/Mus_musculus.GRCm38.93.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /PATH/Out/INDEXm
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  velocyto: yes
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Counting
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /PATH/zUMIs
read_layout: SE

**Comment by cziegenhain** [comment]
Hey,

Yes i see where that issue occurs in the code, thanks for making me aware!
I'll push an update later today, in the meantime this error should not occur if you set a memory limit.
I recommend that anyway to avoid problems. eg `mem_limit: 50`

**Comment by Jachimdejonghe** [comment]
Sweet, thanks a lot. 
Absolutely thank you for mentioning, I was exploring these kind of things when I ran into the bug. I will definitively do what you recommended as it makes perfect sense in this case.

Thanks again for being so quick and efficient.

Cheers,
Jo

**Comment by Jachimdejonghe** [comment]
Hello, I tried to git pull but I get a merge error, this used to work though:

Auto-merging zUMIs-master.sh
CONFLICT (content): Merge conflict in zUMIs-master.sh
Auto-merging zUMIs-dge2.R
Auto-merging UMIstuffFUN.R
Auto-merging README.md
CONFLICT (content): Merge conflict in README.md
Automatic merge failed; fix conflicts and then commit the result.

**Comment by cziegenhain** [comment]
That's really odd! I'd recommend to delete and clone the whole repo from new, just to exclude weird effects rom merging.

**Comment by cziegenhain** [comment]
Closing here for now, let me know if I can help further.
