### ISSUE TITLE
yaml file modified after run start

### ISSUE THREAD

**Issue by ndu-UCSD** [sdparekh/zUMIs#185]
**Describe the bug**
yaml file modified after run start

**Desktop (please complete the following information):**
 - OS: CentOS Linux
 - Version: 7

I specified the directory where apps are located 

YAML file (before run started):
samtools_exec: /mnt/BioHome/ndu/anaconda3/bin/samtools
pigz_exec: /mnt/BioHome/ndu/anaconda3/bin/pigz
STAR_exec: /mnt/BioHome/ndu/anaconda3/bin/STAR
Rscript_exec: /mnt/BioHome/ndu/anaconda3/bin/Rscript

Once the run started the yaml file was changed to the following settings. 

samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript

And I got the following error:
pigz: abort: write error on <stdout> (Broken pipe)

Not sure why the config file was modified by the pipeline; would you help on that please? Thanks

**Comment by cziegenhain** [comment]
Hi,

If you use the conda implementation `zUMIs-master.sh -c,` zUMIs will use these default value because the dependencies should then be found in path.

**Comment by ndu-UCSD** [comment]
Thanks. So to use the apps I specified should I do 
zUMIs-master.sh -y my_config.yaml without the -c flag?

**Comment by cziegenhain** [comment]
Exactly!

**Comment by ndu-UCSD** [comment]
Gotcha, thank you~
