### ISSUE TITLE
BUG : File path error

### ISSUE THREAD

**Issue by hengshanzi** [sdparekh/zUMIs#186]
Hi,
When I run the test data and the Smartseq3 data, I met the same problems. 
“.stat: cannot stat ‘....../test_zUMIs/run_test/zUMIs_output/.tmpMerge//Example.1mio.check.fq.gz’: No such file or directory
rm: cannot remove ‘....../test_zUMIs/run_test/zUMIs_output/.tmpMerge//Example.1mio.check.fq.gz’: No such file or directory
”
**To Reproduce**
**My YAML file**
project: Example
sequence_files:
  file1:
    name: ....../test_zUMIs/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - BC(1-6)
    - UMI(7-16)
  file2:
    name: ....../test_zUMIs/cDNAread_HEK.1mio.fq.gz
    base_definition:
    - cDNA(1-50)
reference:
  STAR_index: ....../test_zUMIs/reference/hg38_chr22
  GTF_file: ....../test_zUMIs/reference/GRCh38.84.chr22.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: ....../test_zUMIs/run_test
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
zUMIs_directory: ....../4zUMIs/zUMIs
read_layout: SE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript

**Desktop (please complete the following information):**
CentOS Linux release 7.6.1810

so，How to deal with this problem?
thanks~

**Comment by cziegenhain** [comment]
Hi,

I'm assuming you just shortened the paths with ... for uploading to GitHub? zUMIs needs absolute paths, relative paths will lead to errors.
It reads to me that the input files can't be found, please double check.

**Comment by cziegenhain** [comment]
reopen if more help is needed.
