### ISSUE TITLE
Scheduled cores did not deliver results

### ISSUE THREAD

**Issue by jeremymsimon** [sdparekh/zUMIs#187]
At a few spots in the zUMIs output to stdout, I get variations on this warning:

```Warning message:
In parallel::mclapply(gtf_info, function(x) { :
  scheduled cores 3, 5, 12, 22, 26 did not deliver results, all values of the jobs will be affected
```

```
[1] "Correcting UMI barcode tags..."
Warning messages:
1: In mclapply(readsamples_list, function(x) ham_helper_fun(x), mc.cores = use_cores,  :
  scheduled cores 2, 7, 12, 13, 22, 24 did not deliver results, all values of the jobs will be affected
2: In mclapply(readsamples_list, function(x) ham_helper_fun(x), mc.cores = use_cores,  :
  scheduled cores 6, 12 did not deliver results, all values of the jobs will be affected
[1] "Coordinate sorting final bam file..."
```

The run seemingly completes successfully, however. 

Are these warnings indicative of a major problem or can they be ignored? Note this doesn't seem to occur on our clean Google Cloud instance of zUMIs v2.8.0, but occurs on our linux compute cluster

**Comment by cziegenhain** [comment]
Hey,

These are different errors of multicore operations in R, sorry for the unspecific error messages.
 
The first one is just a little helper operation to make a geneID - geneName mapping table and should be harmless.

The second one seems to occur when writing hamming-distance collapsed UMI tags to bam file format. There will be a scheduled job for each cell barcode. If some of those jobs crash for some reason, you could risk loosing some cell barcodes in your final output bam & count table. In some instances, I have observed zUMIs using more CPU load than allocated, is that a possible reason the jobs might fail in your compute cluster? The step does not consume any significant RAM, only read-write access & CPU load.

**Comment by jeremymsimon** [comment]
It seems like our particular system has a limit on the number of processes set to 4096. I'm not sure how difficult it would be, but is it possible to impose a limit of some kind (maybe in the yaml config) for a max number of processes like that? I think that may be the underlying source of this issue and our other issue (#141) where the python demultiplexing script may hang, and the perl version can't properly fork.

**Comment by cziegenhain** [comment]
That definitely makes sense for the demultiplexing! I have a plan how to circumvent this issue, it's rather simple but time is currently very limited.

For the above warnings: I don't think that the GTF parsing should have more processes than you give threads in the YAML file, unless R does something bizarre. For the tag correction I would expect approx. 3 processes per thread you give in the YAML: 2xsamtools for input & output and 1x perl script doing the actual parsing.

**Comment by jeremymsimon** [comment]
Hmm so if I'm specifying 48 threads, how might we be exceeding 4096?

**Comment by cziegenhain** [comment]
that is what i am not understand here either, I will keep closer tabs on what's going on next time I run zUMIs myself.

**Comment by jeremymsimon** [comment]
Okay thanks. I'm not 100% sure of this, but it *seems* to be specific to v2.8.0, and not v2.7.2. Especially not sure how that might be the case...

**Comment by cziegenhain** [comment]
The geneName to GeneID mapping function came in with v2.7.3, so that makes sense, the UMI tag correction hasn't changed at all unfortunately...

**Comment by jeremymsimon** [comment]
That's true- however due to the hang, I never got that far on either version in this environment! So it's likely I would have seen it before too

**Comment by HeChao7021** [comment]
I also got the following error:
Warning message:
In parallel::mclapply(gtf_info, function(x) { :
  all scheduled cores encountered errors in user code
I want to know whether it would affect the final resut or not. Thanks

**Comment by cziegenhain** [comment]
in the best case you will simply not get a geneID to gene name mapping table. However it could also mean there is an issue with the GTF file format and that would definitely affect the results.

**Comment by HeChao7021** [comment]
> in the best case you will simply not get a geneID to gene name mapping table. However it could also mean there is an issue with the GTF file format and that would definitely affect the results.

Yes, and the result I got is very unrealistic, I only got several hundred genes, the number is far away from that reported in the published paper. I will check the gtf file, thanks. Here is the yaml I used:
project: SRR12340621
sequence_files:
  file1:
    name: /public/workspace/xuyongyue/snRNA/L001.fq.gz
    base_definition:
    - BC(1-16)
    - UMI(17-28)
  file2:
    name: /public/workspace/xuyongyue/snRNA/L002.fq.gz
    base_definition: cDNA(1-91)
reference:
  STAR_index: /public/workspace/xuyongyue/snRNA/db/ar-genome
  GTF_file: /public/workspace/xuyongyue/snRNA/db/Arabidopsis_thaliana.TAIR10.48.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /public/workspace/xuyongyue/snRNA/SRR12340621fillout
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
