### ISSUE TITLE
'cut: write error: No space left on device' problem

### ISSUE THREAD

**Issue by barosmarko** [sdparekh/zUMIs#19]
Dear zUMIs developers,

I managed to run zUMIs with example data you provided on the EC2 instance, and everything was good! Later, I've tried it with one lane of the 10x t_4k dataset (approx. 4GB):
`bash /opt/zUMIs/zUMIs-master.sh -f /sbgenomics/Projects/project_number/t_4k_S1_L001_R1_001.fastq.gz -r /sbgenomics/Projects/project_number/t_4k_S1_L001_R2_001.fastq.gz -n 10x_t4k_64proc_chrall_proba1 -g star_reference_dir/**/ -a /sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec8370b5/Homo_sapiens.GRCh38.77.gtf -c 1-16 -m 17-26 -l 98 -p 64 -o /opt`

This is what I get when I run:

Your jobs will run on this machine. 

Make sure you have more than 28G RAM and 64 processors available. 

Your jobs will be started from filtering. 

 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec8370b5/t_4k_S1_L001_R1_001.fastq.gz
 cDNA read:			/sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec8370b5/t_4k_S1_L001_R2_001.fastq.gz
 Study/sample name:		10x_t4k_64proc_chrall_proba1
 Output directory:		/sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec8370b5/workspace/543dae27-1c19-4dbf-ba70-989e000a8259/zumis
 Cell/sample barcode range:	1-16
 UMI barcode range:		17-26
 Retain cell with >=N reads:	100
 Genome directory:		star_reference_dir/genomeDir/
 GTF annotation file:		/sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec8370b5/Homo_sapiens.GRCh38.77.gtf
 Number of processors:		64
 Read length:			98
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Barcodes:			NA
 zUMIs directory:		/opt/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:	
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 

Raw reads: 41504804 
Filtered reads: 37232133 

Jan 16 16:10:53 ..... started STAR run
Jan 16 16:10:53 ..... loading genome
Jan 16 16:11:06 ..... processing annotations GTF
Jan 16 16:11:19 ..... inserting junctions into the genome indices
Jan 16 16:12:49 ..... started 1st pass mapping
Jan 16 16:14:11 ..... finished 1st pass mapping
Jan 16 16:14:12 ..... inserting junctions into the genome indices
Jan 16 16:15:54 ..... started mapping
Jan 16 16:20:00 ..... finished successfully
[bam_sort_core] merging from 0 files and 64 in-memory blocks...
[bam_sort_core] merging from 0 files and 64 in-memory blocks...
Loading required package: optparse
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
The "phase" metadata column contains non-NA values for features of type
stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am loading useful packages..."
[1] "2018-01-16 16:21:48 UTC"
[1] "I am loading Rsubread 1.26.0..."
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-01-16 16:21:55 UTC"
[1] "I am making count tables...This will take a while!!"
[1] "2018-01-16 16:23:21 UTC"
        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0
//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /sbgenomics/Projects/6a988ca3-4ac1-486a-9a ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//
//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid85274 ...       ||
||    Features : 290201                                                       ||
||    Meta-features : 29849                                                   ||
||    Chromosomes/contigs : 226                                               ||
||                                                                            ||
|| Process BAM file /sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec83 ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 37232133                                                  ||
||    Successfully assigned reads : 9295781 (25.0%)                           ||
||    Running time : 1.45 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//
        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0
//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /sbgenomics/Projects/6a988ca3-4ac1-486a-9a ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//
//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid85274 ...       ||
||    Features : 1232660                                                      ||
||    Meta-features : 54014                                                   ||
||    Chromosomes/contigs : 270                                               ||
||                                                                            ||
|| Process BAM file /sbgenomics/Projects/6a988ca3-4ac1-486a-9abd-b4aeec83 ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 37232133                                                  ||
||    Successfully assigned reads : 24235413 (65.1%)                          ||
||    Running time : 1.59 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//
[1] "I am loading useful packages for plotting..."
[1] "2018-01-16 16:26:58 UTC"
**cut: write error: No space left on device
cut: write error: No space left on device
Error: Columns `XC`, `XM` must be length 1 or 6012786, not 2485514, 2485514
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
cannot open compressed file '/sbgenomics/Projects/project_number/workspace/instance_number/zumis/zUMIs_output/expression/10x_t4k_64proc_chrall_proba1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted**

I've been searching for the same problem, and I noticed that problem could be that the inodes are maybe full. This is first time I see this kind of problem. Did you face this kind of problem? What do you suggest to resolve it?

Thank you in advance!

Best,
Marko

**Comment by barosmarko** [comment]
Hey guys,

Just want to let you know, I've checked the inodes and they are ok:
`df -i`
Filesystem            Inodes IUsed     IFree IUse% Mounted on
none               196608000 89191 196518809    1% /
tmpfs               33017874    18  33017856    1% /dev
tmpfs               33017874    13  33017861    1% /sys/fs/cgroup
/dev/mapper/crypto 196608000 89191 196518809    1% /etc/hosts
shm                 33017874     1  33017873    1% /dev/shm

`df -h`
Filesystem          Size  Used Avail Use% Mounted on
none                2.9T   39G  2.7T   2% /
tmpfs               126G     0  126G   0% /dev
tmpfs               126G     0  126G   0% /sys/fs/cgroup
/dev/mapper/crypto  2.9T   39G  2.7T   2% /etc/hosts
shm                  64M     0   64M   0% /dev/shm

It looks it is something else.

**Comment by cziegenhain** [comment]
Hey Marko,

Sorry that it took some time for us to get back to this issue.
It seems that the execution fails at the stage of reading in gene IDs and barcode information into R using data.table::fread.
Normally, R needs to place a temporary file somewhere in the system because we cut only the necessary columns instead of reading full files.
As far as I know, the fread function tries to use the /dev/shm partition for this, which seems pretty small in your instance. Unfortunately, data.table [doesn't support a custom tmp path yet](https://github.com/Rdatatable/data.table/issues/1139).
Could you please increase /dev/shm to a couple Gb, and give it another go?

I hope this helps to fix the problem, let me know.

Best,
Christoph
