### ISSUE TITLE
readline() on closed filehandle HEAD

### ISSUE THREAD

**Issue by MartaBenegas** [sdparekh/zUMIs#190]
Hi! 
While running zUMIs I get this error line a really large amount of times:
`readline() on closed filehandle HEAD at /usr/local/zUMIs/misc/demultiplex_BC.pl line 46.`
I would like to paste you the whole error but I can not scroll up any further. 
There are the last lines:
```
readline() on closed filehandle HEAD at /usr/local/zUMIs/misc/demultiplex_BC.pl line 46.
readline() on closed filehandle HEAD at /usr/local/zUMIs/misc/demultiplex_BC.pl line 46.
readline() on closed filehandle BAM at /usr/local/zUMIs/misc/demultiplex_BC.pl line 53.
[main_samview] fail to read the header from "-".
samtools cat: fail to open file '/data/output/10x/zUMIs_output/demultiplexed/mm_neuron_10x.AAAGATGGTCAGCTATCTAGGTGA.demx.UBcorrected.bam': No such file or directory
Error in strsplit(GE, ",") : object 'GE' not found
Calls: convert2countM -> .makewide -> unlist -> strsplit
Execution halted
Loading required package: yaml 
Loading required package: Matrix
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:  
In gzfile(file, "rb") :
  cannot open compressed file '/data/output/10x/zUMIs_output/expression/mm_neuron_10x.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:  
In gzfile(file, "rb") :
  cannot open compressed file '/data/output/10x/zUMIs_output/expression/mm_neuron_10x.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```
I was running it with a [10x dataset](https://support.10xgenomics.com/single-cell-gene-expression/datasets/3.0.0/neuron_1k_v2) with only the 001 lane. I've runned zUMIs before with this dataset and it didn't give me any error, what could be possibly happening?
PD: I'm running zUMIs again because I've realized that de detected barcodes are 25pb long but they should be 16 (as I specified on the yaml file). Any ideas about this? 
[ec2-user@ip-172-31-27-115 10x]$ head mm_neuron_10x.BCstats.txt 
```
TCTGAGAGTAATCGTCCTAGGTGA	2
TTTCCTCTCTTAGAGCCTAGGTGA	1
ACTGAACAGACCACGACTAGGTGA	1
TGGCGCACAGACAAGCCTAGGTGA	1
ATCATGGTCGCGTAGCCTAGGTGA	2
CTAAGTGAAGGCTACGCTAGGTGA	1
GTTAAGCAGGCTATCTCTAGGTGA	1
TGGACGCTCGCCCTTACTAGGTGA	1
GGAACTTAGTAATCCCCTAGGTGA	1
TCAGGTAGTATAGGGCCTAGGTGA	1
```
The .yaml file: 
[zUMIs.txt](https://github.com/sdparekh/zUMIs/files/4678557/zUMIs.txt)

**Comment by cziegenhain** [comment]
Hi Marta,

The detected barcodes are 24 bases long because you specify 16 bases barcode in file1 and 8 bases barcode in file3, so 16+8 = 24bp :)
I see that you use the barcode_sharing feature which is important in the case of 10x, as their i7/index1 read is a particular case.

For the error encountered during demultiplexing: It's unfortunate that we can't see the first error message; but I suspect that you cannot have sufficient open file handles in parallel. What does `ulimit -n` return?
In general I'd say if you can have pysam installed zUMIs should use an internal python script for demultiplexing instead which can more easily deal with datasets with tons of cells.

Another unrelated note on your yaml: 1) I generally give a bit lower memory limit because it actually isn't much slower but a bit safer (i have seen cases where the memory can be unexpectedly exceeded).  2) The default filtering cutoffs for cell BC and UMI are quite strict, especially since you have long barcodes.

 Best,
Christoph

**Comment by MartaBenegas** [comment]
Hi Cristoph,
thanks for the barcode clarification! I didn't realize it could be the sample index. 

Unfortunately right now the server is stopped so I can't tell you what `ulimit -n` return. It's a little bit strange, because I was using the same server as the first time and I didn't encounter this error before. If I retry the pipeline I'll install pysam and let you know if everything works fine :)

Thank you for the advice! So for these long barcodes, do you recommend increasing the number of bases, the phred score or both?

Thank you very much for your help,
Marta.

**Comment by cziegenhain** [comment]
I'd just change the number of bases, maybe ~4 for BC and ~3 for the UMI. I'd say it depends on how many reads you kick out & how the quality overall in the run was!

**Comment by MartaBenegas** [comment]
Got it! I'll keep that in mind for the next time. 
I'll close the issue for now :)

**Comment by MartaBenegas** [comment]
Hi!
I've re-runned it and it gives me the same error. I've stored the stdout in a file just like this 
`root@b3677e0f5112:/data/input# time zUMIs -y zUMIs_10x.yaml > 10x_zumis.log`
And here you have the file: [10x_zumis.txt](https://github.com/sdparekh/zUMIs/files/4688747/10x_zumis.txt)
The stderr is printed on the screen and after a large amount of readline() lines here you have the last ones:
```
readline() on closed filehandle HEAD at /usr/local/zUMIs/misc/demultiplex_BC.pl line 46.
readline() on closed filehandle HEAD at /usr/local/zUMIs/misc/demultiplex_BC.pl line 46.
readline() on closed filehandle BAM at /usr/local/zUMIs/misc/demultiplex_BC.pl line 53.
[main_samview] fail to read the header from "-".
samtools cat: fail to open file '/data/output/10x/zUMIs_output/demultiplexed/mm_neuron_10x.CATGGCGGTAAATGTGCTAGGTGA.demx.UBcorrected.bam': No such file or directory
Error in strsplit(GE, ",") : object 'GE' not found
Calls: convert2countM -> .makewide -> unlist -> strsplit
Execution halted
Loading required package: yaml 
Loading required package: Matrix
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:  
In gzfile(file, "rb") :
  cannot open compressed file '/data/output/10x/zUMIs_output/expression/mm_neuron_10x.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:  
In gzfile(file, "rb") :
  cannot open compressed file '/data/output/10x/zUMIs_output/expression/mm_neuron_10x.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

real    25m42.668s
user    343m36.135s
sys     18m4.868s
```
And the information you asked:
```
root@b3677e0f5112:/data/input# ulimit -n
1024
```
Best,
Marta.

**Comment by cziegenhain** [comment]
Hi Marta,

Yes that's what I thought, you have more cell barcodes than open file handles are permitted. 
I'd recommend for you to set a higher file handle limit, like `ulimit -n 10240`.
The error should then go away!

Best,
Christoph

**Comment by MartaBenegas** [comment]
Hi Cristoph, 
that was it! now it works fine :)
I was thinking: I've seen that there is an option to demultiplex by cell, but is there any way to obtain one DGE for each sample using that sample index? so I can decide later if analyze them separately or together.

Best,
Marta.

**Comment by cziegenhain** [comment]
Great that it works.

I'm not sure if I understand your question correctly ,but the sample index sequence is always part of the cell barcode label so you can subset the count table as needed later.  
The demultiplexing option refers to also giving you the output bam file per cell.

**Comment by MartaBenegas** [comment]
Hi!
I meant if there is any option to obtain  directly one dge per sample, but I'll subset it as you say. 

Thanks,
Marta.
