### ISSUE TITLE
BUG  --sjdbOverhang value does not match genome generation

### ISSUE THREAD

**Issue by Jachimdejonghe** [sdparekh/zUMIs#191]
**Describe the bug**
Hi Christoph, I am running a trimmed 247 bp file (quality and adapter trimmed). When I run zUMIs, I get the following error: EXITING because of fatal PARAMETERS error: present --sjdbOverhang=243 is not equal to the value at the genome generation step =246
SOLUTION:

My genomeParameters.txt for STAR index looks like:
STAR   --runMode genomeGenerate   --runThreadN 20   --genomeDir STAR_MM99_247   --genomeFastaFiles Mus_musculus.GRCm38.dna.primary_assembly.fa      --genomeSAindexNbases 14   --genomeChrBinNbits 18   --genomeSAsparseD 9   --limitGenomeGenerateRAM 50000000000   --sjdbGTFfile Mus_musculus.GRCm38.99.sncRNA.gtf   --sjdbOverhang 246

Does zUMIs somehow try to re-define --sjdbOverhang with trimmed reads? When I try to manually put --sjdbOverhang in additional STAR parameters yaml it tells me it can't have two definitions of --sjdbOverhang

Also can't untrim, as those are the files that were given to me.

Thanks!
Jo

**To Reproduce**
project: FOLDER
sequence_files:
  file1:
    name: PATH/File1.fastq.gz
    base_definition: cDNA(1-247)
  file2:
    name: PATH/File2.fastq.gz
    base_definition:
    - BC(1-32)
    - UMI(33-38)
reference:
  STAR_index: PATH/STAR_MM99_247
  GTF_file: PATH/Mus_musculus.GRCm38.99.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: PATH/OUT/FOLDER
num_threads: 8
mem_limit:80
filter_cutoffs:
  BC_filter:
    num_bases: 5
    phred: 20
  UMI_filter:
    num_bases: 2
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  velocyto: yes
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: PATH/zUMIs
read_layout: SE

**Comment by cziegenhain** [comment]
Hi,

Please prepare the index without any GTF file for zUMIs!
https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping

**Comment by Jachimdejonghe** [comment]
Great thanks, somehow missed that!
