### ISSUE TITLE
BUG: samtools expects program name header lines

### ISSUE THREAD

**Issue by gringer** [sdparekh/zUMIs#192]
**Describe the bug**

Samtools v1.10 appears to require any SAM format piped through 'samtools view' to require a program header line (starting `@PG`).

**To Reproduce**
Run zUMIs with samtools v1.10 or later with any YAML file. An example YAML file is attached.

```
$ ~/install/zUMIs/zUMIs-master.sh -y zUMI_run7/zUMI_1M_Fibroblasts_test7.yaml

 You provided these parameters:
 YAML file:     zUMI_run7/zUMI_1M_Fibroblasts_test7.yaml
 zUMIs directory:               /home/gringer/install/zUMIs
 STAR executable                /home/gringer/bin/STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   0
 zUMIs version 2.8.2 

Mon Jun 15 11:43:56 NZST 2020
Filtering...
pigz: abort: write error on <stdout> (Broken pipe)
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
[main_samview] fail to read the header from "-".
 done filtering...
[main_samview] fail to read the header from "/mnt/BigBirdStornext/Illumina/public/Smart-Seq3/zUMI_run7/zUMIs_output/.tmpMerge//zUMI_1M_Fibroblasts_test7.zUMI_1M_Fibroblasts_test7aa.filtered.tagged.bam".
Mon Jun 15 11:46:30 NZST 2020
Error in eval(bysub, parent.frame(), parent.frame()) : 
  object 'XC' not found
Calls: cellBC -> [ -> [.data.table -> eval -> eval
In addition: Warning message:
In data.table::fread(bccount_file, header = FALSE, col.names = c("XC",  :
  File '/mnt/BigBirdStornext/Illumina/public/Smart-Seq3/zUMI_run7/zUMI_1M_Fibroblasts_test7.BCstats.txt' has size 0. Returning a NULL data.table.
Execution halted

```
[zUMI_1M_Fibroblasts_test6.yaml.txt](https://github.com/sdparekh/zUMIs/files/4777777/zUMI_1M_Fibroblasts_test6.yaml.txt)
[Note: this file has an additional problem in that the barcode/UMI thresholds are not specified]

[fqfilter_v2.pl.diff.txt](https://github.com/sdparekh/zUMIs/files/4777759/fqfilter_v2.pl.diff.txt)

**Desktop**
 - OS: Debian Linux [5.6.0-1-amd64 #1 SMP Debian 5.6.7-1 (2020-04-29) x86_64 GNU/Linux]
 - zUMIs version 2.8.2

**Possible Solution**

I have attached a patch that adds the following header to SAM files as the first line emitted to any output BAM files:

    "@"."PG	ID:zUMIs-fqfilter	PN:zUMIs-fqfilter	VN:2	CL:fqfilter_v2.pl ${argLine}\n"

The patch also adds additional information (e.g. emitting filter errors, and estimated read counts) that helped me in diagnosing this bug.

**Comment by cziegenhain** [comment]
Hey,

Thanks for reporting and providing a potential solution! 
I'll look into this a bit more. Your explanation makes total sense and fits with the samtools changelog. the odd thing is, I have been running with samtools 1.10 without issues since about february. 
Anyway it's probably good to write out properly headered bam files so I will add that soon.

Best,
Christoph

**Comment by cziegenhain** [comment]
Thanks for your pull request! I gave it a few test datasets and all seems good. 
The SAM header printing should take care of this issue
