### ISSUE TITLE
Is there any way to set mismatch number for barcode when filtering ?

### ISSUE THREAD

**Issue by ytang0831** [sdparekh/zUMIs#196]
Hi @cziegenhain , Tanks for your perfect tools,  Is there any way to set mismatch number for barcode when filtering ?

**Comment by cziegenhain** [comment]
Hi,
Thanks for using zUMIs!
You can control how many mismatches to barcodes are being considered using the `BarcodeBinning` setting in the config file
https://github.com/sdparekh/zUMIs/blob/main/zUMIs.yaml#L67

Best
Christoph

**Comment by ytang0831** [comment]
Thanks a lot! @cziegenhain
