### ISSUE TITLE
*.zUMIs_runlog.txt not found

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#200]
Using zUMIs-2.9.3...

Line 188 of the zUMIs.sh script outputs the runlog.txt to $outdir/$project, but by this stage of the script the outdir doesn't appear to be created (not till line 215) and so get a file not found error.

I guess either move the output folder creation chunk up or change line 188 to " zUMIs version ${vers} \n\n" | tee "${project}.zUMIs_runlog.txt"" to get around the minor issue.

**Comment by cziegenhain** [comment]
Hi!

Absolutely, you are right!
I pushed a fix resolving this.

Thanks for the hint!

Best,
Christoph
