### ISSUE TITLE
BUG: split: unrecognized option '--filter=pigz'

### ISSUE THREAD

**Issue by wm-takara** [sdparekh/zUMIs#203]
**Describe the bug**
I was getting this error using the supplied conda environment. The error was apparently from split (part of GNU coreutils).

**To Reproduce**
This appears to only be an issue if you are using a machine with an old version of split (mine was from 2010).
I received the error message when I was using the example dataset provided with the file locations changed for my local system (example_data.yaml):
$ zUMIs/zUMIs.sh -c -y example_data.yaml

**Solution**
$ conda activate zUMIs/zUMIs-env
$ which split
/usr/bin/split

Upgrading to split version 8.31 worked for me:
$ conda install coreutils
$ split --version
split (GNU coreutils) 8.31

**Comment by cziegenhain** [comment]
Hi,

Thanks a lot for the bug report, the coreutils must have slipped when I created the miniconda environment. 
Will add coreutils in the next update!

Let me know if I can help otherwise.

/Christoph
