### ISSUE TITLE
How to include all barcodes from the 10X 3' version 3 whitelist

### ISSUE THREAD

**Issue by TheSingleCell** [sdparekh/zUMIs#205]
Dear Team,
Thank you so much to develop zUMIs! It helps a lot on my project.
I want to look into the low-quality cells or non-cell droplets in my dataset obtained from 10X chromium 3' v3. The company provides a whitelist for all barcodes (about 6.8 million barcodes), and I want to include the expression profiles for these 6.8 million barcodes (including the barcodes that have empty reads) into the final count matrix from the zUMIs output (either *.rds or *.loom file). Is there a way to do this? I assume I can change the settings in the yaml file as below?
**barcodes:
  barcode_num: 6794880 
  barcode_file: /mnt/sdd/10x3v3_barcodes.txt
  automatic: no 
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 0 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.**
Really appreciated!!!
Nelson

**Comment by cziegenhain** [comment]
Hey Nelson,

You don't need to specify the barcode_num, if you give the barcode whitelist together with automatic: no and nReadsperCell: 0 (as you have it above), you should get all encountered cell barcodes in the count table outputs.

Let me know if you encounter any issues!

**Comment by TheSingleCell** [comment]
Thanks so much for the prompt reply! Sure, I will give it a try today. Do you think the output matrix will be super big? I think loom file is a better file format to store huge dataset than rds file but I don't know how to tell zUMIs not to output the rds file.

**Comment by cziegenhain** [comment]
Yes I think the output file can get really big and I'd assume that the pipeline could get slowed down pretty significantly.
You may consider to set the nReadsperCell value to something around the default of 100 to trim off a bit.
The rds file output file can't be switched off, but is typically also relatively space efficient since we utilise the compressed sparse matrix format.

**Comment by TheSingleCell** [comment]
OK, got you. I will try. Thanks again!

**Comment by cziegenhain** [comment]
Closing for now, let us know if you need more help.
/Christoph
