### ISSUE TITLE
how to get a matrix contains all CB in the whitelist

### ISSUE THREAD

**Issue by YOU-k** [sdparekh/zUMIs#206]
Hi, I was trying to use zUMIs on CEL-seq2 data sets (384 well), but i would only obtain about 200 cells in rds. Actually, i want to have a full UMI count matrix containing all CBs and then filter myself. Settings in yaml file is:
barcodes:
  barcode_num: ~
  barcode_file: /data/barcode_annotation
  automatic: no
  BarcodeBinning: 1
  nReadsperCell: 0
  demultiplex: no
Could you help me figure out why this happen and how to get a full matrix? Thanks!

**Comment by cziegenhain** [comment]
Hi,

With these settings, it would mean that the other wells/cell barcodes did not have any reads at all.
I recommend to check that you are not being overly strict in the basecall quality filtering of barcode reads.

**Comment by YOU-k** [comment]
Thanks!

**Comment by YOU-k** [comment]
I tried with lower phred and I got two more cells, which means I still only have about 200 cells. To make sure why some cells are lost, I tried scruff, scPipe and kallisto bustools. Surprisingly, I would got all the 384 cells with any of them. (only about 10 cells say there are 0 mapped reads). So I checked the methods used in each pipeline to collapse CBs, you all use Hamming distance, and I set it at 1 if there is an option. Do you have any idea why this happen? Thanks!

**Comment by YOU-k** [comment]
And I checked for a specific CB in the whitelist, CCGTTAAG. This barcode was not obtained with zUMIs. I checked BCstats.txt and found a record : CCGTTAAN  48742. and the settings in yaml was 
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 10
  UMI_filter:
    num_bases: 1
    phred: 10.

**Comment by cziegenhain** [comment]
Hi,

Ah so it seems like all your reads have just N in the last position. Is that the case for all reads (ie check your fastQC). If so, I would recommend to use one base shorter for extraction of the cell barcode and adapt your whitelist accordingly.
That being said, if there is no other whitelisted barcodes within a hamming distance, BarcodeBinning: 1 should work here.

**Comment by YOU-k** [comment]
Hi, Great! Thanks for your suggestion.

**Comment by YOU-k** [comment]
So, does this mean when applying Hamming distance, N is not taken into consideration?

**Comment by cziegenhain** [comment]
N is treated like any letter in the distance calculation, so that should be ok.

**Comment by YOU-k** [comment]
I am bit confused. so why CCGTTAAN was not corrected to CCGTTAAG?

**Comment by cziegenhain** [comment]
The only reason I could think of is if there would be another barcode in the whitelist with the same distance, eg.  CCGTTAAT.
If you want to upload your data I can take a look as soon as time permits.

**Comment by YOU-k** [comment]
I have solve it by using a base shorter whitelist. Thanks!

**Comment by cziegenhain** [comment]
Great! Let me know if I can help further.
