### ISSUE TITLE
Using output files in Seurat 

### ISSUE THREAD

**Issue by curtisd0886** [sdparekh/zUMIs#208]
Is it possible to get some help using the output files in Seurat? I have tried using both the loom files and rds files without any luck. It seems the loom file contains header names that are not compatible. Any help you can offer with this would be greatly appreciated.

**Comment by cziegenhain** [comment]
Absolutely, we're happy to help! 
For Seurat, I'd typically load the expression matrix from the rds file.

For example:
`zumis_output <- readRDS("zUMIs_output/expression/xyz.dgecounts.rds")`
Then grab the matrix of your choice, e.g. UMI counts for exon features:
`umis <- as.matrix(zumis_output$umicount$exon$all)`
This is all you need to start using Seurat:
`seu <- Seurat::CreateSeuratObject(counts = umis)`

Best,
Christoph

**Comment by cziegenhain** [comment]
Feel free to reopen if further help is needed.

/C

**Comment by jeremymsimon** [comment]
@cziegenhain can you clarify: if I want _all_ counts, ie those from exons, introns, and exon-intron boundaries, is that what is represented in `object$umicount$inex$all` or do I need to take the sum of `object$umicount$exon$all + object$umicount$intron$all + object$umicount$inex$all`? I couldn't seem to find precise language in the documentation or the paper. Thanks!

**Comment by cziegenhain** [comment]
Hi,

Sorry for the unclear description. Yes the inex counts is what you are looking for. 
Exon = any read that is at least partially in an exon (can also be partially intron overlapping!)
Intron = any read that is overlapping with an intron but no exon
IntronExon = any read overlapping intron or exon

Best,
Christoph
