### ISSUE TITLE
Invalid value was provided for reportReads parameter

### ISSUE THREAD

**Issue by micknudsen** [sdparekh/zUMIs#21]
Hi,

I am trying to run your pipeline on some DropSeq data, but I'm running into troubles in the dge script. Everything seems to work fine until all of a sudden this happens:

```
[1] "I am loading useful packages..."
[1] "2018-01-30 14:34:13 CET"
[1] "I am loading Rsubread 1.28.0..."
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-01-30 14:34:27 CET"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-01-30 14:39:26 CET"
Error in Rsubread::featureCounts(files = abamfile[1], annot.ext = safannot[[1]],  :
  Invalid value was provided for reportReads parameter.
Calls: makeGEprofile -> <Anonymous>
Execution halted
```

Do you have any clue what could possibly be wrong? I am using a slightly newer version of Rsubread than the one you recommend (I have troubles accessing CRAN from the HPC cluster I'm using, so I'm restricted to version availble in bioconda).

**Comment by cziegenhain** [comment]
Hey,

Thanks for using zUMIs!
This is indeed the problem of using the slightly newer Rsubread build. The issue is that the reportReads parameter usage and output was changed. Internally, we have already updated zUMIs to work with the new Rsubread format but we are still testing and checking for bugs.

I hope we can release the update soon so you'll be able to use zUMIs!

Best,

Christoph

**Comment by micknudsen** [comment]
Thanks for getting back so quickly. I am sure that it will be possible for me to somehow install the previous version of Rsubread. It will just be painful, so I wanted to make sure that it was actually the thing causing troubles.

**Comment by cziegenhain** [comment]
Sure, happy to help out. Good luck with the installation!

Just as a note: there was also a warning in your log that must have come from something odd in your gtf file, but maybe it'll be fine. 

Let me know if we can be of further assistance!

**Comment by micknudsen** [comment]
Yeah, noticed that one, too. Crossing my fingers that everything is going to be OK. I am using the combined human/mouse GTF from the [McCarroll Lab DropSeq](http://mccarrolllab.com/dropseq/) page.

ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63269/suppl/GSE63269_hg19_mm10_transgenes_reference_metadata.tar.gz
