### ISSUE TITLE
Compute cluster has ulimit set to just 8192. Code changes to accommodate demultiplexing SPLIT-seq data?

### ISSUE THREAD

**Issue by jeremymsimon** [sdparekh/zUMIs#210]
Hi,
I'm helping get another lab to analyze SPLIT-seq data with zUMIs, and they are running into a demultiplexing issue. I suspect it is because their `ulimit -n` is apparently set to only 8192. We will find out if they can increase it, but do you have recommendations on ways we can get the run through? Should we change the number of chunks around `line 380` of `UMIstuffFUN.R`?

<img width="1263" alt="Screen Shot 2020-08-28 at 12 29 00 PM" src="https://user-images.githubusercontent.com/37712091/91608156-01c52780-e943-11ea-8c55-3cb75764c11e.png">

**Comment by cziegenhain** [comment]
Yes that could be tried, however I suspect that it will just fail in the step when the error corrected bam files are then combined again. 
For that step I am currently using `samtools merge` which avoids needing to sort the bam file again but I suspect it needs a file handle per BC then. 
Alternative is `samtools cat` followed by `samtools sort` - obviously sorting is quite resource hungry. 

I'll investigate alternative ways to write the error corrected UMI sequences to bam files soon, so keeping this issue open here as a reminder.

**Comment by jeremymsimon** [comment]
Okay thanks! We'll see if IT is willing to increase their `ulimit` but if you can find a workaround that would be great!

**Comment by cziegenhain** [comment]
Hi,

Today I pushed an update that includes a much faster step for writing the hamming corrected UMI tags to the bam file that also does not require a large number of open filehandles.
Please give it a go and let me know!

**Comment by jeremymsimon** [comment]
Thanks @cziegenhain we will give this a try!

**Comment by cziegenhain** [comment]
Hope this helped, feel free to reopen this issue if necessary.

**Comment by jeremymsimon** [comment]
We ended up having the same issue with the new version, unfortunately. If you have any other ideas, that would be helpful! In the meantime we ran it on GCP to get around the issue

**Comment by cziegenhain** [comment]
I can look at a log if you upload it here!

**Comment by jeremymsimon** [comment]
Looks like it works after all! Thanks so much!

**Comment by cziegenhain** [comment]
Fantastic!
