### ISSUE TITLE
BUG Error at counting stage after loading gtf file

### ISSUE THREAD

**Issue by Jachimdejonghe** [sdparekh/zUMIs#211]
**Describe the bug**
Hello,
I am running the pipeline again with some new samples, and it runs smoothly for Filtering and Mapping. However, it seem to fail at the Counting stage. I think the error seems to be after loading the gtf file (which looks fine to me). No RDS files are created and it seems like it doesn't enter the subhead package. Thanks a lot!

Error file: 
Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Error in loadNamespace(name) : there is no package called ‘plyranges’
Calls: .makeSAF ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
Loading required package: yaml
Loading required package: Matrix
Warning message:
package ‘hdf5r’ was built under R version 3.6.2
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/Path/Sample.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Registered S3 methods overwritten by 'ggplot2':
  method         from
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/Path/Sample.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

Output file:
Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!

 You provided these parameters:
 YAML file:     yaml/Sample.yaml
 zUMIs directory:               /Path
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   10
 zUMIs version 2.9.3e

Wed  9 Sep 09:03:24 BST 2020
WARNING: The STAR version used for mapping is 2.7.5c and the STAR index was created using the version 2.7.4a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.5c.
Mapping...
[1] "2020-09-09 09:03:24 BST"
Sep 09 09:03:33 ..... started STAR run
Sep 09 09:03:34 ..... loading genome
Sep 09 09:03:59 ..... processing annotations GTF
Sep 09 09:04:11 ..... inserting junctions into the genome indices
Sep 09 09:06:10 ..... started 1st pass mapping
Sep 09 11:12:14 ..... finished 1st pass mapping
Sep 09 11:12:16 ..... inserting junctions into the genome indices
Sep 09 11:15:41 ..... started mapping
Sep 09 14:51:49 ..... finished mapping
Sep 09 14:51:52 ..... finished successfully
Wed  9 Sep 14:51:54 BST 2020
Counting...
[1] "2020-09-09 14:52:04 BST"
[1] "1.5e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/Path/Sample.final_annot.gtf"
Wed  9 Sep 14:52:46 BST 2020
[1] "loomR found"
Wed  9 Sep 14:52:48 BST 2020
[1] "2020-09-09 14:52:49 BST"
[1] "Preparing bam file for velocyto..."
[1] "2020-09-09 14:52:49 BST"
[1] "Attempting to run RNA velocity..."
[1] "RNA velocity done!"
[1] "2020-09-09 14:52:59 BST"
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2020-09-09 14:52:59 BST"
Wed  9 Sep 14:53:40 BST 2020

Thank you for the help.
**To Reproduce**
Provide the YAML file and full standard output.
project: Sample
sequence_files:
  file1:
    name: /Path/File_R1.fastq.gz
    base_definition: cDNA(1-114)
  file2:
    name: /Path/File_R2.fastq.gz
    base_definition: BC(1-8)
  file4:
    name: /Path/File_R3.fastq.gz
    base_definition:
    - BC(1-8,31-38)
    - UMI(39-44)
reference:
  STAR_index: /Path/STAR_MM99
  GTF_file: /Path/Mus_musculus.GRCm38.99.gtf
  additional_STAR_params: '--outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread 0 --outFilterMatchNmin 0'
  additional_files: ~
out_dir: /Path/Sample
num_threads: 10
mem_limit: 10
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 1
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Counting
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
zUMIs_directory: /Path
read_layout: SE

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Jachimdejonghe** [comment]
Hi Christoph,
Thank you, I just installed ply ranges but now get the following:
Error in library(ggplot2) : there is no package called ‘ggplot2’
Execution halted
Loading required package: yaml
Loading required package: Matrix
Warning message:
package ‘hdf5r’ was built under R version 3.6.2
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/Path/Sample.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in library(ggplot2) : there is no package called ‘ggplot2’
Execution halted

**Comment by cziegenhain** [comment]
Check all your packages from the link above!
Alternatively you can use the conda environment in zUMIs (`zUMIs.sh -c` )to make sure all dependencies are there.

**Comment by Jachimdejonghe** [comment]
Hi,
I did a R re-install in my environment and also re installed all the packages and it seems to be running now, sorry for that.

Cheers,Jo

**Comment by cziegenhain** [comment]
Nice that its running now!
