### ISSUE TITLE
reproduce smart-seq3 data from the paper

### ISSUE THREAD

**Issue by sanxiongliu** [sdparekh/zUMIs#212]
Hi,

I also tried to reproduce the scRNA-Seq data from the papaer using zUMIs. I always got the same error: Error in data.table::fread(paste(samtools, "view", filtered_bams[1], "| cut -f10 | head -n 1000"), :
input= contains no \n or \r, but starts with a space. Please remove the leading space, or use text=, file= or cmd=
Execution halted.

It seems an error in the intermediate file.  See attached for log and yaml files. 
[Liu_9456325.txt](https://github.com/sdparekh/zUMIs/files/5204712/Liu_9456325.txt)
[run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5204713/run.yaml.txt)
[Smartseq3.zUMIs_runlog.txt](https://github.com/sdparekh/zUMIs/files/5204714/Smartseq3.zUMIs_runlog.txt)
[Smartseq3.zUMIs_YAMLerror.log](https://github.com/sdparekh/zUMIs/files/5204715/Smartseq3.zUMIs_YAMLerror.log)

Can you suggest a solution? Thanks.

**Comment by cziegenhain** [comment]
Hi,

Sorry that you are having trouble running the pipeline.
I don't see any obvious errors in your yaml, but it all goes wrong when preparing to map.
Can you check if the `Smartseq3.filtered.tagged.unmapped.bam` file is being produced in your output folder?
Would be good to see the first few lines of that file to check if everything up till mapping went ok.

best,
Christoph

**Comment by sanxiongliu** [comment]
Hi Christoph,

Thanks for your quick response. The unmapped.bam files are not produced yet, only many Smartseq3.Smartseq3aa.raw.tagged.bam and Smartseq3.Smartseq3aa.filtered.tagged.bam there.

I checked the first few lines of tagged.bam, see below:
NB502120:148:HFLKVBGXC:1:11101:3777:1052        77      *       0       0       *       *       0       0       AACCANAGGAGAGCAGAGCAGTTTCAAACAGCAGCACCACAAGGTCCTTGACAGCTTTGTCGTTTTTGTCTGCCTCAGCCTTCTTCCGCAGGGTCTCCACGATGGGGTGGTCAGGGTTGATCTACAGGTGTTTTTTGGCCATCATGTAGC  AAAAA#EEEEEAEEEE/EAEEEEEEEEEEEEEAEEAEE/A/E/EEEEEEEEEEEE/EEEEEEEE/EEEE/EEA6EE/E/EEEAE/EEAEEEEE/EEEE/EEEEEEEEEAEE/AEE/EEA/EA///EEE/E6<<EEEAEEAE//EEEA<EA  BX:Z:TACCGTCTNCCAGCTA   BC:Z:TACCGTCTNCCAGCTA   UB:Z:   QB:Z:AAAAAEEE#AAAAAEA   QU:Z:
NB502120:148:HFLKVBGXC:1:11101:3777:1052        141     *       0       0       *       *       0       0       GTGTATATNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNAGGACGAGGAAGANAAGAANAAAATNGAGNNNNGNANGGNNAAGTNN  AAAAAAEE###############################################################################################EEA/EEEAEEEEE#EEE/E#EAEEE#EE/####E#E#AE##/AEE##  BX:Z:TACCGTCTNCCAGCTA   BC:Z:TACCGTCTNCCAGCTA   UB:Z:   QB:Z:AAAAAEEE#AAAAAEA   QU:Z:
NB502120:148:HFLKVBGXC:1:11101:11596:1058       77      *       0       0       *       *       0       0       CACACNCACAGTGCCCATCTATGAGGGCTACGCCCTTCCCCACGCCATCTTGCGTCTGGACCTGGCTGGCCGGGACCTGACAGACTACCTCATGAAGATCCTGACTGAACGGGGCTACAGCTTTACCACCACTGCTGAGAGGGAAATTGT  AAAAA#/<EEEEEEEEEEEEEEEAEAAEEEEEE<EEEEEEEEEEEEEEEEAEEEEEEEEEEEEEAEEEEEEEEE/EEAEAEEE6EAEEEAEA<EEEA/EEE/E/EEE//EEEEE<AEAAEEEEE/EE<<E/6AEEEEEE/EEEEEEEEEE  BX:Z:TCCTTGCTNCCGCATT   BC:Z:TCCTTGCTNCCGCATT   UB:Z:   QB:Z:AAAAAEEE#AAAAEEE   QU:Z:
NB502120:148:HFLKVBGXC:1:11101:11596:1058       141     *       0       0       *       *       0       0       GGCCAGAATGNNNNNNNNNNNNNANNCNNANNNNTTNCNCNCANGGGNNGNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTTCTGCATCCTGTCAGCAATGCCTGGGTACATGGTGGTACCACCAGACAGCAC  6AAAAEEEAE#############A##E##E####EE#E#E#E<#EEE##/###############################################EEEEEEEEEEEEEEEEEEEEEEEEEAEEEEEEEEAEEE<AE/EEEEEE/EEEA  BX:Z:TCCTTGCTNCCGCATT   BC:Z:TCCTTGCTNCCGCATT   UB:Z:   QB:Z:AAAAAEEE#AAAAEEE   QU:Z:

The Smartseq3.detected_cells.pdf is produced in output/stats folder. I tried different smart-srq3 data from the paper, both human cell line and mouse cell line. The exactly same error shows up.

I actually use the example data as you suggested in github/wiki, it works quite well.
[Smartseq3.detected_cells.pdf](https://github.com/sdparekh/zUMIs/files/5209333/Smartseq3.detected_cells.pdf)

**Comment by cziegenhain** [comment]
Hi,

Hmm those files look actually good to me & it should not error out. I have to say that I am not 100% certain what causes this, especially if you say the example data worked OK for you.
I just pushed an update for zUMIs today and I included an explicit call for `cmd` in the data.table function that gives the error (default was `input`), so please update your zUMIs and try again.

Best,
Christoph

**Comment by sanxiong-liu** [comment]
Hi Christoph,

I tested the newly released zUMIs for both example data and smart-seq3 data from the paper. Unfortunately, it only works for the example data as the earlier version. But it seems moving a step further than before. The job in output/.tmpMerge is done, the program fails once the folder output/.tmpMap is created. All the bam files in Merge folder are deleted by the program, but no bam files are generated. See attached for the log and yaml files for the 1M_Reads dataset and full dataset.

By the way, how should we set the parameter sjdbOverhang when generating the star index? I use 145bp, the index seems working for the 1M_Reads data but not for the full dataset. The sequencing are using PE 150bp.

Thanks.
[fibro_1M_reads.run.log.txt](https://github.com/sdparekh/zUMIs/files/5213495/fibro_1M_reads.run.log.txt)
[fibro_1M_reads.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5213496/fibro_1M_reads.run.yaml.txt)
[firboblast.run.log.txt](https://github.com/sdparekh/zUMIs/files/5213497/firboblast.run.log.txt)
[firboblast.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5213498/firboblast.run.yaml.txt)

**Comment by cziegenhain** [comment]
Thanks for trying this out so quickly.
Although you got some files, it still cannot finish the same step, sorry for that!

To me, it looks like samtools is not being called correctly, which is odd given that you seem to run with zUMIs' internal conda environment that has all dependencies. Incidentally, I am noting that the samtools path is missing from your yaml file. The pipeline should fix that by itself, but maybe can you just add `samtools_exec: samtools` to your yaml and try once more?

For the sjdbOverhang, please generate the STAR index without giving a gtf file or a specific overhang. zUMIs then asks STAR to make the sjdb calculations on the fly given the observed read length in your current run. Like this you need only one index for whatever read lenghts you will be running in the future.

BEst,
Christoph

**Comment by sanxiongliu** [comment]
Hi Christoph,

I included samtools_exec: samtools in the yaml file, however it disappeared in the run.yaml file. Anyway, I copied the last few lines from the runExample.yaml file in your github and it got fixed. I can't explain why. I got the .rds file finally. Hope it will also work for my own smart-seq3 data in the near future.

Another issue, I requested ~300GB memory from HPC and put 300GB as mem limit in the .yaml file. The program stopped as out of memory (see attached log and yaml files for your review). I replaced the mem_limit to null and it worked out with still 300GB requested.

Thanks for your help and developing such a great tool.
[out of memory.log.txt](https://github.com/sdparekh/zUMIs/files/5222194/out.of.memory.log.txt)
[out of memory.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5222195/out.of.memory.run.yaml.txt)

**Comment by cziegenhain** [comment]
Hi again,

That is very odd behavior, as the pipeline should only remove the line to fix it with the correct `samtools` from the conda environment. But if it works consistently now we'll just move on!

For the memory issue, the memory limit often not being adhered to very precisely, so I usually leave a margin of error. There is also little speedup above say ~150 Gb RAM (similar above 100 threads of CPU), so that's what I tend to run with!

 Best,
Christoph

**Comment by cziegenhain** [comment]
Feel free to reopen if more help is required.
