### ISSUE TITLE
Demultiplex files does not show up

### ISSUE THREAD

**Issue by taniachavarria79** [sdparekh/zUMIs#214]
Hello I need the demultiplex files that zUMIs produce in the zUMIs output but the demultiplex carpet are empty. 
I did this before with the older version and everything was fine, now with the new version ask for the recent version of STAR to make the catalog, so I did again the catalog with this new version but when zUMIs start to run leave a message that Iam using the older version of STAR, so it not recognised the new version.
Then start to run okay and finish fine but when I look for the demultiplex files that what I need the carpet is empty
Here is the zUMIs running text and my yaml information .
Thanks so much for your help

[zumis_runlog889_philipp.txt](https://github.com/sdparekh/zUMIs/files/5268896/zumis_runlog889_philipp.txt)
[lobaria_analysis_zumisexp2algae.yaml.txt](https://github.com/sdparekh/zUMIs/files/5268903/lobaria_analysis_zumisexp2algae.yaml.txt)

**Comment by cziegenhain** [comment]
Hi,

Sorry I'm not sure if I understand what you are describing. What do you mean by carpet?
From what I gather the demultiplexed bam files are missing? In your log, it seems like it worked on that step for about 30 min so I'd be surprised if really nothing happened. 
Anyway you can always try to explicitly run the demultiplexing script one more time without rerunning the whole pipeline:
`python3 zUMIs/misc/demultiplex_BC.py --bam xyz.filtered.Aligned.GeneTagged.sorted.bam --out /outputfolder/zUMIs_output/demultiplexed/xyz. --bclist /outputfolder/zUMIs_output/xyzkept_barcodes.txt --pin 10 --pout 10 --chr allreads`
(just replace with your actual path names)

For the STAR warning, if the genome index version is compatible and the mapping runs fine its ok to ignore this.

**Comment by taniachavarria79** [comment]
Hello,

Thanks so much for answer to my issue. Sorry If I make a grammar mistake, I meant that my demultiplex folder was empty and i need the demultiplex data for my analysis.
I will run it again as you suggested today and let you know.

Thanks again


________________________________

**Comment by taniachavarria79** [comment]
Hello,

Under the new version of zUMIs-2.6.0/misc that python script is missing. The only one that Ifound was these demultiplex_BC.pl
Do you have the script to run this on perl?

Thanks so much

Best,

Tania
________________________________

**Comment by taniachavarria79** [comment]
Never mind I found the script in the older version of zUMIs and I ran the python script and I got my demultiplex files. The problem is fixed.
Thanks so much for your help
Best,

Tania

________________________________

**Comment by cziegenhain** [comment]
Hi,

My answer was referring to the latest version, I do recommend to be up to date.
But great if it works out now!
