### ISSUE TITLE
How to create YAML file for more than 4 fastq files

### ISSUE THREAD

**Issue by arshiyaakeel** [sdparekh/zUMIs#216]
Hi Christoph, 

In order to use zUMIs 2.9.4 I want to create a YAML file for my input fastq files. 
YAML config Rshiny application" allows only maximum 4 files to load. In my case I have 87 fastq files from the Smart-seq2 platform for a single sample. 

http://shiny.bio.lmu.de:3838/zUMIs-config/

Is there any way to create YAML files for such files?

Basically I am interested in creating data expression file like your case study (HEK293T cells: GSE99822). 

Could you help with this?Do let me know if you need more informationThanks,

Best regards

Arshiya

**Comment by cziegenhain** [comment]
Hi Arshiya,

So it seems that you misunderstand the way fastq files are input into zUMIs - fastq file input refers to the various reads from the illumina sequencer (eg. read1, read2, index reads 1/2).
When you have demultiplexed files, please check the relevant wiki section:
https://github.com/sdparekh/zUMIs/wiki/Starting-from-demultiplexed-fastq-files

Best,
Christoph

**Comment by arshiyaakeel** [comment]
Hello Christoph ,
Thank you very much for your prompt reply.

I will check the wiki section to run my data.

Thanks again.
Best wishes

Arshiya

**Comment by cziegenhain** [comment]
Closing here since you opened a new issue.
