### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OliInTheValley** [sdparekh/zUMIs#218]
**Describe the bug**
Hi,
I have tried to make zUMIs run for Smartseq2 data, that has been provided to us already de-multiplexed. I thus used your [workaround](https://github.com/sdparekh/zUMIs/wiki/Starting-from-demultiplexed-fastq-files). That one seems to have worked well. However, when running zUMIs on those merged files, shortly after starting the filtering process, zUMIs throws out numerous warning messages saying "couldn't open WARNING: for reading: No such file or directory" and all subsequent steps fail consistently (see below). I've checked - multiple times - that the files are present under the correct locations.
For more context: The SS2 experiment does not include any UMIs. In my understanding, zUMIs should be able to find the barcods in the index file.
zUMIs has previously been used to successfully map other single cell data (10X) in the same software environment. I have thus modified the YAML file only with respect to file paths and BC/cDNA ranges to fit the protocol but otherwise left all settings as they were. 
I really have no idea what is going on here and would thus appreciate any feedback.

**To Reproduce**
The YAML file
`
###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: THmicroglia_Pooled

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /labs/twc/USER/data_raw/2020_09_29-Tha_Microglia_plasma/usftp21.novogene.com/combineFASTQ/reads_for_zUMIs.index.fastq.gz 
    base_definition:
      - BC(1-8)
  file2:
    name: /labs/twc/USER/data_raw/2020_09_29-Tha_Microglia_plasma/usftp21.novogene.com/combineFASTQ/reads_for_zUMIs.R1.fastq.gz
    base_definition:
      - cDNA(12-130)
  file3:
    name: /labs/twc/USER/data_raw/2020_09_29-Tha_Microglia_plasma/usftp21.novogene.com/combineFASTQ/reads_for_zUMIs.R2.fastq.gz
    base_definition:
      - cDNA(12-130)

#reference genome setup
reference:
  STAR_index: /labs/twc/USER/Index/STAR237_mm10 #path to STAR genome index
  GTF_file: /labs/twc/USER/Index/STAR237_mm10/gencode.vM22.annotation.gtf #path to gene annotation file in GTF format
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: --limitOutSJcollapsed 2500000 --limitSjdbInsertNsj 3000000 #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: ./ #specify the full path to the output directory

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 8
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: /labs/twc/USER/data_raw/2020_09_29-Tha_Microglia_plasma/usftp21.novogene.com/combineFASTQ/reads_for_zUMIs.expected_barcodes.txt
  automatic: yes #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 20 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  write_ham: no #If hamming distance collapse of UMI sequences is performed, write out mapping tables & UB corrected bam files.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths

#below, fqfilter will add a read_layout flag defining SE or PE
zUMIs_directory: /labs/lab_folder/USER/data_proc/2020_10_04_TH_Microglia/TH_Plate2_3_zUMImerged/zUMIs
read_layout: SE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
`

**Additional context**
This is what zUMIs spit out via the console:

`
Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!

 You provided these parameters:
 YAML file:	zumis_TH_Plat2_100k.yaml
 zUMIs directory:		/oak/stanford/scg/lab_folder/USER/data_proc/2020_10_04_TH_Microglia/TH_Plate2_3_zUMImerged/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.9.4c 

Mon Oct  5 00:51:34 PDT 2020
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Filtering...
couldn't open WARNING: for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledai.filtered.tagged.bam'
couldn't open WARNING: for reading: No such file or directory
couldn't open ignoring for reading: No such file or directory
couldn't open environment for reading: No such file or directory
couldn't open value for reading: No such file or directory
couldn't open of for reading: No such file or directory
couldn't open R_HOME for reading: No such file or directory
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledae.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledaa.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledab.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledah.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledac.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledad.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledag.filtered.tagged.bam'
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `samtools view -Sb - > BC(1-8) cDNA(12-130) cDNA(12-130)/zUMIs_output/.tmpMerge/./.THmicroglia_Pooledaf.filtered.tagged.bam'
ls: cannot access .//zUMIs_output/.tmpMerge//THmicroglia_Pooled.*.filtered.tagged.bam: No such file or directory
cat: .//zUMIs_output/.tmpMerge//THmicroglia_Pooled.*.BCstats.txt: No such file or directory
Mon Oct  5 02:16:13 PDT 2020
WARNING: ignoring environment value of R_HOME
Error in eval(bysub, parent.frame(), parent.frame()) : 
  object 'XC' not found
Calls: cellBC -> [ -> [.data.table -> eval -> eval
In addition: Warning message:
In data.table::fread(bccount_file, header = FALSE, col.names = c("XC",  :
  File './/THmicroglia_Pooled.BCstats.txt' has size 0. Returning a NULL data.table.
Execution halted
Mapping...
WARNING: ignoring environment value of R_HOME
[1] "2020-10-05 02:16:18 PDT"
[E::hts_open_format] Failed to open file NA
samtools view: failed to open "NA" for reading: No such file or directory
Warning message:
In data.table::fread(cmd = paste(samtools, "view", filtered_bams[1],  :
  File '/tmp/RtmpT9ngav/filecd757956faae' has size 0. Returning a NULL data.table.
Usage: samtools cat [options] <in1.bam>  [... <inN.bam>]
       samtools cat [options] <in1.cram> [... <inN.cram>]

Concatenate BAM or CRAM files, first those in <bamlist.fofn>, then those
on the command line.

Options: -b FILE  list of input BAM/CRAM file names, one per line
         -h FILE  copy the header from FILE [default is 1st input file]
         -o FILE  output BAM/CRAM
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory

EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile
SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
Oct 05 02:16:34 ...... FATAL ERROR, exiting
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory
[E::hts_open_format] Failed to open file NULL
samtools view: failed to open "NULL" for reading: No such file or directory

EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile
SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
Oct 05 02:16:34 ...... FATAL ERROR, exiting

EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile
SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
Oct 05 02:16:34 ...... FATAL ERROR, exiting
[main_cat] ERROR: input is not BAM or CRAM
[main_cat] ERROR: input is not BAM or CRAM
Mon Oct  5 02:16:35 PDT 2020
Counting...
WARNING: ignoring environment value of R_HOME
[1] "2020-10-05 02:16:53 PDT"
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt")) : 
  File './/zUMIs_output/THmicroglia_Pooledkept_barcodes_binned.txt' does not exist or is non-readable. getwd()=='/oak/stanford/scg/lab_folder/USER/data_proc/2020_10_04_TH_Microglia/TH_Plate2_3_zUMImerged'
Execution halted
Mon Oct  5 02:16:53 PDT 2020
WARNING: ignoring environment value of R_HOME
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file './/zUMIs_output/expression/THmicroglia_Pooled.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Oct  5 02:16:58 PDT 2020
Descriptive statistics...
WARNING: ignoring environment value of R_HOME
[1] "I am loading useful packages for plotting..."
[1] "2020-10-05 02:16:58 PDT"
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File './/zUMIs_output/THmicroglia_Pooledkept_barcodes.txt' does not exist or is non-readable. getwd()=='/oak/stanford/scg/lab_folder/USER/data_proc/2020_10_04_TH_Microglia/TH_Plate2_3_zUMImerged'
Execution halted
Mon Oct  5 02:17:04 PDT 2020
`

**Comment by cziegenhain** [comment]
Hi,

Looks to me like you have not given a useful path in the Output directory field - hopefully it's as simple as that.
Also for the previously demultiplexed data, you should not use automatic barcode detection and only give the whitelist path. 

Best
Christoph

**Comment by OliInTheValley** [comment]
Hi Christoph,

Thanks for the fast reply. Altering the output directory and switching the automatic barcode detection off did not change the outcome. Again, I was used to run zUMIs many times in the exact same software environment, using the same YAML, in which I only changed the input file paths and BC annotations. 
Could this mean that zUMIs doesn't find detect any BC at all, and hence throws an error because it does not create the respective temp files? I could in theory imagine something like that in general but not with your de-demultiplexed workaround... I assume cDNA range settings etc. look correct for SS2?

**Comment by cziegenhain** [comment]
It's hard to judge the YAML for correctness, it seems like some things have line breaks but that could be due to copy pasting in GitHub here?

I also generally avoid odd characters like dashes in path names, not sure if that could break things.

The error reads like there is a mess with some file path or another!

**Comment by OliInTheValley** [comment]
Apologies for not having that one submitted in the original post already. 
[zumis_TH_Plat2_100k.yaml.zip](https://github.com/sdparekh/zUMIs/files/5346679/zumis_TH_Plat2_100k.yaml.zip)

I'll go over some of the filepaths and try to remove the odd characters. Thanks for helping narrowing it down!

**Comment by OliInTheValley** [comment]
I moved the working directory of the mapping into a folder where it used to work before and to my surprise, that did the trick!
It's running smoothly now - thanks for all the assistance!

**Comment by cziegenhain** [comment]
Great that it works!
