### ISSUE TITLE
Can't run two samples in parallel

### ISSUE THREAD

**Issue by zhanglab2008** [sdparekh/zUMIs#219]
**Describe the bug**
Hi Team, congrats on the awesome software! I used zUMIs for two years and it worked like a charm. However, when I updated the version to 2.9.4d, I can't run two samples in parallel. Below is the error I got:

 You provided these parameters:
 YAML file:	zUMIs/zUMIs.yaml
 zUMIs directory:		/mnt/sdd/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.9.4d 

Sun 11 Oct 2020 09:39:18 AM CDT
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Filtering...
pigz: skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOaf.gz does not exist
pigz: skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOaf.gz does not exist
pigz: pigz: pigz: pigz: pigz: pigz: pigz: pigz: pigz: pigz: skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOaj.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOad.gz does not existpigz: pigz: pigz: pigz: skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOah.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOad.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOah.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOag.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOab.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOaj.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOam.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOai.gz does not exist

skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOak.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOab.gz does not existpigz: skipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_1.fastqRUUOak.gz does not existskipping: /mnt/sdd/UUO7_output/zUMIs_output/.tmpMerge/SRR10407696_2.fastqRUUOag.gz does not exist

When I ran each sample separately, everything looks fine. When I ran the same two samples in an older version (zUMIs 2.6.1), everything looks fine. Do you know what the culprit might be? Thanks in advance!!

Zhang

**To Reproduce**
Here is my yaml file setup:

###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project: UUO7

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI sequences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /mnt/sdd/SRR10407696_1.fastq.gz
    base_definition:
      - BC(1-16)
      - UMI(17-26)
  file2:
    name:  /mnt/sdd/SRR10407696_2.fastq.gz
    base_definition:
      - cDNA(1-98)

#reference genome setup
reference:
  STAR_index: /mnt/sdd/zUMIs/zUMIs_mouse_ref
  GTF_file: /mnt/sdd/genes.gtf
  exon_extension: no #extend exons by a certain width?
  extension_length: 0 #number of bp to extend exons by
  scaffold_length_min: 0 #minimal scaffold/chromosome length to consider (0 = all)
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /mnt/sdd/UUO7_output

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 24
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null #Optional for combining several barcode sequences per cell (see github wiki)
  automatic: yes #Give yes/no to this option. If the cell barcodes should be detected automatically. If the barcode file is given in combination with automatic barcode detection, the list of given barcodes will be used as whitelist.
  BarcodeBinning: 1 #Hamming distance binning of close cell barcode sequences.
  nReadsperCell: 100 #Keep only the cell barcodes with atleast n number of reads.
  demultiplex: no #produce per-cell demultiplexed bam files.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  intronProb: no #perform an estimation of how likely intronic reads are to be derived from mRNA by comparing to intergenic counts.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desired range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  velocyto: no #Would you like velocyto to do counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  multi_overlap: no #Do you want to assign reads overlapping to multiple features?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes

#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#define dependencies program paths
samtools_exec: samtools #samtools executable
Rscript_exec: Rscript #Rscript executable
STAR_exec: STAR #STAR executable
pigz_exec: pigz #pigz executable

#below, fqfilter will add a read_layout flag defining SE or PE

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS with 512 Gb Ram

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

What is the output folder & sample name for the second run that you are running in parallel?
At the end of the filtering step, zUMIs should clean up some temporary fastq files (which produce the errors above), but we had accidentally commented out this cleaning step for some versions. As of 2.9.4 this is correct again.
The removal should not affect other runs even in the same output directory, provided they have a unique name.

Best,
Christoph

**Comment by zhanglab2008** [comment]
I see. I used two different sample names so that shouldn't be the issue. I will do it again today and provide you more detail if I run into the same problem. Thanks for troubleshooting. Chris!
Best,
Zhang
