### ISSUE TITLE
a ' symbolic link' error

### ISSUE THREAD

**Issue by ChongLu121** [sdparekh/zUMIs#22]
Hello!

When I ran the zUMIs in a server with the use of example data. I got an error message:
**************************
ln: failed to create symbolic link 'path/to/chr22test.aligned.sorted.bam.in': Operation not supported
**************************
It looks like the "ln -s " command in "zUMIs-master.sh" doesn't work.
Is there any solution if I don't have a root permission for the server?

Thank you.
Chong

**Comment by cziegenhain** [comment]
ln should be possible without root permission. But you should make sure you have the necessary write permissions in the folder you are working in. 

More information on your server environment (eg operating system) would be good if you need further help. 

Best 
Christoph

**Comment by ChongLu121** [comment]
Thank you for the reply!


Here is the detailed error message:
********
Feb 08 11:23:08 ..... started STAR run
Feb 08 11:23:08 ..... loading genome
Feb 08 11:23:29 ..... processing annotations GTF
Feb 08 11:23:30 ..... inserting junctions into the genome indices
Feb 08 11:23:53 ..... started 1st pass mapping
Feb 08 11:23:54 ..... finished 1st pass mapping
Feb 08 11:23:55 ..... inserting junctions into the genome indices
Feb 08 11:24:03 ..... started mapping
Feb 08 11:24:04 ..... finished successfully
[1] "I am loading useful packages..."
[1] "2018-02-08 11:24:15 CET"
[1] "I am loading Rsubread 1.26.0..."
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-02-08 11:24:37 CET"
[1] "I am making count tables...This will take a while!!"
[1] "2018-02-08 11:24:50 CET"

ln: failed to create symbolic link '/reference/chr22test.aligned.sorted.bam.in': Operation not supported
ln: failed to create symbolic link '/reference/chr22test.aligned.sorted.bam.ex': Operation not supported
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Loading required package: optparse
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Warning message:
In if (installed.packages()[grep("Rsubread", installed.packages()),  :
  the condition has length > 1 and only the first element will be used
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
There were 17 warnings (use warnings() to see them)
'select()' returned 1:many mapping between keys and columns
Error in file(file, "rt") : cannot open the connection
Calls: makeGEprofile -> <Anonymous> -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './.Rsubread_featureCounts_pid22775': No such file or directory
Execution halted
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/reference/zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
rm: cannot remove '/reference/chr22test.aligned.sorted.bam.in': No such file or directory
rm: cannot remove '/reference/chr22test.aligned.sorted.bam.ex': No such file or directory
********

And the followed files were generated in the output folder:
chr22test.aligned.sorted.bam
chr22test.barcodelist.filtered.sort.sam
chr22test.Log.final.out
chr22test.Log.out
chr22test.Log.progress.out
chr22test.SJ.out.tab
chr22test._STARgenome
chr22test._STARpass1
zUMIs_output

But in the next step, zUMIs couldn't find them.

About the server: Linux version 4.14.3-1-ARCH

**Comment by sdparekh** [comment]
Hi,
First, "Operation not supported" for ln -s can be due to various reasons.

1. ln does not exist -- which is unlikely becase you are using linux system but to be sure I would check you have `ln`
2. Your output folder is on a shared volume
3. The output folder is on an external drive

I don't think it has anything to do with permissions because the symlink is created in the same folder as your output files. If you have permissions to write files in a folder, you should have permissions to create symlinks.

On the other hand, the stdout from zUMIs you have pasted here does not seem quite in order. The symlink is created before the DGE module is initiated. However, your output tells me that it first initiates DGE and then tries to create symlink.

I would like to see your zUMIs command and the complete standard out from zUMIs.

Best,
Swati

**Comment by ChongLu121** [comment]
Hello Swati,

Here is a copy of the bash file and standard out from zUMIs:
*********************************
#!usr/bin/bash
p="/scratch/software/zUMIs"
r="/home/lu/phyles/users/lu/genome-index/ref/reference"
o="/home/lu/phyles/users/lu/genome-index/out"
$p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $r/hg38_chr22 -a $r/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $o

*********************************

Your jobs will run on this machine.


Make sure you have more than 1.4G RAM and 8 processors available.


Your jobs will be started from filtering.




 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/scratch/software/zUMIs/ExampleData/barcoderead_HEK.1mio.fq.gz
 cDNA read:			/scratch/software/zUMIs/ExampleData/cDNAread_HEK.1mio.fq.gz
 Study/sample name:		chr22test
 Output directory:		/home/lu/phyles/users/lu/genome-index/out
 Cell/sample barcode range:	1-6
 UMI barcode range:		7-16
 Retain cell with >=N reads:	100
 Genome directory:		/home/lu/phyles/users/lu/genome-index/ref/reference/hg38_chr22
 GTF annotation file:		/home/lu/phyles/users/lu/genome-index/ref/reference/GRCh38.84.chr22.gtf
 Number of processors:		8
 Read length:			50
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Barcodes:			NA
 zUMIs directory:		/scratch/software/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0


Raw reads: 1000000
Filtered reads: 853296

Feb 08 16:19:33 ..... started STAR run
Feb 08 16:19:33 ..... loading genome
Feb 08 16:20:16 ..... processing annotations GTF
Feb 08 16:20:17 ..... inserting junctions into the genome indices
Feb 08 16:20:42 ..... started 1st pass mapping
Feb 08 16:20:43 ..... finished 1st pass mapping
Feb 08 16:20:43 ..... inserting junctions into the genome indices
Feb 08 16:20:52 ..... started mapping
Feb 08 16:20:53 ..... finished successfully
ln: failed to create symbolic link '/home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.in': Operation not supported
ln: failed to create symbolic link '/home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.ex': Operation not supported
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-02-08 16:21:04 CET"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am loading Rsubread 1.26.0..."
Warning message:
In if (installed.packages()[grep("Rsubread", installed.packages()),  :
  the condition has length > 1 and only the first element will be used
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-02-08 16:21:21 CET"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
There were 17 warnings (use warnings() to see them)
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-02-08 16:21:33 CET"

ERROR: invalid parameter: '/home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.in'

Error in file(file, "rt") : cannot open the connection
Calls: makeGEprofile -> <Anonymous> -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './.Rsubread_featureCounts_pid25980': No such file or directory
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2018-02-08 16:21:35 CET"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/lu/phyles/users/lu/genome-index/out/zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
rm: cannot remove '/home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.in': No such file or directory
rm: cannot remove '/home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.ex': No such file or directory

Thank you for your help!

Best,
Chong

**Comment by sdparekh** [comment]
All right!! This issue is only due to the lack of `ln` in your system. My suggestion would be to resolve the usage of symlink on your server. However, if that is not possible, you can replace `ln -s -f` with `cp` in "zUMIs-noslurm.sh" file. As long as you are not using slurm queuing system to submit your jobs, you only need to change this once in "zUMIs-noslurm.sh" file.

Let me know if this works for you.
Best,
Swati

**Comment by ChongLu121** [comment]
Yes, after changing the command in  "zUMIs-noslurm.sh", there was no "failed to create symbolic link" error. 

But I got a new error:
************************
Feb 08 17:04:52 ..... started STAR run
Feb 08 17:04:52 ..... loading genome
Feb 08 17:05:14 ..... processing annotations GTF
Feb 08 17:05:16 ..... inserting junctions into the genome indices
Feb 08 17:05:42 ..... started 1st pass mapping
Feb 08 17:05:43 ..... finished 1st pass mapping
Feb 08 17:05:43 ..... inserting junctions into the genome indices
Feb 08 17:05:51 ..... started mapping
Feb 08 17:05:53 ..... finished successfully
[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-02-08 17:06:04 CET"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am loading Rsubread 1.26.0..."
Warning message:
In if (installed.packages()[grep("Rsubread", installed.packages()),  :
  the condition has length > 1 and only the first element will be used
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-02-08 17:06:20 CET"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
There were 17 warnings (use warnings() to see them)
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-02-08 17:06:33 CET"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/lu/phyles/users/lu/genome-index/out/ ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid26724 ...       ||
||    Features : 5737                                                         ||
||    Meta-features : 698                                                     ||
||    Chromosomes/contigs : 3                                                 ||
||                                                                            ||
|| Process BAM file /home/lu/phyles/users/lu/genome-index/out/chr22test.a ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 0                                                         ||
||    Successfully assigned reads : 0                                         ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.26.0

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /home/lu/phyles/users/lu/genome-index/out/ ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid26724 ...       ||
||    Features : 26131                                                        ||
||    Meta-features : 1190                                                    ||
||    Chromosomes/contigs : 4                                                 ||
||                                                                            ||
|| Process BAM file /home/lu/phyles/users/lu/genome-index/out/chr22test.a ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 0                                                         ||
||    Successfully assigned reads : 0                                         ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

Error in data.table::fread(paste("cut -f3 ", abamfile[2], ".featureCounts",  :
  File is empty: /dev/shm/file6864292781c2
Calls: makeGEprofile -> <Anonymous>
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2018-02-08 17:06:36 CET"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/lu/phyles/users/lu/genome-index/out/zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
************************

Best,
Chong

**Comment by sdparekh** [comment]
Can you please give me the output of 
`ls -lh /home/lu/phyles/users/lu/genome-index/ref/reference/*` and
`ls -lh /home/lu/phyles/users/lu/genome-index/out/*` and
`cat  /home/lu/phyles/users/lu/genome-index/out/chr22test.Log.final.out`

**Comment by ChongLu121** [comment]
Hi Swati,
sorry for the late reply.
You may check the information below.
1. 
***************************
-rwxr-xr-x 1 lu phyles 28M Feb  6 22:59 /home/lu/phyles/users/lu/genome-index/ref/reference/GRCh38.84.chr22.gtf

/home/lu/phyles/users/lu/genome-index/ref/reference/hg38_chr22:
total 1.4G
-rwxr-xr-x 1 lu phyles    9 Feb  6 23:00 chrLength.txt
-rwxr-xr-x 1 lu phyles   15 Feb  6 23:00 chrNameLength.txt
-rwxr-xr-x 1 lu phyles    6 Feb  6 23:00 chrName.txt
-rwxr-xr-x 1 lu phyles   11 Feb  6 23:00 chrStart.txt
-rwxr-xr-x 1 lu phyles  49M Feb  6 23:00 Genome
-rwxr-xr-x 1 lu phyles  496 Feb  6 23:00 genomeParameters.txt
-rwxr-xr-x 1 lu phyles 309M Feb  6 23:00 SA
-rwxr-xr-x 1 lu phyles 1.5G Feb  6 23:05 SAindex
***************************
2.
***************************
-rwxr-xr-x 1 lu phyles  471 Feb  8 16:20 /home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam
-rwxr-xr-x 1 lu phyles    0 Feb  8 17:06 /home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.ex.featureCounts
-rwxr-xr-x 1 lu phyles    0 Feb  8 17:06 /home/lu/phyles/users/lu/genome-index/out/chr22test.aligned.sorted.bam.in.featureCounts
-rwxr-xr-x 1 lu phyles  78M Feb  8 16:20 /home/lu/phyles/users/lu/genome-index/out/chr22test.barcodelist.filtered.sort.sam
-rwxr-xr-x 1 lu phyles 1.8K Feb  8 16:20 /home/lu/phyles/users/lu/genome-index/out/chr22test.Log.final.out
-rwxr-xr-x 1 lu phyles  54K Feb  8 16:20 /home/lu/phyles/users/lu/genome-index/out/chr22test.Log.out
-rwxr-xr-x 1 lu phyles  329 Feb  8 16:20 /home/lu/phyles/users/lu/genome-index/out/chr22test.Log.progress.out
-rwxr-xr-x 1 lu phyles    0 Feb  8 17:05 /home/lu/phyles/users/lu/genome-index/out/chr22test.SJ.out.tab

/home/lu/phyles/users/lu/genome-index/out/chr22test._STARgenome:
total 7.0M
-rwxr-xr-x 1 lu phyles 741K Feb  8 16:19 exonGeTrInfo.tab
-rwxr-xr-x 1 lu phyles 359K Feb  8 16:19 exonInfo.tab
-rwxr-xr-x 1 lu phyles  22K Feb  8 16:19 geneInfo.tab
-rwxr-xr-x 1 lu phyles 194K Feb  8 16:19 sjdbInfo.txt
-rwxr-xr-x 1 lu phyles 194K Feb  8 16:19 sjdbList.fromGTF.out.tab
-rwxr-xr-x 1 lu phyles 194K Feb  8 16:19 sjdbList.out.tab
-rwxr-xr-x 1 lu phyles 233K Feb  8 16:19 transcriptInfo.tab

/home/lu/phyles/users/lu/genome-index/out/chr22test._STARpass1:
total 2.0M
-rwxr-xr-x 1 lu phyles 1.8K Feb  8 16:20 Log.final.out
-rwxr-xr-x 1 lu phyles    0 Feb  8 17:05 SJ.out.tab

/home/lu/phyles/users/lu/genome-index/out/zUMIs_output:
total 0
drwxr-xr-x 2 lu phyles 0 Feb  8 15:35 expression
drwxr-xr-x 2 lu phyles 0 Feb  8 16:21 filtered_fastq
drwxr-xr-x 2 lu phyles 0 Feb  8 11:28 stats
***************************
3.
***************************
                                 Started job on |	Feb 08 17:04:52
                             Started mapping on |	Feb 08 17:05:51
                                    Finished on |	Feb 08 17:05:53
       Mapping speed, Million of reads per hour |	0.00

                          Number of input reads |	0
                      Average input read length |	0
                                    UNIQUE READS:
                   Uniquely mapped reads number |	0
                        Uniquely mapped reads % |	0.00%
                          Average mapped length |	0.00
                       Number of splices: Total |	0
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	0
                       Number of splices: GC/AG |	0
                       Number of splices: AT/AC |	0
               Number of splices: Non-canonical |	0
                      Mismatch rate per base, % |	-nan%
                         Deletion rate per base |	0.00%
                        Deletion average length |	0.00
                        Insertion rate per base |	0.00%
                       Insertion average length |	0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	0
             % of reads mapped to multiple loci |	0.00%
        Number of reads mapped to too many loci |	0
             % of reads mapped to too many loci |	0.00%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	0.00%
                     % of reads unmapped: other |	0.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%
***************************

**Comment by ChongLu121** [comment]
Hello Swati,

I changed the output folder, and there is no error when using the example data now.
I will try it in our own data (from 10X) later.

The problem may be the output folder, it's on a shared volume. You are totally right. That shared volume does not support "ln -s" command.

You may close this issue now. Thank you for your help!!!

Best wishes,
Chong
