### ISSUE TITLE
Unable to load shared object 

### ISSUE THREAD

**Issue by bwfait** [sdparekh/zUMIs#223]
**Describe the bug**
Hello! I'm running zUMIs within the provided miniconda environment. I receive the following error when counting: 

[1] "Assigning reads to features (ex)"
Error in dyn.load(fcounts_clib) :
  unable to load shared object '/myLocalPath/zUMIs/misc/fcountsLib2':
  /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /myLocalPath/zUMIs/misc/fcountsLib2)

**To Reproduce**
The YAML file was as-provided for the test case modified to my local file paths. The data was the provided HEK test data, and STAR index, with a GTF file for Chr 22. I updated R in the conda environment to 3.6.3 to no avail.

**Additional context**
There was a similar problem [submitted before](https://github.com/sdparekh/zUMIs/issues/149), but the solution provided was specific to their context and was closed. They concluded that "I think the change that causes the break comes from the use of the pre-compiled featureCounts. The R installation on the AWS doesn't appear to be configured for shared libraries, and so there is actually no libR.so file." 

I'll work to see if this diagnosis is generalizable, but I think it'll be difficult to fix with my permissions and inexperience. Any guidance would be appreciated!

**Comment by cziegenhain** [comment]
Hi,

I think it is related to your C libraries, we have had similar issues before:
https://github.com/sdparekh/zUMIs/issues/221#issuecomment-713806539
https://github.com/sdparekh/zUMIs/issues/184#issuecomment-631054909

Best,
Christoph

**Comment by bwfait** [comment]
Beautiful. Re-compiling worked, as you suggest. Apologies for missing that in my initial research, and thanks for your quick response!

**Comment by cziegenhain** [comment]
No worries, great that it works now!
