### ISSUE TITLE
Error in .make_splicings 

### ISSUE THREAD

**Issue by bwfait** [sdparekh/zUMIs#224]
**Describe the bug**

Hello! I've run through the test data successfully, and have moved on to a small-scale analysis of some of my own data. I really appreciate all the work y'all have put into this tool -- it's very helpful! I'm processing Smart-Seq3 data and the analysis seems to work well up until the following: 

Error in .make_splicings(exons, cds, stop_codons) : 
  some CDS cannot be mapped to an exon
Calls: .get_tx_lengths
Execution halted

**To Reproduce**

1) The YAML file and nohup.out files are attached. 
2) The STAR Index was generated using STAR 2.7.3a and GRCm39 fastq and gtf files
3) Data was generated using a MiSeq nano kit (300 bp single read)
4) Linux 2.6.32-754.35.1.el6.x86_64 x86_64 (quite old from my understanding, but the test case worked well after updating what needed to be updated) 

**Additional context**

I'm a bench person trying to analyze their data for the first time, so I wouldn't assume any baseline competence. 

(Edit) I should mention as well I saw the previous [issue pertaining to this error.](https://github.com/sdparekh/zUMIs/issues/209) However, I'm having trouble applying it to our own case given what we're doing is using pretty standard genomes. It seems likely I've missed something very basic due to my inexperience...

Thanks for any help you might offer! 

[nohup.txt](https://github.com/sdparekh/zUMIs/files/5538259/nohup.txt)
[YAML.txt](https://github.com/sdparekh/zUMIs/files/5538269/YAML.txt)

**Comment by cziegenhain** [comment]
Hi,

Sorry to hear that there are issues.
From reading your nohup log and yaml, you did set up everything correctly.
However two steps fail when parsing the GTF file (once for fetching gene names  & once for calculating gene lengths). 
Interestingly enough, it does function well enough to assign the reads to the gene features.
Which gene annotation are you using here? I typically verify zUMIs on ensembl and gencode gene annotations.

Best,
Christoph

**Comment by bwfait** [comment]
Hi Christoph, 

Thanks for getting back so quickly (especially during the weekend). I've tried a couple of genomes: 

1. The Gencode assembly from [here](https://www.ncbi.nlm.nih.gov/assembly/GCF_000001635.27/). Only one fasta and gtf are available to download, so I used those. 

2. The Gencode assembly from the same source but one version prior, in case it was some issue with the newest release. 

3. The Ensembl assembly from [here](http://uswest.ensembl.org/Mus_musculus/Info/Index): specifically, Mus_musculus.GRCm38.dna.primary_assembly.fa.gz and Mus_musculus.GRCm38.101.gtf.gz. 

All of these yielded the same error.

I'm not sure it's possible for me to have changed the gtf file formatting, but just in case here are some random lines from both gtfs: 

[ensembleGTFSample.txt](https://github.com/sdparekh/zUMIs/files/5541379/ensembleGTFSample.txt)
[gencodeGTFSample.txt](https://github.com/sdparekh/zUMIs/files/5541380/gencodeGTFSample.txt)


I'd add this is also my first time using STAR, so it's also possible I messed that up in some way. 

Thanks for any insight you might have!

**Comment by cziegenhain** [comment]
Hi again,

Very weird! 
For Gencode, you would normally fetch the annotation here:
https://www.gencodegenes.org/

**Comment by cziegenhain** [comment]
Hi again,

Very weird! 
For Gencode, you would normally fetch the annotation here:
https://www.gencodegenes.org/

But anyway, the Ensembl GTF file looks fully as I would expect it and that should work just fine.
Could you send me the exact YAML and slurm log from your try with the `Mus_musculus.GRCm38.dna.primary_assembly.fa.gz ` and `Mus_musculus.GRCm38.101.gtf.gz` files (Note the GTF cannot be gzipped for zUMIs).
Maybe there is something I had overlooked.

Best,
Christoph

**Comment by bwfait** [comment]
Christoph, 

Thanks for your help! Actually, I think my directory was off and I was re-checking one of the old runs. With the Ensembl gtf file it worked perfectly! 

So I conclude that I downloaded the incorrect GTF file somehow from Gencode initially and used a correct set of files from Ensembl. 

Thank you so much for your help, both here and in your past replies which were incredibly helpful.

**Comment by cziegenhain** [comment]
Great that it seems to be running now!
