### ISSUE TITLE
2 errors reported after installation. 

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#225]
Hi, 
Thank you for developing this wonderful tools. 
I tried to install zUMIs for my analysis. After the installation, I did a test run and got two error message below. 
~/zUMIs/zUMIs.sh: line 161: ~/zUMIs/zUMIs-env/bin/activate: No such file or directory
~zUMIs/zUMIs.sh: line 162: conda-unpack: command not found

It could be not a problem about zUMIs, but my settings. But is that possible that still get help from experts here? thank you so much in advance!
Y

**Comment by cziegenhain** [comment]
Hi,

Thanks for using zUMIs.
This issue has occured before when the first unpacking of the conda environment breaks or gets interrupted for some reason.
I would recommend to remove the zUMIs folder and clone it again from GitHub. When running the first time, the unpacking will take place and can take quite a while, be sure to not abort it!

Best,
Christoph

**Comment by ysu2015** [comment]
Hi Christoph,

Thank you so much for the quick response and help. It works!!

Bests,
Y
