### ISSUE TITLE
Defined dependencies program paths have not been taken by zUMIs

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#227]
Hi,

When I run zUMIs, the program does not take all the defined dependencies program paths, which I input into the .yaml file. It only take the zUMIs directory, but not samtools, STAR and others. I notice that, there is a note show up saying that
"Using miniconda environment for zUMIs!
note: internal executables will be used instead of those specified in the YAML file!"
How could I solve this problem? Thank you so much in advance.

Y

**Comment by cziegenhain** [comment]
Hi,

This is intentional. 
You need to choose to either use the conda environment with preinstalled dependencies, or supply your own paths with dependencies (leave out -c option).

Best,
C

**Comment by ysu2015** [comment]
Sorry, My bad. I leave out the -c parameter to use my own path. but get error message below. 
~/zUMIs/zUMIs.sh: line 174: [[: error:: syntax error in expression (error token is ":")

Y

**Comment by cziegenhain** [comment]
It sounds like somewhere in your YAML you could be missing a space after the colon, but then again I can only guess since you did not provide any information!

**Comment by ysu2015** [comment]
Thank you. I will check my YAML accordingly to your suggestion.

Y

**Comment by ysu2015** [comment]
Hi C, 
I checked my YAML file. Kind of do not see any missing space. I attached the .txt format of my YAML file. Could you help to go through? Thank you so much.
[split_HIPP.txt](https://github.com/sdparekh/zUMIs/files/5554297/split_HIPP.txt)


Y

**Comment by cziegenhain** [comment]
I don't see anything obvious either, what's the content of the .zUMIs_YAMLerror.log ?

**Comment by ysu2015** [comment]
Thank you for helping. 
The content of .zUMIs_YAMLerror.log is 

Fatal error: cannot open file '/media/yijingsu/ubuntu/Software/zUMIs/checkyaml.R': No such file or directory

**Comment by cziegenhain** [comment]
Sounds like the zUMIs directory could not be found!

**Comment by ysu2015** [comment]
Below is all the files in zUMIs.
drwxrwxrwx 1 yijingsu yijingsu      8192 Nov 17 09:28 ./
drwxrwxrwx 1 yijingsu yijingsu      4096 Nov 17 09:09 ../
drwxrwxrwx 1 yijingsu yijingsu      4096 Nov 17 08:24 zUMIs-env/
-rwxrwxrwx 1 yijingsu yijingsu   3219865 Nov 17 08:08 zUMIs_GI2017_poster.pdf*
-rwxrwxrwx 1 yijingsu yijingsu      7174 Nov 17 08:08 zUMIs-mapping.R*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partaa*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partab*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partac*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partad*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partae*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partaf*
-rwxrwxrwx 1 yijingsu yijingsu 103809024 Nov 17 08:08 zUMIs-miniconda.partag*
-rwxrwxrwx 1 yijingsu yijingsu   7557912 Nov 17 08:08 zUMIs-miniconda.partah*
-rwxrwxrwx 1 yijingsu yijingsu 734221080 Nov 17 08:22 zUMIs-miniconda.tar.bz2*
-rwxrwxrwx 1 yijingsu yijingsu   1519791 Nov 17 08:08 zUMIs.png*
-rwxrwxrwx 1 yijingsu yijingsu     10490 Nov 17 08:08 zUMIs.sh*
-rwxrwxrwx 1 yijingsu yijingsu      6704 Nov 17 08:08 zUMIs-stats2.R*
-rwxrwxrwx 1 yijingsu yijingsu      4237 Nov 17 08:08 zUMIs.yaml*

There is no checkyaml.R there. Should I reclone zUMI?

Y

**Comment by cziegenhain** [comment]
Yes seems like the clone was incomplete!
Reclone and check that you have all files as visible on GitHub.

Best,
C

**Comment by ysu2015** [comment]
Great. Thank you for your help. Ongoing~~

Y
