### ISSUE TITLE
How to use in BD Rhapsody WTA?

### ISSUE THREAD

**Issue by wajm** [sdparekh/zUMIs#228]
Hi,
I use BD Rhapsody system, but I don't know how to adjust it.
This is UMI information for BD Rhapsody.
https://teichlab.github.io/scg_lib_structs/methods_html/BD_Rhapsody.html
How can I set up zUMI yaml for BD Rhapsody?

**Comment by cziegenhain** [comment]
Hi,

Rhapsody data should not be a problem, I added a description of the barcode/UMI setup in the wiki:
https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#bd-rhapsody-wta-3

**Comment by cziegenhain** [comment]
Feel free to reopen if you need further assistance and let us know if zUMIs works well with your Rhapsody data!

**Comment by wajm** [comment]
Thanks.
I have one more question.
https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#bd-rhapsody-wta-3

file2:
    name: R2.fastq.gz
    base_definition:
      - cDNA(1-100)

What is cDNA (1-100) meaning?
Usually I do 2x150bp illumina sequencing. 
In this case, I can use cDNA 1-100?

**Comment by cziegenhain** [comment]
Hi,

You should change this parameter to however many bases of transcript cDNA you sequenced / would like to use.
