### ISSUE TITLE
Samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#229]
**Describe the bug**
In the "Counting" step, when go in to the "Loading reference annotation from:", I got error message "samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory" and the program went wrong. It looks like it is an issue while zUMIs try to call samtools. I could not find a solution when I google this error message and try to fix it by myself. I am happy to provide any info needed for dibug. Could anyone help? Thank you so much.

Y

**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

yes there is an issue calling on samtools. 
Did I remember right from your last github issue that you were using a custom path to samtools instead of the zUMIs miniconda?

**Comment by ysu2015** [comment]
Yeah. I do use the custom path to samtools and I specify the path in my yaml file. The mapping step went through smoothly. 

Y

**Comment by cziegenhain** [comment]
Okay I found a place where the samtools path did not get used correctly.
I updated zUMIs accordingly, so just update to the new version and it should be good to go.

Best,
Christoph

**Comment by ysu2015** [comment]
Sounds good. Thank you so much for quick response. 
I will give another try and keep you update.

Y

**Comment by ysu2015** [comment]
Hi Christoph,

Thank you so much. The newly updated zUMIs solved the samtools version problem. It works very nicely. I am going to close this issue for now. 

Y
