### ISSUE TITLE
Error running the example dataset

### ISSUE THREAD

**Issue by garrett-parker** [sdparekh/zUMIs#23]
Hi,

I am having trouble figuring out an error that comes up when I try to run the example data. In my bashrc I added p=`/path/to/zUMIs/` but I receive the following error when trying to run zUMIs

bash $p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/ExampleData/
bash: /zUMIs-master.sh: No such file or directory
[garrettp@n2193 zUMIs]$ p
-bash: /u/home/g/garrettp/scratch2/february/zUMIs: is a directory

**Comment by cziegenhain** [comment]
Hey,

it seems that you did not give the right path to your zUMIs installation.
if you type `ls $p/zUMIs-master.sh` the file should actually be there.
change your variable `p` to the correct path to run zUMIs.

Best,
Christoph
