### ISSUE TITLE
zUMIs output format

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#231]
Hi Christoph,
I made zUMIs run nicely on my hand. It is very impressive that it was much faster than other software, which have the similar application. Really save a lot of time when dealing with big dataset. I have one more questions. 
1) I prefer to have the gene in gene name rather than ensembl gene IDs.  How do I specify this in the settings.
Thank you so much in advance.

Y

**Comment by cziegenhain** [comment]
Hi,
Thanks for the positive feedback.
In the zUMIs_output/expression/ folder, you will find a text file containing all GeneIDs and their corresponding gene name. You can simply use this table to change your count table accordingly!

Best,
Christoph

**Comment by ysu2015** [comment]
Hi Christoph,
Thank you so much. Nice work.

Y
