### ISSUE TITLE
My YAML file has an error! but I don't know the reason, can you help me?

### ISSUE THREAD

**Issue by Some-is-thing** [sdparekh/zUMIs#232]
cat test_smart_seq3.zUMIs_YAMLerror.log 
$file1
NULL

$file2
NULL

[1] ""
[1] ""
[1] "" ""
[1] ""
[1] ""
[1] "" ""
[1] "NULL" "NULL"
$file1
NULL

$file2
NULL

$file1
NULL

$file2
NULL

[1] "Please check barcode list file path."
[1] 1

This is my YAML file:

project: test_smart_seq3
sequence_files:
  file1:
    name: /gpfsdata/home/zhangmy/MengJuan/monkey/smartseq3/v3-1_BKDL202604333-2a_1.clean.fq.gz
    base_definition:
    - cDNA(23-150)
    - UMI(12-19)
    find_pattern: ATTGCGCAATG
  file2:
    name: /gpfsdata/home/zhangmy/MengJuan/monkey/smartseq3/v3-1_BKDL202604333-2a_2.clean.fq.gz
    base_definition: cDNA(1-150)
reference:
  STAR_index: /gpfsdata/home/zhangmy/MengJuan/monkey/ref/mice/STAR_mu_no_gtf/
  GTF_file: /gpfsdata/home/zhangmy/MengJuan/monkey/ref/mice/Mus_musculus.GRCm38.99.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /gpfsdata/home/zhangmy/MengJuan/monkey/smartseq3/UMI/
num_threads: 50
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ''
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

**Comment by sdparekh** [comment]
Hi,

I think specifying _null_ for barcode_num and barcode_file options in your yaml file. 
https://github.com/sdparekh/zUMIs/blob/681502558a696a3cb613f83bf34a52609b5d0296/zUMIs.yaml#L63

It is always good to use the [pre-annotated yaml ](https://github.com/sdparekh/zUMIs/blob/main/zUMIs.yaml)file for avoiding such issues.

Let me know if this does not resolve your issue.

Best,
Swati

**Comment by Some-is-thing** [comment]
> Hi,
> 
> I think specifying _null_ for barcode_num and barcode_file options in your yaml file will help.
> https://github.com/sdparekh/zUMIs/blob/681502558a696a3cb613f83bf34a52609b5d0296/zUMIs.yaml#L63
> 
> It is always good to use the [pre-annotated yaml ](https://github.com/sdparekh/zUMIs/blob/main/zUMIs.yaml)file for avoiding such issues.
> 
> Let me know if this does not resolve your issue.
> 
> Best,
> Swati

Hi, Swati

I try your method, it works!
Thanks a lot.

Best wishes,
June
