### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by shangyf-stu** [sdparekh/zUMIs#234]
**Describe the bug**
zUMIs_YAMLerror.log only show 1

**To Reproduce**
Provide the YAML file and full standard output.
project: GSE117988
sequence_files:
  file1:
    name: 
    /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/0_fastq/10x/GSE117988/SRR7722937/SRR7722937_S1_L001_I1_001.fastq.gz
    base_definition:   
    - BC(1-8)
  file2:
    name: 
    /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/0_fastq/10x/GSE117988/SRR7722937/SRR7722937_S1_L001_R1_001.fastq.gz
    base_definition: 
    - BC(1-16)
    - UMI(17-28)
  file3:
    name: 
    /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/0_fastq/10x/GSE117988/SRR7722937/SRR7722937_S1_L001_R2_001.fastq.gz
    base_definition: 
    - cDNA(1-97)
reference:
  STAR_index: /asnas/pmod/zengjy/softwares/STAR-master/bin/Linux_x86_64/index
  GTF_file: /asnas/pmod/zengjy/softwares/STAR-master/bin/Linux_x86_64/index
  additional_STAR_params: '--runMode alignReads --readFilesCommand zcat '
  additional_files: ~
out_dir: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/4_zUMIs/10x/GSE117988/SRR7722937
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ''
  barcode_sharing: shared_i7_bcs.txt
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

**Screenshots**
------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------
Error: Syntax error loading yaml file
Execution halted
YAML file has an error. Look at the zUMIs_YAMLerror.log or contact developers.

**Desktop (please complete the following information):**
CentOS 7.2.1511
samtools-1.9
r-3.6.1
pigz-2.4
star-2.7
**Additional context**
I want to process a 10x datasets, follow Protocol specific setup in wiki. 
I have checked checkyaml.R, what should I do?
Anything would be appriciated!!

**Comment by cziegenhain** [comment]
Hi,
Please share the error log text file here too!
Most common issue would be a path that cannot be found.
Note: You cannot give relative paths, please change `barcode_sharing`
Also please remove your `additional_STAR_params` arguments, these basic things are taken care of by zUMIs.

Best,
Christoph

**Comment by shangyf-stu** [comment]
the error log text file only show "1"

**Comment by LGCSherlock** [comment]
> the error log text file only show "1"

Could you please tell me how you solved it?
