### ISSUE TITLE
one suggestion and one question

### ISSUE THREAD

**Issue by shangyf-stu** [sdparekh/zUMIs#235]
**Is your feature request related to a problem? Please describe.**
Dear sir or madam, 
Thanks for your attention, here are my suggestion and question, any thing is grateful.

Suggestion: The INDEX I have built by STAR is using --sdbOverhang 100. But when I run zUMIs, I must set the `--sdbOverhang cDNA_length-1`, so I need to rebuild the INDEX. But if I am processing a lot of datasets, I couldn't rebuilt so much time.

Question: How to use zUMIs to run a dataset with more than one pair of fastq files? Is there any scripts? What should I do?

**Describe the solution you'd like**

If you could let the users to adjust `--sdbOverhang` in the yaml file, it is easier.
Or if I can only adjust the `--sdbOverhang` in the Source code?

**Describe alternatives you've considered**

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

Thanks for the feedback. 
Regarding the splice junction overhang length: zUMIs detects the read length automatically and generates the sjdb on the fly. For this reason you should not use a STAR index with a specific overhang length in zUMIs, please see: https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping

If you have a dataset with more than one pair of fastq files, you can simply concatenate them prior to running.

Best,
Christoph

**Comment by shangyf-stu** [comment]
Hi, Christoph

Thanks for your reply so rapidly.
But I am still a little confused. For example, if I have thirty fastq files divided into two batches, then I should merge the files without batch effect into one file in the shell. and then run zUMIs twice?

Best wishes,
shang

**Comment by cziegenhain** [comment]
Hi shang,

Batch effects don't matter, each cell gets processed independent of the rest. As long as the barcodes for the cells are unique, you are fine.

**Comment by shangyf-stu** [comment]
Oh, I get it!
If I am dealing with Smart-seq2 data that does not contain barcode, can I not merge the data?

**Comment by cziegenhain** [comment]
https://github.com/sdparekh/zUMIs/wiki/Starting-from-demultiplexed-fastq-files

**Comment by shangyf-stu** [comment]
Hi, Christoph
One more question,
For some sequencing methods that include UMI and barcode, should adapters of reads which contain UMI and barcode sequence be removed? 
best,
Shang

**Comment by cziegenhain** [comment]
Hi,

Any sequence that is not defined as a base to use for BC, UMI or cDNA will be discarded.
Therefore, trimming is not necessary in most cases.

**Comment by shangyf-stu** [comment]
Thanks for your answer. It is useful for me.
In the output, the barcode number I usually get is 6-7 times more than the number of cell in the article. Is it normal? I used "Automatic" to detect barcode. And I am processing data from 10x, Microwell, Drop-seq, inDrop and scTrio-seq2.

**Comment by cziegenhain** [comment]
That is hard to answer for me, it really depends on the data. In general I find zUMIs highly concordant with the number of cells eg. CellRanger predicts.
I would always recommend to inspect the automatic barcode selection plot zUMIs will produce in the stats output folder, that should be informative to decide if the cell selection was useful.

**Comment by shangyf-stu** [comment]
That's it, I know
I have an idea about the extra cells compared to the cellranger
zUMIs uses the barcode range I provided to search within the range. If the range is correct, then after filtering and confirmation by zUMIs, these barcodes can also represent the correct cells. It’s just that the number of all cells has increased due to the threshold of zUMIs
Can I think about it this way?

**Comment by cziegenhain** [comment]
I'm not sure I understand correctly, but yes the cell selection crucially needs to have the correct barcode range. The automatic threshold of kept barcodes ("real cells") then depends on your other settings (eg. filtering) and the distribution of barcodes in the data.
