### ISSUE TITLE
BUGFATAL ERROR in reads input: quality string length is not equal to sequence length

### ISSUE THREAD

**Issue by shangyf-stu** [sdparekh/zUMIs#236]
**Describe the bug**
Dear zUMIs developers,
Thank you for giving us a nice tool to process single-cell data
I'm using zUMI pipeline to analyze data GSE103224, GSE111672 and GSE84465, which come from Microwell, inDrop, Smart-seq2 Respectively. I got this error several times:

EXITING because of FATAL ERROR in reads input: quality string length is not equal to sequence length
@SRR6825056.1.106
0
GGGCCTGCTAGTCTGTCAGGGCCTTGGCCCAGGGG
SOLUTION: fix your fastq file

Dec 29 09:08:40 ...... FATAL ERROR, exiting 
 
I have seen the checked the fastq file, the length of quality string and sequence is consistent. 
Then I use STAR 2.7.6a to run this file, it works well. And I rerun the fustq-dump with  the flags `--origfmt --defline-qual '+'`, it still does not work for the same error.

Here is the wrong read:
 @106
ATTGGATCGGAGTGATTGCTTGTGACGCCTTACTCACCGAACACATTTTTT
+
AAAAAEAEAAE<E6E<E<E<EA/EEE/<AEEEAE<<<A<<<AA<EEE<AE<

What should I do? Thanks for your help!!!!!
**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**
project: GSE103224
sequence_files:
  file1:
    name: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/0_fastq/test/GSE103224/SRR5988127.1_1.fastq.gz
    base_definition:
    - BC(1-26)
    - UMI(1-26)
  file2:
    name: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/0_fastq/test/GSE103224/SRR5988127.1_2.fastq.gz
    base_definition: cDNA(1-65)
reference:
  STAR_index: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/3.2.0_star_index
  GTF_file: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/3.2.0_star_index/Homo_sapiens.GRCh38.102.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /xtdisk/xiaojf_group/shangyf/a_result/Sequencing_data_quality_control/4_zUMIs/GSE103224
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools

**Desktop (please complete the following information):**
CentOS 7.2.1511
samtools-1.9
r-3.6.2
pigz-2.4
star-2.7.6a

**Additional context**

**Comment by cziegenhain** [comment]
Hi,

This is a known problem with SRA read ID lines:
https://github.com/sdparekh/zUMIs/wiki/Reprocessing-of-public-data

Best,
Christoph

**Comment by shangyf-stu** [comment]
thank you for your answer, it works now!
