### ISSUE TITLE
samtools failed to open "NA"

### ISSUE THREAD

**Issue by zakieh-tayyebi** [sdparekh/zUMIs#237]
Hi!
I am getting a lot of samtools errors in the 'Mapping' stage (please see the run-time log), indicating that the BAM files are NA and do not exist (I have provided correct absolute paths to everything):
```
[E::hts_open_format] Failed to open file NA
samtools view: failed to open "NA" for reading: No such file or directory
```
Then, in the counting step, the 'filtered.Aligned.GeneTagged.sorted.bam' file can not be opened (please see the run-time log).

I am using zUMIs 2.9.4f and its Conda environment (samtools 1.9, STAR 2.7.3a, R 3.6.3, pigz 2.3.4, Python 3.6.10, pysam 0.15.4, velocyto 0.17.17), on CentOS Linux 7 (Core), using 32 cores each with 10GB memory.

I have attached the run-time stdout/stderr file (zUMIs.Log), the config file (config.run.yaml), and the script used to run zUMIs (zUMIs.sh).

[zUMIs.Log](https://github.com/sdparekh/zUMIs/files/5765983/zUMIs.Log)

[config.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5765984/config.run.yaml.txt)

[zUMIs.sh.txt](https://github.com/sdparekh/zUMIs/files/5765985/zUMIs.sh.txt)

**Comment by cziegenhain** [comment]
Hi,

Sorry to hear that you are having problems with zUMIs!
I have seen the NA verbose before, seems to be some imprecision in chunking of the input which relies on an estimation of the read number by file size. Anyway I never had any downstreams issues so far!
I can see that the gene tagging (featureCounts) actually does run after STAR finishes, could you confirm that you have a non-zero looking Aligned.bam file?
According to the log, there were 875927253 reads - does that fit with your input?

My suspicion is that the error actually happens during the samtools sort operation. Usually using less memory at that step is safer! zUMIs should be plenty fast with just `mem_limit: 100`  instead.

Best,
Christoph

**Comment by zakieh-tayyebi** [comment]
Thank you for the prompt response!
I will decrease the memory limit.

This is what the 'filtered.tagged.Aligned.out.bam' file looks like:

<img width="1257" alt="Screen Shot 2021-01-04 at 13 47 17" src="https://user-images.githubusercontent.com/41304842/103568342-65340880-4e93-11eb-959f-25144df4ecb4.png">

Just in case, here's what the entire output looks like:

<img width="1014" alt="Screen Shot 2021-01-04 at 13 40 37" src="https://user-images.githubusercontent.com/41304842/103567982-babbe580-4e92-11eb-9c28-823242ca7815.png">

**Comment by cziegenhain** [comment]
Yes that looks fine to me, let's see what happens in the rerun!

**Comment by zakieh-tayyebi** [comment]
Thank you!
