### ISSUE TITLE
Unable to load fcountsLib2

### ISSUE THREAD

**Issue by Abonacolta** [sdparekh/zUMIs#239]
I am trying to run zUMIs on some 10x data on my university's supercomputer cluster (IBM Power9/Nvidia Volta- LINUX). I keep getting the following error after ```[1] "Assigning reads to features (ex)"```:
```
Error in dyn.load(fcounts_clib) : 
  unable to load shared object '/home/amb195/zUMIs_dir/zUMIs/misc/fcountsLib2':
  /home/amb195/zUMIs_dir/zUMIs/misc/fcountsLib2: cannot open shared object file: No such file or directory
Calls: .runFeatureCount -> featureCounts -> dyn.load
Execution halted
```
I checked and made sure the fcountsLib2 is in this directory. The binary file is just not executable.
I have also updated the RSubread package and still came across the same error. I am using R4.0.2 and my own dependencies for this run. 

Error File: [zumi-err.txt](https://github.com/sdparekh/zUMIs/files/5810675/zumi-err.txt)
Output File: [zumi-out.txt](https://github.com/sdparekh/zUMIs/files/5810676/zumi-out.txt)
YAML File: [zUMIs_Ofav1.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/5810674/zUMIs_Ofav1.run.yaml.txt)

I appreciate any help in addressing this error. Thanks!

**Comment by cziegenhain** [comment]
Hey,

I haven’t heard about Volta Linux, but I could imagine that the precompiled C library will not work there for you.
For other users with this issue before, recompiling and replacing this library file has worked so far, please check this comment that has the source code to compile:
https://github.com/sdparekh/zUMIs/issues/184#issuecomment-631054909

Good luck,
Christoph

**Comment by Abonacolta** [comment]
Hello,

I wasn't sure if it was  C library or not because I didn't get the typical glibc mention that the others have reported. But I have tried recompiling fcounts from the zip file but can't seem to get it to work.
```
$ R CMD SHLIB *.c -o fcountsLib2
gcc -std=c99 -shared -L/home/amb195/miniconda2/envs/r-linux/lib/R/lib -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,/home/amb195/miniconda2/envs/r-linux/lib -Wl,-rpath-link,/home/amb195/miniconda2/envs/r-linux/lib -L/home/amb195/miniconda2/envs/r-linux/lib -Wl,-rpath-link,/home/amb195/miniconda2/envs/r-linux/lib -o fcountsLib2 aligner.o atgcContent.o build-sam-index.o core-bigtable.o core.o core-indel.o core-interface-aligner.o core-interface-subjunc.o core-junction.o detectionCallAnnotation.o detectionCall.o detection-calls.o exon-algorithms.o exon-align.o exon-align-indel.o flattenAnnotations.o fullscan.o fusion-align.o gene-algorithms.o gene-value-index.o hashtable.o HelperFunctions.o index-builder.o input-files.o interval_merge.o long-hashtable.o longread-mapping.o LRMbase-index.o LRMchro-event.o LRMfile-io.o LRMhashtable.o LRMhelper.o LRMseek-zlib.o LRMsorted-hashtable.o mergeVCF.o processExons.o propmapped.o qualityScores.o read-repair.o readSummary.o removeDupReads.o R_wrapper.o sam2bed.o sambam-file.o seek-zlib.o SNPCalling.o sorted-hashtable.o sublog.o tx-unique.o -lz -lpthread -DMAKE_FOR_EXON -L/home/amb195/miniconda2/envs/r-linux/lib/R/lib -lR
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: Relocations in generic ELF (EM: 62)
/home/amb195/miniconda2/envs/r-linux/bin/ld: atgcContent.o: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [/home/amb195/miniconda2/envs/r-linux/lib/R/share/make/shlib.mk:10: fcountsLib2] Error 1
```

Any idea what this could be?

Thanks,
Anthony

**Comment by cziegenhain** [comment]
Hi Anthony,

Sorry to say that I don't have any tips there on how to get the compilation to work.
The standard Rsubread package via bioconductor won't help unfortunately because we need some custom tags for the exon/intron assignments.

Could running via docker be a solution for you?
https://hub.docker.com/r/chrzie/zumis2/tags?page=1&ordering=last_updated

I haven't updated the docker image in a while but you can always run a quick git pull within it before starting to get the latest updates!

Best
Christoph

**Comment by Abonacolta** [comment]
Hi Christoph,

No worries. Thanks for the help. I have contacted IT for my University's Supercomputer and will post here if we find a solution. Unfortunately, the cluster doesn't support docker. 

Thanks,
Anthony

**Comment by cziegenhain** [comment]
Fingers crossed!
