### ISSUE TITLE
Can't RUN zUMIs

### ISSUE THREAD

**Issue by Jianye-Chang** [sdparekh/zUMIs#241]
Dear sir:
  I have a  trouble about the running of zUMIs.Because when i run it, it will give me the reply as follow.
- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -
$./zUMIs-master.sh -y zUMIs.yaml
-------------

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs

-------------
Error:
Execution halted
YAML file has an error. Look at the zUMIs_YAMLerror.log or contact developers.

- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - -- - - 

In fact, i have check my YAML file .it doesn't have mistakes,and i use the command "cat UMIs_YAMLerror.log" ,it also doesn't have any useful information for me.

YAML file:[zUMIs.yaml.txt](https://github.com/sdparekh/zUMIs/files/5846995/zUMIs.yaml.txt)

and my sequencing file is from smart-seq3. So can you give me some suggestions to make the software run ？I 've spent two weeks on this thing.Thanks!!!

**Comment by cziegenhain** [comment]
The error means that your YAML file is incorrect. you can upload the  zUMIs_YAMLerror.log  here so I can take a look.

From the first glance I see that you are eg. missing a space between the colon and the value of your fields (eg. project:).
I would also advise against using - characters within file names.

Even though not technical errors that will produce errors, there are other things in your YAML that are not correct settings to run Smart-seq3. 
Please check carefully the documentation and examples:
https://github.com/sdparekh/zUMIs/wiki/Usage#setup-using-the-yaml-config-file
https://github.com/sandberg-lab/Smart-seq3/blob/master/allele_level_expression/mouse_cross.yaml
https://www.protocols.io/view/smart-seq3-protocol-bcq4ivyw?step=18

**Comment by cziegenhain** [comment]
Also please always run the latest version of the pipeline.

**Comment by Jianye-Chang** [comment]
> Also please always run the latest version of the pipeline.

ok  thanks！ Advice that will benefit me for life....

**Comment by Jianye-Chang** [comment]
@cziegenhain Excuse me.sir.  I have a new error on the verge of success....You see as follow:
###
Traceback (most recent call last):
  File "/md01/changjy/software/zUMIs/correct_UBtag.py", line 123, in <module>
    main()
  File "/md01/changjy/software/zUMIs/correct_UBtag.py", line 99, in main
    bcs = load_bcs(args.bcs)
  File "/md01/changjy/software/zUMIs/correct_UBtag.py", line 16, in load_bcs
    with open(bcpath) as f:
FileNotFoundError: [Errno 2] **No such file or directory: '/md01/changjy/data/result/zUMIs_output/Smart-seq3kept_barcodes_binned.txt'**
[1] "4.5e+08 Reads per chunk"
[E::hts_open_format] **Failed to open file "/md01/changjy/data/result/Smart-seq3.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam"** : No such file or directory
samtools index: failed to open "**/md01/changjy/data/result/Smart-seq3.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam":** No such file or directory
[1] "2021-01-25 17:08:07 CST"
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 184 barcodes in this chunk..."
**Error in value[[3L]](cond) : 
  failed to open BamFile: file(s) do not exist:
  ‘/md01/changjy/data/result/Smart-seq3.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam’**
Calls: reads2genes_new ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted
Mon Jan 25 17:08:08 CST 2021
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/md01/changjy/data/result/zUMIs_output/expression/Smart-seq3.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan 25 17:08:13 CST 2021
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2021-01-25 17:08:13 CST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/md01/changjy/data/result/zUMIs_output/expression/Smart-seq3.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan 25 17:08:18 CST 2021


I run the smart-seq3 data,my yaml file is okay...
This error tell me that I don't have these files.....

Look forward to your reply

**Comment by cziegenhain** [comment]
Hi,

Seems like there was an issue when running zUMIs with the UMI hamming correction switched on but not doing cell barcode error correction.
I have pushed an update to github that should take or of that.

Please fetch the update and rerun.
Best,
Christoph

**Comment by Jianye-Chang** [comment]
THx！I have get the result ! May I can use this software to validate my experiment result ,hope this software is getting better and better with the arising of smart-seq3 and other sequence method.Thanks!!!

**Comment by cziegenhain** [comment]
Good to hear it works!
