### ISSUE TITLE
Errors right before summarizing stem

### ISSUE THREAD

**Issue by curtisd0886** [sdparekh/zUMIs#243]
Hello, I am trying to run a dataset and I keep getting an error message during the last stages of zUMIs. Any idea what could be causing this? 

Error in rbindlist(rsamtools_reads, fill = TRUE, use.names = TRUE) :
  Item 1 of input is not a data.frame, data.table or list
Calls: reads2genes_new -> rbindlist
In addition: Warning message:
In mclapply(1:nrow(idxstats), function(x) { :
  all scheduled cores encountered errors in user code
Execution halted
Mon Jan 25 20:45:42 EST 2021
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/cndd3/Data/Multi_hybrid/new/zUMIs_output/expression/Invivo_multi.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan 25 20:45:45 EST 2021
Descriptive statistics...
[1] "I am loading useful packages for plotting..."   
[1] "2021-01-25 20:45:46 EST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/cndd3/Data/Multi_hybrid/new/zUMIs_output/expression/Invivo_multi.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by cziegenhain** [comment]
Hi,
This usually means that an error already occured before this step.
Please attach your yaml file and the full log so I can have a look.

**Comment by curtisd0886** [comment]
Thanks for your help. I have attached the files below. 
Yaml:
project: Invivo_multi
sequence_files:
  file1:
    name: /home/cndd3/Data/Multi_hybrid/Multi_hybrid_R1_good.fq.gz
    base_definition:
    - BC(1-48)
    - UMI(50-57)
  file2:
    name: /home/cndd3/Data/Multi_hybrid/Multi_hybrid_R2_good.fq.gz
    base_definition: cDNA(1-100)
reference:
  STAR_index: /home/cndd3/genomes/MM10_all_2.7.6
  GTF_file: /home/cndd3/genomes/Mus_musculus.GRCm38.99-vhh-td-cre.gtf
  additional_STAR_params: --outFilterScoreMinOverLread 0 --outFilterMatchNminOverLread     0
    --outFilterMatchNmin 0
  additional_files: ~
out_dir: /home/cndd3/Data/Multi_hybrid/new
num_threads: 32
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 15
  UMI_filter:
    num_bases: 1
    phred: 15
barcodes:
  barcode_num: ~
  barcode_file: ~
  automatic: yes
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
Rscript_exec: Rscript
STAR_exec: /home/cndd3/STAR-2.7.6a/source/STAR
pigz_exec: pigz
samtools_exec: samtools


[log.txt](https://github.com/sdparekh/zUMIs/files/5872871/log.txt)

**Comment by cziegenhain** [comment]
Sorry for the late reply.

Your YAML file looks good!
It seems that the error occurs when loading reads from the bam file in R. STAR had complained about a GTF format error, but that seems to be just one transgene you added so I am unsure if this is the cause of the problem.

Would you be able to share your zUMIs output with us somehow? Feel free to email a link.

Best,
Christoph

**Comment by curtisd0886** [comment]
Hey Christoph,
Thanks for the reply. I was able to get passed that previous error message (I modified my R1 so the barcodes were shorter and that seem to do the trick), however I am still running into an issue with the processing of the loom file. I keep getting the error below: 

[1] "loomR found"
Error in asMethod(object) :
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105
Calls: rds_to_loom ... as.matrix -> .local -> as.matrix.Matrix -> as -> asMethod
Execution halted
 
I still get the RDS file, but its quite large and I cannot seem to load it into Seruat. Thanks for your help.

**Comment by cziegenhain** [comment]
Hey,

Great to hear!
This can be because of the sparseMatrix to denseMatrix not enjoying a large number of cells.

You can load the rds file using:

`dge <- readRDS(filename)`

and then simply construct a Seurat along those lines:

`CreateSeuratObject(counts = dge$umicount$exon$all)`

(this would be for exon counts, or use `inex` for intron+exon)

Best,
Christoph

**Comment by curtisd0886** [comment]
That worked perfectly. Thank you!

**Comment by cziegenhain** [comment]
Good to hear!
