### ISSUE TITLE
Errors on zUMIs.sh: command substitution: line 235: `cut -d' ' -f1 <(echo ${fqfiles}))'

### ISSUE THREAD

**Issue by loverlyday** [sdparekh/zUMIs#244]
hi,
 i get  a error like this:
 You provided these parameters:
 YAML file:	run2.yaml
 zUMIs directory:		/home/xxx/biosoft/zUMIs-main
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   100
 zUMIs version 2.9.4f 

Thu Jan 28 10:16:40 CST 2021
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Filtering...
/home/xxx/biosoft/zUMIs-main/zUMIs.sh: command substitution: line 235: syntax error near unexpected token `('
/home/xxx/biosoft/zUMIs-main/zUMIs.sh: command substitution: line 235: `cut -d' ' -f1 <(echo ${fqfiles}))'

the yaml file like this:
project: no10A
sequence_files:
  file1:
    name: /home/xxx/smartseq3/test/L3_R1.fastq.gz
    base_definition:
      - cDNA(1-150)
  file2:
    name: /home/xxxx/smartseq3/test/L3_R2.fastq.gz
    base_definition:
      - BC(23-38)
      - UMI(39-48)
    find_pattern: CTACACGACGCTCTTCCGATCT
reference:
  STAR_index: /home/xxx/ref/Macaca_fascicularis_5.0_STAR2.7.3a_index
  GTF_file: /home/xxx/index/Macaca_fascicularis_5.0/Macaca_fascicularis.Macaca_fascicularis_5.0.98.gtf
  additional_STAR_params: '--limitSjdbInsertNsj 2000000'
  additional_files:
out_dir: /home/xxx/smartseq3/test
num_threads: 40
mem_limit: 100
filter_cutoffs:
  BC_filter:
    num_bases: 3
    phred: 20
  UMI_filter:
    num_bases: 3
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: /home/xxxx/smartseq3/test/barcode.txt
  automatic: no
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: yes
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 1
  write_ham: yes
  velocyto: no
  primaryHit: yes
  twoPass: no
make_stats: yes
which_Stage: Filtering
read_layout: SE

it is so strange that i can't find why.The zUMIs works fine yesterday,but get the error now.I can't  figure out what happened. Can you suggest a solution? Thanks

**Comment by sdparekh** [comment]
Can you show a couple of reads from your fastq file

**Comment by cziegenhain** [comment]
i agree with @sdparekh that a look into the fastq file would be helpful.
Otherwise could it also be a formatting/indentation issue in the YAML config file?
Happy to check that if you attach it as a file instead of copying the text (which loses the indentation in GitHub).

**Comment by loverlyday** [comment]
thank a lot .I have solved it.use the command: bash zUMIs.sh -y xxx.yaml rather than sh zUMIs.sh -y xxx.yaml
