### ISSUE TITLE
Cells right to the blue line are selected

### ISSUE THREAD

**Issue by yiyelinfeng** [sdparekh/zUMIs#245]
Hi, 
  there is a question, the parameter 'nReadsperCell' is the first filter the barcode, and then zUMIs will filter barcode according the distribution of left barcode with the reads and plot the "detected_cells.pdf" in the zUMIs_output/stats files again. so, there is a parameter for not filter the barcode second? because some methods like smart-seq2 can get the cell number(96) according to the library. I check the filtered barcode and found some barcode in the smart-seq2 barcode files which have ~20,000 reads but the second cutoff is 30,000. but I want retain the barcode with ~20,000 reads, what can I do for that?

  thanks!

**Comment by cziegenhain** [comment]
Hi,

If the automatic barcode detection is removing too many barcodes you are interested in, please use one of the other barcode selection methods (eg barcode whitelist or fixed number of BCs):
https://github.com/sdparekh/zUMIs/wiki/Barcodes

Best,
Christoph
