### ISSUE TITLE
How to explain the "User"

### ISSUE THREAD

**Issue by yiyelinfeng** [sdparekh/zUMIs#246]
hello,
   
   When I use the zUMIs with input the barcode_file, there are output the 'XXXX.feature.pdf' under the zUMIs_output/stats path, how to explain this figure whith the "User"? In my opinion, It should be the reads with my input barcode cells, but there are large reads in the Exon but not include the proportion in 'User' in the middle plot. my data use the smart-seq2 protocols.

this is the figure.
![图片](https://user-images.githubusercontent.com/20608660/107944998-f2f23000-6fc9-11eb-8b08-2fcafe6d2485.png)
 
  thanks!

**Comment by sdparekh** [comment]
Hi,
The "user" reads are the ones assigned to the reference you specified to the option "additional_files". Did you have external references like ERCC or other spike-in genes? They are ultimately added to the final count tables. 

Let us know if you have any further questions.

Best
S

**Comment by yiyelinfeng** [comment]
Hi S,

Thanks for your reply. I got this. my data have ERCC genes.

Best,

lin
