### ISSUE TITLE
BUG splitfq.sh add an extra path to fastq file when fastq file is plain but not gz suffixed.

### ISSUE THREAD

**Issue by crotoc** [sdparekh/zUMIs#248]
Thanks for developing this great tool! I meet a bug when running it using non gz fastq input. Please see the following details.

**Describe the bug**
The splitfq.sh has a bug in the function of splitfq:

![image](https://user-images.githubusercontent.com/12446554/109424551-a6cfc400-79a9-11eb-965a-e4f28aa99165.png)

In this line:

split --lines=$nl --filter=''$pexc' -p '$nthreads' > $FILE.gz' $d/$fqfile $t$pref$project 

it will add $d to $fqfile that cause a "file not find error"

Remove "$d/" will fix it!

**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sdparekh** [comment]
Hi crotoc,

Thanks for pointing this out. It is fixed.
