### ISSUE TITLE
BUG When using fastq with no .gz suffixed, cell barcode can not be extracted.

### ISSUE THREAD

**Issue by crotoc** [sdparekh/zUMIs#249]
Thanks for fix my last bug and I encounter a new one.

**Describe the bug**
In zUMIs.sh at line 257, 
pref=$(basename ${f} )
should be 
pref=$(basename ${f} .gz)

![image](https://user-images.githubusercontent.com/12446554/109589422-eabce900-7acf-11eb-8c03-1c45d9d71a88.png)

Because the former step is splitfq.sh, which will generate splitted gz files. If the .gz is not removed from basename of ${f}, it will result the line 96 of qfilter_v2.ql to add an extra .gz at the end of the splited gz files. Then no bam file can be produced and no cell barcode can be identified.

**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by cziegenhain** [comment]
I would recommend to start with gzipped fastq files instead. We will probably retire the option for uncompressed input because it is not really practical.

**Comment by crotoc** [comment]
Okay. Thanks!
