### ISSUE TITLE
Problem running zUMIs on bam file

### ISSUE THREAD

**Issue by garrett-parker** [sdparekh/zUMIs#25]
Hi,

How do I properly use zUMIs on a bam file I have already created?

I tried

$ bash /u/home/g/garrettp/scratch2/february/zUMIs/zUMIs-master.sh -X reads.simulated.bam 

and received the error
 No Barcode read!! One can not run this pipeline without -f option. 

How do i use this pipeline if I am beginning with a bam file?

Thanks

**Comment by sdparekh** [comment]
Hi,

The -X option works for a mapped BAM file. This option is especially designed when you want to use a mapper other than STAR. However, you need to provide all the "required parameters" for the downstream process as given here https://github.com/sdparekh/zUMIs/wiki/Usage.

The example zUMIs command is given below.
bash zUMIs-master.sh -f barcoderead.fq.gz -r cDNAread.fq.gz -c 1-6 -m 7-16 -l 50 -g STARidx -a annotation.gtf -n studyname -w Counting -X mapped.bam

Let me know if you need any further help.

Best,
Swati

**Comment by rcosentino** [comment]
Dear zUMIs-team,
I am also willing to run zUMIs using an already mapped BAM file. But I could not figure out how to do it. I tried to run it as in your example but I get an error saying "This key is not available! Please check the usage again: -f" , when I print the usage info, I don't see any of the parameters that you gave in that example, the only required parameter present is the "-y".. and I also cannot find anything in here [https://github.com/sdparekh/zUMIs/wiki/Usage](url) , am I missing something?
I am using zUMIs version 2.4.5b

Best,

Raúl

**Comment by cziegenhain** [comment]
Hi Raul,

Thanks for using zUMIs. As you can see from the wiki, all parameters are now set up in a config file. This issue here is very old and refers to the usage in the old version of zUMIs. 

Previously mapped bam files will likely only work if they have been generated by zUMIs - otherwise they will lack the correct barcode and UMI tags. 

Best,
Christoph

**Comment by rcosentino** [comment]
Hi Christoph,

Thank you for your quick response. So, it is not possible anymore to use a different mapper. What a pity. Thanks, though.
Best,
Raúl

**Comment by cziegenhain** [comment]
Hi Raul,

Yes we focused in on STAR a bit more to speed up processing times.
Which mapper would you want to use?

**Comment by rcosentino** [comment]
Hi Christoph,
I have been using bwa, and for consistency reasons, I did not want to change.

**Comment by cziegenhain** [comment]
bwa is not a good idea at all for RNA-seq. you'd need to align to the transcriptome but even that will result in a loss of power.
https://www.biorxiv.org/content/biorxiv/early/2019/03/19/583013.full.pdf

You'll get more accurate results with defaults in zUMIs.

**Comment by rcosentino** [comment]
Thank you for pointing out that paper. Actually I am working with an organism with no cis-splicing, so, using a non-splice-aware aligner and aligning to the genome it is ok, don't you think? But I see your point regarding higher false-positive mapping rate with bwa compared to STAR, although I don't know if it would also be the case for organisms without cis-splicing...

**Comment by cziegenhain** [comment]
Even for non-spliced alignments, STAR will perform very well.

**Comment by rcosentino** [comment]
Ok, I will try to switch. Thank you very much for your help and advice.
Best,
Raúl
