### ISSUE TITLE
exiting because of fatal error in reads input

### ISSUE THREAD

**Issue by HeChao7021** [sdparekh/zUMIs#250]
**Describe the bug**

**To Reproduce**
Provide the YAML file and full standard output.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by cziegenhain** [comment]
... it seems like you didn't send any description of your issue here.

**Comment by HeChao7021** [comment]
Yes, sorry. because the internet here is not good, and these days I cannot open the github properly. Actually, my question is that when I using zUMIs to analysis the data generate from 10 genome (SRR12340620), and the error comes "exiting because of FATAL ERROR in reads input: short read sequence line: 0 Read Name=@SRR12340620.30185066". I has checked the fastq file, that reads exited. Could you please help me to fix this problem? 
















At 2021-03-20 06:36:30, "cziegenhain" ***@***.***> wrote:

... it seems like you didn't send any description of your issue here.

**Comment by cziegenhain** [comment]
Please review the documentation on how to reprocess data from SRA: https://github.com/sdparekh/zUMIs/wiki/Reprocessing-of-public-data

**Comment by HeChao7021** [comment]
> Please review the documentation on how to reprocess data from SRA: https://github.com/sdparekh/zUMIs/wiki/Reprocessing-of-public-data

ok, thank you very much.

**Comment by HeChao7021** [comment]
> Please review the documentation on how to reprocess data from SRA: https://github.com/sdparekh/zUMIs/wiki/Reprocessing-of-public-data

Hello cziegenhain. I reprocessed the public data as you recommend, i.e, use fastq-dup --split file --origfmt --defline-qual '+' x.sra --gzip to unzip the sra data, and run the zUMIs.sh again. While the error comes "pigz:skipping:/.temMerge/SRR12340621_3.fastqSRR12340621ai.gz does not exist @ A00261:171:hl3ftdsxx:4:2653:22797:26694 Error! Fastq files are not in the same order ..............". Bug your reply again. Thanks!

**Comment by sdparekh** [comment]
The error suggests that your read files are not in the same order. Please have both your fastq files sorted by readid in the same order.

**Comment by HeChao7021** [comment]
> The error suggests that your read files are not in the same order. Please have both your fastq files sorted by readid in the same order.

Thanks. Now I fix it using this way:
seqkit seq --name --only-id SRR12340622_2.fastq.gz SRR12340622_3.fastq.gz | sort | uniq -d >id.txt
seqkit grep --pattern-file id.txt SRR12340622_2.fastq.gz -o SRR12340622_S1_L001_R1_001.fq.gz
seqkit grep --pattern-file id.txt SRR12340622_3.fastq.gz -o SRR12340622_S1_L001_R2_001.fq.gz
