### ISSUE TITLE
How to deal with tolerating one mismatched base in each X-base barcode for reads?

### ISSUE THREAD

**Issue by yiyelinfeng** [sdparekh/zUMIs#251]
Hi zUMIs team,

    Thanks a lot for this amazing tool to deal with single cell data! I'm wondering to know there is a function or how to set the parameters in yaml files with  tolerating one mismatched base in each X-base barcode for reads? such as the BC(1-8, 20-28, 40-48), and I want to keep one mismatched base in 1-8, 20-28, 40-48 respectively.

    Thanks so much in advance for your help.

Best,
Lin

**Comment by cziegenhain** [comment]
Hi Lin,

There is no setting for allowing exactly one mismatch in each of the individual barcode pieces.
 You can control the overall number of mismatches with the BarcodeBinning setting.

Best,
Christoph

**Comment by yiyelinfeng** [comment]
> Hi Lin,
> 
> There is no setting for allowing exactly one mismatch in each of the individual barcode pieces.
> You can control the overall number of mismatches with the BarcodeBinning setting.
> 
> Best,
> Christoph
