### ISSUE TITLE
samtools index: failed to create index for AK58.filter.Aligned.GeneTagged.sorted.bam": Numerical result out of range

### ISSUE THREAD

**Issue by HeChao7021** [sdparekh/zUMIs#254]
**Describe the bug**
When I analysis the snRNA-seq data from wheat roots, the error comes [E::hts-idx-push] Region 536878855..536878953 cannot be stored in a bai index, Try using a csi index with min_shift=14, n_lvls>=6. samtools index: failed to create index for 'AK58.filtered.Aligned.GeneTagged.sorted.bam": Numerical result out of range. 
I add a '-c' in the line 145 of the zUMIs-dge2.R file: index_cmd<-paste(samtoolsexc, "index -c -@", opt$num_threads, outbamfile), However no work. So come here to ask you how to solve this problem. By the way, zUMIs is a amazing tools, I really love it.

**Comment by cziegenhain** [comment]
Hi,

Nice to hear that you like zUMIs!
For this issue, it seems samtools indexing as we use it doesn't support chromosome longer than 512 Mb. We have only validated the tool with mammalian genomes. 
Are there any workarounds people with huge plant genomes typically do, like break up long genomes in several contigs in the reference?
