### ISSUE TITLE
Question: Is the donwsampling of UMI reads performed on all reads or just 5' reads ? 

### ISSUE THREAD

**Issue by Radek91** [sdparekh/zUMIs#255]
Hi!

I run the latest version of zUMIs on SS3 data and generated a matrix of count object (`dgecount.rds`) containing several downsampling matrices. 

`sce <- read_rds("Smartseq3.dgecounts.rds")`

While I assume that the following downsampling matrix has been generated using all the reads (5' & internal):

`sce$readcount$inex$downsampling$downsampled_100000`

Could you confirm that the `umicount` and the `readcount_internal` have been produced by downsampling 100K 5' reads and internal reads respectively ? 

`sce$umicount$inex$downsampling$downsampled_100000`
`sce$readcount_internal$inex$downsampling$downsampled_100000`

and not by downsampling first 100K reads from all the reads and then re-extracting the UMI or internal reads ? 

Thank you in advance!

**Comment by cziegenhain** [comment]
Hi,

Yes the downsampling is always done on all reads in that barcode. So for Smartseq3 data the number of UMIs within e.g. 100k reads would also depend on the fraction of 5' vs internal reads.

Best,
Christoph

**Comment by Radek91** [comment]
Thank you for the super fast clarification! 

Have a nice day,

Vincent
