### ISSUE TITLE
10x v2 data error

### ISSUE THREAD

**Issue by thomsak** [sdparekh/zUMIs#26]
Hi, 

I am trying to run zUMIs on 10x v2 data like this: zUMIs-master.sh -f 16_SI-GA-H10_S7_L001_R1_001.fastq -r 16_SI-GA-H10_S7_L001_R2_001.fastq -n samplename -g GRCm38/Sequence/STARIndex -a GRCm38/Annotation/Genes/genes.gtf -c 1-16 -m 17-26 -l 58

And I am getting the following error: 

Raw reads: 12684411 
Filtered reads: 8105811 

Mar 05 15:14:27 ..... started STAR run
Mar 05 15:14:27 ..... loading genome

EXITING because of fatal PARAMETERS error: present --sjdbOverhang=57 is not equal to the value at the genome generation step =100
SOLUTION: 

Mar 05 15:14:27 ...... FATAL ERROR, exiting

Also it is unclear to me how to provide the i7 index read file to zUMIs. 

Thx,
Thom

**Comment by cziegenhain** [comment]
Hey Tom,

thanks for using zUMIs.
it seems your STAR genome index is prepared with a fixed read length.
Please check [here on STAR genome indexing](https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping).

To add the i7 Index read, add these parameters to your call:
`-T i7_file.txt -U 1-8`

Let me know if you need any other help.

Thanks for using zUMIs!

Best,
Christoph

**Comment by thomsak** [comment]
Thanks for the quick answer.

B/w,
T
