### ISSUE TITLE
Shebang line in perl scripts

### ISSUE THREAD

**Issue by samfux84** [sdparekh/zUMIs#261]
Hi,

Please consider using the following shebang line for perl scripts

#!/usr/bin/env perl

instead of

#!/usr/bin/perl

as this is more flexible and allows the users to also use a perl interpreter that is not installed in a standard location (/usr/bin)

Best regards

Sam

**Comment by sdparekh** [comment]
Thank you! That indeed is a good input. We will make these changes in the next release.
