### ISSUE TITLE
zUMI STAR error by clip3pAdapterSeq

### ISSUE THREAD

**Issue by MJ-Yang** [sdparekh/zUMIs#264]
Hi 

I'm running zUMI for Smart Seq 3 library, following your guidelines. 

```
reference:
  STAR_index: /home/users/mjyang/Reference/GRCm38/STAR_dir/
  GTF_file: /home/users/mjyang/Reference/GRCm38/gencode.vM16.primary_assembly.annotation.gtf
  additional_STAR_params: --limitSjdbInsertNsj 2000000 --clip3pAdapterSeq CTGTCTCTTATACACATCT
  additional_files: ~

```
My reference part of YAML config are above, however, throws error 
```
EXITING because of fatal PARAMETER error: --clip3pAdapterSeq has to contain 2 values to match the number of mates.
SOLUTION: specify 2values in --clip3pAdapterSeq , for no clipping use -
Jun 06 19:16:01 ...... FATAL ERROR, exiting
```
Seems 

> clip3pAdaterSeq

 requires two inputs, while I looked at other examples of yaml configs, those have not.

Can you help me what's going wrong?

**Comment by sdparekh** [comment]
Hi

It is an error prompting from STAR recently. I would wait until Alex Dobin resolves this or go to a little older version of STAR (2.7x). For your reference, there is a recent issue on STAR Github if you want to follow (https://github.com/alexdobin/STAR/issues/1260).

I hope this resolves your query.

Best
Swati
