### ISSUE TITLE
Error version problem

### ISSUE THREAD

**Issue by hsriniva11** [sdparekh/zUMIs#268]
Hi I have multiple problems. Here's my log file

First Error: I'm using s STAR index created with 2.7.3 but the program detects it as 2.7.1.

Wed Jun 23 11:20:16 UTC 2021
WARNING: The STAR version used for mapping is 2.7.3a and the STAR index was created using the version 2.7.1a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.3a.
Filtering...
Wed Jun 23 11:59:24 UTC 2021
[1] " reads were assigned to barcodes that do not correspond to intact cells."
Error in setnames(x, value) : 
  Can't assign 0 names to a 1 column data.table
Calls: BCbin ... colnames<- -> names<- -> names<-.data.table -> setnames
Execution halted

Mapping...
[1] "2021-06-23 11:59:27 UTC"

EXITING: FATAL INPUT ERROR: duplicate parameter "quantMode" in input "Command-Line"
SOLUTION: keep only one definition of input parameters in each input source

**Comment by cziegenhain** [comment]
Hi,

You should always attach a full log, the used config file and any other relevant information when asking for help.

As discussed in other issue threads, the STAR message is just a warning and is okay. 

The other error during Barcode handling sounds like there are no valid reads from which barcodes could be extracted. 

Best
Christoph

**Comment by hsriniva11** [comment]
Hi Christoph,
Thanks for the quick response. Here's the full log file. I'm trying to run Smart-Seq3 using zUMIs. By config file, do you mean yaml file? 
[04-run-zUMIs.log](https://github.com/sdparekh/zUMIs/files/6704463/04-run-zUMIs.log)

**Comment by cziegenhain** [comment]
Yes I meant the yaml file. 
There seems to be a lot of end of file (EOF) Errors, right in the start, this indicates there is an issue with the input files!

**Comment by hsriniva11** [comment]
I managed to fix that issue. The second time I rmanaged to debug them (using the same log file, look for the next date)
Here's the yaml file. 
[new.run.yaml.txt](https://github.com/sdparekh/zUMIs/files/6704508/new.run.yaml.txt)

**Comment by cziegenhain** [comment]
I see!

Could you try switching off error correction in the barcodes? Wondering if this is the problem because in this case all reads will of course match perfectly to the expected barcodes. 
BarcodeBinning: 0

What's the file size of the unmapped bam file?

Also, you can remove --quantMode TranscriptomeSAM
This is a default within zumis and shouldn't be given as a duplicate argument.

**Comment by hsriniva11** [comment]
12G unmapped bam file
Yup, I'm currently running a version without quantMode parameter. I can try BarcodeBinning but I'm not sure I get the logic behind it.

**Comment by hsriniva11** [comment]
Hi, I tried what you said, I'm still getting the same error. Here's the log file. 
[04-run-zUMIs1.log](https://github.com/sdparekh/zUMIs/files/6709755/04-run-zUMIs1.log)

**Comment by cziegenhain** [comment]
I see a different error now in your log: are you giving the `sjdbOverhang` parameter explicitly or have you generated the genome index with a specific overhang? You should not do that as zUMIs with deal with this on the fly.

**Comment by hsriniva11** [comment]
Thanks for your help,  I managed to get the sjdbOverhang option to work. Now GeneTagged bam aren't getting created so it says file not found. Here's the complete log file and the yaml file. 
[pipeline.txt](https://github.com/sdparekh/zUMIs/files/6733792/pipeline.txt)
[run-zUMIs.log](https://github.com/sdparekh/zUMIs/files/6733794/run-zUMIs.log)

**Comment by cziegenhain** [comment]
It reads to me that for some reason the coordinate sort of the Gene tagged files doesn't work (~line 330 in your log). 
I don't see an error message related to that, was there any other verbose related to samtools?
I'm thinking this could be some issue when calling to samtools from within R, was this run with the zUMIs conda environment?
Maybe it's worth it to clone zUMIs fresh from GitHub in case there was any issues with the installation / initial unpacking of zUMIs' miniconda environment.

You can always set `which_Stage: Counting` to skip over the filtering/preprocessing & mapping steps and jump straight to the problematic part.

**Comment by hsriniva11** [comment]
There are three lists in the rds object. Readcount_internal, readcount and umicount. Is there written documentation anywhere that I can look up what each list contains? Thanks

**Comment by cziegenhain** [comment]
Hi,

In the latest log you sent there is some lines on STAR getting killed. Maybe you should specify less RAM usage in the YAML file in case that is triggering this issue? There has been several users before where their server environment didn't like the peak memory usage.

Regarding the output files, the description can be found in our wiki: https://github.com/sdparekh/zUMIs/wiki/Output

**Comment by hsriniva11** [comment]
Hi, thanks for all your help. I think I fixed everything!
