### ISSUE TITLE
Error with Smart-seq2 dataset

### ISSUE THREAD

**Issue by juicejulia** [sdparekh/zUMIs#269]
Hi there, thank you for creating such a powerful and flexible tool. 
I have received a smart-seq2 datasets with reads already demultiplexed. I have followed the wiki procedure to generate concatenated reads and pseudobarcode files. However, when I execute zUMIs filtering step, I encountered the following error:
 
You provided these parameters:
 YAML file:	Smart-seq2_zUMIs.yaml
 zUMIs directory:		/home/jwang/software/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   0
 zUMIs version 2.9.6 

[1] " reads were assigned to barcodes that do not correspond to intact cells."
Error in setnames(x, value) : 
  Can't assign 0 names to a 1 column data.table
Calls: BCbin ... colnames<- -> names<- -> names<-.data.table -> setnames
Execution halted
 
My yaml file attached here. Could you help? Thank you!
[Smart-seq2_zUMIs.yaml.txt](https://github.com/sdparekh/zUMIs/files/6733788/Smart-seq2_zUMIs.yaml.txt)

**Comment by cziegenhain** [comment]
Hi,

I think this issue could arise from attempting to error correct on the barcode (` BarcodeBinning: 1`) because all reads with their pseudo barcodes all fit perfectly to the expectation!
Could you please retry with   `BarcodeBinning: 0`?

**Comment by juicejulia** [comment]
The pipeline runs with no issues after changing the Binning to 0. Thank you Christoph!

**Comment by cziegenhain** [comment]
Great, I'll make some changes to prevent this problem in the next update.
