### ISSUE TITLE
Error writing bam files after finishing mapping.

### ISSUE THREAD

**Issue by wsphillips** [sdparekh/zUMIs#270]
Apparent file write error when finishing mapping. I am working with up-to-date `main` of zUMIs and using miniconda env to run. YAML config and stdout attached. Any ideas? Happens on two different, but similarly spec'd workstations.

```Jun 29 23:11:57 ..... finished mapping
Jun 29 23:11:58 ..... finished successfully
[bam_cat] Error writing to '/home/wikphi/data/zumisout/ss3pilot.filtered.tagged.Aligned.out.bam'.
[bam_cat] Error writing to '/home/wikphi/data/zumisout/ss3pilot.filtered.tagged.Aligned.toTranscriptome.out.bam'. 
```

The above results in a subsequent segfault with subread. 

[Full stdout of run here.](https://github.com/sdparekh/zUMIs/files/6736784/error.txt)

[YAML config (as txt for upload)](https://github.com/sdparekh/zUMIs/files/6736808/ss3pilot.txt)

OS: Fedora 34 & CentOS 8.3 (reproduces on two machines)

Version: running zUMIs `main` with conda `-c` flag, but dependency versions are...

samtools 1.12
STAR 2.7.3a
R 4.05 (all packages in your CRAN/Bioconductor lists installed)
pigz 2.4

**Comment by cziegenhain** [comment]
Very odd, when this kind of basic operations in samtools fails, it's usually because users have some sort of folder permissions issue or there is not enough disk space. Rule of thumb is to have 5x the fastq input size free space.

**Comment by wsphillips** [comment]
I went back and ran the pipeline with 4TB free disk space and out of paranoia recursively ran `chmod -R a+rw /path/to/data` and `chown -R myusername /path/to/data` on the data/output folders. Maybe overkill, but seems to work fine now. :sweat_smile:
