### ISSUE TITLE
 BD Rhapsody compatability

### ISSUE THREAD

**Issue by alanaleah89** [sdparekh/zUMIs#271]
Is there a way to insert 3 separate whitelist files?  
The BD Rapsody single cell analysis system contains 3 BCs. Can zUMIs accept this type of parameter and if so should this file path be separated by a comma or a space?

**Comment by cziegenhain** [comment]
Hi,

zUMIs will paste the three bits of barcode into one unique string when extracting from your fastq reads, so in your whitelist you should give the expected combinations in a single file. You can use `expand.grid()` in R to find the unique combinations easily.

There is no option inbuilt for several whitelists.

Best,
C

**Comment by cziegenhain** [comment]
Feel free to reopen if you need further input.
