### ISSUE TITLE
converting loom files to seurat objects

### ISSUE THREAD

**Issue by kwglam** [sdparekh/zUMIs#273]
Thanks for creating and maintaining the zUMIs!!

I have successfully run my Smart-seq3 data using zUMIs. I am trying to do the downstream analysis by converting the loom files generated in the zUMIs_output folder into Seurat objects. However, when I use as.Seurat() function to convert my loom files, it came up with an error message: "Error in x$version() : attempt to apply non-function". To my understanding, you use loomR package to convert rds files to loom files. Do you know if the problem is caused by the version of loomR? I am wondering if you have ever come across similar problems in converting loom files generated by the zUMIs to Seurat objects. Many thanks!

**Comment by cziegenhain** [comment]
If you're working in R / with Seurat and the loom files are iffy, I suggest to just take the count table from zUMIs main output file (zUMIs_output/expression/*.dgecounts.rds)
https://github.com/sdparekh/zUMIs/wiki/Output#structure-of-the-output-dgecounts-object-in-project_namedgecountsrds

**Comment by kwglam** [comment]
Thanks, Christoph. I will use the rds file instead.
