### ISSUE TITLE
How to analyze the isforms of smart-seq3 data?

### ISSUE THREAD

**Issue by yiyelinfeng** [sdparekh/zUMIs#274]
Hi someone of zUMIs team,

thanks for the friendly tools for single cell transcriptome data. There I wound want to know how to  assign reconstructed RNA molecules to transcript isoforms? 

According the results of smart-seq3 of pipeline, the zUMIs_out/expression/*dgecounts.rds include the umicount and readcount_internal matrix. In my opinion, the umicount matrix is the results of the 5' UMI reads assignments and the readcount_internal matrix is only the internal reads assignments? or including the 5' UMI reads?

I know there have the  pipeline of  assign reconstructed RNA molecules to transcript isoforms(https://github.com/sandberg-lab/Smart-seq3), wound you integrate this in zUMIs smart-seq3 pipeline to output the isform matrix? It will help more projects with smart-seq3 data.

thanks!

**Comment by cziegenhain** [comment]
Hi,

Thanks for the feedback. Since zUMIs is a general pipeline and not specific for smartseq3, we will probably not integrate any isoform scripts.

Best,
Christoph
