### ISSUE TITLE
One or more of your executables were not found.

### ISSUE THREAD

**Issue by roxyisat-rex** [sdparekh/zUMIs#278]
Hi I am trying to run zUMIs with a small set of test data (2 samples). 
This is the command I used `bash zUMIs/zUMIs.sh -y SS3_human_2samples_test.yaml`
I git cloned zUMIs and are using my own dependencies. 
Below is the terminal output after I ran this line of code. 
```
(base) MacBook-Pro:nextflow_with_python user$ bash zUMIs/zUMIs.sh -y SS3_human_2samples_test.yaml
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
sed: 1: "./SS3_human_2samples_te ...": invalid command code .
Error: invalid multibyte character in parser at line 1
Execution halted
tail: -n1: No such file or directory
zUMIs/zUMIs.sh: line 174: [[: SS3_human_2samples_test.zUMIs_YAMLerror.log: syntax error: invalid arithmetic operator (error token is ".zUMIs_YAMLerror.log")

 You provided these parameters:
 YAML file:	SS3_human_2samples_test.yaml
 zUMIs directory:		
 STAR executable		STAR
STAR
 samtools executable		samtools
samtools
 pigz executable		pigz
pigz
 Rscript executable		Rscript
/usr/local/bin/Rscript
 RAM limit:   0
 zUMIs version 2.9.7 

Fri 13 Aug 2021 23:26:41 BST
One or more of your executables were not found. Please check back
```
Within the YAMLerror.log, it says : 
`Fatal error: cannot open file 'Rscript': No such file or directory`
However, I do have Rscript installed and it is an exe on my $PATH. If I `which Rscript` in terminal, I get
` /usr/local/bin/Rscript`. 
Also because I started with demultiplexed files, when I merged them back using the R script provided within zUMIs, I also used Rscript 
`Rscript zUMIs/misc/merge_demultiplexed_fastq.R --dir /path/to/individual_fastqs `
and that happened yesterday, so I am slightly confused to why this is happening. 

I also tried to use the miniconda it came with by using -c, and that gives similar terminal output and YAMLerror.log. Also says one or more of my executables were not found. 
YAMLerror.log says 
`Fatal error: cannot open file '/checkyaml.R': No such file or directory`
This is even more strange as 'checkyaml.R' is a R file with in the zUMIs directory. Perhaps there is something I am doing wrong, and I can imagine by this error this is going to be something very basic. But I have set up the YAML according to the wiki. Below is the section of my YAML that specifies the executables. 
```
STAR_exec: STAR
pigz_exec: pigz
samtools_exec: samtools
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
Rscript_exec: Rscript
zUMIs_directory: zUMIs
```
I also also tried to supply the full path for Rscript when I first received the error that says Rscript not found. But that also results in the same error message, only this time the YAMLerror.log is empty so I am unsure which exe it is that was not found. Still Rscript or one of the others.  

Sorry this is very long! If you guys could give me some advice would be great! Thank you!

**Comment by cziegenhain** [comment]
Hi,

It reads a bit like you are running this on Mac OS?
zUMIs is only tested & supported on Linux systems.

Best,
Christoph

**Comment by cziegenhain** [comment]
Closing here assuming your issue was solved.
