### ISSUE TITLE
Rplots.pdf is empty

### ISSUE THREAD

**Issue by barosmarko** [sdparekh/zUMIs#28]
Hey guys,

I'm wondering what should be in Rplots.pdf, since every single time I run it I can't open it? Also, where does it come from?

Thank you in advance!

Cheers!

**Comment by cziegenhain** [comment]
Hey Marko,

sorry for the slow reply! This is just an accidental file that gets created in the R processing (probably some dev.off() that shouldnt be there). 
So just ignore it, it should be empty.
We'll fix it in the next update.

Thanks for letting us know,

Christoph
