### ISSUE TITLE
several fastq files when running zUMIs

### ISSUE THREAD

**Issue by Eneritz** [sdparekh/zUMIs#29]
Hi,
I am running zUMIs with and for several samples I have fastq files from different lanes.
Is it possible to pass more than one fastq when running it?

-f sample1_L005_R1_001.fastq.gz sample1_L006_R1_001.fastq.gz -r sample1_L005_R2_001.fastq.gz sample1_L006_R2_001.fastq.gz

something like this?

Thanks

E

**Comment by cziegenhain** [comment]
Hey, 

no sorry, something like this is currently not implemented.
In these cases i simply concatenate the fastq files before passing them into zUMIs.

Let me know if you need further help.

Best,
Christoph

**Comment by Eneritz** [comment]
Thanks for your fast answer.

In that case, I will concatenate them before.

Best,
E
