### ISSUE TITLE
creating SJ.out.tab in zUMIs

### ISSUE THREAD

**Issue by kwglam** [sdparekh/zUMIs#292]
Hi,

I would like to create a SJ.out.tab file generated from STAR in zUMIs. Do you know how to do it? Thanks!

Gabriel

**Comment by cziegenhain** [comment]
Hi,

In the current implementation for zUMIs, there are 2 scenarios with regards to STAR:

1. If starting from the Filtering stage (ie beginning of the pipeline) and a sufficiently high memory limit (>= 2x the reference genome size), zUMIs will run several jobs of STAR in parallel and concatenate the output bam files. You will not get the SJ out file from the individual jobs. 
2. If starting the pipeline from "which_stage: Mapping" or when a small memory limit is set, a single STAR job is run and you should just find the SJ.out.tab in your zUMIs run folder.

Best,
Christoph

**Comment by kwglam** [comment]
Hi Christoph,

Thanks for replying! I ran the pipeline again with "which_stage: Mapping", it gave me this error:

EXITING because of FATAL INPUT ERROR: --readFilesType SAM requires specifying SE or PE reads
SOLUTION: specify --readFilesType SAM SE for single-end reads or --readFilesType SAM PE for paired-end reads

And then I tried to follow the suggestion by adding "--readFilesType BAM PE" or "--readFilesCommand samtools view" in the additional STAR parameter (my input is BAM file), it gave another error:

EXITING: FATAL INPUT ERROR: duplicate parameter "readFilesType" in input "Command-Line"
SOLUTION: keep only one definition of input parameters in each input source

Any insights?? 

Thanks,
Gabriel

**Comment by cziegenhain** [comment]
There should be a *.run.yaml that zUMIs adds some information to during the pipeline execution, sorry I forgot to mention that it would have been better to use that one. zUMIs always keeps the original yaml untouched and writes a copy which is named *.run.yaml

You can add a line with `read_layout: SE`  (or PE) depending on if you have single or paired cDNA reads.

**Comment by kwglam** [comment]
Thanks! It works great with the 'read_layout: SE' line.

I am working on some Smart-seq3 data and wondering if zUMIs can generate SJ.out.tab for individual cells instead? Thanks!

**Comment by cziegenhain** [comment]
I don't think that's going to be possible.
