### ISSUE TITLE
Read count table for intergenic, ambiguous, unmapped reads

### ISSUE THREAD

**Issue by pm-Genome2021** [sdparekh/zUMIs#293]
**Is your feature request related to a problem? Please describe.**
We need to compare genomic distribution of reads from a non-UMI based method with a UMI-based method. While there are count tables for exonic, intronic reads and intron-exon reads, I couldn't find counts for intergenic and even unambiguous and unmapped reads from the plot in the features pdf file. I can generate this outside of zUMIs but it would be nice to have a table generated within this pipeline. Please let me know if it is already available somewhere and I have missed it. 

**Describe the solution you'd like**
Count table containing the number of reads for each category displayed in the bar plot in features pdf file. 

**Describe alternatives you've considered**
Running QC tools outside of zUMIs on read mapping. 

**Additional context**

**Comment by cziegenhain** [comment]
These are found under zUMIs_output/stats/*.readspercell.txt.

**Comment by pm-Genome2021** [comment]
That's awesome. Thank you for your quick reply & for all your work on this pipeline!
