### ISSUE TITLE
Error in (function (cl, name, valueClass)  : 

### ISSUE THREAD

**Issue by ytang0831** [sdparekh/zUMIs#296]
Hi， I recently had a problem I couldn't solve，Judging by the results, there seems to be something wrong with matrix, but Featurecounts worked fine. At the same time I noticed that there was no output file named featurecounts.bam，really confusing. Looking forward to your answer!
------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------

 You provided these parameters:
 YAML file:	zUMIs-single_1_4.yaml
 zUMIs directory:		/share/home/fanglab/tangyin/HSET/1.rawdata/RNA/zUMIs-master
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.7.1c 

2021年 12月 03日 星期五 14:36:33 CST
Counting...
[1] "2021-12-03 14:37:35 CST"
[1] "2e+09 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/share/home/fanglab/tangyin/HSET/1.rawdata/RNA/result/Exp_HSET_Single_cell_rep1_4/HSET-single1_4.final_annot.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.32.4

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S HSET-single1_4.filtered.tagged.Aligned.out ... ||
||                                                                            ||
||              Annotation : R data.frame                                     ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 30                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||      Multimapping reads : counted                                          ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid81819 ...         ||
||    Features : 233760                                                       ||
||    Meta-features : 22813                                                   ||
||    Chromosomes/contigs : 32                                                ||
||                                                                            ||
|| Process BAM file HSET-single1_4.filtered.tagged.Aligned.out.bam...         ||
||    Single-end reads are included.                                          ||
||    Assign alignments to features...                                        ||
||    Total alignments : 4364758                                              ||
||    Successfully assigned alignments : 625181 (14.3%)                       ||
||    Running time : 0.11 minutes                                             ||
||                                                                            ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Coordinate sorting final bam file..."
[bam_sort_core] merging from 0 files and 30 in-memory blocks...
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Extracting reads from bam file(s)..."
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 4 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  : 
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>

data.table and Rsubread version：
 Rsubread_2.4.3    data.table_1.14.0

run_log here:
 You provided these parameters:
 YAML file:	zUMIs-single_1_4.yaml
 zUMIs directory:		/share/home/fanglab/tangyin/HSET/1.rawdata/RNA/zUMIs-master
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.7.1c

**Comment by ytang0831** [comment]
1400 -rw-r--r-- 1 tangyin fanglab   1432669 12月  3 10:59 HSET-single1_4.BCstats.txt
308593 -rw-r--r-- 1 tangyin fanglab 315998480 12月  3 14:39 HSET-single1_4.filtered.Aligned.GeneTagged.sorted.bam
  2064 -rw-r--r-- 1 tangyin fanglab   2112720 12月  3 14:39 HSET-single1_4.filtered.Aligned.GeneTagged.sorted.bam.bai
378849 -rw-r--r-- 1 tangyin fanglab 387941033 12月  3 11:08 HSET-single1_4.filtered.tagged.Aligned.out.bam
     2 -rw-r--r-- 1 tangyin fanglab      1851 12月  3 11:08 HSET-single1_4.filtered.tagged.Log.final.out
   570 -rw-r--r-- 1 tangyin fanglab    583466 12月  3 11:08 HSET-single1_4.filtered.tagged.Log.out
     1 -rw-r--r-- 1 tangyin fanglab       447 12月  3 11:08 HSET-single1_4.filtered.tagged.Log.progress.out
     1 -rw-r--r-- 1 tangyin fanglab       434 12月  3 11:08 HSET-single1_4.filtered.tagged.Log.std.out
   222 -rw-r--r-- 1 tangyin fanglab    226549 12月  3 11:08 HSET-single1_4.filtered.tagged.SJ.out.tab
     8 drwx------ 2 tangyin fanglab      8192 12月  3 11:01 HSET-single1_4.filtered.tagged._STARgenome
     8 drwx------ 2 tangyin fanglab      8192 12月  3 11:04 HSET-single1_4.filtered.tagged._STARpass1
     8 drwx------ 2 tangyin fanglab      8192 12月  3 11:08 HSET-single1_4.filtered.tagged._STARtmp
323668 -rw-r--r-- 1 tangyin fanglab 331435781 12月  3 11:00 HSET-single1_4.filtered.tagged.unmapped.bam
147853 -rwxr-xr-x 1 tangyin fanglab 151400465 12月  3 11:00 HSET-single1_4.final_annot.gtf
     1 -rw-r--r-- 1 tangyin fanglab       297 12月  3 14:36 HSET-single1_4.zUMIs_runlog.txt
     8 drwxr-xr-x 5 tangyin fanglab      8192 12月  3 14:39 zUMIs_output


Bam files are not empty and can be opened with smatools View

**Comment by cziegenhain** [comment]
Hi,

I don't see your YAML file so cant check if there is any obvious errors coming from that.
It seems from your output that there are only 4 barcodes to be processed? Is that expected?
The gene assignment rate seems very low too, I could imagine that there are matrix creation errors if some of these barcodes have 0 counts assigned or something like that.

Best,
Christoph
