### ISSUE TITLE
10X data in zUMIs

### ISSUE THREAD

**Issue by Eneritz** [sdparekh/zUMIs#30]
Hi again,
I am using zUMIS with 10X samples (v2). Would you recommend to run zUMIs with the filtered barcodes from the output of CellRanger or would be better to leave the -b parameter empty.

Now I am running my samples like this:

bash zUMIs-master.sh -f  10X_R1_cat.fastq.gz  -r 10X_R2_cat.fastq.gz  -n 10X_test  -g STAR_HS_GRCh38_index_noGTF -o ZUMIS_OUT  -a genes.gtf  -s 1 -c 1-16 -m 17-26 -l 58  -T 10X_I1.fastq.gz  -U 1-8 -b 

zUMIs is selecting more barcodes than cellranger. I would like to compare the results with and without cellranger barcodes. So, then I tried adding  -p barcodes.tsv  
But I got
[1] "Error! None of the barcodes has more than the requested number of reads"

What Im doing wrong?

Thanks
Eneritz

**Comment by sdparekh** [comment]
You left the `-b` parameter empty. It expects the list of barcodes without any headers. `-b barcodes.tsv` where barcodes.tsv has the list of selected cellranger barcodes separated by `\n`.

The `-p` option is for giving how many threads/processors you want to use.

**Comment by Eneritz** [comment]
# Hi thanks for the quick answer.

Sorry, I meant -b not -p

bash zUMIs-master.sh -f 10X_R1_cat.fastq.gz -r 10X_R2_cat.fastq.gz -n 10X_test -g STAR_HS_GRCh38_index_noGTF -o ZUMIS_OUT -a genes.gtf -s 1 -c 1-16 -m 17-26 -l 58 -T 10X_I1.fastq.gz -U 1-8 -b  barcodes.tsv
 
#where barcodes are

head barcodes.tsv
AAACCTGCACGTTGGC-1
AAACGGGCAGATCTGT-1
AAACGGGCATGACATC-1
AAACGGGGTCTGCGGT-1

# i also tried taking out the sample name ( -1) from the barcodes.
# And I still get the same error.

Thanks.
E

**Comment by cziegenhain** [comment]
Hey Eneritz,
in case of the plate barcode option, you will need to supply the barcode list by concatenating expected plate barcode plus cell barcode.
If you choose 8 bp plate barcode and 16 bp cell barcode, each string in the -b barcodes.tsv needs to be 24 bases.
And please remove the -1, that will not work.

Hope that helps,
Christoph

**Comment by Eneritz** [comment]
Thanks for the tips.
I was confused with the barcodes. 

Eneritz
