### ISSUE TITLE
how to use the UMI information of intron.exon

### ISSUE THREAD

**Issue by zjwang6** [sdparekh/zUMIs#300]
Hi
I have some issue, can I ues the UMI information of exon and intron? Is there some differences between using exon and using exonintron? And how I get the UMI information sum of exon and intron?
Thanks

**Comment by cziegenhain** [comment]
You can find the exon, intron or exon+intron count tables in your zUMIs output:
https://github.com/sdparekh/zUMIs/wiki/Output#structure-of-the-output-dgecounts-object-in-project_namedgecountsrds

For the general differences of when to use or not use exon or exon+intron quantification, please review the relevant literature in the field.
Note that the exon+intron quantification for UMIs is *not* equivalent to the simple sum of exonic UMIs and intronic UMIs.
