### ISSUE TITLE
How can I get mapping rate for each cell?

### ISSUE THREAD

**Issue by diyang1354** [sdparekh/zUMIs#303]
Hi,
In the running log, I can see the alignment rate in the output of Rsubread. Is this alignment rate calculated with respect to all the reads in the fastq file? How can I get the alignment rate for each individual barcode? 
Thanks.

**Comment by cziegenhain** [comment]
Hi,

You can find this information as a text file and an automatically generated plot in the zUMIs_output/stats folder.

Best,
Christoph
