### ISSUE TITLE
"43 barcodes detected"  in test data"

### ISSUE THREAD

**Issue by parichitran** [sdparekh/zUMIs#308]
**Describe the bug**
Greetings
I ran the test data set everything is fine except this lesser barcode when comparing to "78 barcodes detected" in the example data set
 I followed same parameters in yaml file as same as the example yaml

Also this variations in barcode makes lot of differences though its done same data

I am here attaching my yaml file and the log data
[yaml.txt](https://github.com/sdparekh/zUMIs/files/8335711/yaml.txt)
[logfile.txt](https://github.com/sdparekh/zUMIs/files/8335712/logfile.txt)
Additonal file:my testbarcode file(43)and inbuilt example testbarcode (78)
[testkept_barcodes.txt](https://github.com/sdparekh/zUMIs/files/8335728/testkept_barcodes.txt)
[Examplekept_barcodes.txt](https://github.com/sdparekh/zUMIs/files/8335730/Examplekept_barcodes.txt)

Thanks in advance

**Comment by cziegenhain** [comment]
Hey,

Nothing to worry about - the uploaded example data runthrough is quite old and the automatic detection may have changed since then.

From your log it looks like there was no errors, so you can proceed with analysing your own data!

best,
Christoph

**Comment by parichitran** [comment]
Hey christoph
Thanks a lot for your speedy reply.I ran 10cells of my own data too.Its a single cell rna-seq ( cel-seq data with umi(8bp**BC**-5bp**UMI)**) and its an 
[logofdata.txt](https://github.com/sdparekh/zUMIs/files/8344017/logofdata.txt)
already demultiplexed one.So i used the following code as recommended for this kind of reads in zumi

Rscript misc/merge_demultiplexed_fastq.R --dir /media/ValidationofDedup/merge --pigz /media/software/zUMIs-main/zUMIs-env/bin/pigz --threads 10

And i generated all the 5 files
Now in my yaml file if include the **index read file** I am getting the following error

"ERROR! Fastq files are not in the same order.
 Make sure to provide reads in the same order."
I even tried to sort my merged reads with fastq_pair i got the same error

Then if i wont include the index file in my yaml.i can run zumi.whether my run is correct or not.can you help me.
I am here attatching my log file and yaml file
[mydata.yaml.txt](https://github.com/sdparekh/zUMIs/files/8343758/mydata.yaml.txt)
[logofdata.txt](https://github.com/sdparekh/zUMIs/files/8344019/logofdata.txt)
