### ISSUE TITLE
error hamming binning: segfault: memory not mapped

### ISSUE THREAD

**Issue by jcschupp** [sdparekh/zUMIs#31]
Hi!
We got a similar issue as the open one. However, we only have the following error/problem whenever we include the hamming binning based on barcodes or UMIs. 

We used the most recent zUMIs version (.004) and cloned it from github.
What could be the problem here? Do you need more information?

Thanks so much in advance!
Jonas

This is the BAM log:
[bam_sort_core] merging from 16 files and 8 in-memory blocks...
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
Loading required package: optparse
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Selecting by nreads

 *** caught segfault ***
address 0x2b2978592a58, cause 'memory not mapped'

Traceback:
 1: vapply(b, do_dist, USE.NAMES = FALSE, FUN.VALUE = numeric(length(a)),     a, method, weight, maxDist, q, p, bt, useBytes, nthread)
 2: stringdist::stringdistmatrix(bc$V1, unique(reads$XC), method = "hamming",     useNames = "strings", nthread = ncores)
 3: makeGEprofile(bams, ubamfile, barcodes, saf, ncores, stra, bcstart,     bcend, umistart, umiend, subsampling, ftype[2], sn, out,     nReadsBC)
An irrecoverable exception occurred. R is aborting now ...
/gpfs/loomis/home.grace/fas/software/zUMIs_v004/zUMIs/zUMIs-noslurm.sh: line 68:  7931 Segmentation fault      (core dumped) $Rexc $zumisdir/zUMIs-dge.R --gtf $gtf --abam $o/$sn.aligned.sorted.bam --ubam $o/$sn.barcodelist.filtered.sort.sam --barcodenumber $bn --out $o --sn $sn --cores $t --strandedness $stra --bcstart $xcst --bcend $xcend --umistart $xmst --umiend $xmend --subsamp $subs --nReadsBC $nreads --hamming $ham --XCbin $XCbin
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/8CO/zUMIs_output/expression/8CO.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

this is the zUMI_run.txt:
 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/8CO/merged_r1/8CO_R1_merged.fastq.gz
 cDNA read:			/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/8CO/merged_r2/8CO_R2_merged.fastq.gz
 Study/sample name:		8CO
 Output directory:		/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/8CO
 Cell/sample barcode range:	1-16
 UMI barcode range:		17-26
 Retain cell with >=N reads:	5000
 Genome directory:		/gpfs/loomis/project/fas/kaminski/public/Backup/genome_indices/GRCh38/release91/STAR_Index
 GTF annotation file:		/gpfs/loomis/project/fas/kaminski/public/Backup/genome_indices/GRCh38/release91/gtf/Homo_sapiens.GRCh38.91.gtf
 Number of processors:		8
 Read length:			98
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Hamming Distance (UMI):	1
 Hamming Distance (CellBC):	1
 Plate Barcode Read:    NA
 Plate Barcode range:   NA
 Barcodes:			8000
 zUMIs directory:		/gpfs/loomis/home.grace/fas/software/zUMIs_v004/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:	
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 

 zUMIs version 0.0.4 

and ls -lh of the output dir:
-rwxr-s--- 1 15G Mar 23 00:48 8CO.aligned.sorted.bam
-rwxr-s--- 1 9.5G Mar 23 01:15 8CO.aligned.sorted.bam.ex.featureCounts
-rwxr-s--- 1 9.6G Mar 23 01:07 8CO.aligned.sorted.bam.in.featureCounts
-rwxr-s--- 1 18G Mar 23 00:56 8CO.barcodelist.filtered.sort.sam
-rwxr-s--- 1 1.9K Mar 23 00:36 8CO.Log.final.out
-rwxr-s--- 1 32K Mar 23 00:36 8CO.Log.out
-rwxr-s--- 1 4.6K Mar 23 00:36 8CO.Log.progress.out
-rwxr-s--- 1 3.2M Mar 23 00:36 8CO.SJ.out.tab
drwsr-s--- 2 4.0K Mar 22 23:55 8CO._STARgenome
drwsr-s--- 2 4.0K Mar 23 00:12 8CO._STARpass1
-rwxr-s--- 1 60G Mar 23 01:24 core.7931
drwsr-s--- 2 4.0K Mar 22 21:41 merged_r1
drwsr-s--- 2 4.0K Mar 22 21:41 merged_r2
drwsr-s--- 5 4.0K Mar 22 21:55 zUMIs_output

**Comment by cziegenhain** [comment]
Hey,

I am investigating this issue but have no definite solution yet. 

When binning cell barcodes, I have experienced our server really running out of memory, especially for long cell barcode strings. As a 16 bp cell barcode has a coding capacity of over 4 billion combinations, it's quite computationally costly to calculate many pairwise hamming distances.
We will need to recode this functionality.

The UMI binning using Hamming should run through without problems though, because the hamming distances are calculated per gene-cell combination. Thus there should not be crazy numbers of pairwise distances to be generate. Furthermore, we prevent the hamming distance binning of >100,000 UMIs per gene/cell.

That you still get this error could point to a problem with one of the underlying packages that we use in zUMIs.
Could you give me a bit more info on the server you are using?

Sorry for the inconvenience.

**Comment by jcschupp** [comment]
Hi!
So, I'm getting the same error, for -B 1 -H 0, as well as for -B 0 -H 1.
I also tried to grab more memory (200GB), that didn't help either. 
Below is the log for -B 0 -H 1.
Thanks so much in advance!

Btw, I just read that you uploaded a new zUMIs version (005), I will re-run it with the new version.


[bam_sort_core] merging from 16 files and 8 in-memory blocks...
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
Loading required package: optparse
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Selecting by nreads
Initialising 8 core cluster.
/gpfs/loomis/home.grace/fas/software/zUMIs_v004/zUMIs/zUMIs-noslurm.sh: line 68: 12457 Segmentation fault      (core dumped) $Rexc $zumisdir/zUMIs-dge.R --gtf $gtf --abam $o/$sn.aligned.sorted.bam --ubam $o/$sn.barcodelist.filtered.sort.sam --barcodenumber $bn --out $o --sn $sn --cores $t --strandedness $stra --bcstart $xcst --bcend $xcend --umistart $xmst --umiend $xmend --subsamp $subs --nReadsBC $nreads --hamming $ham --XCbin $XCbin
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/034C/zUMIs_output/expression/034C.dgecounts.rds', probable reason 'No such file or directory'
Execution halted



Your jobs will run on this machine. 


Make sure you have more than 28G RAM and 8 processors available. 


Your jobs will be started from filtering. 




 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/034C/merged_r1/034C_R1_merged.fastq.gz
 cDNA read:			/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/034C/merged_r2/034C_R2_merged.fastq.gz
 Study/sample name:		034C
 Output directory:		/gpfs/loomis/scratch60/fas/zUMIs_lung_soup/sample_out/034C
 Cell/sample barcode range:	1-16
 UMI barcode range:		17-26
 Retain cell with >=N reads:	5000
 Genome directory:		/gpfs/loomis/project/fas/public/Backup/genome_indices/GRCh38/release91/STAR_Index
 GTF annotation file:		/gpfs/loomis/project/fas/public/Backup/genome_indices/GRCh38/release91/gtf/Homo_sapiens.GRCh38.91.gtf
 Number of processors:		8
 Read length:			98
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Hamming Distance (UMI):	1
 Hamming Distance (CellBC):	0
 Plate Barcode Read:    NA
 Plate Barcode range:   NA
 Barcodes:			8000
 zUMIs directory:		/gpfs/loomis/home.grace/fas/software/zUMIs_v004/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:	
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 


 zUMIs version 0.0.4 


Raw reads: 195333126 
Filtered reads: 155326581 

Mar 29 15:14:45 ..... started STAR run
Mar 29 15:14:45 ..... loading genome
Mar 29 15:15:06 ..... processing annotations GTF
Mar 29 15:15:21 ..... inserting junctions into the genome indices
Mar 29 15:16:46 ..... started 1st pass mapping
Mar 29 15:44:12 ..... finished 1st pass mapping
Mar 29 15:44:13 ..... inserting junctions into the genome indices
Mar 29 15:45:53 ..... started mapping
Mar 29 16:11:28 ..... finished successfully
[1] "I am loading useful packages..."
[1] "2018-03-29 16:30:27 EDT"
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-03-29 16:30:50 EDT"
[1] "I am making count tables...This will take a while!!"
[1] "2018-03-29 16:32:23 EDT"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /gpfs/loomis/scratch60/fas/kaminski/jcs275 ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid12457 ...       ||
||    Features : 275949                                                       ||
||    Meta-features : 28257                                                   ||
||    Chromosomes/contigs : 36                                                ||
||                                                                            ||
|| Process BAM file /gpfs/loomis/scratch60/fas/zUMIs_lung ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 155326581                                                 ||
||    Successfully assigned reads : 47680700 (30.7%)                          ||
||    Running time : 6.45 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//


        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /gpfs/loomis/scratch60/fas/... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid12457 ...       ||
||    Features : 1199851                                                      ||
||    Meta-features : 49614                                                   ||
||    Chromosomes/contigs : 47                                                ||
||                                                                            ||
|| Process BAM file /gpfs/loomis/scratch60/fas/zUMIs_lung ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 155326581                                                 ||
||    Successfully assigned reads : 81404947 (52.4%)                          ||
||    Running time : 6.61 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//


Read 0.0% of 155326581 rows
Read 10.6% of 155326581 rows
Read 21.3% of 155326581 rows
Read 31.9% of 155326581 rows
Read 42.6% of 155326581 rows
Read 53.2% of 155326581 rows
Read 63.9% of 155326581 rows
Read 74.5% of 155326581 rows
Read 85.2% of 155326581 rows
Read 95.7% of 155326581 rows
Read 155326581 rows and 1 (of 1) columns from 1.420 GB file in 00:00:13

Read 0.0% of 155326581 rows
Read 2.2% of 155326581 rows
Read 4.1% of 155326581 rows
Read 4.3% of 155326581 rows
Read 6.0% of 155326581 rows
Read 6.6% of 155326581 rows
Read 7.4% of 155326581 rows
Read 9.2% of 155326581 rows
Read 9.9% of 155326581 rows
Read 11.8% of 155326581 rows
Read 13.5% of 155326581 rows
Read 15.1% of 155326581 rows
Read 16.9% of 155326581 rows
Read 18.6% of 155326581 rows
Read 20.3% of 155326581 rows
Read 21.9% of 155326581 rows
Read 22.6% of 155326581 rows
Read 23.0% of 155326581 rows
Read 25.1% of 155326581 rows
Read 27.1% of 155326581 rows
Read 29.1% of 155326581 rows
Read 31.0% of 155326581 rows
Read 32.9% of 155326581 rows
Read 34.8% of 155326581 rows
Read 35.0% of 155326581 rows
Read 36.8% of 155326581 rows
Read 38.7% of 155326581 rows
Read 40.6% of 155326581 rows
Read 42.4% of 155326581 rows
Read 44.2% of 155326581 rows
Read 46.0% of 155326581 rows
Read 47.8% of 155326581 rows
Read 49.6% of 155326581 rows
Read 51.3% of 155326581 rows
Read 53.1% of 155326581 rows
Read 54.3% of 155326581 rows
Read 56.0% of 155326581 rows
Read 57.7% of 155326581 rows
Read 59.4% of 155326581 rows
Read 61.1% of 155326581 rows
Read 62.7% of 155326581 rows
Read 64.4% of 155326581 rows
Read 66.0% of 155326581 rows
Read 67.6% of 155326581 rows
Read 69.2% of 155326581 rows
Read 70.8% of 155326581 rows
Read 72.4% of 155326581 rows
Read 74.0% of 155326581 rows
Read 75.6% of 155326581 rows
Read 77.2% of 155326581 rows
Read 78.8% of 155326581 rows
Read 80.4% of 155326581 rows
Read 82.0% of 155326581 rows
Read 83.5% of 155326581 rows
Read 85.0% of 155326581 rows
Read 86.6% of 155326581 rows
Read 88.1% of 155326581 rows
Read 88.8% of 155326581 rows
Read 90.8% of 155326581 rows
Read 92.8% of 155326581 rows
Read 94.7% of 155326581 rows
Read 96.8% of 155326581 rows
Read 98.8% of 155326581 rows
Read 155326581 rows and 1 (of 1) columns from 3.906 GB file in 00:02:29
[1] "I am loading useful packages for plotting..."
[1] "2018-03-29 17:16:15 EDT"

**Comment by cziegenhain** [comment]
Hey,

Thanks for the updated log. 
Let's hope the improved version will help with your issue.

Best,
Christoph

**Comment by jcschupp** [comment]
Since v005, I got new errors (not the segfault one):



[bam_sort_core] merging from 16 files and 8 in-memory blocks...
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
Loading required package: optparse
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Selecting by nreads
Error in if (length(XC_obs) * length(bc$V1) > 1e+10) { : 
  missing value where TRUE/FALSE needed
Calls: makeGEprofile
In addition: Warning message:
In length(XC_obs) * length(bc$V1) : NAs produced by integer overflow
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs/loomis/scratch60/fas//zUMIs_lung_soup/sample_out/92C/zUMIs_output/expression/92C.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by cziegenhain** [comment]
Hey,

sorry for that. Was not aware that in R, integers (as returned by `as.numeric()`) are more limited than numeric data.
I just pushed a fix for that. please try again.

Best,
Christoph

**Comment by jcschupp** [comment]
I now have a new error, but i think at a similar position:

[bam_sort_core] merging from 16 files and 8 in-memory blocks...
[bam_sort_core] merging from 8 files and 8 in-memory blocks...
Loading required package: optparse
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
Selecting by nreads
/gpfs/loomis/home.grace/fas/kaminski/jcs275/software/zUMIs_v005/zUMIs/zUMIs-noslurm.sh: line 91: 11205 Killed                  $Rexc $zumisdir/zUMIs-dge.R --gtf $gtf --abam $o/$sn.aligned.sorted.bam --ubam $o/$sn.barcodelist.filtered.sort.sam --barcodenumber $bn --out $o --sn $sn --cores $t --strandedness $stra --bcstart $xcst --bcend $xcend --umistart $xmst --umiend $xmend --subsamp $subs --nReadsBC $nreads --hamming $ham --XCbin $XCbin
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/gpfs/loomis/scratch60/fas/kaminski/jcs275/zUMIs_lung_soup/sample_out/Farida_1/zUMIs_output/expression/Farida_1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
slurmstepd: error: Detected 1 oom-kill event(s) in step 11843109.batch cgroup.

**Comment by cziegenhain** [comment]
Definitely try to increase the RAM.
Hamming distance operations may need significantly more than runs with our default settings.

**Comment by sdparekh** [comment]
Hi, it seems your problem is resolved so I am closing this issue. Please feel free to open it if you need.
Best,
Swati
