### ISSUE TITLE
zUMI counts multi-mappers, is there an option to only allow uniquely mapped reads counted?

### ISSUE THREAD

**Issue by MengjunWu** [sdparekh/zUMIs#319]
Hi, 
I noticed during counting by featureCount, zUMI allows multi-mapper and without fractional counting. I was wondering if there is an option which allows the user to flexibly choose count multi-mapper or uniquely mapped reads? 

Thanks a lot! 

Best,
Mengjun

**Comment by cziegenhain** [comment]
Hi Mengjun,

You can choose to count multimappers or only count uniquely mapped reads via the `primaryHit` option.
https://github.com/sdparekh/zUMIs/blob/main/zUMIs.yaml#L79

Best,
Christoph

**Comment by MengjunWu** [comment]
Hi Christoph,

thanks for quick response! If I understood correctly, the primiaryHit still include multi-mapper but only count once (the primary hit), which means in featureCount the "primaryOnly" option was set to be TRUE? But this will still include multi-mappers. What I was wondering is if one could set the "countMultiMappingReads"  option to be FALSE in featureCount function, so one will only count reads that mapped only once in the genome

Many thanks,
Mengjun

**Comment by cziegenhain** [comment]
Hi Mengjun,

Yes, if you set `primaryHit: no` in zUMIs, you will only get counts from uniquely mapped reads.

**Comment by MengjunWu** [comment]
Great, thanks a lot!
