### ISSUE TITLE
Split-Seq Help

### ISSUE THREAD

**Issue by dylanmr** [sdparekh/zUMIs#32]
Hi! Thanks for this great tool. 

Do you have any suggestions on the inputs to zUMI for split-seq data? The barcodes we have for each cell is 18 bp long, but is separated every 6 basepairs by a gap of about 20 nucleotides. Thus I am unsure how to input a base range into the command. Any help would be greatly appreciated!

Dylan

**Comment by dylanmr** [comment]
Hi Christoph, 

Sorry for the delay! Just ran the pre-processing script and it seems to have worked great. Going to be proceeding with the rest of the pipeline now and will let you know how everything looks! 

Dylan

**Comment by dylanmr** [comment]
Hi Christoph, 

When I run the full script, zUMIs seems to be generating empty bam files. I am not exactly sure how or where the information is lost, but it does seem to take a very long time to go through and unzip and filter my fastq files. Below is the output from the pipeline I have received. Any advice would be greatly appreciated.

Dylan

Command: #!/usr/bin/env bash

module load star/2.5.4b
module load samtools/1.6

p=/projects/dylan/tmp-splitseq/zUMIs
$p/zUMIs-master.sh -f /projects/dylan/tmp-splitseq/fastq_final/read2.barcoderead.preprocess.fastq.gz -r /projects/dylan/tmp-splitseq/fastq_final/read1.fastq.gz -i $p -m 1-10 -c 11-35 -l 66 -g /projects/dylan/star/genome/ -a /projects/dylan/star/Mus_musculus.GRCm38.91.gtf -n split_test.v2 -p 20 -o /projects/dylan/tmp-splitseq/split_test-v2 -P $p/pigz

Output:

 You provided these parameters:
 SLURM workload manager:        no
 Summary Stats to produce:      yes
 Start the pipeline from:       filtering
 A custom mapped BAM:           NA
 Custom filtered FASTQ:         no
 Barcode read:                  /projects/dylan/tmp-splitseq/fastq_final/read2.barcoderead.preprocess.fastq.gz
 cDNA read:                     /projects/dylan/tmp-splitseq/fastq_final/read1.fastq.gz
 Study/sample name:             split_test.v2
 Output directory:              /projects/dylan/tmp-splitseq/split_test-v2
 Cell/sample barcode range:     11-35
 UMI barcode range:             1-10
 Retain cell with >=N reads:    100
 Genome directory:              /projects/dylan/star/genome/
 GTF annotation file:           /projects/dylan/star/Mus_musculus.GRCm38.91.gtf
 Number of processors:          20
 Read length:                   66
 Strandedness:                  0
 Cell barcode Phred:            20
 UMI barcode Phred:             20
 # bases below phred in CellBC: 1
 # bases below phred in UMI:    1
 Hamming Distance (UMI):        0
 Hamming Distance (CellBC):     0
 Plate Barcode Read:    NA
 Plate Barcode range:   NA
 Barcodes:                      NA
 zUMIs directory:               /projects/dylan/tmp-splitseq/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                /projects/dylan/tmp-splitseq/zUMIs/pigz
 Rscript executable             Rscript
 Additional STAR parameters:
 STRT-seq data:                 no
 InDrops data:                  no
 Library read for InDrops:      NA
 Barcode read2(STRT-seq):       NA
 Barcode read2 range(STRT-seq): 0-0
 Bases(G) to trim(STRT-seq):    3
 Subsampling reads:             0


 zUMIs version 0.0.5

Raw reads: 356864070
Filtered reads: 0

Apr 14 15:36:56 ..... started STAR run
Apr 14 15:36:56 ..... loading genome
Apr 14 15:39:07 ..... processing annotations GTF
Apr 14 15:39:31 ..... inserting junctions into the genome indices
Apr 14 15:42:40 ..... started 1st pass mapping
Apr 14 15:42:41 ..... finished 1st pass mapping
Apr 14 15:42:42 ..... inserting junctions into the genome indices
Apr 14 15:45:15 ..... started mapping
Apr 14 15:45:30 ..... finished successfully
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-04-14 15:45:33 CEST"
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-04-14 15:46:06 CEST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-04-14 15:47:51 CEST"

        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /projects/dylan/tmp-splitseq/split_test-v2 ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid6691 ...        ||
||    Features : 237113                                                       ||
||    Meta-features : 28174                                                   ||
||    Chromosomes/contigs : 38                                                ||
||                                                                            ||
|| Process BAM file /projects/dylan/tmp-splitseq/split_test-v2/split_test ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 0                                                         ||
||    Successfully assigned reads : 0                                         ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//


        ==========     _____ _    _ ____  _____  ______          _____
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.28.1

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S /projects/dylan/tmp-splitseq/split_test-v2 ... ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 1                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : no                                               ||
||         Strand specific : no                                               ||
||      Multimapping reads : primary only                                     ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file ./.Rsubread_UserProvidedAnnotation_pid6691 ...        ||
||    Features : 795038                                                       ||
||    Meta-features : 46957                                                   ||
||    Chromosomes/contigs : 45                                                ||
||                                                                            ||
|| Process BAM file /projects/dylan/tmp-splitseq/split_test-v2/split_test ... ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 0                                                         ||
||    Successfully assigned reads : 0                                         ||
||    Running time : 0.00 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

Error in data.table::fread(paste("cut -f4 ", abamfile[2], ".featureCounts",  :
  File is empty: /dev/shm/file1a236b79faac
Calls: makeGEprofile -> <Anonymous>
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2018-04-14 15:47:59 CEST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/projects/dylan/tmp-splitseq/split_test-v2/zUMIs_output/expression/split_test.v2.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by cziegenhain** [comment]
Hey Dylan,

thanks for sending the log. since you had roughly 350 mio reads, I would expect filtering to take a moment (maybe 2 hours?).
It seems however like all the reads were discarded. That seems very unlikely, so maybe there is a problem with the quality encoding?

Let's have a look at the produced barcode fastq file, so could you please send me the output of 
`zcat read2.barcoderead.preprocess.fastq.gz | head`

Thanks for your help in improving zUMIs for this protocol!

Best,
Christoph

**Comment by dylanmr** [comment]
Hi Christoph,

Thank you for such a prompt reply! This is the output from the command you sent me. I also should have noticed that! I am currently re-running the script with the adjusted ranges and will keep you updated as to the output from that run. 

Best,
Dylan

@NS500606:120:HLVKVBGX5:2:11101:3666:1039 2:N:0:CAGATC
GCGCGGNNNNNNNGNNNNNNNNNNTNNACTTNNA
+
AAAAAE#######E##########E##EEEE##E
@NS500606:120:HLVKVBGX5:2:11101:11672:1039 2:N:0:CAGATC
CTTGGANNNNNNNTNNNNNNNNNCTNNGATGNNA
+
AAAAAE#######E#########EE##EEEE##E
@NS500606:120:HLVKVBGX5:2:11101:3151:1039 2:N:0:CAGATC
GCGTCGNNNNNNNGNNNNNNNNNNGNNACTTNNA
+
AAAAAE#######6##########/##/AEE##E
@NS500606:120:HLVKVBGX5:2:11101:15349:1039 2:N:0:CAGATC
AGCTGANNNNNNNGNNNNNNNNNGCNNTGTCNNT

**Comment by cziegenhain** [comment]
Hey Dylan,

no worries, happy to help!
So the reads and quality encoding seem correct but there are also quite some Ns in your reads. that may just be the first couple of reads, but could you also run FastQC for your read2 and/or the preprocessed read2 file just to be sure what to expect in terms of reads passing the filter?

Best,
Christoph

**Comment by dylanmr** [comment]
Hi Christoph, 

I have attached PDF copies of the fastqc reports here. I think they look decent, but I don't have a lot of experience reviewing these outputs for single cell data. Let me know what you think. 

Dylan


[read1.fastq.gz FastQC Report.pdf](https://github.com/sdparekh/zUMIs/files/1912351/read1.fastq.gz.FastQC.Report.pdf)
[read2.barcoderead.preprocess.fastq.gz FastQC Report.pdf](https://github.com/sdparekh/zUMIs/files/1912352/read2.barcoderead.preprocess.fastq.gz.FastQC.Report.pdf)

**Comment by cziegenhain** [comment]
Yes that looks pretty solid! 
Let me know how the run with the adjusted base ranges goes.

**Comment by dylanmr** [comment]
Hi Christoph, 

The output from the run now looks quite good. Unfortunately, we seem to have quite a low mapping rate, ~40%, so I may go back and do some read trimming on read1. I have attached here the output files from the run. If you have any suggestions on how best to optimize this output it would be greatly appreciated! 

Dylan
[split_test_hum.detected_cells.pdf](https://github.com/sdparekh/zUMIs/files/1914246/split_test_hum.detected_cells.pdf)
[split_test_hum.downsampling_thresholds.pdf](https://github.com/sdparekh/zUMIs/files/1914247/split_test_hum.downsampling_thresholds.pdf)
[split_test_hum.features.pdf](https://github.com/sdparekh/zUMIs/files/1914248/split_test_hum.features.pdf)
[split_test_hum.geneUMIcounts.pdf](https://github.com/sdparekh/zUMIs/files/1914249/split_test_hum.geneUMIcounts.pdf)
[split_test_hum.readspercell.pdf](https://github.com/sdparekh/zUMIs/files/1914250/split_test_hum.readspercell.pdf)

**Comment by cziegenhain** [comment]
Hey,

Great that zUMIs is running. I'm gonna close the issue for this, but feel free to send me more questions on the output.

So it does look fairly low mapping. You can also trim reads using STAR within a zUMIs run if you think thats more convenient.
You can pass custom commands to STAR within zUMIs using the `-x ` key. 
For example: `-x "--clip3pAdapterSeq NNNNNNNN"`

It also looks to me like your data is dominated by a couple of barcodes that take up most reads.
Double check that you have selected the right variable bases in the preprocessing step!!
If all is correct, this might indicate a problem with ligating the barcode adapters during the library preparation.

Good luck,
Christoph

**Comment by aemoor** [comment]
Hi,

Sorry for hijacking this thread. @dylanmr I'm also testing Split-Seq and will analyze the Data with Split-Seq (thanks for the preprocessing tools). In test experiments I also rather low exonic mapping rate, were you able to resolve this issue computationally or is it a wet-lab issue?

Thanks

Andreas

**Comment by dylanmr** [comment]
Hi @aemoor,

I haven't had a chance to work through this issue yet. However, I will be sitting down with those who did all the wet lab work to see if there was an issue on that end. 

For now on the computational side, I am planning to check on the barcode processing step. However I can keep you updated on how things look on our end. 

Did you have any ideas on how to go about resolving this computationally?

Dylan

**Comment by cziegenhain** [comment]
In my opinion STAR is pretty robust in this regard. Usually, adapter reads will be soft-clipped and should be taken care of.
So my guess would also be more a problem in library preparation, although I have no experience with Split-seq myself.

**Comment by dylanmr** [comment]
Hi @cziegenhain,

I took a look into the outputs from zUMIs and it looks like there is one cell which receives a disproportionate number of reads, ~ 15000 UMI detected. When I looked further into it the cell barcode is actually just all G's, indicating this is definitely not a cell.  

When I go back into the raw fastq files and grep for the expected 30 bp filler sequence between each barcode, there does not appear to be any sequence of G's which falls between them. I am wondering, should we consider maybe adding the expected filler sequences to the pre-processing step and only keeping BC's which are found between the known filler sequences which are in the correct locations? e.g 19-48 and 57-86? 

Dylan

**Comment by cziegenhain** [comment]
Hey Dylan,

Sure, I will note this for future implementation. I could imagine having a fuzzy string matching in the fqfilter.
The downside will be a slowdown in runtime, but let's see.

In the meantime: It should be relatively fast to make a list of all possible BC combinations and subset the output matrices from zUMIs for only those.

The all G sequences were already listed as overrepresented in the fastQC report you had sent previously. As to why you get these all G reads, I am not entirely sure. Could be an artifact of the template switching? But best to ask the Split-seq authors for more support on that side!

Best,
Christoph
