### ISSUE TITLE
R library cannot detect

### ISSUE THREAD

**Issue by lingnanyuan** [sdparekh/zUMIs#321]
I'm trying to work with zUMIs with some yaml file. I have the R 4.1.1 installed and all the packages installed as well. But when I try to run zUMIs.sh, it reports:

```
Error in withCallingHandlers(expr, message = function(c) if (inherits(c,  : 
  Library 'yaml' is needed by R; please install it
Calls: suppressMessages -> withCallingHandlers
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘yaml’
Execution halted
```

![Screenshot from 2022-06-14 23-30-37](https://user-images.githubusercontent.com/25348985/173737175-eccda332-2d23-4efb-bfcc-06c696f8f6db.png)

**To Reproduce**
yaml file attached:
[Spike.txt](https://github.com/sdparekh/zUMIs/files/8905655/Spike.txt)

**Desktop (please complete the following information):**
Ubuntu 20.04.4 LTS

Thank you in advance!
Lingnan

**Comment by cziegenhain** [comment]
Hi,

Seems like you are running as sudo? what is the reason for that? I could imagine that this can lead to some libPath issues.
Furthermore, I can see it seems like you are running this on a laptop? The RAM limit you set will not be followed by zUMIs - especially since loading the human genome for mapping using STAR needs at least approx. 25 GB RAM

**Comment by lingnanyuan** [comment]
If I don't run sudo, it will say 
```
YAML file has an error. Look at the zUMIs_YAMLerror.log or contact developers.
```
The log attached:
[Spike.zUMIs_YAMLerror.log](https://github.com/sdparekh/zUMIs/files/8908012/Spike.zUMIs_YAMLerror.log)
Basically cannot detect the fastq files.

And the yaml file:
[Spike.txt](https://github.com/sdparekh/zUMIs/files/8908016/Spike.txt)

I'm testing on one chromosome so I think it would not take that many RAM.

**Comment by cziegenhain** [comment]
Hi Lingnan,

The error log says the path to the barcode file is not found. Please double check that.
Depending on the number of reads, mapping against only one chromosome can be quite slow because STAR will have trouble finding alignments. 

Best,
Christoph

**Comment by lingnanyuan** [comment]
Hi Christoph,

Thanks again for your patience. There might be something wrong with my environment, if I run with sudo, it cannot find the r packages, if I run without sudo, it cannot detect the fastq files. Maybe I'll try with other device latter.
