### ISSUE TITLE
FeatureCount output

### ISSUE THREAD

**Issue by Shinichiro03** [sdparekh/zUMIs#322]
I run example data.
In my output directory, I can *.filtered.Aligned.GeneTagged.sorted.bam, but without any featureCounts.bam such as *.aligned.sorted.bam.featureCounts *.ex.featureCounts and *.in.featureCounts. 
I saw those files in /.temp directory, and can not see any error in the terminal. 

Could you please tell me how to solve this issue? 
Really appreciate any of your suggestions and help.
Best,
Shin

**Comment by cziegenhain** [comment]
Hi Shin,

That is expected, the final GeneTagged bam file contains both the exon and intron gene information derived from featureCounts:

https://github.com/sdparekh/zUMIs/wiki/Output#explanation-of-the-bam-tags-zumis-uses

Best,
Christoph

**Comment by Shinichiro03** [comment]
Hi Christoph,

Thank you for your reply.
Should I use *.filtered.Aligned.GeneTagged.sorted.bam for running ss3iso?
This is because ss3iso option part mention that  "Use '*filtered.tagged.Aligned.out.bam.ex.featureCounts.UBfix.sort.bam' generated by zUMIs. Every read should have a UB:Z tag.”

Best,
Shin

**Comment by cziegenhain** [comment]
Hi Shin,

yes this is the appropriate bam file. 
since it seems this is smartseq3 data, I do strongly recommend to use the UMI error correction in zUMIs. 
In case of issues or doubt with other scripts like ss3iso please refer to those GitHub repositories. 

Best
Christoph

**Comment by Shinichiro03** [comment]
Hi Christoph,

Thank you very much for your help!

Best,
Shin

**Comment by Shinichiro03** [comment]
Hi Christoph,

Thank you for your reply.
Should I use *.filtered.Aligned.GeneTagged.sorted.bam for running ss3iso?
This is because ss3iso option part mention that  "Use '*filtered.tagged.Aligned.out.bam.ex.featureCounts.UBfix.sort.bam' generated by zUMIs. Every read should have a UB:Z tag.”

Best,
Shin

**Comment by cziegenhain** [comment]
Sounds correct, yes!
