### ISSUE TITLE
Rerun from mapping step using filtered.tagged.unmapped.bam?

### ISSUE THREAD

**Issue by Anacristina0914** [sdparekh/zUMIs#324]
Hello,

I am a new zUMIs user, trying to analyze scRNA-seq data from Smart-Seq3. Due to an OUT_OF_MEMORY error in the HPC cluster I am using my run failed after the filtering step. Though this error has been sorted out, I would  (if possible) like to re-run the pipeline from the step where it was left out. I noticed the YAML file contains a section to indicate zUMIs which step to start from, but I couldn't find any field to indicate  which filtered.tagged.unmapped.bam file to use when starting from the mappign step, which makes me think that zUMIs will simply not carry out the filtering and jump to the mapping step instead. Is it possible to use the output from the previous step, or would I need to rerun everything from the beginning? Thank you in advance for your answer. 

Best,

Ana C.

**Comment by cziegenhain** [comment]
Hey,

You can set which_stage: Mapping to skip the Filtering step and resume from the mapping.
The file name of the unmapped bam will be automatically inferred by zUMIs based on the project name & output folder set in the yaml file.

Best,
C

**Comment by Anacristina0914** [comment]
Hello,

Thank you for your super fast response! Great, I just wanted to make sure the content of the output folder wouldn't be deleted if I set it to the same one as my previous run. 

One more question: since the mapping step had already started at the moment the run crashed I have a lot of temp files with the format 'filtered.Aligned.GeneTagged.sorted.bam.tmp.00XX.bam'. Since zUMIs appends content into these files, is it advisable to delete them before rerunning, or would new files be created by default?

Best,

Ana C.

**Comment by cziegenhain** [comment]
No problem. It should overview any existing tmp files like this, but you can also delete them before to be sure - it should not really matter.

**Comment by Anacristina0914** [comment]
Perfect! thank you very much!
