### ISSUE TITLE
expected_barcodes file with dual indices

### ISSUE THREAD

**Issue by carmensandoval** [sdparekh/zUMIs#329]
How should one format the list of expected barcodes when using dual indices?

I am using zUMIs to process libraries generated with Takara mRNA LP with UMIs kit, and each library has a unique dual index.

Should my file be:

```
barcode_1_i5   barcode_1_i7
barcode_2_i5   barcode_2_i7
barcode_3_i5   barcode_3_i7
.
.
.
```

Thanks!

**Comment by cziegenhain** [comment]
Hi Carmen,

Your file should contain the concatenated barcode string of every expected combination:
https://github.com/sdparekh/zUMIs/wiki/Barcodes#number-of-barcodes-with-most-reads

Best,
Christoph

**Comment by carmensandoval** [comment]
Thanks!
