### ISSUE TITLE
wrong version check

### ISSUE THREAD

**Issue by brainfo** [sdparekh/zUMIs#331]
**Describe the bug**
I used STAR in the same environment to index genome and to map, the version is 2.7.10a, but when I runned the zUMIs (version 2.9.7), it says: 
`WARNING: The STAR version used for mapping is 2.7.10a and the STAR index was created using the version 2.7.4a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.10a.`

**Actually STAR index was created using the version 2.7.10a**
STAR genomeGenerate:

```
        STAR --runMode genomeGenerate --runThreadN 16 --genomeDir STARIndex --genomeFastaFiles WholeGenomeFasta/GRCm39.primary_assembly.genome.fa
        STAR version: 2.7.10a   compiled: 2022-01-14T18:50:00-05:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Sep 20 18:30:16 ..... started STAR run
Sep 20 18:30:16 ... starting to generate Genome files
Sep 20 18:30:49 ... starting to sort Suffix Array. This may take a long time...
Sep 20 18:31:00 ... sorting Suffix Array chunks and saving them to disk...
Sep 20 18:37:47 ... loading chunks from disk, packing SA...
Sep 20 18:38:29 ... finished generating suffix array
Sep 20 18:38:29 ... generating Suffix Array index
Sep 20 18:41:27 ... completed Suffix Array index
Sep 20 18:41:27 ... writing Genome to disk ...
Sep 20 18:41:28 ... writing Suffix Array to disk ...
Sep 20 18:41:46 ... writing SAindex to disk
Sep 20 18:41:50 ..... finished successfully
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04.4 LTS

**Additional context**
I also have other errors with this job but I wanna make sure step by step first if it's the index version
not match. I will open another issue to report that.

**Comment by cziegenhain** [comment]
Hi,

The Genome version number encoded in the STAR index is not always in sync with the real STAR version number - seems something the STAR authors only occasionally update.
Do you get a mapped bam file output? If so its ok to ignore the warning (zUMIs just warns, it is not an error per se)

**Comment by brainfo** [comment]
> Hi,
> 
> The Genome version number encoded in the STAR index is not always in sync with the real STAR version number - seems something the STAR authors only occasionally update. Do you get a mapped bam file output? If so its ok to ignore the warning (zUMIs just warns, it is not an error per se)

Yes, I got bam output and mapping report.Nice of your clarification on the version number :)
