### ISSUE TITLE
BUG: conda activate, conda-unpack, RScript not found.

### ISSUE THREAD

**Issue by carmensandoval** [sdparekh/zUMIs#332]
Hi, I just made a fresh clone of the repo and I see this error I had not encountered before:
Any ideas why this could be happening?
My previous clone did have conda-unpack and conda-activate.

```
> /path/to/bin/zUMIs/zUMIs.sh -c -y zUMIs_tiny.yaml

Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!

/path/to/bin/zUMIs/zUMIs.sh: line 161: /path/to/bin/zUMIs/zUMIs-env/bin/activate: No such file or directory
/path/to/bin/zUMIs/zUMIs.sh: line 162: conda-unpack: command not found
/path/to/bin/zUMIs/zUMIs.sh: line 171: Rscript: command not found
```

**Comment by carmensandoval** [comment]
Resolved by removing the zumis-env directory and running zUMIs.sh with -c option again.

**Comment by cziegenhain** [comment]
Hi Carmen,

Typical error that happens when the first run after cloning is interruped & the unpacking of the conda environment doesn't complete. But as you say, removing the zumis-env directory and rerunning will fix this.
