### ISSUE TITLE
samtools empty query name

### ISSUE THREAD

**Issue by brainfo** [sdparekh/zUMIs#334]
**Describe the bug**
I got errors:

```
[W::sam_parse1] empty query name
[W::sam_read1_sam] Parse error at line 10630
samtools view: error reading file "-"
[W::sam_parse1] empty query name
[W::sam_read1_sam] Parse error at line 12723
samtools view: error reading file "-"
```

and thus there's no BCstats.txt out.

**To Reproduce**
yaml:
[prime_seq.yaml.txt](https://github.com/sdparekh/zUMIs/files/9673020/prime_seq.yaml.txt)

log (which I killed the process while it's running star mapping after the samtools error):
[prime_seq_.log](https://github.com/sdparekh/zUMIs/files/9672973/prime_seq_.log)

barcode counts from bbduk:
[stats.txt](https://github.com/sdparekh/zUMIs/files/9673060/stats.txt)

fastqc of the two fastqs:
_These two fastqs were trimmed polyA/polyT (I think some r2 reads get to the polyA region), so the r2 read length may not always get to 150bp. could this be a problem with the cDNA specification in r2 as cDNA(9-150)?_
[AZ_Placenta_PS_2_EKDL220011301-1A_H5HLYDSX5_L1_cutadapt_1_fastqc.zip](https://github.com/sdparekh/zUMIs/files/9673056/AZ_Placenta_PS_2_EKDL220011301-1A_H5HLYDSX5_L1_cutadapt_1_fastqc.zip)
[AZ_Placenta_PS_2_EKDL220011301-1A_H5HLYDSX5_L1_cutadapt_2_fastqc.zip](https://github.com/sdparekh/zUMIs/files/9673057/AZ_Placenta_PS_2_EKDL220011301-1A_H5HLYDSX5_L1_cutadapt_2_fastqc.zip)

**Desktop (please complete the following information):**
OS: Ubuntu
Version: 20.04.4 LTS
zUMIs: version 2.9.7
samtools version: 1.15.1

**Additional context:**
Because I can't figure this out, I tested demultiplex these files using flexbar and umi_tools to dedup and then map and get 90% mapping rate and 41% assigned to exons. But still, I need zUMIs to go (especially with introns assignment).

Best,

**Comment by cziegenhain** [comment]
the problem is that there are empty reads that were completely trimmed out (0bp).
