### ISSUE TITLE
zUMIs-env no longer in download from GitHub

### ISSUE THREAD

**Issue by katharinebca** [sdparekh/zUMIs#335]
We started working with zUMIs a couple of weeks ago.  Several people downloaded the miniconda version from github---started using it with no problem.  We start with demultiplexed fastq files so we needed the zUMIs-env directory to change environments to merge our fastq files.

All working great--thank you for a great tool.

However, today several lab members tried to set it up and the download no longer automatically generates the zUMIs-env directory?  Did something change?

We are puzzled.

Thanks,
*

**Comment by cziegenhain** [comment]
Hi,

Thanks for downloading zUMIs! 
The zUMIs-env is packed up for saving space on GitHub, and unpacks during the first run of zUMIs.sh.

You can also unpack yourself after cloning from GitHub:
`cat zUMIs-miniconda.parta* > zUMIs-miniconda.tar.bz2`
 `tar -xj --overwrite -f zUMIs-miniconda.tar.bz2 -C zUMIs-env`

Best,
Christoph

**Comment by katharinebca** [comment]
Thanks Christoph….very helpful. 

Since we merge fastq files we were looking for the environment before running it the first time!

Kate

Katharine Abruzzi, PhD
HHMI; Brandeis University
Rosbash Lab
415 South ST.
Waltham, MA 02454

Fedex #: 1530-1071-4
***@***.***
781-736-3161

**Comment by cziegenhain** [comment]
Let me know if you need anything else!
