### ISSUE TITLE
samtools view: error closing standard output: -1

### ISSUE THREAD

**Issue by Liripo** [sdparekh/zUMIs#336]
When I run the zUMIs-mapping.R script in Rstduio, I get the error message in the figure below, but the program does run with results. I don't know what is causing the error message. 
And my samtools version is 1.10.
![image](https://user-images.githubusercontent.com/54770415/198947837-8705195a-bcce-472b-af4a-733b94ee5815.png)
![image](https://user-images.githubusercontent.com/54770415/198949880-dc20b36e-f7b5-4687-98e7-f5938cfc8235.png)

**Comment by cziegenhain** [comment]
Hi,

Running zUMIs as individual scripts in RStudio is not tested or supported.
Please run via zUMIs.sh and post the full log and your config file if you need assistance.

Best,
Christoph

**Comment by Liripo** [comment]
Hi，
Thank you for your quick reply! I am closing this issue for now.
Best
