### ISSUE TITLE
Is it possible to generate ht-seq gene count based data with cell ID?

### ISSUE THREAD

**Issue by greener98103** [sdparekh/zUMIs#34]
Hi Swati,
I am currently testing zUMIs with the Biorad/Illumina ddseq platform. I am able to generate bams and featurecount files but the output does not contain gene counts (like ht-seq) based on cell ID like what is list below. Please let me know the best way to obtain this. Thanks -Rich

GeneId	Count.1_gccgttgtggtgcaaccg	Count.1_ctgtggtcgcctaggtta	Count.1_cgaaagtagaggacaagg	Count.1_gttaacatgaagatccgg
A1CF	3	NA	NA	NA
AACS	2	19	4	NA
AADACP1	14	2	NA	NA
AADAT	5	7	NA	1
AAED1	12	22	27	5
AAGAB	18	36	9	2
AAK1	2	2	14	2
AAMP	5	1	5	10
AAR2	11	4	20	5
AARS	23	17	20	13

**Comment by sdparekh** [comment]
Hi Richard,

If zUMIs ran through, all the count tables in should be in zUMIs_output/expression. With the increasing throughput of scRNA-seq data, we generate count tables as sparse matrix saved as an rds file. You will find detailed explanation here to convert this format to a text file if you need.

https://github.com/sdparekh/zUMIs/wiki/Output

Let me know if you need any further help.

Swati
