### ISSUE TITLE
Does zUMIs remove PCR duplicates from the bam files?

### ISSUE THREAD

**Issue by pschinke** [sdparekh/zUMIs#342]
Hello,

I'm using zUMIs on my SMART-seq3 data in order to obtain bam files which don't contain PCR duplicates for further analysis steps. 
My question is just if the ouput demultiplexed bam files from zUMIs pipeline have undergone duplicate removal, this was not clear to me from reading the paper and the documentation.

Thanks in advance!

**Comment by cziegenhain** [comment]
Hi,

No duplicates are being removed from the bam file in zUMIs.

Best,
Christoph

**Comment by pschinke** [comment]
Hi Christoph,

thanks for the quick response! Can you maybe recommend a tool which works well with zUMIs and can be used for that purpose? Or is there an option in zUMIs to at least mark PCR duplicates similar to what cell ranger does?

**Comment by cziegenhain** [comment]
For quantification of gene expression, we have previously argued that duplicate removal of reads based on mapping coordinates is not recommended https://www.nature.com/articles/srep25533

Other than that, zUMIs-generated bam files should be compatible with any tool of your preference, so you could check for example duplicate marking in eg. picard-tools

Best,
Christoph

**Comment by pschinke** [comment]
Makes sense. Unfortunately, UMI-based (!) duplicate removal is a vital step for my analysis. Does zUMIs provide any information about the UMIs in the bam files, so I could plug them a tool like UMI-tools? (Sorry for the late reply, I've been on vacation).

**Comment by cziegenhain** [comment]
Oh absolutely, the UMI is present in the bam file for every read so you can use that!

Here is the legend of the utilized tags:
https://github.com/sdparekh/zUMIs/wiki/Output#explanation-of-the-bam-tags-zumis-uses

**Comment by pschinke** [comment]
Oh, I missed that somehow. Many thanks!

**Comment by cziegenhain** [comment]
No worries let me know if anything else is unclear. 11 jan. 2023 kl. 18:36 skrev Patrick Schinke ***@***.***>:﻿
Oh, I missed that somehow. Many thanks!
