### ISSUE TITLE
Pipeline QC metrics

### ISSUE THREAD

**Issue by royfrancis** [sdparekh/zUMIs#349]
The pipeline doesn't seem to generate any report so I was wondering if it is possible to get/create QC metrics for read quality (FastQC) and alignment qc. I am interested to know if reads are of good quality and how many are mapping and where in the genome as well as duplication rate etc.  If I were to manually run a post alignment qc using RseQC, qualimap, QoRTs etc, which bam file would I use?

```
sample.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam 
sample.filtered.tagged.Aligned.toTranscriptome.out.bam
sample.filtered.tagged.Aligned.out.bam
sample.filtered.tagged.unmapped.bam
```

**Comment by cziegenhain** [comment]
There is a folder with some stats and a few plots concerning where reads map. `zUMIs_output/stats`

For further QC-ing, `sample.filtered.Aligned.GeneTagged.UBcorrected.sorted.bam ` is the final file to use!

**Comment by royfrancis** [comment]
That was helpful. Thanks!
