### ISSUE TITLE
Parameters related to Multimapping genes count

### ISSUE THREAD

**Issue by zmf0621** [sdparekh/zUMIs#350]
Hello dear author, I noticed that the parameters used when gene counting with FeatureCounts are "-M" and "--primary", in the final result I got some key genes are pseudogenes, which makes me have to look back at this parameter Because I don't know whether this  setting can distinguish the parent gene from the pseudogene. Hope to get your answer, this is very important to me.

**Comment by cziegenhain** [comment]
Hi,

Sorry for the slow reply.
In principle there could be highly similar reads that are subject to multi-mapping but assigning them to a putative parent gene may not be trivial and is not implemented in zUMIs.

Best,
Christoph
