### ISSUE TITLE
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt"))

### ISSUE THREAD

**Issue by shangyf-stu** [sdparekh/zUMIs#357]
Hello! 
I encountered an error while running the code, but couldn't find the reason.

Here is my error message: 
`/zUMIs_v2.9.7d/zUMIs/zUMIs.sh: line 285:  1216 Killed                  ${Rexc} ${zumisdir}/zUMIs-BCdetection.R ${yaml}
Error in fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project, "kept_barcodes_binned.txt")) : 
  File '/dataset456/zUMIs/zUMIs_output/dataset456kept_barcodes_binned.txt' does not exist or is non-readable. getwd()=='/zUMIs'
Execution halted
Loading required package: yaml
Loading required package: Matrix
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dataset456/zUMIs/zUMIs_output/expression/dataset456.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/dataset456/zUMIs/zUMIs_output/expression/dataset456.dgecounts.rds', probable reason 'No such file or directory'
Execution halted`

**To Reproduce**
Here is my yaml file: 
`project: dataset456
sequence_files:
  file1:
    name: /dataset456/filter_fastp/dataset456_clean_1.fastq.gz
    base_definition: 
      - BC(1-12)
      - UMI(13-20)
  file2:
    name: /dataset456/filter_fastp/dataset456_clean_2.fastq.gz
    base_definition: 
      - cDNA(1-60)
reference:
  STAR_index: /zUMIs_v2.9.7d/star_index_2.7.1a_nogtf
  GTF_file: /3.2.0_star_index/Homo_sapiens.GRCh38.102.gtf
  exon_extension: no
  extension_length: 0
  scaffold_length_min: 0
  additional_files: 
  additional_STAR_params: 
out_dir: /dataset456/zUMIs
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
counting_opts:
  introns: yes
  intronProb: no
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  multi_overlap: no
  fraction_overlap: 0
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz
`
Thank you for your help!

**Comment by shangyf-stu** [comment]
The format of the yaml file is not convenient for viewing, I will send it again.

project: dataset456
sequence_files:
  file1:
    name: /dataset456/filter_fastp/dataset456_clean_1.fastq.gz
    base_definition: 
      - BC(1-12)
      - UMI(13-20)
  file2:
    name: /dataset456/filter_fastp/dataset456_clean_2.fastq.gz
    base_definition: 
      - cDNA(1-60)
reference:
  STAR_index: /zUMIs_v2.9.7d/star_index_2.7.1a_nogtf
  GTF_file: /3.2.0_star_index/Homo_sapiens.GRCh38.102.gtf
  exon_extension: no
  extension_length: 0
  scaffold_length_min: 0
  additional_files: 
  additional_STAR_params: 
out_dir: /dataset456/zUMIs
num_threads: 8
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: null
  barcode_file: null
  barcode_sharing: null
  automatic: yes
  BarcodeBinning: 1
  nReadsperCell: 100
  demultiplex: no
counting_opts:
  introns: yes
  intronProb: no
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  multi_overlap: no
  fraction_overlap: 0
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
Rscript_exec: Rscript
STAR_exec: STAR
pigz_exec: pigz

**Comment by cziegenhain** [comment]
Seems like your job got killed for external reasons during barcode correction, could it be that you ran out of memory or similar?

**Comment by shangyf-stu** [comment]
Yes, the operation of zUMIs has been stopped due to ran out of memory. I have encountered this type of problem twice, probably including the kill error, all of which are caused by this reason.
Thank you for your patient answer. Additionally, I have encountered difficulties in library that contains multiple barcodes, and I will create a new issue.
