### ISSUE TITLE
-N  <nReadsperCell>: how does this parameter work?

### ISSUE THREAD

**Issue by helene-ccfk** [sdparekh/zUMIs#36]
Hi, I am trying out different parameters on a ddSEQ/Illumina dataset and I don't understand the results I get when I set up the N parameter to 2000. My understanding was that only barcodes/cells with more than 2,000 reads would be kept. However, out of three samples (each with ~600 expected cells), this was only the case for one of them. The other two have a median number of reads per cell way below 2,000 (around 600 reads/cell).
Are there circumstances when the N minimum of reads cannot be fulfilled? Am I misunderstanding this option?
Note: Apart from setting the N parameter to 2000 and lowering the base quality parameters q and Q to 0 (I had to preprocessed and correct the cell and UMI barcodes prior to running zUMIs), all the parameters are default parameters.
Also, the three samples have pretty similar characteristics: they have between 16 and 19 million reads and when I set up the b parameter to 600 cells, the median number of reads per cell is between 10,000 and 13,000, with a median number of detected genes between 2,000 and 3,000.
Thanks for your help!

**Comment by helene-ccfk** [comment]
Hi Christoph,
Thank you so much for your quick answer.
Sorry if my message was confusing. When I ran zUMIs with the -N parameter set to 2000, I did not specify -b, so it was in automatic barcode selection. I obtained between 2,000 and 5,000 automatically selected barcodes per sample, and the median number of reads per cell was largely below 2,000, except for one sample for which the -N 2000 limit seems to have actually been applied.
This is why I was wondering if other characteristics of a dataset could be in conflict with the -N parameter.
I hope this makes sense.
Thanks,
Helene

**Comment by cziegenhain** [comment]
Hey Helene,

I understand, thats odd then! 
Could you upload the output from the `zUMIs_output/stats/` folder as a zip file so we can look at that?
And would also be great if you could paste the full command or the parameter text file (`*.zUMIs_run.txt`) here.

Thanks,
Christoph

**Comment by helene-ccfk** [comment]
[zUMIs.zip](https://github.com/sdparekh/zUMIs/files/1972011/zUMIs.zip)

Thanks Christoph,
I attached a zip file with the stats for 4 samples A, B, C, D. I rerun zUMIs with the same parameters but the latest version (0.0.6b). These are the stats that I have attached. I wanted to check if the problem was a version issue (I was using 0.0.3 so far). It didn't change the results, except for sample B.
Interestingly, sample B was the only sample for which the -N 2000 limit seemed to have been applied in zUMIs version 0.0.3 (2,020 barcodes selected, and a median reads per cell of 4,854); in version 0.0.6b, zUMIs selected 79,705 barcodes (!) and the median reads per cell is 5.
The parameters for each run are in the log files in the folder "logs".
Let me know if you need any additional info.
Best,
Helene

**Comment by cziegenhain** [comment]
Hey Helene,

thanks for uploading these! Thats very informative. Actually I have never seen as pronounced multimodal distributions of reads per cell barcode. as in the plots from you. It seems that our clustering algorithm gets a bit confused there with the barcode selection.
So it'll actually be a great idea to help with the nReadsperCell parameter.
Back to topic:
I have identified and fixed the bug. 
Furthermore I have added a note in the usage that the parameter is only considered for automatic barcode selection.
If you clone zUMIs again, version 0.0.6c should be it!

Thanks for helping us hunt down this bug.

Best,
Christoph

**Comment by helene-ccfk** [comment]
Thank you so much Christoph.
It works well now and it is a nice option to have.

I have noticed that the detected cells plot has changed. It looks like only some of the data might be present. I am attaching my plots so you can see what I mean if you compare with the plots I had in the previous run.

[zUMIs_detected_cells.zip](https://github.com/sdparekh/zUMIs/files/1975249/zUMIs_detected_cells.zip)

Thanks for making this super useful tool available.
Best,
Helene

**Comment by cziegenhain** [comment]
Thanks for testing & your feedback!
Aha, yes I see the difference. 
So only those barcodes that have above the specified depth go into the barcode selection step - that explains the difference.

Would you as a user find a different solution more practical? (ie barcode selection from all barcodes and then later discarding according to the threshold?)

Best,
Christoph

**Comment by helene-ccfk** [comment]
Thanks Christoph. Sorry it took me so long to get back to you.
Yes, I think I would slightly prefer as a user to have all the barcodes in that plot to be able to visualize where the threshold is exactly in the distribution, but the current plot also makes sense now.
Thanks,
Helene

**Comment by cziegenhain** [comment]
Excellent, I will note it down for future releases.

Thanks for the feedback!
