### ISSUE TITLE
Is there a way to overwrite the STAR parameter --outSAMunmapped ?

### ISSUE THREAD

**Issue by TatevikJ** [sdparekh/zUMIs#364]
I don't want to have unmapped reads included within the output bam, so I specify these STAR parameters in yaml file:
```
additional_STAR_params: '--outSAMunmapped None --limitSjdbInsertNsj 2000000 --outFilterIntronMotifs RemoveNoncanonicalUnannotated --clip3pAdapterSeq CTGTCTCTTATACACATCT CTGTCTCTTATACACATCT'
```

However, I get this error:
```
EXITING: FATAL INPUT ERROR: duplicate parameter "outSAMunmapped" in input "Command-Line"
SOLUTION: keep only one definition of input parameters in each input source
```

Is there a way to overwrite the STAR parameter --outSAMunmapped ?

**Comment by cziegenhain** [comment]
Hi,

This is not intended for zUMIs and skipping the unmapped reads output during zUMIs may disrupt correct generation of statistics within zUMIs.
I recommend that you remove unmapped reads from the bam file using samtools after zUMIs is completed.

Best,
Christoph

**Comment by TatevikJ** [comment]
Thank you for your prompt response.

Regarding the unmapped reads, I would like to confirm if they have any additional purpose or if they are used in any other way within the analysis pipeline, aside from the generation of statistics.

**Comment by cziegenhain** [comment]
Apart from statistics, they are used for ensuring the accuracy of the downsampling feature. Other than that unmapped reads are just kept for not discarding observed data.

**Comment by TatevikJ** [comment]
Ok, thank you!
