### ISSUE TITLE
Example of dual index Smart-seq3

### ISSUE THREAD

**Issue by russellxie** [sdparekh/zUMIs#367]
Hello, 

Is it possible to share an example of how to set up the barcode white list for the dual index smart-seq3 libraries? The manual only has the example of single i7 indexed libraries. 

Best,
-Russell

**Comment by cziegenhain** [comment]
Hi, 

when using dual index barcodes (example for YAML attached), 
, the expected barcodelist should contain the concatenated string of all possible expected barcode combinations!


<img width="487" alt="image" src="https://github.com/sdparekh/zUMIs/assets/16579427/69f63e8d-6971-4bd1-807e-19ee129be87d">

**Comment by russellxie** [comment]
Cool, thanks!
