### ISSUE TITLE
"More reads than allowed for the memory limit"

### ISSUE THREAD

**Issue by gevro** [sdparekh/zUMIs#372]
Hi,
I'm getting the warning:
[1] "Warning: Barcode SVGCSJLD has more reads than allowed for the memory limit!\n                  Proceeding anyway..."

Will this exclude reads? If so, then should I restart with a higher mem_limit ?

Or does it include all reads, and I can let the run try and finish and hopefully won't crash?

**Comment by cziegenhain** [comment]
Hi,

This is just a warning for you, it will try to run with all the reads in memory for the barcode and you can just let it run and if there is no crash it should be all good!
There should never be a discarding of reads.

Best,
Christoph
