### ISSUE TITLE
Processing RNA-Seq data with UMIs from SMARTer® Stranded Total RNA-Seq Kit v3 - Pico Input Mammalian

### ISSUE THREAD

**Issue by seifudd** [sdparekh/zUMIs#376]
Hi, I need some help defining the inputs for processing plate-based RNA-Seq data (with UMIs) generated using the SMARTer® Stranded Total RNA-Seq Kit v3 - Pico Input Mammalian from Takara.

Description of sequencing protocol is [here](https://www.takarabio.com/learning-centers/next-generation-sequencing/technical-notes/rna-seq/stranded-libraries-from-picogram-input-total-rna-(v3)#Pico-v2-workflow). 

I have R1 and R2 per sample.

Here is the YAML file that I am using for running zUMIs for 1 sample - [BMS073_retry4.zUMIs_config_formated.txt](https://github.com/sdparekh/zUMIs/files/12834863/BMS073_retry4.zUMIs_config_formated.txt)

Here is the barcode file - [barcode_BMS073.txt](https://github.com/sdparekh/zUMIs/files/12834868/barcode_BMS073.txt)

After running zUMIs, there are no _Expression files_ generated. 

The header of the fastq files (both R1 and R2) contains the barcode (included in the barcode file above), for e.g. 

`@lh00172:46:GW23091633rd:5:1101:3145:1064 2:N:0:ACTAAGAT+CCGCGGTT
TTTGATCACCCGGGCACCTAGAGTGCGGAGTTGAGCACCTCAGAAGGGAGGTGTGGCCCTCAGGACATTGTCAGCATGTGCGATGATAGTGGAGGCCATGGATTTGAGAACATTTCAGAGAATATTTGATGGAGGGGAACGCCAAGGGGA
+
FFFFFFFFFFFFFFFFF-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5FFF5F-FFFFF-`

What am I missing? Any help will be appreciated.

Thanks, Fayaz

**Comment by cziegenhain** [comment]
Hi Fayaz,

zUMIs does not support barcodes stored in headers and running already demultiplexed data.
It is mandatory to have a BC field in the config file
If you dont have access to the data prior to demultiplexing, I suggest to check here:
https://github.com/sdparekh/zUMIs/wiki/Starting-from-demultiplexed-fastq-files

**Comment by seifudd** [comment]
Thank you. This makes sense. Appreciate your response and help with this.
