### ISSUE TITLE
[main_cat] ERROR: input is not BAM or CRAM

### ISSUE THREAD

**Issue by Thomas0194** [sdparekh/zUMIs#385]
Hi,

I'm having issues while starting zUMIs as follows,

This problem confused me for a while,

I ran the file in Ubuntu and also tried changing all the paths from /mnt/d to the wsl file folder.

However, the error still appears.

Do you know what's wrong with it and could you please give me some suggestions?

Thanks a lot

Best,

[zUMIs.txt](https://github.com/sdparekh/zUMIs/files/13856899/zUMIs.txt)

Using miniconda environment for zUMIs!
 note: internal executables will be used instead of those specified in the YAML file!

 You provided these parameters:
 YAML file:     zUMIs.yaml
 zUMIs directory:               /mnt/d/zUMIs-main
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   null
 zUMIs version 2.9.7e

Mon Jan  8 17:41:35 JST 2024
WARNING: The STAR version used for mapping is 2.7.11a and the STAR index was created using the version 2.7.4a. This may lead to an error while mapping. If you encounter any errors at the mapping stage, please make sure to create the STAR index using STAR 2.7.11a.
Filtering...
Mon Jan  8 17:42:46 JST 2024
[1] "180 barcodes detected."
[1] "961431 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Found 386 daughter barcodes that can be binned into 148 parent barcodes."
[1] "Binned barcodes correspond to 78143 reads."
Mapping...
[1] "2024-01-08 17:43:00 JST"
        STAR --readFilesCommand samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/STAR_index --sjdbGTFfile /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/Homo_sapiens.GRCh38.110.gtf --runThreadN 3 --sjdbOverhang 65 --readFilesType SAM SE --twopassMode Basic --readFilesIn /home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ai.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121aj.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ak.filtered.tagged.bam --outFileNamePrefix /home/thomaslio/test/zUMIs_output/.tmpMap//tmp.Project121.3.
        STAR version: 2.7.11a   compiled: 2023-08-15T11:38:34-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Jan 08 17:43:05 ..... started STAR run
Jan 08 17:43:06 ..... loading genome
        STAR --readFilesCommand samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/STAR_index --sjdbGTFfile /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/Homo_sapiens.GRCh38.110.gtf --runThreadN 3 --sjdbOverhang 65 --readFilesType SAM SE --twopassMode Basic --readFilesIn /home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121aa.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ab.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ac.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ad.filtered.tagged.bam --outFileNamePrefix /home/thomaslio/test/zUMIs_output/.tmpMap//tmp.Project121.1.
        STAR version: 2.7.11a   compiled: 2023-08-15T11:38:34-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Jan 08 17:43:05 ..... started STAR run
Jan 08 17:43:06 ..... loading genome
        STAR --readFilesCommand samtools view -@ 2 --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --outSAMtype BAM Unsorted --quantMode TranscriptomeSAM --genomeDir /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/STAR_index --sjdbGTFfile /mnt/d/P3_Far_S1_CMLC-zumi_test_file/STAR_Reference/Homo_sapiens.GRCh38.110.gtf --runThreadN 3 --sjdbOverhang 65 --readFilesType SAM SE --twopassMode Basic --readFilesIn /home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ae.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121af.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ag.filtered.tagged.bam,/home/thomaslio/test/zUMIs_output/.tmpMerge//Project121.Project121ah.filtered.tagged.bam --outFileNamePrefix /home/thomaslio/test/zUMIs_output/.tmpMap//tmp.Project121.2.
        STAR version: 2.7.11a   compiled: 2023-08-15T11:38:34-04:00 :/home/dobin/data/STAR/STARcode/STAR.master/source
Jan 08 17:43:05 ..... started STAR run
Jan 08 17:43:06 ..... loading genome
Jan 08 17:44:16 ..... processing annotations GTF
Jan 08 17:46:05 ..... inserting junctions into the genome indices
Jan 08 17:47:19 ..... started 1st pass mapping
Jan 08 17:47:46 ..... finished 1st pass mapping
Jan 08 17:47:46 ..... inserting junctions into the genome indices
Jan 08 17:48:41 ..... started mapping
Jan 08 17:49:19 ..... finished mapping
Jan 08 17:49:19 ..... finished successfully
[main_cat] ERROR: input is not BAM or CRAM
[main_cat] ERROR: input is not BAM or CRAM
Mon Jan  8 17:49:21 JST 2024
Counting...
[1] "2024-01-08 17:49:41 JST"
[1] "4.5e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/thomaslio/test/Project121.final_annot.gtf"
[E::hts_open_format] Failed to open file /home/thomaslio/test/Project121.filtered.tagged.Aligned.out.bam
samtools view: failed to open "/home/thomaslio/test/Project121.filtered.tagged.Aligned.out.bam" for reading: No such file or directory
[E::hts_open_format] Failed to open file /home/thomaslio/test/Project121.filtered.tagged.Aligned.out.bam
samtools view: failed to open "/home/thomaslio/test/Project121.filtered.tagged.Aligned.out.bam" for reading: No such file or directory
Error in gsub("SN:", "", chr) : object 'chr' not found
Calls: .makeSAF ... .chromLengthFilter -> [ -> [.data.table -> eval -> eval -> gsub
In addition: Warning message:
In data.table::fread(bread, col.names = c("chr", "len"), header = F) :
  File '/tmp/Rtmp32axoi/file7e5b964e69974' has size 0. Returning a NULL data.table.
Execution halted
Mon Jan  8 17:49:51 JST 2024
Loading required package: yaml
Loading required package: Matrix
[1] "loomR found"
Error in gzfile(file, "rb") : cannot open the connection
Calls: rds_to_loom -> readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/thomaslio/test/zUMIs_output/expression/Project121.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan  8 17:49:59 JST 2024
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2024-01-08 17:50:01 JST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/thomaslio/test/zUMIs_output/expression/Project121.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
Mon Jan  8 17:50:11 JST 2024

**Comment by cziegenhain** [comment]
Hi,

Seems like there is a problem loading the STAR index during mapping.
I recommend to repeat the genome generation step and try again!
All the best,
Christoph

**Comment by Thomas0194** [comment]
Hi Christoph,

Thanks for your suggestion,

I fixed the problem after receiving your useful suggestion!

Thanks a lot!

Best,
