### ISSUE TITLE
aligning to multiple genomes?

### ISSUE THREAD

**Issue by brennaremick** [sdparekh/zUMIs#387]
I would like to align my reads to 2 genomes (human genome and a viral genome). Is this possible with zUMIs?

**Comment by cziegenhain** [comment]
Hi, should not be a problem.
You can either make a STAR reference genome with all the fasta files that you want to map against or you can add smaller fasta files (eg. viral genome) to a regular run against the  human genome on the fly in zUMIs. Simply input the fasta in the YAML section reference: additional_files: , see line 34 here https://github.com/sdparekh/zUMIs/blob/main/zUMIs.yaml#L34
