### ISSUE TITLE
Is there a way to overwrite the STAR parameter --sjdbOverhang ?

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#39]
Dear zUMIs developers,
Thank you for the nice tools. I have meet an issue when I try zUMI on my split seq dataset. the length of read1 is 66nt. I generated my STAR genome by setting --sjdbOverhang as 100. Do I have to regenerate my genome set --sjdbOverhang as 65 or is there a way to overwrite this parameter in zUMIs.

Thank you.
Y

**Comment by cziegenhain** [comment]
Hey,

For zUMIs, you should not use a STAR index with fixed splice annotation and sjdbOverhang.
Please create an index without those options set, and zUMIs will pass these variables to STAR on the fly.
That way, you can easily run data through the pipeline in case you sequence longer/shorter reads or just want to update your gene annotation.

For more information, there is also a little bit on STAR in our wiki:
https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping

**Comment by ysu2015** [comment]
I see. Thank you. Just to make sure.
I will generate STAR index for zUMIs, only include the setting in below:
STAR --runMode genomeGenerate --runThreadN 4 --genomeDir --genomeFastaFiles --sjdbGTFfile

Thank you for the quick reply. I believe this is the record in my entire live so far. Thank you.

**Comment by cziegenhain** [comment]
Very happy to help!
Just also leave out the sjdbGTFfile for zUMIs!

Let us know if you encounter other issues.

**Comment by ysu2015** [comment]
Got it. Thank you so much. I will be very happy to run my single cell study with zUMI from now on.
