### ISSUE TITLE
Isentify unmatched barcodes in Split seq

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#41]
Hi,
After trying zUMIs, I will say this is a very hand on and useful tools for scRNAseq data processes. Thank you.
I tested zUMIs on my Splitseq dataset, it works quite nice. But I met an issue that the cell barcodes being identified is not matched to any combinations. I think that may come from the sequencing error or incorrectly ligation products. Then we actually identified more cells (barcodes) than the real case. I was wondering is that possible to add this consideration to the preprocessing script. That will be very useful for applying zUMIs to split-seq.
Thank you.
Y

**Comment by cziegenhain** [comment]
Hey,

Thanks for your feedback on zUMIs and sorry to hear you are having trouble with the output.
I think one must find out wether there is still a mistake in the processing or maybe if something has gone wrong in the library preparation procedures.

First of all, can you please tell me exactly which base ranges you selected in the preprocessing? It would be a good idea to crosscheck if these ranges make sense with the person who made the library (unless you did that yourself ;) )

Did you have automatic barcode detection by zUMIs? I would be curious to see the output plots.
Especially for long barcodes, it would be normal to observe many more than expected, but they should not make up a large fraction of the reads! Reasons include sequencing and PCR errors that create "spurious" barcodes.
Also: How many cells did you expect to see?

Best,
Christoph

**Comment by ysu2015** [comment]
Hi Christoph,

Thank you for the quick response. I really appreciated.

So for the first question, I made the library by myself, and using exactly the same sequence as the published paper. The base ranges were set as "1-18 49-56 87-94" which is totally make sense. I also check into the fastq file to make sure.

I am not quite clear about the "automatic barcode detection" parameter on zUMIs. Could you guide me and explain a little bit? 

Thank you.
Y

**Comment by sdparekh** [comment]
Hi Y,

For the barcode detection option, you can refer to https://github.com/sdparekh/zUMIs/wiki/Cell-barcodes-selection

If you share your plots generated in the "zUMIs_output/stats" <studyname>.detected_cells.pdf and <studyname>.downsampling_thresholds.pdf we could guide you further.

Best wishes,
Swati

**Comment by ysu2015** [comment]
Hi Swati,

Thank you for your help. Please find my stats files in attached. I really appreciate your help.

**Comment by ysu2015** [comment]
/Volumes/YSu_2015/SPLiTseq_180413/splitT1_180531/WT_All/zUMIs_output/stats/WT_All.detected_cells.pdf
/Volumes/YSu_2015/SPLiTseq_180413/splitT1_180531/WT_All/zUMIs_output/stats/WT_All.downsampling_thresholds.pdf

**Comment by ysu2015** [comment]
Hi Swati,

I have problem on attaching files. Any issue could be?

Yijing

**Comment by cziegenhain** [comment]
Try compressing them as a zip file!

**Comment by ysu2015** [comment]
still could not work. Could I send to you directly? Thank you. 
Y

**Comment by sdparekh** [comment]
Yes of course!!
swatidparekh@gmail.com
cziegenhain@gmail.com
