### ISSUE TITLE
downsampling

### ISSUE THREAD

**Issue by yongjieliu** [sdparekh/zUMIs#43]
Hi,

I want to determine whether the RNA-seq library was sequenced to saturation. Then I pick up the intron.exon umicounts downsampled matrix. But I cannot understand the structure of this matrix. Could you please give me any advice to plot the relationship of sequencing depth and gene detected?

yours

yongjie

**Comment by cziegenhain** [comment]
Hey yongjie,

First of all, to determine the saturation I would recommend to downsample to different depths using zUMIs. 
This depends on the number of reads and number of cells you have but for instance you could say `-d 100000,250000,500000` and run zUMIs with that.
Then in your dgecounts object, you would find a list of matrices for each of the requested depths in  dgecounts$intron.exon$downsampled. 
Eg to access the umi counts for intron.exon for 100000 reads per cell, use dgecounts$intron.exon$downsampled$downsampled_100000$umicounts_downsampled

More information on zUMIs output can be found in our wiki:
https://github.com/sdparekh/zUMIs/wiki/Output#structure-of-the-output-dgecounts-object-in-dgecountsrds

**Comment by yongjieliu** [comment]
Hey,
 
Thank you very much. I will try `-d`  parameter  later.

**Comment by hmassalha** [comment]
Hi,
I am running the analysis with downsampling asking for 2M reads. But when I look at the output find dgecounts$exon$downsampled$downsampled_2000000 I see that I have a range between 600k and 10M for different samples. Why is that? (I am interested only on exons, do that downsampling count for intros and exons or only exons? 
Any help or any direction to tackle this will be much appreciated. 

Thanks, HM

**Comment by cziegenhain** [comment]
Hi,
The point of our downsampling is sampling a requested amount of raw reads. thus the total number of exon reads in a sample depends on the mapping rate & exonic fraction.

**Comment by hmassalha** [comment]
Thanks a lot for the clarification of this point. HM
