### ISSUE TITLE
Is there a way to output the gene names instead of EN ID on the .rds file?

### ISSUE THREAD

**Issue by ysu2015** [sdparekh/zUMIs#44]
Hi, 
I was wondering is there a way to specify the output parameter of the .rds files? such as output gene name instead of EN IDs. Thank you.

Y

**Comment by cziegenhain** [comment]
Hey,

In principle, this just depends on your input GTF file,
However, I do not recommend short names because they can be ambiguous.

If you want to convert later, I recommend the biomaRt package
https://www.r-bloggers.com/converting-mouse-to-human-gene-names-with-biomart-package/
