### ISSUE TITLE
InDrop (#UMI = #genes)  

### ISSUE THREAD

**Issue by jakaye** [sdparekh/zUMIs#45]
Hello, 

I have been trying to run the zUMI pipeline for my InDrop (v3) data but am getting kind of strange results where for every gene there is only one UMI - so my zUMI generated geneUMIcounts plots look identical for number of genes and number of UMIs.

As told by our scRNA core, R1 (61bp) is the transcript; R2 (8bp) is part 1 of the sc barcode; R3 (8bp) is the library index; and R4 (8bp + 6bp) is part 2 of the sc barcode followed by the UMI barcode. [details](https://iccb.med.harvard.edu/files/iccb/files/sequencing_indrops_libraries_02_28_18.pdf)

I have been a little confused about the “-c” option. On your Usage page, you say that this should be the total cell barcode (so 1-16?). However, on your InDrops mode page, you say this should be the total of all the barcodes. Does this mean library+sc+UMI (which are all barcodes and would be 30 in my case?). I noticed that when I run zUMIs the readspercell plot has the sc barcodes on the x-axis. From this, I can see that the first part of the sc barcode is always the library. So in order to make this string read Library+fullscbarcode, I have designated -c 1-24 (8 bp library + 8 bp part 1 + 8 bp part 2). Using -c 1-24 my reads per cell histogram look most like the reads per barcode histogram generated from the InDrops pipeline. So I think -c should be 1-24. However, I have no idea how to resolve the UMI = gene issue. 

I have been supplying zUMIs with 121,636,018 reads from one library with 89,743,025 reads ultimately passing filtering and about 80% being mapped.

The command I use to run zUMI is something like this:

```
bash path/to/zUMIs-master.sh \
-f path/to/R2.fastq.gz \
-r path/to/R1.fastq.gz \
-c 1-24 -m 1-6 -l 61 \
-g path/to/STARindex \
-a path/to/my.gtf \
-n Project \
-p 20 \
-o path/to/zUMIs_out \
-Y yes \
-F path/to/R4.fastq.gz \
-L path/to/R3.fastq.gz \
-z 3 \
-u 3 \
-q 17 \
-Q 17
```
Should -c be 1-24? and why do I have the same number of genes as umis (this is not the case when I process using the InDrops pipeline)? Thanks in advance for your help!

**Comment by jakaye** [comment]
So diving further into this issue, I looked through your fqfilter-inDrops.pl code and noticed that it doesn't seem to call the -c argument. Subsequently, the length of the barcoderead.filtered.fastq is hard-coded to be 28 bp in length (lines 125-128) regardless of the -c I put in. I checked through my different filtered fastqs that were generated with different -c parameters and it was indeed always 28 bp. I think this is problematic when zUMIs then goes to generate the UMI counts info. For me, this should probably be 30 bp instead of 28.

**Comment by sdparekh** [comment]
Hi Jakaye,

Thank you for using zUMIs and thank you for noticing this bug in inDrops mode.

I have fixed this. Currently, I do not have a inDrops V3 data at hand to properly test it. Can you please test and let me know if the bug is fixed!

Thank you once again. Looking forward to your feedback.

Swati

**Comment by jakaye** [comment]
Hi Swati,

Thanks for the super fast response! After re-downloading zUMIs, I tried the patched code and it doesn't seem to be generating filtered fastqs at all. 

Also, I tried running the old code last night using 24 instead of 22 in those 4 lines of code that I mentioned in the previous post. When ran with `-c 1-24` and `-m 1-6` this again produced results with identical geneUMIcounts plots. However when ran with `-c 1-24` and `-m 25-30` this produced plots that look accurate (more UMIs than genes). Not sure if your patches address this, but just thought that info might be helpful. 

On another note, I noticed that I am getting a lot of reads associated with a poly-G barcode. I think the InDrops pipeline addresses this with a low-complexity filter. Do you guys have anything (parameter I can flag) that I could help with this issue?

Best,
Judith

**Comment by cziegenhain** [comment]
Hey Judith,

Swati will get back to you shortly with a bugfix for the bugfix ;-) sorry for that.

For your other question: Sorry we don't have a smart filter for barcodes like that right now.
However I think its a good idea, and other protocols can have similar low-complexity barcode reads (eg. poly A), so I will note this down for our upcoming zUMIs 2.0 release!
For now, best to filter afterwards.

Thanks,
Christoph

**Comment by sdparekh** [comment]
Hi Judith,

Sorry for the delay!! My to-do list is just expanding each day. ;)
I have fixed it, please test it and let me know if it helped. I tested with a small dataset and it worked for me.

Best,
Swati

**Comment by jakaye** [comment]
Hi Swati and Christoph,

First off, thanks for the super great responsiveness. I just finished running the patched version by Swati. I still get the issue of #UMI = #Genes when I use the `-m 1-6` but with `-m 25-30` I get a geneUMIcounts.pdf that looks right. I think everything is working as you guys have intended, but you might want to update your usage page and wiki for indrops mode for the -m flag. 

I haven't finished downstream analysis yet, but I will let you know if clustering looks wonky. Thanks again! I will be recommending zUMIs as a great alternative for InDrops processing to our InDrops core at HMS!

Judith

**Comment by cziegenhain** [comment]
Hey Judith,

you're absolutely right it's just the usage instructions that should be changed now.
Thanks for testing and we appreciate the recommendation!

Best,
Christoph
