### ISSUE TITLE
Error running the test: bash: /zUMIs-noslurm.sh: No such file or directory

### ISSUE THREAD

**Issue by danieleyumi** [sdparekh/zUMIs#46]
Hi,

The error **bash: /zUMIs-noslurm.sh: No such file or directory** is displayed when I run the test:
p=`/path/to/zUMIs/`
/SOFTWARES/zUMIs$ bash $p/zUMIs-master.sh -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 3 -o $p/ExampleData

When I remove the 
"$zumisdir" from the line:
bash $zumisdir/zUMIs-noslurm.sh in zUMIs-master.sh, apparently zUMIs-noslurm.sh is found but then another error occurs:
 ~/SOFTWARES/zUMIs$ bash $p/zUMIs-master.sh -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 3 -o $p/ExampleData
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Your jobs will run on this machine.

Make sure you have more than 1.8G RAM and 3 processors available.

Your jobs will be started from filtering.

 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/Users/tania/SOFTWARES/zUMIs/ExampleData/barcoderead_HEK.1mio.fq.gz
 cDNA read:			/Users/tania/SOFTWARES/zUMIs/ExampleData/cDNAread_HEK.1mio.fq.gz
 Study/sample name:		chr22test
 Output directory:		/Users/tania/SOFTWARES/zUMIs/ExampleData
 Cell/sample barcode range:	1-6
 UMI barcode range:		7-16
 Retain cell with >=N reads:	100
 Genome directory:		/Users/tania/SOFTWARES/zUMIs/reference/hg38_chr22/
 GTF annotation file:		/Users/tania/SOFTWARES/zUMIs/reference/GRCh38.84.chr22.gtf
 Number of processors:		3
 Read length:			50
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Hamming Distance (UMI):	0
 Hamming Distance (CellBC):	0
 Plate Barcode Read:    	NA
 Plate Barcode range:   	NA
 Barcodes:			NA
 zUMIs directory:
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 Additional STAR parameters:
 STRT-seq data:			no
 InDrops data:			no
 Library read for InDrops:	NA
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0

 zUMIs version 0.0.6c

du: illegal option -- B
usage: du [-H | -L | -P] [-a | -s | -d depth] [-c] [-h | -k | -m | -g] [-x] [-I mask] [file ...]
expr: not a decimal number: 'no'
expr: not a decimal number: 'NA'
expr: syntax error
expr: syntax error
rm: /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.Aligned.out.bam: No such file or directory
rm: /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.aligned.sorted.bam.in: No such file or directory
rm: /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.aligned.sorted.bam.ex: No such file or directory
rm: /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.barcodelist.filtered.sam: No such file or directory
mv: rename /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.barcoderead.filtered.fastq.gz to /Users/tania/SOFTWARES/zUMIs/ExampleData/zUMIs_output/filtered_fastq/chr22test.barcoderead.filtered.fastq.gz: No such file or directory
mv: rename /Users/tania/SOFTWARES/zUMIs/ExampleData/chr22test.cdnaread.filtered.fastq.gz to /Users/tania/SOFTWARES/zUMIs/ExampleData/zUMIs_output/filtered_fastq/chr22test.cdnaread.filtered.fastq.gz: No such file or directory

Thank you in advance!!!

**Comment by cziegenhain** [comment]
Hey,

Sorry that I couldnt get back earlier.
seems like you could resolve your issue?

of course you should replace the path with your own in the assignment to variable $p here:
p=/path/to/zUMIs/

Best,

Christoph

**Comment by danieleyumi** [comment]
Hi Christoph,

I ended up installing zUMIs on our server and it is working! Thank you for asking.
I am a bit unsure about the use of “-c” parameter and I immensely appreciate if you could help me.
My fastq files are result of the demultiplexing using bcl2fastq. The Illumina barcodes were removed during this process. I have R1 and R2, where in R1 are the UMIs:
@SN541:395:H2HVNBCX2:1:1106:1578:2133 1:N:0:ACAGTG
NACCTTAGCTAGTTTT
where:
1: N
2-7: UMI
8-13: cell barcode
14-16: polyA

Illumina barcodes were removed. I tried to run without -c parameter but is is required. Should I set -c 0 and -m 2-7?

Many thanks in advance!
Best,
Daniele




---
Dr. Daniele Yumi Sunaga-Franze
Bioinformatician
Scientific Genomics Platforms
Max-Delbrück-Centrum für Molekulare Medizin in der Helmholtz-Gemeinschaft
Robert-Rössle-Str. 10 (House 64 - R 214)
13125 Berlin

Web: genomics.mdc-berlin.de<http://genomics.mdc-berlin.de/>
Email: daniele.franze@mdc-berlin.de<mailto:daniele.franze@mdc-berlin.de>
Tel.-nr:  0049-030-9406-3102

On Jul 13, 2018, at 11:17, cziegenhain <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey,

Sorry that I couldnt get back earlier.
seems like you could resolve your issue?

of course you should replace the path with your own in the assignment to variable $p here:
p=/path/to/zUMIs/

Best,

Christoph

**Comment by cziegenhain** [comment]
Hey Daniele,

you should run with `-c 8-13 -m 2-7`!

Let me know if you need further input.

**Comment by danieleyumi** [comment]
Thank you Christoph for the prompt reply.
I have one more question about UMIs. They start at position 1-7, but most of the sequences are starting with a N instead.
My question is if zUMIs accept mismatch or should I inform 2-7, instead? 

Thank you again,
Daniele

**Comment by cziegenhain** [comment]
Hey,

With default settings, zUMIs will probably filter most of the reads that have inacceptable bass call qualities in the barcode or UMI sequences.
You may tune mismatches using the Hamming distance (but beware this significantly increases runtime!).

I would recommend to check using  fastQC how many Ns there actually are.

Best
C

**Comment by danieleyumi** [comment]
Hey,

First of all, congrats for the new zUMIs release. I still did not have the opportunity to try it but it looks pretty easy/straightforward to use. Btw, I applied the last zUMIs version to analyze RNASeq data with UMIs (no single cell) and seems to be worked very well.

I am now writing to ask you if zUMIs is able to handle with PacBio long reads. Maybe it is just a question of STAR adjustments?

Thank you in advance.
Best,
Daniele

**Comment by cziegenhain** [comment]
Hey,

thanks for the message! 
I don't think STAR works well with PacBio long reads. You can check this post by the STAR author Alex Dobin on how to tune the parameters:
https://groups.google.com/forum/#!searchin/rna-star/starlong/rna-star/-2mBTPWRCJY/PKSPCNcade8J

Maybe you would need to look at other aligners more specifically geared towards long reads?
