### ISSUE TITLE
Can zUMIs work with SPLIT-Seq

### ISSUE THREAD

**Issue by niehu2018** [sdparekh/zUMIs#47]
I read the Wiki page of "Combinatorial Indexing".
Range of UMI sequence + first barcode segment (Round 1 RT barcode)

In the SPLIT-seq protocol, the round 1 primers for RT actually include random hexamer and anchored poly(dT)15 barcoded RT  primers. And, the author put the two barcodes in one well. That is to say, one cell should be labeled by two barcodes ( combination of the Round1 barcode, Round2 barcode, and Round3 barcode).

So, can the next workflow of zUMIs still work well for SPLIT-seq?

Best!

**Comment by cziegenhain** [comment]
Hey,

This sort of setup would at the moment only work if the random-hexamer and the oligo-dT primer carry the same barcode seqeunce per well.

Hope this information helps,

Christoph

**Comment by niehu2018** [comment]
Hey, Christoph
        
      I checked the barcodes they provide,  the random-hexamer and the oligo-dT primer do not carry the same barcode per well. (https://docs.google.com/spreadsheets/d/1edX2uqkMH-z0j0IXt-RGzbVCsUkxSPZYDpXNtJhwnwg/edit#gid=997527550)

I do not understand why they want to capture non-polyA RNA molecules, as the rRNAs account for most of the total RNAs in one cell, and rRNAs are not what we need.

Whatever, thanks for your answer!

Best!

**Comment by cziegenhain** [comment]
Yes that is indeed confusing, best to clarify with the authors of the protocol!

I will close this issue for now, feel free to reopen if you need more input at a later stage.
