### ISSUE TITLE
error when running the example data

### ISSUE THREAD

**Issue by Ann19970822** [sdparekh/zUMIs#48]
Hi,

I am trying to run the sample data in zUMIs but I got an unsolvable error. Would you please check this for me? Thank you so much.

Yours,
Yi

`unix305 532 % p='/stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs/'
unix305 533 % bash $p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/ExampleData/
Your jobs will run on this machine.

Make sure you have more than 2.0G RAM and 8 processors available.

Your jobs will be started from filtering.

 You provided these parameters:
 SLURM workload manager:        no
 Summary Stats to produce:      yes
 Start the pipeline from:       filtering
 A custom mapped BAM:           NA
 Custom filtered FASTQ:         no
 Barcode read:                  /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData/barcoderead_HEK.1mio.fq.gz
 cDNA read:                     /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData/cDNAread_HEK.1mio.fq.gz
 Study/sample name:             chr22test
 Output directory:              /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData/
 Cell/sample barcode range:     1-6
 UMI barcode range:             7-16
 Retain cell with >=N reads:    100
 Genome directory:              /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//reference/hg38_chr22/
 GTF annotation file:           /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//reference/GRCh38.84.chr22.gtf
 Number of processors:          8
 Read length:                   50
 Strandedness:                  0
 Cell barcode Phred:            20
 UMI barcode Phred:             20
 # bases below phred in CellBC: 1
 # bases below phred in UMI:    1
 Hamming Distance (UMI):        0
 Hamming Distance (CellBC):     0
 Plate Barcode Read:            NA
 Plate Barcode range:           NA
 Barcodes:                      NA
 zUMIs directory:               /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 Additional STAR parameters:
 STRT-seq data:                 no
 InDrops data:                  no
 Library read for InDrops:      NA
 Barcode read2(STRT-seq):       NA
 Barcode read2 range(STRT-seq): 0-0
 Bases(G) to trim(STRT-seq):    3
 Subsampling reads:             0

 zUMIs version 0.0.6d

Raw reads: 1000000
Filtered reads: 853296

Make sure you have approximately 11493 Mb RAM availableJul 25 15:15:10 ..... started STAR run
Jul 25 15:15:10 ..... loading genome
Jul 25 15:15:13 ..... processing annotations GTF
Jul 25 15:15:14 ..... inserting junctions into the genome indices
Jul 25 15:15:35 ..... started 1st pass mapping
Jul 25 15:18:09 ..... finished 1st pass mapping
Jul 25 15:18:09 ..... inserting junctions into the genome indices
Jul 25 15:18:29 ..... started mapping
Jul 25 15:21:08 ..... finished successfully
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-07-25 15:21:27 EST"
Error in installed.packages()[grep("Rsubread", installed.packages()),  :
  subscript out of bounds
Calls: as.numeric_version -> is.numeric_version
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2018-07-25 15:22:08 EST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData//zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted`

**Comment by cziegenhain** [comment]
Hey Yi,

Sorry to hear that you are having trouble with zUMIs. 
It looks like our internal check for the version of the Rsubread package fails. 
Could you tell me if you installed it and which version you have on your machine?
Would also be great to know the version of R you are running. 

Best,

Christoph

**Comment by sdparekh** [comment]
Hi Yi,

I installed the same R. version and checked the condition where this error comes from and it works fine. Can you try the following chunk of code?

if(length(grep("Rsubread",installed.packages()))==0){
   print("I did not find Rsubread so I am installing it...")
   BiocInstaller::biocLite("Rsubread",dependencies = TRUE, ask = FALSE)
 }else{
   if(all(as.numeric_version(installed.packages()[grep("Rsubread",installed.packages()),"Version"])<'1.26.1')){
     print("I need newer Rsubread so I am updating it...")
     BiocInstaller::biocUpdatePackages("Rsubread", ask=FALSE)
   }
}

Please write us back what this code chunk gives you.

Best,
Swati

**Comment by Ann19970822** [comment]
Hi Swati,

I think I have figured it out. There is something wrong with the `grep` so I add `[,"Package"]` as a restriction and modify the `zUMIs-dge.R` file. Then I run the example data again and it works.

> grep("Rsubread",installed.packages())
[1]   19  725 7191
> dim(installed.packages())
[1] 881  16
> grep("Rsubread",installed.packages()[,"Package"])
[1]  19 725

if(length(grep("Rsubread",installed.packages()))==0){
   print("I did not find Rsubread so I am installing it...")
   BiocInstaller::biocLite("Rsubread",dependencies = TRUE, ask = FALSE)
 }else{
   if(all(as.numeric_version(installed.packages()[**grep("Rsubread",installed.packages()[,"Package"]),"Version"**])<'1.26.1')){
     print("I need newer Rsubread so I am updating it...")
     BiocInstaller::biocUpdatePackages("Rsubread", ask=FALSE)
   }
}

Thank you again!!
Yours,
Yi

**Comment by sdparekh** [comment]
Hi Yi,

I am glad that you found a solution. However, it is a bit weird that it works with 'Package' and not 'Version' for you! In any case, feel free to write to us if you have any troubles.

I am closing this issue now.

Best,
Swati
