### ISSUE TITLE
Issues when running the sample 

### ISSUE THREAD

**Issue by tom-snir** [sdparekh/zUMIs#5]
Hello,

I believe all dependencies are installed, but I still get an error when trying to run the basic, sample zUMIs run. I apologize for the unclear formatting, copy pasting from the terminal:

[tom@zelda ~]$ bash $p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.f                                          q.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/refer                                          ence/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/Ex                                          ampleData
Your jobs will run on this machine.

Make sure you have more than 1.9G RAM and 8 processors available.

Your jobs will be started from filtering.

 You provided these parameters:
 SLURM workload manager:        no
 Summary Stats to produce:      yes
 Start the pipeline from:       filtering
 Barcode read:                  /private/zel/tom/zUMIs/ExampleData/barcoderead_                                          HEK.1mio.fq.gz
 cDNA read:                     /private/zel/tom/zUMIs/ExampleData/cDNAread_HEK                                          .1mio.fq.gz
 Study/sample name:             chr22test
 Output directory:              /private/zel/tom/zUMIs/ExampleData
 Cell/sample barcode range:     1-6
 UMI barcode range:             7-16
 Genome directory:              /private/zel/tom/zUMIs/reference/hg38_chr22/
 GTF annotation file:           /private/zel/tom/zUMIs/reference/GRCh38.84.chr2                                          2.gtf
 Number of processors:          8
 Read length:                   50
 Strandedness:                  0
 Cell barcode Phred:            20
 UMI barcode Phred:             20
 # bases below phred in CellBC: 1
 # bases below phred in UMI:    1
 Barcodes:                      NA
 zUMIs directory:               /private/zel/tom/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 Additional STAR parameters:
 STRT-seq data:                 no
 Barcode read2(STRT-seq):       NA
 Barcode read2 range(STRT-seq): 0-0
 Bases(G) to trim(STRT-seq):    3
 Subsampling reads:             0

Raw reads: 1000000
Filtered reads: 853296

Jul 26 11:24:39 ..... started STAR run
Jul 26 11:24:39 ..... loading genome
Jul 26 11:24:40 ..... processing annotations GTF
Jul 26 11:24:40 ..... inserting junctions into the genome indices
Jul 26 11:24:48 ..... started 1st pass mapping
Jul 26 11:26:00 ..... finished 1st pass mapping
Jul 26 11:26:00 ..... inserting junctions into the genome indices
Jul 26 11:26:09 ..... started mapping
Jul 26 11:27:23 ..... finished successfully
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-07-26 11:27:31 IDT"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-07-26 11:27:37 IDT"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... Error in c(x, value) :
  could not find symbol "recursive" in environment of the generic function
Calls: makeTxDbFromGFF ... eval -> .nextMethod -> replaceROWS -> replaceROWS ->                                           c
Execution halted
[1] "I am loading useful packages..."
[1] "2017-07-26 11:27:38 IDT"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/private/zel/tom/zUMIs/ExampleData/zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
[tom@zelda ~]$

**Comment by tom-snir** [comment]
Looks like the issue I described above was solved by running this in R after loading the bioconductor library:

biocLite(c("BiocGenerics", "XVector", "S4Vectors", "IRanges", "GenomicRanges"), type="source")

I am not sure if the issue is local to me or not, but this can be closed I believe.

**Comment by cziegenhain** [comment]
Yes it looks like one of the packages was not installed properly before, sometimes there may also be issues when there are several package libraries (user/system).

Great that it works now.
