### ISSUE TITLE
Fail to start from mapping

### ISSUE THREAD

**Issue by Ann19970822** [sdparekh/zUMIs#50]
Hi,

When I tried to run example data, everything was perfect and I got all the results successfully.
```
p='/stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs/'

bash $p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/ExampleData/

(...)


[1] "I am done!! Look what I produced.../stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData//zUMIs_output/"
           used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells  6681736 356.9   12258021 654.7 12258021 654.7
Vcells 13829464 105.6   41210595 314.5 41117511 313.8
```

**However, when I am trying to start zUMIs from <-w Mapping> stage with example data. It shows warning like this:**
``` 
p='/stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs/'
bash $p/zUMIs-master.sh -w Mapping -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/ExampleData/
```

```
gzip: /stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs//ExampleData//chr22test.cdnaread.filtered.fastq.gz: No such file or directory
```

Then I find `chr22test.cdnaread.filtered.fastq.gz`  in this directory: `/stornext/General/data/user_managed/grpu_mritchie_1/YiXie/scpipe/zUMIs/ExampleData/zUMIs_output/filtered_fastq/` , which is generated from last stage `Filtering`.

It is weird that zUMIs fails to open a file generated by itself from the `Filtering` stage. Do I miss some parameters?

Please guide.
Thanks!

Cheers,
Yi

**Comment by Ann19970822** [comment]
Another issue, why there would be a `NA` category in this plot:
<img width="870" alt="screen shot 2018-08-06 at 10 24 38 am" src="https://user-images.githubusercontent.com/34535456/43691672-52499632-9963-11e8-951c-b50b4975e62a.png">

**Comment by cziegenhain** [comment]
I'll close the issue for now, let me know if you need further assistance.
