### ISSUE TITLE
zUMIs 2.0 run time error

### ISSUE THREAD

**Issue by thomsak** [sdparekh/zUMIs#51]
Hi, 
I just switched to zUMIs 2.0 and I'm getting the following runtime error:

/XXX/zUMIs-master.sh: line 8: [: !=: unary operator expected

 You provided these parameters:
 YAML file:     1round.yaml
 zUMIs directory:              /XXX/zUMIs
 STAR executable                STAR
 samtools executable            samtools
 pigz executable                pigz
 Rscript executable             Rscript
 RAM limit:   32
 zUMIs version 2.0 

Filtering...
[W::bam_merge_core2] No @HD tag found.
Mapping...

EXITING: FATAL INPUT ERROR: unrecoginzed parameter name "readFilesType" in input "Command-Line-Initial"
SOLUTION: use correct parameter name (check the manual)

Aug 10 15:43:04 ...... FATAL ERROR, exiting

Here is my yaml file:
project: 4271_eWAT
sequence_files:
  file1:
    name: /XXX/1stRound/4271_eWAT_R1_001.fastq.gz
    base_definition:
    - BC(1-16)
    - UMI(7-26)
  file2:
    name: /XXX/1stRound/4271_eWAT_R2_001.fastq.gz
    base_definition: 
    - cDNA(1-58)
  file3:
    name: /XXX/1stRound/4271_eWAT_I1_001.fastq.gz
    base_definition: 
    - BC(1-8)
reference:
  STAR_index: /XXX/GRCm38_STARindx_noGTF/
  GTF_file: /XXX/genes.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /XXX/1stRound/out
num_threads: 10
mem_limit: 32
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /XXX/zUMIs
read_layout: SE

Any idea what went wrong there?

Thx,
Tom

**Comment by cziegenhain** [comment]
Hey Tom,

Thanks for using zUMIs and updating!

This looks like your STAR doesn't like the bam file input. 
Which version of STAR are you running there?

**Comment by thomsak** [comment]
Hi,
it's STAR_2.5.3a.
T

**Comment by cziegenhain** [comment]
Hey,

yes I think then i would recommend to update; STAR only implemented this functionality from [2.5.4a](https://github.com/alexdobin/STAR/releases/tag/2.5.4a) 

Here is the link to the latest executables:
https://github.com/alexdobin/STAR/archive/2.6.0a.tar.gz

Please try and let me know if that works!

**Comment by thomsak** [comment]
Thanks, that seems to work.
T
