### ISSUE TITLE
Variable cDNA read length may lead to truncated file error

### ISSUE THREAD

**Issue by MaxKman** [sdparekh/zUMIs#53]
Unfortunately I ran into another issue. The zUMIs pipeline now works with the example data set but not with my own fastq file. Yaml file:
[MB_new.yaml.txt](https://github.com/sdparekh/zUMIs/files/2286550/MB_new.yaml.txt)

Here is the output:

> You provided these parameters:
>  YAML file:     MB_new.yaml
>  zUMIs directory:               /home/makaufm/apps/zUMIs
>  STAR executable                /home/makaufm/apps/STAR_2.5.4a/bin/Linux_x86_64/STAR
>  samtools executable            /home/makaufm/apps/samtools_1.9/bin/samtools
>  pigz executable                pigz
>  Rscript executable             Rscript
>  RAM limit:   0
>  zUMIs version 2.0
> 
> 
> Filtering...
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 2
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 4
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 4
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 4
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 5
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 2
> [main_samview] truncated file.
> [W::sam_read1] [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 4
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 4
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 3
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 2
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 2
> [main_samview] truncated file.
> [W::sam_read1] Parse error at line 1
> [main_samview] truncated file.
> [W::bam_merge_core2] No @HD tag found.
> cat: /data/max/01_projects/03_MadeleineB/zUMIs_out/zUMIs_output/.tmpMerge//MB.*.BCstats.txt: No such file or directory
> 

The result is a bam file, which only contains 41 lines:
[MB.filtered.tagged.txt](https://github.com/sdparekh/zUMIs/files/2286389/MB.filtered.tagged.txt)

The input fastq files looks perfectly normal to me.

Any idea what could be going on?

Best Max

**Comment by cziegenhain** [comment]
Hey Max,

Again, sorry for the issues. 
Just a wild guess: was trimming performed on these fastq cDNA files? Could be then that the cDNA sequence extraction gets out of bounds if there are less bases then specified.
Now that I think about it, this would have worked in the previous version of zUMIs but not in the newest.

**Comment by MaxKman** [comment]
Hey Christoph,

Again thanks for your quick response. Apparently some kind of of trimming has been performed with these fastq files (I didn't do the processing myself all the way from the start) because fastqc shows a range of read lengths between 54-76 for read2 (with most reads having a length of 76). I reduced the cDNA range to 1-50 for read2 and the error disappeared. Is there a way to run the pipeline without a fixed cDNA range for read2?

Best Max

**Comment by cziegenhain** [comment]
Hey Max,

Hmm okay that confirms my theory, thanks for checking so quickly!

Unfortunately I have to say I don't have an immediate solution. 
Of course we will implement this type of variable cDNA length soon. 

For now, you would need to stick with the shortest read length found or with the previous version of zUMIs.

I will keep this issue open for other users until we have changed this handling. 

Best

Christoph

**Comment by MaxKman** [comment]
Some of the fastq files turned out to have a couple of reads as short as 30bp in read2 so I couldn't set the range to that minimum without loosing a lot of information. Trimming the short reads was also not straightforward because tools like cutadapt don't give you the possibility to trim only read2 when its shorter than x bp, whithout applying the same criterium to the inherently short read1 containing the cell barcodes / UMIs. My work around for now is to use a phyton script found [here](https://www.biostars.org/p/17148/) to fill up each read with Ns to the desired length for all the fastqs that I later want to feed into the zUMIs pipeline:

`parallel "gzip -cd {} | python read_length_76.py | gzip -vc >  /data/max/01_projects/MB/fastq_76bp/{/}" ::: /data/max/01_projects/MB/fastq/*.fastq.gz`

read_length_76.py:
```
import itertools, string, sys

# strip newlines from the standard input
stream = itertools.imap(string.strip, sys.stdin)

# this works only if sequences span only one line
for head in stream:

    # advance the stream
    seq  = stream.next()
    tmp  = stream.next()
    qual = stream.next()

    # this is how much to pad
    size = 76 - len(seq)

    # pad each line
    seq  = seq  + "N" * size
    qual = qual + "2" * size

    # print the joined elements
    print "\n".join( (head, seq, tmp, qual) ) 
```

Best Max

**Comment by cziegenhain** [comment]
Hey Max,

thanks for leaving this temporary workaround until we have updated our sequence extraction! 

Best,
Christoph

**Comment by cziegenhain** [comment]
Hey Max,

We have just pushed a fix for this issue. 
You can just give the range as you want now and shorter reads will just be taken over completely.

Best,

Christoph
