### ISSUE TITLE
Barcode and UMI parameters for ddSEQ data

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#54]
Hi there!

I have a couple of questions regarding using zumi for surecell data.
1 - Be it the online shiny page or the zumis.yaml file provided in the git download, there is only space for up to 4 input files (or specifically written up to 4).  I have a sequencing run where I have 2 read files for 4 lanes - so a total of 8 files for the run.  Do I need to run zumis twice or can I just include all the files in a single yaml and zumis will process all 8 files specified in the yaml?  

2 - As per the attached tech note from Illumina, referencing fig2, there are 6 possible "read structures" as outlined.  If only read structure 1 is utilized, my understanding is in the yaml, under base definition I could just write BC(1-6) BC(22-27) BC(43-48) UMI(52-59) (also referencing https://github.com/sdparekh/zUMIs/issues/35).  However, what if multiple read structures are utilized, what would be the best way to define that or the best approach to dealing with that?

[single-cell-rna-algorithm-tech-note_VerA.pdf](https://github.com/sdparekh/zUMIs/files/2288063/single-cell-rna-algorithm-tech-note_VerA.pdf)

**Comment by mbassalbioinformatics** [comment]
Wow, you really do reply quickly (awesome!).

regarding 1 - thanks, will concatenate them as suggested.  I've received the pre-split fq files so thats why was just asking.

regarding 2 - Im not sure whether whether the shifted reads will be an issue here, Id have to check with the lab that actually generated the experiment.  However, I could simply re-run zumis with the shifted read indexes and combine afterwards I guess.  Or at least re-run and see what gets dropped etc..

Thanks for the advice and insights!  Great work to you and the others btw!!

**Comment by cziegenhain** [comment]
Hey,

we have now implemented the phase-block correction necessary for optimal analysis of ddSeq data.
Please update zUMIs to the newest release and check out the wiki for an example! 
https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#ddseq--surecell-3

Let us know if this works for you - we rely on the feedback of users since we don't have all datasets in our own research.

Thanks a lot,

Swati & Christoph

**Comment by mbassalbioinformatics** [comment]
Great thanks heaps!

Ill hopefully be testing this in the next couple of weeks and get back to you if any issues arise!

**Comment by cziegenhain** [comment]
Hey,

a very large percentage of reads as "unused" barcodes could also be the
data. Did you use automatic barcode detection? If so, could you show us the
plot that zUMIs generates for that?

mbassalbioinformatics <notifications@github.com> schrieb am Mo., 22. Okt.
2018 um 04:32 Uhr:

**Comment by mbassalbioinformatics** [comment]
Hi
Yes I did use auto barcode detection.  Not quite sure which plot you want to look at so ive attached 
[the downsampling thresholds](https://github.com/sdparekh/zUMIs/files/2503895/CD34CD45-Nxxx.downsampling_thresholds.pdf) and [the detected cells](https://github.com/sdparekh/zUMIs/files/2503897/CD34CD45-Nxxx.detected_cells.pdf).  Hope that's what you were asking for...

Thanks for your help!

**Comment by mbassalbioinformatics** [comment]
The expected number of cells (usable) for this experiment **_is_** low thats for sure.

Would i be right in assuming that zUMIs detected valid barcode sequences, but there were not valid reads to map/use beyond that - hence such a large % of unused bc's?

**Comment by yxiao832** [comment]
I'd like to know how you solved your large % of unused bc. I am having the same issue. 
Thanks!
Yang

**Comment by cziegenhain** [comment]
Hi Yang,

Without any background information it's impossible to give a good hint.
Generally, large numbers of reads falling into unused barcodes can be due to: Problems in library preparation, low quality sequencing in barcode reads, wrong settings in barcode extraction.

As discussed above, it can make a difference to use automatic barcode detection vs giving a fixed number of expected barcodes in zUMIs, so check your output carefully.

**Comment by mbassalbioinformatics** [comment]
> I'd like to know how you solved your large % of unused bc. I am having the same issue.
> Thanks!
> Yang

In my case what I realised was that i didnt have all the fq files for the analysis.  I havent had a chance to re-run zumi's on the dataset with thew additional fq files included so I cant comment at the moment as to how much the % unused bc's went down, but I suspect by a fair bit.  So, as @cziegenhain said, without more background information its hard to give a more direct answer, but what i explained above seems to be the situation in my case... Ill post again when i get a chance to re-run zumi's.

**Comment by mbassalbioinformatics** [comment]
An additional point that ive realized is the threshold for the minimum number of reads for a barcode.  

So in the optional parameters shiny interface, the last item of "Barcode Options" is the min number of reads per cell barcode.  May need to play around with that to drop the unused bc percentage down.  You may need to go through the log files to see how many barcodes have low numbers of reads associated with them etc...
