### ISSUE TITLE
Mixed Species Use

### ISSUE THREAD

**Issue by dylanmr** [sdparekh/zUMIs#56]
Hi again, 

I am working on generating data from a split-seq mixed species experiment. I first renamed the mouse and human dna assembly fastas to differentiate the files and then concatenated. I then downloaded the matching GTF files, renamed the chromosomes and concatenated them. I then generated new STAR genome indices with the concatenated fasta file without splice junctions.  When I then attempt to run zUMIs I get through the filtering step but hit this error: 

project: mixed_species
sequence_files:
project: mixed_species
sequence_files:
  file1:
    name: /nfsdata/data/sc-splitseq/180403-splitseq_optimization/splitseq_dualspecies/fastq/splitseq_S1_R1_001.fastq.gz
    base_definition: cDNA(1-66)
  file2:
    name: /nfsdata/data/sc-splitseq/180403-splitseq_optimization/splitseq_dualspecies/fastq/splitseq_S1_R2_001.fastq.gz

 You provided these parameters:
 YAML file:	mixed_species.yaml
 zUMIs directory:		/raid5/projects/dylan/splitseq/zUMIs
 STAR executable		/projects/dylan/splitseq/star/star_for_zumis/STAR-2.5.4a/STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   0
 zUMIs version 2.0

Filtering...
[W::bam_merge_core2] No @HD tag found.
Mapping...
Error in data.table::fread(paste(samtools, "view", filtered_bam, "| cut -f10 | head -n 100"),  :
  File is empty: /tmp/Rtmpzztrfc/file82222aebfd6d
Execution [halted]

It looks as though the bam file is empty. I am unsure if you have any troubleshooting recommendations, but any help would be appreciated. I have also attached my yaml file
[mixed_species.txt](https://github.com/sdparekh/zUMIs/files/2302313/mixed_species.txt)

Best,
Dylan

**Comment by cziegenhain** [comment]
Hey Dylan,

this is odd! Your approach seems correct and the YAML looks nice. 
However, SPLiT-seq data tends to have a bit lower quality barcodes, since they are read only in the pair and quite long as well. Thus, it could be that simply none of the reads matched the BC filtering criteria.
It'd be useful to crosscheck that with FastQC too!

Meanwhile, try to run with this setting:
```
filter_cutoffs:
  BC_filter:
    num_bases: 6
    phred: 20
```

Hope this helps!
Best,
Christoph

**Comment by LittleFrogHill** [comment]
Hi Dylan,

I'm running the SPLIT-seq data from the science paper, and I remember the cutoff in supplement said "removed any dephased reads in our library (last 6 bases of read did not match the expected sequence). Reads were then filtered based on quality score in the UMI region. Any read with >1 low-quality base (phred <=10) were discarded."  

And I have a question, I download the mixed SPLIT-seq data from science data (human and mouse), should I cat the fq files together run zUMIs or run a single sample with the SRR number?

Best,
Shan Gao

**Comment by LittleFrogHill** [comment]
Hi Christoph,

Excellent! The SPLIT-seq data doesn't seem like the RNA-seq I ever analyzed. I have question, if it's necessary to clean the fq by trimmomatic? 

Also, a error I met yesterday, when STAR mapping, the 'EXITING because of fatal PARAMETERS error: present --sjdbOverhang=65 is not equal to the value at the genome generation step =100
SOLUTION:', I change the PARAMETERS to --sjdbOverhang=65 when I build the index for STAR, I hope it can be helpful to you.

Best,
Shan Gao

**Comment by cziegenhain** [comment]
Hey Shan Gao,

If you wish you can trim the cDNA read with trimmomatic, but for high quality data it should not be necessary. If I am concerned about adapter sequences, I usually just add adapter or poly-A clipping by STAR in zUMIs:
`additional_STAR_params: --clip3pAdapterSeq AAAAAAAAAAA`

For the genome generation, please leave out the --sjdbOverhang parameter, as described in the wiki: https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping

**Comment by LittleFrogHill** [comment]
Hi Christoph,

Thanks for the quick reply!I had ever leaved out this parameter, but my STAR seems default "--sjdbOverhang 100". So I have to use the "--sjdbOverhang 65", when I build the index. If you did not meet this problem, you just ignore what I say. I just want to share some experience to you.

Best,
Shan Gao

**Comment by cziegenhain** [comment]
Aha, okay I get it!
This could be a STAR version issue, it came up for another user before:
https://github.com/sdparekh/zUMIs/issues/52

**Comment by LittleFrogHill** [comment]
Hi Christoph,

A "Warning" turn to my log file, it makes the Rplots.pdf in my result broken.

tail of log file:
[bam_sort_core] merging from 60 files and 30 in-memory blocks...
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 873 barcodes in this chunk..."
[1] "2018-08-24 21:12:35 CST"
[1] "I am done!! Look what I produced.../home/Share01/GaoShan/zUMIs/zUMIs_SRR6750059/zUMIs_output/"
            used   (Mb) gc trigger    (Mb)   max used    (Mb)
Ncells   7781635  415.6   20417335  1090.5   49847012  2662.2
Vcells 557872918 4256.3 1641481170 12523.6 2051851442 15654.4
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-08-24 21:12:42 CST"
Warning messages:
1: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
3: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
4: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
Warning messages:
1: In bind_rows_(x, .id) : Unequal factor levels: coercing to character
2: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
3: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
4: In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
Warning message:
In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
            used   (Mb) gc trigger    (Mb)   max used    (Mb)
Ncells   1842537   98.5   20293757  1083.9   17327516   925.4
Vcells 148358974 1131.9 2100043451 16022.1 2607827140 19896.2

Best,
Shan Gao

**Comment by cziegenhain** [comment]
Hey,

that should all be fine! 
The Rplots.pdf file is just temporary and can be ignored. The actual output is in the zUMIs_output folder.

Since it seems like zUMIs is working for you now, I will close the issue  👍

**Comment by LittleFrogHill** [comment]
OK，thank you very much！




| |
邮箱：gaoshan30954@163.com
|

签名由 网易邮箱大师 定制

On 08/28/2018 21:28, cziegenhain wrote:

Hey,

that should all be fine!
The Rplots.pdf file is just temporary and can be ignored. The actual output is in the zUMIs_output folder.

Since it seems like zUMIs is working for you now, I will close the issue 👍
