### ISSUE TITLE
Error when running the new version 2.0

### ISSUE THREAD

**Issue by bgbrink** [sdparekh/zUMIs#57]
I just downloaded the new version of zUMIs and I appreciate the change towards using a yaml file. However, the new version produces an error on the same dataset where 0.0.6e would run fine. Here is the error log:

```
/work/project/ladsie_002/zUMIs/zUMIs-master.sh: line 8: [: !=: unary operator expected
[W::bam_merge_core2] No @HD tag found.
Error: subscript contains NAs
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/work/project/ladsie_002/analyses/2018-08-07_single_cell_seq/zUMIs2.0/zUMIs_output/expression/trypanosoma_scRNA.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```

I have been digging around in the folder to find a more detailed log, without success. The previous version had a -R option for enabling slurm scheduling, has that option been removed? With -R, one would get seperate error logs for individual steps, which would make debugging easier. Here, I am not sure where to look for the error. Maybe you could point me in the right direction?

By the way, the error in line 8 of zUMIs-master.sh can be avoided simply by using quotes on both sides of the comparison operator.

**Comment by cziegenhain** [comment]
Hey Benedikt,

sorry that you are having troubles with zUMIs2.

Not sure why you are getting this line 8 errors because it seems to run for me? 
But anyway thanks for the suggestion, I'll add some quotes in the next commit.

As for the -R option, yes it actually has been removed. We would recommend to just wrap the whole call for zUMIs in slurm with `sbatch -J myJob --wrap="zUMIs-master -y test.yaml"`

Now for the actual issue: I'm a bit puzzled whats happening there. Can you upload your YAML? Maybe the run also never started properly after this first exception? Also, there should be more verbose printed to standard out, so its a bit hard to check. Do you get a `*.filtered.tagged.bam` file with useful size?

Best,
Christoph

**Comment by bgbrink** [comment]
Hi Christoph,
thanks for the quick response! The line 8 error can be ignored, I just wanted to point it out because it's a quick fix.

Now for the zUMIs issue. I am running it on a cluster just as you described it and the mapping runs fine, i.e. I do get a `*.filtered.tagged.bam` with a useful size. The issue seems to be in the counting step, but I am not sure what happens exactly since I cannot seem to find the correct log files. I am pasting stdout and attaching the yaml file as well.

```
 You provided these parameters:
 YAML file:	/work/project/ladsie_002/analyses/2018-08-07_single_cell_seq/zUMIs2.0/zUMIs.yaml
 zUMIs directory:		/work/project/ladsie_002/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   128
 zUMIs version 2.0 


Filtering...
Mapping...
Aug 20 16:10:58 ..... started STAR run
Aug 20 16:10:58 ..... loading genome
Aug 20 16:10:59 ..... processing annotations GTF
Aug 20 16:11:00 ..... inserting junctions into the genome indices
Aug 20 16:11:07 ..... started 1st pass mapping
Aug 20 16:14:10 ..... finished 1st pass mapping
Aug 20 16:14:10 ..... inserting junctions into the genome indices
Aug 20 16:14:22 ..... started mapping
Aug 20 16:17:41 ..... finished successfully
Counting...
[1] "2018-08-20 16:17:51 CEST"
[1] "312 barcodes detected."
[1] "2400151 reads were assigned to barcodes that do not correspond to intact cells."
[1] "5.76e+08 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/work/project/ladsie_002/Tbrucei_Genomes/HGAP3_Tb427v9/HGAP3_Tb427v9.sorted.gtf"
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-08-20 16:17:57 CEST"
```


[zUMIs.yaml.zip](https://github.com/sdparekh/zUMIs/files/2305274/zUMIs.yaml.zip)

**Comment by cziegenhain** [comment]
Hey Benedikt, 

this all looks perfect to me. Just one hunch: Can you try to run using the counting option `introns: yes`? You will still get exon only counts too.

Fingers crossed!

**Comment by cziegenhain** [comment]
Hmm, that is very strange.
I found a bug for `introns: no` nevertheless but that should be okay now.

You don't get a `.tagged.Aligned.out.bam.ex.featureCounts.bam` file, right?

could you send me the output of:
`samtools view trypanosoma_scRNA.tagged.Aligned.out.bam | head`

**Comment by bgbrink** [comment]
I suppose you meant `trypanosoma_scRNA.filtered.tagged.Aligned.out.bam`? The 'unfiltered' file does not exist. Here is the output:

```
L183:428:CCJ1AANXX:1:1101:16619:94037	0	unitig_2311_Tb427v9	16128	0	50M	*	0	0	CCAACGGGGTGGGAACTTTTCGTTTCTTCTCCGGAGTCTTGTTTCGAGAC	CCCCCGCGG;EGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGF	NH:i:18	HI:i:1	AS:i:49	nM:i:0	BC:Z:TTTTGA	UB:Z:GTCTACTTCC
L183:428:CCJ1AANXX:1:1101:16650:94137	4	*	0	0	*	*	0	0	CTTTCCCTACACGACGCGGGGGTCCAAGAGAGTAGCACTGTTTGGGAATG	CCCCCGGGGGGGGGGGGGGGGCGGGGGGDGBFGGGGGG>FF>F@GGCFGGNH:i:0	HI:i:0	AS:i:29	nM:i:0	uT:A:1	BC:Z:TAATGA	UB:Z:GTGAACTTGG
L183:428:CCJ1AANXX:1:1101:16939:94038	0	unitig_1878_Tb427v9	17108	0	50M	*	0	0	TTTATATACAATACAATAATATTTTGTCCCTCTCCAAACGAGAGTACATG	CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGG	NH:i:19	HI:i:1	AS:i:49	nM:i:0	BC:Z:CATCAG	UB:Z:AATGTCCGCG
L183:428:CCJ1AANXX:1:1101:16961:94180	0	unitig_1884_Tb427v9	6233	0	50M	*	0	0	ACGTTACACCGTGTTGTTAGGAAAGTGAAGGTGGTCGGCGCACATCTCCC	BBCCCGGGGGGGGGGGGGGGGCGGGGGGGGGGGGGGGCGGGGGD>FGGGG	NH:i:7	HI:i:1	AS:i:47	nM:i:1	BC:Z:ATTGTT	UB:Z:CATTTACAAA
L183:428:CCJ1AANXX:1:1101:17196:94023	16	Chr11_core_Tb427v9	1798761	255	50M	*	0	0	GCTCTCCTTATTGGTCTCCCCCCGGCGTTTCGCATCCCGCTGTTTTGCCC	GDGGGDGDGEGGGD<GGG<AG<GGGGGGGGGGGGGGFGGGGGGGGCCCCC	NH:i:1	HI:i:1	AS:i:49	nM:i:0	BC:Z:GGTCAT	UB:Z:GGTAGAGATT
L183:428:CCJ1AANXX:1:1101:17095:94170	4	*	0	0	*	*	0	0	GTTCAGGGACAGTGCCTGATGGGTAGTTTAACTGGGGCGGTTGCCTCCCA	BCCCBGGGGGGGGGGGGGEGGGGGGGGGGGGGGGGGGGGFGGGGGEGGGGNH:i:0	HI:i:0	AS:i:13	nM:i:1	uT:A:1	BC:Z:CCTCGG	UB:Z:TGAATGGGCA
L183:428:CCJ1AANXX:1:1101:17217:94203	0	Chr9_core_Tb427v9	585096	255	50M	*	0	0	CTCGCGATGCATGCATAAGTACTAAAGGACAAACGAACGGCCGCCCCCGC	BBCCCG>GGGFGGGGEGGGGFGGGC>GGGGGGFGGGGGGBDGGDGGGGGG	NH:i:1	HI:i:1	AS:i:45	nM:i:2	BC:Z:TGGATT	UB:Z:GCGGGCTTCC
L183:428:CCJ1AANXX:1:1101:17389:94025	16	unitig_851_maxicircle_Tb427v9	12344	255	50M	*	0	0	AATAATAATACTCAGTATTGTAATTCCATTCATATTGGATATGCTAGTAC	GGGGGGGFGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGCCCCC	NH:i:1	HI:i:1	AS:i:47	nM:i:1	BC:Z:GCGCCA	UB:Z:ACGGGGAAAA
L183:428:CCJ1AANXX:1:1101:17462:94045	4	*	0	0	*	*	0	0	CTCCCCTAGTAGTGGCGAGCGAACGGGGACCAGCCGAGCCGTGAGAATGA	BCB@B<E>=@FGGCGDGGGGGDGGDGGF>GGGGGGGDG@DGBCGGGGGGGNH:i:0	HI:i:0	AS:i:12	nM:i:0	uT:A:1	BC:Z:TATAAG	UB:Z:TCACTGACCC
L183:428:CCJ1AANXX:1:1101:17308:94068	16	unitig_2456_Tb427v9	9017	0	50M	*	0	0	ATGTGCGCCGACCACCTTCACTTTCCTAACAAAACGGTGTAACGTTGTGC	FC@D@GGGGGGFFGGGFDF:FCGGGCGGFEE1==GGGGGGGGGGGBBBCC	NH:i:7	HI:i:1	AS:i:49	nM:i:0	BC:Z:TGGATT	UB:Z:TGTCGTTCTG
```

**Comment by sdparekh** [comment]
Hi Benedikt,

This is really strange and confusing. It would be great if you can send us test fastq files (maybe 1mio reads) and link to genome and GTF files so that we can test and debug easily.

If not, you could also just share the tagged.Aligned.out.bam with us to further investigate.

Best,
Swati

**Comment by cziegenhain** [comment]
Since this turned out to an issue with non-standard GTF files and shouldnt be a problem for other users, I am closing this issue.
