### ISSUE TITLE
reads -> umis

### ISSUE THREAD

**Issue by fxjonas** [sdparekh/zUMIs#58]
Dear zUMI team,

thanks for providing such a useful pipeline to the community. However, when doing some QC on my experiments I noticed that for some intron genes with reads>0, I get zero UMIs ..
I first suspected that the UMI quality of this read is too low and it's therefor not considered.. but actually, the filtering happens before the alignment.
Another explanation could be that the same UMI occurred in another read that aligned to another region, and it is therefore disregarded. 
Do you know what happened in this instances?
And do you mind telling me what happens to different gene same UMI pairs?

thx,
felix

**Comment by cziegenhain** [comment]
Hey Felix,

Thanks for your feedback. This sounds like it can be real. Given a Gene, you could have reads mapping to exons and introns. In the case that there are reads in introns that have new UMIs which were not seen yet in exons, this will be counted as intronic. However, it could also be that for the same UMI sequence for this particular gene you sample both exon and intron fragments. In this case it would be wrong to count it twice and zUMIs will consider this scenario as an exonic UMI.

Thus, I assume for your example there was no intronic UMI that was not also seen in exonic reads.

Hope this clears it up!

Best,

Christoph

**Comment by fxjonas** [comment]
yes, that sounds reasonable. I somehow think this is a little worry some, as it suggests that the 'exon read' is a genomic read which happened to be in an exonic region and not from cDNA.
Moreover, I still wanted to know what happens to the same UMI in different genes.

**Comment by cziegenhain** [comment]
Hmm, I think it depends on your method.
For many methods, you have preamplification of cDNA before fragmentation. Thus it is reasonably likely to obtain intronic and exonic fragments from unspliced mRNA molecules.

The same UMI can of course be independently sampled in different genes (likelihood entirely dependant on the length of the sequence), not sure what you are getting at there?

**Comment by cziegenhain** [comment]
It seems that dont have any further questions, so I will close this issue.

**Comment by hmassalha** [comment]
Dear Christoph,

So we have: 
1. exonic reads (coming from spliced and unspliced RNA)
2. intronic reads (coming only form the unspliced RNA, assuming that retained intronic fragments in the mature RNA resulted by alternative splicing are not important at this stage)

Can I use the intronic reads from the dgecounts file as an input for velocity unspliced layer? 
In the same way, can I use the exonic counts as the spliced layer of the loom file?

If this is the case, why zUMIs outputs a velocity BAM file and not a ready to use loom file? 

Thanks, HM

**Comment by cziegenhain** [comment]
Hi,

Please refer to #135 for this! The important part for RNA velocity are spliced & unspliced intron-exon junctions, this is different than the pure intron counts zUMIs makes!

The bam file is just a temporary file parsed to make zUMIs output compatible with velocyto. if everything can be run and the velocyto executable is present, you will obtain the loom file made by velocyto.
Best,
C

**Comment by hmassalha** [comment]
Thanks for your reply. 
How would the zUMIs count for the 'logic' used by velocyto [https://velocyto.org/velocyto.py/tutorial/cli.html#run-with-different-logics](url)

Thanks, 
HM

**Comment by cziegenhain** [comment]
The default logic is run.
In case the data doesn't contain UMIs, we set the `--without-umi` flag automatically.

**Comment by hmassalha** [comment]
Sorry Christoph, just updated my above comment. HM

**Comment by cziegenhain** [comment]
I think the sorted bam file should be fine!
I'll check if we can presort differently to make this step obsolete, seems like that should speed up the runtime
