### ISSUE TITLE
A error when try to run the example data set by zUMIs

### ISSUE THREAD

**Issue by zhangyj2017** [sdparekh/zUMIs#6]
Dear 
      We are learning to run zUMIs. But a error when try to run the example data set by zUMIs. Please help us to resolve it. Thanks very much.

johannes@johannes-linux[johannes] p='/home/johannes/zUMIs/'         [10:56上午]
johannes@johannes-linux[johannes] bash $p/zUMIs-master.sh -f $p/ExampleData/barcoderead_HEK.1mio.fq.gz -r $p/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 -g $p/reference/hg38_chr22/ -a $p/reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o $p/ExampleData/
Your jobs will run on this machine. 

Make sure you have more than 1.9G RAM and 8 processors available. 

Your jobs will be started from filtering. 

 You provided these parameters:
 SLURM workload manager:	no
 Summary Stats to produce:	yes
 Start the pipeline from:	filtering
 A custom mapped BAM:		NA
 Custom filtered FASTQ:		no
 Barcode read:			/home/johannes/zUMIs//ExampleData/barcoderead_HEK.1mio.fq.gz
 cDNA read:			/home/johannes/zUMIs//ExampleData/cDNAread_HEK.1mio.fq.gz
 Study/sample name:		chr22test
 Output directory:		/home/johannes/zUMIs//ExampleData/
 Cell/sample barcode range:	1-6
 UMI barcode range:		7-16
 Genome directory:		/home/johannes/zUMIs//reference/hg38_chr22/
 GTF annotation file:		/home/johannes/zUMIs//reference/GRCh38.84.chr22.gtf
 Number of processors:		8
 Read length:			50
 Strandedness:			0
 Cell barcode Phred:		20
 UMI barcode Phred:		20
 # bases below phred in CellBC:	1
 # bases below phred in UMI:	1
 Barcodes:			NA
 zUMIs directory:		/home/johannes/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 Additional STAR parameters:	
 STRT-seq data:			no
 Barcode read2(STRT-seq):	NA
 Barcode read2 range(STRT-seq):	0-0
 Bases(G) to trim(STRT-seq):	3
 Subsampling reads:		0 

Raw reads: 1000000 
Filtered reads: 853296 

/home/johannes/zUMIs/zUMIs-noslurm.sh: line 66: STAR: command not found
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file bam
sort: invalid option -- 'O'
sort: invalid option -- 'T'
open: No such file or directory
[bam_sort_core] fail to open file sam
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-09-28 10:57:58 CST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am loading Rsubread 1.26.0..."
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-09-28 10:58:02 CST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2017-09-28 10:58:05 CST"

ERROR: invalid parameter: '/home/johannes/zUMIs//ExampleData//chr22test.aligned.sorted.bam.in'

Error in file(file, "rt") : cannot open the connection
Calls: makeGEprofile -> featureCounts -> read.delim -> read.table -> file
In addition: Warning message:
In file(file, "rt") :
  cannot open file './.Rsubread_featureCounts_pid6312': No such file or directory
Execution halted
[1] "I am loading useful packages..."
[1] "2017-09-28 10:58:05 CST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/johannes/zUMIs//ExampleData//zUMIs_output/expression/chr22test.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
rm: cannot remove '/home/johannes/zUMIs//ExampleData//chr22test.Aligned.out.bam': No such file or directory

**Comment by cziegenhain** [comment]
Hey,

Thanks for using zUMIs!

It seems that you do not have STAR installed, which is required to map the reads to the genome. 

Please download STAR here:
https://github.com/alexdobin/STAR

If you do already have STAR, it is not found as "STAR" in your bin. You can use a custom path to STAR using the -e parameter in zUMIs. 
Check the according section of the usage Wiki for more information:
https://github.com/sdparekh/zUMIs/wiki/Usage

I'm closing the issue for now, but feel free to reopen when you encounter further problems.

Best,
Christoph
