### ISSUE TITLE
About the Example data

### ISSUE THREAD

**Issue by FatiaoNi** [sdparekh/zUMIs#60]
Hi,
I am a freshman on data analysis
When I run the Example data, there is some problem, please see the nohup attached
[nohup.zip](https://github.com/sdparekh/zUMIs/files/2335133/nohup.zip)

**Comment by sdparekh** [comment]
Your file does not seem to be a zip file or maybe it is corrupt. Can you please upload it again? I guess it is not that big, you could just upload it without zipping???

**Comment by FatiaoNi** [comment]
[nohup.out.txt](https://github.com/sdparekh/zUMIs/files/2335190/nohup.out.txt)

**Comment by sdparekh** [comment]
Hi, can you send us the following:

1) ex.yaml 
2) STAR final.log
3) ls -lha in zUMIs_output directory to see what outputs are generated

It seems no reads are assigned to features so we need to check if the mapping worked.

**Comment by cziegenhain** [comment]
I dont see an obvious problem yet, the STAR log is the `example.filtered.tagged.Log.final.out`
Also, what's your STAR version? `STAR --version`

**Comment by FatiaoNi** [comment]
T

his is the STAR
# packages in environment at /home/test/miniconda3:
#
star                      2.6.1a                        1    bioconda

and the STAR log is here,please check, Thank you!
                                 Started job on |	Aug 30 16:36:22
                             Started mapping on |	Aug 30 16:36:32
                                    Finished on |	Aug 30 16:36:36
       Mapping speed, Million of reads per hour |	767.97

                          Number of input reads |	853296
                      Average input read length |	1
                                    UNIQUE READS:
                   Uniquely mapped reads number |	0
                        Uniquely mapped reads % |	0.00%
                          Average mapped length |	0.00
                       Number of splices: Total |	0
            Number of splices: Annotated (sjdb) |	0
                       Number of splices: GT/AG |	0
                       Number of splices: GC/AG |	0
                       Number of splices: AT/AC |	0
               Number of splices: Non-canonical |	0
                      Mismatch rate per base, % |	-nan%
                         Deletion rate per base |	0.00%
                        Deletion average length |	0.00
                        Insertion rate per base |	0.00%
                       Insertion average length |	0.00
                             MULTI-MAPPING READS:
        Number of reads mapped to multiple loci |	0
             % of reads mapped to multiple loci |	0.00%
        Number of reads mapped to too many loci |	0
             % of reads mapped to too many loci |	0.00%
                                  UNMAPPED READS:
       % of reads unmapped: too many mismatches |	0.00%
                 % of reads unmapped: too short |	0.00%
                     % of reads unmapped: other |	100.00%
                                  CHIMERIC READS:
                       Number of chimeric reads |	0
                            % of chimeric reads |	0.00%

**Comment by FatiaoNi** [comment]
Maybe I have to check if the STAR works

**Comment by sdparekh** [comment]
`samtools view example.filtered.tagged.bam | head -n2` should tell us if the input bam file was created correctly. It looks like you do not pass cDNA reads to STAR.

**Comment by FatiaoNi** [comment]
Hi ! It works! 
But also have some difference in assigned reads

 You provided these parameters:
 YAML file:	ex.yaml
 zUMIs directory:		/home/test/NiJian/zUMIs/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   20
 zUMIs version 2.0.5 


Filtering...
Mapping...
Aug 30 19:06:31 ..... started STAR run
Aug 30 19:06:31 ..... loading genome
Aug 30 19:06:32 ..... processing annotations GTF
Aug 30 19:06:32 ..... inserting junctions into the genome indices
Aug 30 19:06:41 ..... started mapping
Aug 30 19:08:09 ..... finished successfully
Counting...
[1] "2018-08-30 19:08:19 CST"
[1] "78 barcodes detected."
[1] "8279 reads were assigned to barcodes that do not correspond to intact cells."
[1] "9e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/test/NiJian/zUMIs/test/reference/reference/GRCh38.84.chr22.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.5

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S example.filtered.tagged.Aligned.out.bam        ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid27497                 ||
||                 Summary : .Rsubread_featureCounts_pid27497.summary         ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid27497 (SAF)  ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid27497 ...         ||
||    Features : 26131                                                        ||
||    Meta-features : 1190                                                    ||
||    Chromosomes/contigs : 4                                                 ||
||                                                                            ||
|| Process BAM file example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 853296                                                    ||
||    Successfully assigned reads : 18619 (2.2%)                              ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.5

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S example.filtered.tagged.Aligned.out.bam        ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid27497                 ||
||                 Summary : .Rsubread_featureCounts_pid27497.summary         ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid27497 (SAF)  ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid27497 ...         ||
||    Features : 5737                                                         ||
||    Meta-features : 698                                                     ||
||    Chromosomes/contigs : 3                                                 ||
||                                                                            ||
|| Process BAM file example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 853296                                                    ||
||    Successfully assigned reads : 21725 (2.5%)                              ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 78 barcodes in this chunk..."
[1] "2018-08-30 19:08:53 CST"
[1] "I am done!! Look what I produced.../home/test/NiJian/zUMIs/test/output/zUMIs_output/"
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4706870 251.4    8273852 441.9  8273852 441.9
Vcells 5292698  40.4   13167806 100.5 13161209 100.5
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-08-30 19:08:54 CST"
Warning message:
In bind_rows_(x, .id) :
  binding character and factor vector, coercing into character vector
          used (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 1424395 76.1    2164898 115.7  2164898 115.7
Vcells 2186520 16.7    9767886  74.6 12209858  93.2

**Comment by cziegenhain** [comment]
That looks all good 👍 
Thanks for using zUMIs and hope that your own data runs just as fine.

**Comment by FatiaoNi** [comment]
Thank you!
The next step is my own data, and I also do single cell RNA-seq base on mcSCRB-seq!
