### ISSUE TITLE
yaml files

### ISSUE THREAD

**Issue by fxjonas** [sdparekh/zUMIs#61]
dear zUMI team, is there an option to omit the yaml file and run zUMI like previously?
While the yaml file is very good for consistency among the runs, it is troublesome to change it each time I want to run a new sample...

**Comment by cziegenhain** [comment]
Hey,

We as developers decided that the command line calls were getting too long for more complicated protocols, hence the switch to YAML.
Practically, you just need to change a couple of lines (project name & input file path) if you get new samples, so I think that's ok.

If not, the last version of command-line based zUMIs is available here: https://github.com/sdparekh/zUMIs/tree/zUMIs-version1 
Note that this branch will not receive updates.

Best,
Christoph
