### ISSUE TITLE
sjdbOverhang

### ISSUE THREAD

**Issue by FatiaoNi** [sdparekh/zUMIs#62]
Hi,
This time is my own data, when I construct the STAR index , the --sjdbOverhang 149 (my is paired-end 150pb )

Here is the erro.

EXITING because of fatal PARAMETERS error: present --sjdbOverhang=53 is not equal to the value at the genome generation step =149
SOLUTION: 

Aug 31 10:49:08 ...... FATAL ERROR, exiting

**Comment by FatiaoNi** [comment]
project: N_w_zUMIs
sequence_files:
  file1:
    name: /mnt/disk4/test/data/wl/w_R1.fastq.gz
    base_definition:
    - cDNA(49-102)
    - BC(1-6)
    - UMI(6-16)
  file2:
    name: /mnt/disk4/test/data/wl/w_R2.fastq.gz
    base_definition: cDNA(1-51)
reference:
  STAR_index: /mnt/disk4/test/reference/index/star/hg19
  GTF_file: /mnt/disk4/test/index0/Human/Homo_sapiens.GRCh38.84.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/test/NiJian/zUMIs/wl/output/
num_threads: 15
mem_limit: 20
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /home/test/NiJian/zUMIs/zUMIs
read_layout: PE

**Comment by cziegenhain** [comment]
As described in the wiki, please don't use a specific overhang in the genome generation step. 
https://github.com/sdparekh/zUMIs/wiki/Usage#preparing-star-index-for-mapping
Junctions will be inserted on the fly!

**Comment by FatiaoNi** [comment]
Sorry for the late reply,
Got it, and now it works!
Thanks a lot!

**Comment by sdparekh** [comment]
Awesome!! Then I close this issue :)
feel free to contact us if you have any questions.
All the best!
