### ISSUE TITLE
Any examples for split-seq 

### ISSUE THREAD

**Issue by niehu2018** [sdparekh/zUMIs#63]
Your "Protocol specific setup" part provides examples for sci-RNA-seq, can you give an example of split-seq?

Thanks!

**Comment by cziegenhain** [comment]
[Splitseq_example.txt](https://github.com/sdparekh/zUMIs/files/2345378/Splitseq_example.txt)
This worked on the public data from Rosenberg et al.

**Comment by niehu2018** [comment]
Thanks! @cziegenhain .

It seems that the author did not use the user-defined cell barcodes.

Since the barcode sequences of each round of ligation are known, they may be helpful to detect true cells.

What is your advice?

**Comment by cziegenhain** [comment]
I usually prefer the automatic barcode detection to directly filter for the relevant observed cells.
Especially with the large number of possible BCs in SPLiT-seq, you will have many many unobserved BC combinations.

Of course you can always backtrack if the automatically chosen BC sequence is an actual expected ligation combination.

**Comment by niehu2018** [comment]
Yes, I agree with you.

I have another question.

Reads with the same UMI and mapped to the same genomic location are considered as PCR duplicates. 

How does zUMI deal with duplication?

**Comment by cziegenhain** [comment]
We count the number of unqiue UMIs per gene per barcode.
The exact mapping position within the gene is not considered by zUMIs for several reasons.

**Comment by niehu2018** [comment]
Another question.

About base_definition for cDNA,

(I have PE150 data)

What if I want to use the whole cDNA read since I have removed the adapter sequences, 
how should I set the base_definition for cDNA?

**Comment by cziegenhain** [comment]
hey,

just go with cDNA(1-150) for the pure cDNA read.
zUMIs will take as many cDNA bases as available if the read is shorter than the given range.

**Comment by niehu2018** [comment]
How should I set the BarcodeBinning and Ham_Dist opts which control the distance between barcodes and the distance between umis to be binned separately?

In my experiment, the hamming distance between any two barcodes are at least 3, and the length of the umi is 10 bp, the length of the barcode is 24 bp.

**Comment by cziegenhain** [comment]
Hey,

I believe this depends on the actual quality of the data. 

UMI filtering:
In the zUMIs paper, we presented evidence how the base quality filtering takes care of most spurious UMIs. For long UMIs (eg 10 bases), it might still be interesting to do Ham_Dist. I never use values other than 0 (default) or 1. 

BC filtering:
Note that the BarcodeBinning functionality is not yet implemented in the current release of zUMIs. It will be added later.
Please observe the verbose as it will tell you how many reads are "lost" in uninformative barcodes. This is also visible in the statistics plots that zUMIs will output.


Is your data processing running through now without problemns? If so, we can close this issue.

Best,

Christoph

**Comment by niehu2018** [comment]
Hey, 
 
 Thanks to your guid, everything goes well.
Best

**Comment by cziegenhain** [comment]
Glad to hear that!
