### ISSUE TITLE
project_name.BCstats.txt does not exist

### ISSUE THREAD

**Issue by niehu2018** [sdparekh/zUMIs#64]
When zUMI started counting, an error occurred.

Please see the log file.
[log.txt](https://github.com/sdparekh/zUMIs/files/2346821/log.txt)

And the config file:

[split-seq.yaml.txt](https://github.com/sdparekh/zUMIs/files/2346834/split-seq.yaml.txt)

Below is the output directory: 
$ l outdir/
总用量 9.4G
-rw-rw-r-- 1 niehu niehu  71M 9月   4 01:09 MY-SPLIT2.BCstats.txt
-rw-rw-r-- 1 niehu niehu 5.7G 9月   4 02:17 MY-SPLIT2.filtered.tagged.Aligned.out.bam
-rw-rw-r-- 1 niehu niehu 3.7G 9月   4 01:07 MY-SPLIT2.filtered.tagged.bam
-rw-rw-r-- 1 niehu niehu 1.9K 9月   4 02:21 MY-SPLIT2.filtered.tagged.Log.final.out
-rw-rw-r-- 1 niehu niehu  30K 9月   4 02:21 MY-SPLIT2.filtered.tagged.Log.out
-rw-rw-r-- 1 niehu niehu 1.1K 9月   4 02:21 MY-SPLIT2.filtered.tagged.Log.progress.out
-rw-rw-r-- 1 niehu niehu  14M 9月   4 02:21 MY-SPLIT2.filtered.tagged.SJ.out.tab
drwx------ 2 niehu niehu  204 9月   4 02:01 MY-SPLIT2.filtered.tagged._STARgenome
-rw-rw-r-- 1 niehu niehu 1001 9月   4 01:09 MY-SPLIT2.postmap.yaml
drwxr-xr-x 4 niehu niehu   49 9月   4 01:09 zUMIs_output
-rw-r--r-- 1 niehu niehu  250 9月   4 00:20 zUMIs_runlog.txt

The MY-SPLIT2.BCstats.txt actually existed, however, it could not be found by zUMI?

And, How should  I  set the yaml file if I want to restart and skip the filter and alignment step?

**Comment by cziegenhain** [comment]
Hey,

[As written in the wiki](https://github.com/sdparekh/zUMIs/wiki/Setting-Mandatory-parameters-using-Shiny), please use full paths for all file and output locations in your YAML.

Relative paths can lead to these issues.

Set `which_Stage: Counting` for running just that step.
