### ISSUE TITLE
Per-Cell BAM File

### ISSUE THREAD

**Issue by DarioS** [sdparekh/zUMIs#65]
I request that it be possible to output a BAM file per cell after cell barcodes are error-corrected. It would facilitate the evaluation of the locations of read alignments to analyse alternative poly-A site usage, rather than just gene counting.

**Comment by cziegenhain** [comment]
Hey Dario,

Thanks for your feature request.
While we think about implementing this functionality, please use this short loop to produce the desired per-cell BC files from the zUMIs output.

```
sn=test
for i in `cut -d ',' -f1 zUMIs_output/"$sn"kept_barcodes.txt | grep -v 'XC'`; do
  cat <(samtools view -H $sn.filtered.tagged.Aligned.out.bam.ex.featureCounts.bam) <(samtools view -@ 4 $sn.filtered.tagged.Aligned.out.bam.ex.featureCounts.bam | grep "BC:Z:$i") | samtools view -b -@ 4 -o $sn.$i.bam
done
```

Let me know if this helps.

Best,
Christoph

**Comment by DarioS** [comment]
It looks good to me, but I was wondering why you filter on tag BC rather than CB. [CB](https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/output/bam) is the tag for "barcode sequence that is error-corrected and confirmed against a list of known-good barcode sequences".

**Comment by cziegenhain** [comment]
Hey,

CellRanger employs different tags than zUMIs. 

Let me know if you need further help.
