### ISSUE TITLE
example-low <Successfully assigned reads>

### ISSUE THREAD

**Issue by FatiaoNi** [sdparekh/zUMIs#66]
Hi,
I find when I run the examplel, the successfully assigned reads are low.

You provided these parameters:
 YAML file:	ex.yaml
 zUMIs directory:		/home/test/NiJian/zUMIs/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   20
 zUMIs version 2.0.5 

Filtering...
Mapping...
Sep 05 16:08:33 ..... started STAR run
Sep 05 16:08:33 ..... loading genome
Sep 05 16:08:37 ..... processing annotations GTF
Sep 05 16:08:37 ..... inserting junctions into the genome indices
Sep 05 16:08:46 ..... started mapping
Sep 05 16:10:16 ..... finished successfully
Counting...
[1] "2018-09-05 16:10:27 CST"
[1] "78 barcodes detected."
[1] "8279 reads were assigned to barcodes that do not correspond to intact cells."
[1] "9e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/home/test/NiJian/zUMIs/test/reference/reference/GRCh38.84.chr22.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.5

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S example.filtered.tagged.Aligned.out.bam        ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid3823                  ||
||                 Summary : .Rsubread_featureCounts_pid3823.summary          ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid3823 (SAF)   ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid3823 ...          ||
||    Features : 26131                                                        ||
||    Meta-features : 1190                                                    ||
||    Chromosomes/contigs : 4                                                 ||
||                                                                            ||
|| Process BAM file example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 853296                                                    ||
||    Successfully assigned reads : 18619 (2.2%)                              ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.5

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S example.filtered.tagged.Aligned.out.bam        ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid3823                  ||
||                 Summary : .Rsubread_featureCounts_pid3823.summary          ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid3823 (SAF)   ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 8                                                ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid3823 ...          ||
||    Features : 5737                                                         ||
||    Meta-features : 698                                                     ||
||    Chromosomes/contigs : 3                                                 ||
||                                                                            ||
|| Process BAM file example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 853296                                                    ||
||    Successfully assigned reads : 21725 (2.5%)                              ||
||    Running time : 0.01 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 78 barcodes in this chunk..."
[1] "2018-09-05 16:11:02 CST"
[1] "I am done!! Look what I produced.../home/test/NiJian/zUMIs/test/output/zUMIs_output/"
          used  (Mb) gc trigger  (Mb) max used  (Mb)
Ncells 4706901 251.4    8273852 441.9  8273852 441.9
Vcells 5293071  40.4   13168337 100.5 13161582 100.5
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-09-05 16:11:03 CST"

**Comment by sdparekh** [comment]
Hi, 
The example data is meant to test only if zUMIs with dependencies is installed well. To facilitate quick test, we have only uploaded one chromosome reference. It is normal that the assignment rate is low.

**Comment by FatiaoNi** [comment]
But I find that your example data is high

**Comment by FatiaoNi** [comment]
ok, got it, thank you!
