### ISSUE TITLE
Whitelist File Apparently Not a YAML Option

### ISSUE THREAD

**Issue by DarioS** [sdparekh/zUMIs#67]
Figure 1 of the journal article describing zUMIs suggests that it accepts a whitelist but I don't see any field of the YAML to specify it. I only see some reference to a whitelist in the Shiny application's R code. Could this be made consistent between the command line and graphical versions of the pipeline?

**Comment by cziegenhain** [comment]
Hey, 

for this use the `barcode_file:` field.
https://github.com/sdparekh/zUMIs/blob/master/zUMIs.yaml#L61

**Comment by DarioS** [comment]
I will.
