### ISSUE TITLE
Virtualization type on AWS

### ISSUE THREAD

**Issue by skannan4** [sdparekh/zUMIs#69]
Excited to test out zUMIs 2.0! I'm having problems ssh'ing into the new AMI (perhaps due to virtualization type) - could you perhaps switch the virtualization to HVM? Thanks!

**Comment by cziegenhain** [comment]
Hey,

sure, no problem. find the hvm type image as `zUMIs2.0-release-hvm` or `ami-05c223683acf98e82`

I think the AMI is a couple of bug fixes behind GitHub, so just run `git clone https://github.com/sdparekh/zUMIs.git` quickly before starting.

Best,

Christoph
