### ISSUE TITLE
Anothor mistake when running zUMIs

### ISSUE THREAD

**Issue by zhangyj2017** [sdparekh/zUMIs#7]
Dear
      When we running zUMIs， a mistake occured. Please help us to reslove it. Thanks very much.
Best wish 
Johannes
The mistake as follow:
johannes@johannes-linux[cutadapt_out] bash /home/johannes/zUMIs/zUMIs-master.sh -f cutadapt.2.fastq -r cutadapt.1.fastq -c 1-8 -b /home/johannes/linux/k562_first_sequence/clean_data/barcodes.txt -m 9-16 -l 150 -g /home/johannes/linux/ENSEMBL/genome_directory/ -a /home/johannes/linux/GTF/ensembl_GTF/Homo_sapiens.GRCh38.90.gtf -n kcell_1 -p 8 -o zUMIs_out/kcell_1 -e /home/johannes/STAR-2.5.3a/bin/Linux_x86_64/STAR -t /home/johannes/samtools-1.1/samtools
Your jobs will run on this machine.

Make sure you have more than 29G RAM and 8 processors available.

Your jobs will be started from filtering.

 You provided these parameters:
 SLURM workload manager:    no
 Summary Stats to produce:    yes
 Start the pipeline from:    filtering
 A custom mapped BAM:        NA
 Custom filtered FASTQ:        no
 Barcode read:            cutadapt.2.fastq
 cDNA read:            cutadapt.1.fastq
 Study/sample name:        kcell_1
 Output directory:        zUMIs_out/kcell_1
 Cell/sample barcode range:    1-8
 UMI barcode range:        9-16
 Genome directory:        /home/johannes/linux/ENSEMBL/genome_directory/
 GTF annotation file:        /home/johannes/linux/GTF/ensembl_GTF/Homo_sapiens.GRCh38.90.gtf
 Number of processors:        8
 Read length:            150
 Strandedness:            0
 Cell barcode Phred:        20
 UMI barcode Phred:        20
 # bases below phred in CellBC:    1
 # bases below phred in UMI:    1
 Barcodes:            /home/johannes/linux/k562_first_sequence/clean_data/barcodes.txt
 zUMIs directory:        /home/johannes/zUMIs
 STAR executable        /home/johannes/STAR-2.5.3a/bin/Linux_x86_64/STAR
 samtools executable        /home/johannes/samtools-1.1/samtools
 Additional STAR parameters:   
 STRT-seq data:            no
 Barcode read2(STRT-seq):    NA
 Barcode read2 range(STRT-seq):    0-0
 Bases(G) to trim(STRT-seq):    3
 Subsampling reads:        0

Raw reads: 6505595
Filtered reads: 4534605

Oct 11 09:58:27 ..... started STAR run
Oct 11 09:58:28 ..... loading genome
Oct 11 10:01:10 ..... processing annotations GTF
Oct 11 10:01:24 ..... inserting junctions into the genome indices
Oct 11 10:11:57 ..... started 1st pass mapping
Oct 11 10:42:39 ..... finished 1st pass mapping
Oct 11 10:42:42 ..... inserting junctions into the genome indices
Oct 11 11:01:57 ..... started mapping
Oct 11 11:43:00 ..... finished successfully
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2017-10-11 11:44:10 CST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
[1] "I am loading Rsubread 1.26.0..."
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2017-10-11 11:44:19 CST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
'select()' returned 1:many mapping between keys and columns
Error in gzfile(file, mode) : cannot open the connection
Calls: saveRDS -> gzfile
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file 'zUMIs_out/kcell_1/zUMIs_output/expression/kcell_1.annotationsSAF.rds', probable reason 'No such file or directory'
Execution halted
[1] "I am loading useful packages..."
[1] "2017-10-11 11:45:25 CST"
Warning message:
In is.na(x[[i]]) :
  is.na() applied to non-(list or vector) of type 'environment'
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'zUMIs_out/kcell_1/zUMIs_output/expression/kcell_1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by cziegenhain** [comment]
Hey Johannes,

The mapping seems to have run fine.
However, it seems there is a problem writing the output files. "zUMIs_out/kcell_1/zUMIs_output/expression/kcell_1.annotationsSAF.rds', probable reason 'No such file or directory"
Since I don't know your directory structure, I suggest you try to run zUMIs giving an absolute path for an existing output directory. (eg -o /home/johannes/yourfolder/)

I'm closing the issue, but feel free to reopen it if this doesn't solve your problem.

**Comment by cziegenhain** [comment]
FYI: We just updated  zUMIs to automatically deal with relative paths and convert them in absolute path.
