### ISSUE TITLE
Error at split step

### ISSUE THREAD

**Issue by bioysu** [sdparekh/zUMIs#70]
I tried to run zUMI with example data. But I got error at split step.
Could you tell me how to fix the problem?

Here is the output:
You provided these parameters:
 YAML file:	/data/suyao/tools/zUMIs/ExampleData/test.yaml
 zUMIs directory:		/data/suyao/tools/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   10
 zUMIs version 2.0 

Filtering...
split: unrecognized option '--filter=pigz -p 20 > $FILE.gz'
Try `split --help' for more information.
ls: cannot access /data/suyao/tools/zUMIs/ExampleData/test_output/zUMIs_output/.tmpMerge/cDNAread_HEK.1mio.fq*: No such file or directory
split: unrecognized option '--filter=pigz -p 20 > $FILE.gz'
Try `split --help' for more information.
ls: cannot access /data/suyao/tools/zUMIs/ExampleData/test_output/zUMIs_output/.tmpMerge/barcoderead_HEK.1mio.fq*: No such file or directory
ls: cannot access /data/suyao/tools/zUMIs/ExampleData/test_output/zUMIs_output/.tmpMerge/barcoderead_HEK.1mio.fq*: No such file or directory
ls: cannot access /data/suyao/tools/zUMIs/ExampleData/test_output/zUMIs_output/.tmpMerge//test.*.filtered.tagged.bam: No such file or directory

**Comment by sdparekh** [comment]
Hi, 
Can you please let us know which OS are you using? It might be that you have a different "split".

**Comment by bioysu** [comment]
I have update 'split' by installing new version of coreutils. The problem is fixed now.

**Comment by cziegenhain** [comment]
Fantastic. 
Hope you are enjoying zUMIs and let us know if you encounter further problems!
