### ISSUE TITLE
zUMIs stuck at Filtering stage 

### ISSUE THREAD

**Issue by ghoshal** [sdparekh/zUMIs#73]
Hi,

I am running zUMIs on Centos now using 80 threads and 202 GB memory. The program starts running and then just keep splitting the fastq file in the .tmpMerge directory. It has been over 6 hours now adn the program will be timed out at 24 hours, so I am not sure if we can get past the mapping stage by that time. Is this normal?

Also, I have multiple samples from the split seq protocol. I am guessing I need separate YAML files for each sample, is that correct?

Thanks,

Bibaswan

**Comment by cziegenhain** [comment]
Hey Bibaswan,

No this sounds entirely odd. The filtering step should use only minimal RAM and also only occupy as many cores as you specified in your YAML! 

it's correct that it starts splitting the fastq files into the temporary folder, the length of this step only depending on the amount of reads that you have in your files. My recent stress-test on ~4.5 billion reads finished filtering in about 16hours.

Could you check which process exactly goes crazy on resources like that using htop or similar?

**Comment by cziegenhain** [comment]
For your second question: if your different samples are using unique barcodes or can be distinguished by an additional illumina barcode read, you can concatenate the fastq files and run zUMIs for that. Otherwise you should start one job per sample as you suggested.

**Comment by ghoshal** [comment]
Hi,

I have around 38 million reads. It has been ~12 hours and it is still splitting the files. I checked htop and no large process is running just bash and it is not taking a lot of memory at all.

**Comment by sdparekh** [comment]
Hey, could you share your yaml file, verbose printed while running zUMIs and the zUMIs command you are using? I now tried with ~124mio reads and it seems to work.

**Comment by ghoshal** [comment]
Hi,

Here is the YAML file:

###########################################
#Welcome to zUMIs
#below, please fill the mandatory inputs
#We expect full paths for all files.
###########################################

#define a project name that will be used to name output files
project:sample_0078

#Sequencing File Inputs:
#For each input file, make one list object & define path and barcode ranges
#base definition vocabulary: BC(n) UMI(n) cDNA(n).
#Barcode range definition needs to account for all ranges. You can give several comma-separated ranges for BC & UMI se
quences, eg. BC(1-6,20-26)
#you can specify between 1 and 4 input files
sequence_files:
  file1:
    name: /project/l/ltri2014/bghoshal/September_2018/Seda/samples/BC_0078_R1.fastq.gz
    base_definition:
      - cDNA(1-66)
  file2: 
    name: /project/l/ltri2014/bghoshal/September_2018/Seda/samples/BC_0078_R1.fastq.gz
    base_definition:
      - UMI(1-10)
      - BC(11-18, 49-56, 87-94)

#reference genome setup
reference:
  STAR_index: /scratch/w/wrana/bghoshal/mm10/star_indices
  GTF_file: /scratch/w/wrana/bghoshal/mm10/annotation/Mus_musculus.GRCm38.77.gtf 
  additional_files: #Optional parameter. It is possible to give additional reference sequences here, eg ERCC.fa
  additional_STAR_params: #Optional parameter. you may add custom mapping parameters to STAR here

#output directory
out_dir: /project/l/ltri2014/bghoshal/September_2018/Seda/samples/sample_0078

###########################################
#below, you may optionally change default parameters
###########################################

#number of processors to use
num_threads: 80
mem_limit: null #Memory limit in Gigabytes, null meaning unlimited RAM usage.

#barcode & UMI filtering options
#number of bases under the base quality cutoff that should be filtered out.
#Phred score base-cutoff for quality control.
filter_cutoffs:
  BC_filter:
    num_bases: 2
    phred: 10
  UMI_filter:
    num_bases: 2
    phred: 10

#Options for Barcode handling
#You can give either number of top barcodes to use or give an annotation of cell barcodes.
#If you leave both barcode_num and barcode_file empty, zUMIs will perform automatic cell barcode selection for you!
barcodes:
  barcode_num: null
  barcode_file: null
  BarcodeBinning: 0 #Hamming distance binning of close cell barcode sequences. ATTENTION! This option is currently not
 implemented!
  nReadsperCell: 50 #Keep only the cell barcodes with atleast n number of reads.

#Options related to counting of reads towards expression profiles
counting_opts:
  introns: yes #can be set to no for exon-only counting.
  downsampling: 0 #Number of reads to downsample to. This value can be a fixed number of reads (e.g. 10000) or a desir
ed range (e.g. 10000-20000) Barcodes with less than <d> will not be reported. 0 means adaptive downsampling. Default: 
0.
  strand: 0 #Is the library stranded? 0 = unstranded, 1 = positively stranded, 2 = negatively stranded
  Ham_Dist: 0 #Hamming distance collapsing of UMI sequences.
  velocyto: no #Would you like velocyto-compatible counting of intron-exon spanning reads
  primaryHit: yes #Do you want to count the primary Hits of multimapping reads towards gene expression levels?
  twoPass: yes #perform basic STAR twoPass mapping

#produce stats files and plots?
make_stats: yes


#Start zUMIs from stage. Possible TEXT(Filtering, Mapping, Counting, Summarising). Default: Filtering.
which_Stage: Filtering

#below, the fqfilter will add a read_layout flag defining SE or PE
samtools_exec: samtools
pigz_exec: pigz
STAR_exec: STAR
zUMIs_directory: /gpfs/fs0/scratch/w/wrana/bghoshal/software/zUMIs

This is the output from the log file.
 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------


 You provided these parameters:
 YAML file:	zUMIs_0078.yaml
 zUMIs directory:		/gpfs/fs0/scratch/w/wrana/bghoshal/software/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.0.6 


Filtering...


This is the command that I ran.
bash /scratch/w/wrana/bghoshal/software/zUMIs/zUMIs-master.sh -y zUMIs_0078.yaml

**Comment by sdparekh** [comment]
I see that you have specified the same fastq file for file1 and file2. Could you correct that and run it again?

**Comment by ghoshal** [comment]
Thanks. Didn't even notice. I have rerun the samples with that updated. Will let you know if it runs.

**Comment by ghoshal** [comment]
Hi,

I ran it again with the correct filename and all the files look exactly the same as above. It is splitting the files in the .tpmMerge directory. According to your tests how long should this step take?

**Comment by cziegenhain** [comment]
Hmm it's odd. I'd expect it to finish in about 15 minutes or so for so few reads. 
Can you check if the file sizes are actually increasing in there `ls -sha .tmpMerge` ?

**Comment by ghoshal** [comment]
All filesizes looks to be zero.

**Comment by cziegenhain** [comment]
Right, something is not working there as it should. Could you confirm that pigz is correctly installed on the cluster you are using?

**Comment by ghoshal** [comment]
Yes pigz is installed correctly.

pigz --version
pigz 2.3.4

**Comment by ghoshal** [comment]
As soon as I run the program, pigz and split starts running in the processes which means the the program is successfully calling these.

**Comment by sdparekh** [comment]
Could you share your data? Maybe sub-sampled to 100,000 reads or such? We can not reproduce your issue.

**Comment by ghoshal** [comment]
Yes sure. How do I share? Can I get an email?

**Comment by ghoshal** [comment]
I have sent it

**Comment by sdparekh** [comment]
I have not received any email!!

**Comment by ghoshal** [comment]
I have sent the email to hellmann@bio.lmu.de <hellmann@bio.lmu.de> email.

**Comment by ghoshal** [comment]
Sorry I have resent it to your email. I realized I had mistakenly sent it to the corresponding author email.

**Comment by ghoshal** [comment]
Hi,

I created a virtual box instance with Ubuntu and installed zUMIs and all its dependancies and ran with the trial samples that I had sent you. With this went past the Filtering... line and got the following error.

<pre>You provided these parameters:
 YAML file:	trial_zumis.yaml
 zUMIs directory:		/home/biba/Downloads/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.0.6 


Filtering...
/home/biba/Downloads/zUMIs/splitfq.sh: line 41: /home/biba/Downloads/trial/trial_0077/zUMIs_output/.tmpMerge///home/biba/Downloads/trial/trial_77_R1.fastq.gz.listPrefix.txt: No such file or directory
/home/biba/Downloads/zUMIs/splitfq.sh: line 41: /home/biba/Downloads/trial/trial_0077/zUMIs_output/.tmpMerge///home/biba/Downloads/trial/trial_77_R1.fastq.gz.listPrefix.txt: No such file or directory
/home/biba/Downloads/zUMIs/splitfq.sh: line 41: /bin/ls: Argument list too long
/home/biba/Downloads/zUMIs/splitfq.sh: line 41: /bin/ls: Argument list too long
/home/biba/Downloads/zUMIs/zUMIs-master.sh: line 149: /bin/ls: Argument list too long
/home/biba/Downloads/zUMIs/mergeBAM.sh: line 14: /home/biba/Downloads/trial/trial_0077/zUMIs_output/.tmpMerge///home/biba/Downloads/trial/trial_0077.bamlist.txt: No such file or directory
/home/biba/Downloads/zUMIs/mergeBAM.sh: line 17: trial_zumis.yaml//home/biba/Downloads/trial/trial_0077.BCstats.txt: Not a directory
head: cannot open &apos;/home/biba/Downloads/trial/trial_0077/zUMIs_output/.tmpMerge///home/biba/Downloads/trial/trial_0077.bamlist.txt&apos; for reading: No such file or directory

Please let me know what you think.

**Comment by ghoshal** [comment]
I checked ls -hsa .tmpMerge and all of the files are 4.0 k in size

**Comment by cziegenhain** [comment]
Hey,

I tried your test data on our ubuntu server and it went fine within seconds - attached the YAML i used for reference.
You had some whitespace in the barcode base definition that was problematic but that didn't hang the jobs like this.
 
For the errors you got from the virtual box, can you try with less threads specified? Although 80 works for me it could be related to that.

Also, can you check your coreutils version? `apt-cache policy coreutils` Another user reported a problem with his too old version of the `split` command recently.


I hope we get to the bottom of this issue soon so you can use zUMIs.

[test.yaml.txt](https://github.com/sdparekh/zUMIs/files/2408694/test.yaml.txt)

**Comment by ghoshal** [comment]
Thanks a lot for trying the data out. Here is the coreutils output.

coreutils:
  Installed: 8.28-1ubuntu1
  Candidate: 8.28-1ubuntu1
  Version table:
 *** 8.28-1ubuntu1 500
        500 http://ca.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status

I ran this in the cluster environment and Ubuntu virtual box and both are getting stuck. I need to run this on the cluster since there are 400M reads from 7 samples which the virtualbox won't be able to handle.

**Comment by ghoshal** [comment]
Somehow I am also getting a feeling the zUMIs pipeline I am running is not calling for the Rscript as well since no Rscript_exec line getting added in the yaml file. Also, should the yaml file be input as a .txt file?

**Comment by ghoshal** [comment]
Also, I had "curl" missing from the Ubuntu VM and after I installed it the previous errors were not there. It was just back in getting stuck at Filtering.

**Comment by sdparekh** [comment]
Can you try just splitting without running in zUMIs.
split --lines=1000000 --filter='pigz -p 10 > $FILE.gz' yourinput.fastq.gz someprefix

**Comment by ghoshal** [comment]
These are the files created from the full R1.fastq.gz file.

-rw-r--r-- 1 bghoshal ltri2014  231951799 Sep 23 21:23 ABCDaa.gz
-rw-r--r-- 1 bghoshal ltri2014  232005492 Sep 23 21:23 ABCDab.gz
-rw-r--r-- 1 bghoshal ltri2014  232271600 Sep 23 21:23 ABCDac.gz
-rw-r--r-- 1 bghoshal ltri2014  231444249 Sep 23 21:23 ABCDad.gz
-rw-r--r-- 1 bghoshal ltri2014  229939129 Sep 23 21:23 ABCDae.gz
-rw-r--r-- 1 bghoshal ltri2014  230003914 Sep 23 21:23 ABCDaf.gz
-rw-r--r-- 1 bghoshal ltri2014  230955720 Sep 23 21:23 ABCDag.gz
-rw-r--r-- 1 bghoshal ltri2014  230279732 Sep 23 21:23 ABCDah.gz
-rw-r--r-- 1 bghoshal ltri2014   53929730 Sep 23 21:23 ABCDai.gz

My friend merged the R1 and R2 in one file and ran zUMIs and it ran for them. I tried the split on one file and it worked fast as well.

**Comment by ghoshal** [comment]
One thing I thought pertinent to be mentioned here is that the filenames of the output of the Filtering step in .tmpMerge is 
   0 -rw-r--r-- 1 bghoshal ltri2014  153 Sep 23 22:33 trial_77_R2.fastqzisc.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  137 Sep 23 22:33 trial_77_R2.fastqzisd.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  136 Sep 23 22:33 trial_77_R2.fastqzise.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  154 Sep 23 22:33 trial_77_R2.fastqzisf.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  159 Sep 23 22:33 trial_77_R2.fastqzish.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  156 Sep 23 22:33 trial_77_R2.fastqzisi.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  158 Sep 23 22:33 trial_77_R2.fastqzisj.gz
   0 -rw-r--r-- 1 bghoshal ltri2014  163 Sep 23 22:33 trial_77_R2.fastqziso.gz

This is different from the output of the split step where the someprefix.fastq.gz was the output.

**Comment by cziegenhain** [comment]
Hey,

I just went through some older issues with zUMIs, it looks like you are missing a space after  the colon in the `project_name` definition in the yaml.

I think this should solve your issue!
I'll talk to Swati to make this a bit more failsafe in a future update.

**Comment by ghoshal** [comment]
It worked. Finally!!!! Thanks a lot for sticking with me. An absence of a space kept me working for the last week. I can't thank you enough.

**Comment by cziegenhain** [comment]
Great that it worked now! 
Let us know if we can help further.

**Comment by ghoshal** [comment]
I have a question outside of this error actually. We want to allow for 1 mismatch in each of the three barcodes for better barcode mapping. Is there a way to allow for this?

**Comment by cziegenhain** [comment]
Sorry unfortunately the addition of adjacent barcodes with a set hamming distance is currently not implemented yet. We'll have this in an update once we have coded up a good solution.
