### ISSUE TITLE
Error in Counting step

### ISSUE THREAD

**Issue by ghoshal** [sdparekh/zUMIs#74]
Hi,

I got this error in the Counting step. I check and data.table is installed properly in R. 

Counting...
[1] "2018-09-24 11:32:11 EDT"
Error in mvnX(data = data, prior = prior) : data must be one dimensional
Calls: cellBC ... eval -> eval -> mclustBIC -> mvn -> eval -> eval -> mvnX
Execution halted
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-09-24 11:32:13 EDT"
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/project/l/ltri2014/bghoshal/September_2018/Seda/samples/sample_0077/zUMIs_output/sample_0077kept_barcodes.txt
' does not exist or is non-readable. getwd()=='/gpfs/fs0/project/l/ltri2014/bghoshal/September_2018/Seda/samples/sampl
e_0077'
Execution halted

Thanks,

Bibaswan

**Comment by ghoshal** [comment]
Also, when I checked the BC_stats.txt, I got this output. 

head sample_0077/sample_0077.BCstats.txt 
	590920
	590802
	590772
	590717
	590702
	590642
	590701
	590891
	590736
	590796

There are no detected barcodes and just numbers and I think that is causing the problem. When I give a file of all barcode combinations then this is what it returns.

Counting...
[1] "2018-09-24 12:39:33 EDT"
[1] "Warning! None of the annotated barcodes were detected."
[1] "Less than 100 barcodes present, will continue with all barcodes..."
[1] " reads were assigned to barcodes that do not correspond to intact cells."
[1] "Inf Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/scratch/w/wrana/bghoshal/mm10/annotation/Mus_musculus.GRCm38.77.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"
[bam_sort_core] merging from 0 files and 40 in-memory blocks...
[bam_sort_core] merging from 0 files and 40 in-memory blocks...
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 1 barcodes in this chunk..."
Error in bmerge(i, x, leftcols, rightcols, io, xo, roll, rollends, nomatch,  : 
  x.'RG' is a character column being joined to i.'XC' which is type 'logical'. Character columns must join to factor o
r character columns.
Calls: collectCounts ... .sampleReads4collapsing -> [ -> [.data.table -> bmerge
Execution halted
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-09-24 12:47:13 EDT"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/project/l/ltri2014/bghoshal/September_2018/Seda/samples/sample_0077/zUMIs_output/expre
ssion/sample_0077.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

**Comment by ghoshal** [comment]
I solved this issue. I gave spaces after the comma with the Barcode locations. 

However, it gave me an error in the last step while plotting.

Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed
Calls: <Anonymous> ... as -> .class1 -> .TM.repl.i.mat -> [<- -> [<- -> int2i
In addition: Warning message:
In int2i(as.integer(i), n) : NAs introduced by coercion to integer range
Execution halted

**Comment by cziegenhain** [comment]
hey Bibaswan,

good that you found the first error! Sorry I had spotted your problem with the spaces before but must have not stated that clearly enough in one of the replies in the earlier conversation ( https://github.com/sdparekh/zUMIs/issues/73#issuecomment-423812135 ) 

For the plotting issue, could you attach the full verbose (stdout and stderr) of your zUMIs call up until that point? Not quite clear to me yet where it breaks.

**Comment by sdparekh** [comment]
What also helps is `ls -lha zUMIs_output/`. so that we can see which results are printed and where it breaks.

**Comment by ghoshal** [comment]
This is the output of the stdout and stderr

------------- 

 Good news! A newer version of zUMIs is available at https://github.com/sdparekh/zUMIs 

-------------


 You provided these parameters:
 YAML file:	zUMIs_0077.yaml
 zUMIs directory:		/gpfs/fs0/scratch/w/wrana/bghoshal/software/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.0.6 


Filtering...
Mapping...
Sep 24 16:39:55 ..... started STAR run
Sep 24 16:39:55 ..... loading genome
Sep 24 16:40:04 ..... processing annotations GTF
Sep 24 16:40:21 ..... inserting junctions into the genome indices
Sep 24 16:41:39 ..... started 1st pass mapping
Sep 24 16:46:20 ..... finished 1st pass mapping
Sep 24 16:46:21 ..... inserting junctions into the genome indices
Sep 24 16:47:51 ..... started mapping
Sep 24 16:52:47 ..... finished successfully
Counting...
[1] "2018-09-24 16:53:05 EDT"
[1] "24789595 reads were assigned to barcodes that do not correspond to intact cells."
[1] "Inf Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/scratch/w/wrana/bghoshal/mm10/annotation/Mus_musculus.GRCm38.77.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S 77.filtered.tagged.Aligned.out.bam             ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid232237                ||
||                 Summary : .Rsubread_featureCounts_pid232237.summary        ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid232237 ( ... ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 64                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid232237 ...        ||
||    Features : 653441                                                       ||
||    Meta-features : 37666                                                   ||
||    Chromosomes/contigs : 58                                                ||
||                                                                            ||
|| Process BAM file 77.filtered.tagged.Aligned.out.bam...                     ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 47250423                                                  ||
||    Successfully assigned reads : 6019585 (12.7%)                           ||
||    Running time : 0.12 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[1] "Assigning reads to features (in)"

        ==========     _____ _    _ ____  _____  ______          _____  
        =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \ 
          =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
            ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
              ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
        ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
       Rsubread 1.30.6

//========================== featureCounts setting ===========================\\
||                                                                            ||
||             Input files : 1 BAM file                                       ||
||                           S 77.filtered.tagged.Aligned.out.bam             ||
||                                                                            ||
||             Output file : .Rsubread_featureCounts_pid232237                ||
||                 Summary : .Rsubread_featureCounts_pid232237.summary        ||
||              Annotation : .Rsubread_UserProvidedAnnotation_pid232237 ( ... ||
||      Assignment details : <input_file>.featureCounts.bam                   ||
||                      (Note that files are saved to the output directory)   ||
||                                                                            ||
||      Dir for temp files : .                                                ||
||                 Threads : 64                                               ||
||                   Level : meta-feature level                               ||
||              Paired-end : yes                                              ||
||         Strand specific : no                                               ||
||      Multimapping reads : not counted                                      ||
||     Multiple alignments : primary alignment only                           ||
|| Multi-overlapping reads : not counted                                      ||
||   Min overlapping bases : 1                                                ||
||                                                                            ||
||          Chimeric reads : not counted                                      ||
||        Both ends mapped : not required                                     ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

//================================= Running ==================================\\
||                                                                            ||
|| Load annotation file .Rsubread_UserProvidedAnnotation_pid232237 ...        ||
||    Features : 217428                                                       ||
||    Meta-features : 23727                                                   ||
||    Chromosomes/contigs : 51                                                ||
||                                                                            ||
|| Process BAM file 77.filtered.tagged.Aligned.out.bam...                     ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 47250423                                                  ||
||    Successfully assigned reads : 5002691 (10.6%)                           ||
||    Running time : 0.12 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

[bam_sort_core] merging from 0 files and 40 in-memory blocks...
[bam_sort_core] merging from 0 files and 40 in-memory blocks...
[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 274190 barcodes in this chunk..."
[1] "2018-09-24 17:31:27 EDT"
[1] "I am done!! Look what I produced.../project/l/ltri2014/bghoshal/September_2018/Seda/samples/sample_0077/zUMIs_out
put/"
           used  (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells  7699599 411.3   22225392 1187.0  22225392 1187.0
Vcells 81516461 622.0  169393587 1292.4 169393586 1292.4
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-09-24 17:31:30 EDT"
Error in if (any(i < 0L)) { : missing value where TRUE/FALSE needed
Calls: <Anonymous> ... as -> .class1 -> .TM.repl.i.mat -> [<- -> [<- -> int2i
In addition: Warning message:
In int2i(as.integer(i), n) : NAs introduced by coercion to integer range
Execution halted
Finished zUMIs run with exit code 1 at: Mon Sep 24 17:32:14 EDT 2018


Here is the output of ls -lha

drwxr-sr-x 4 bghoshal ltri2014 4.0K Sep 24 16:54 .
drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
-rw-r--r-- 1 bghoshal ltri2014 9.1M Sep 24 16:54 77kept_barcodes.txt
-rw-r--r-- 1 bghoshal ltri2014 6.6M Sep 24 17:21 .currentRGgroup.txt
drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:31 expression
-rw-r--r-- 1 bghoshal ltri2014   27 Sep 24 12:39 sample_0077kept_barcodes.txt
drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:21 stats

**Comment by ghoshal** [comment]
Hi,

Here's the output for both the project and zUMIs_output directories.

719M -rw-r--r-- 1 bghoshal ltri2014 719M Sep 24 16:39 77.BCstats.txt
3.3G -rw-r--r-- 1 bghoshal ltri2014 3.3G Sep 24 16:52 77.filtered.tagged.Aligned.out.bam
2.9G -rw-r--r-- 1 bghoshal ltri2014 2.9G Sep 24 17:21 77.filtered.tagged.Aligned.out.bam.ex.featureCounts.bam
2.9G -rw-r--r-- 1 bghoshal ltri2014 2.9G Sep 24 17:21 77.filtered.tagged.Aligned.out.bam.in.featureCounts.bam
2.2G -rw-r--r-- 1 bghoshal ltri2014 2.2G Sep 24 16:39 77.filtered.tagged.bam
   0 -rw-r--r-- 1 bghoshal ltri2014 1.9K Sep 24 16:52 77.filtered.tagged.Log.final.out
 27M -rw-r--r-- 1 bghoshal ltri2014  27M Sep 24 16:52 77.filtered.tagged.Log.out
   0 -rw-r--r-- 1 bghoshal ltri2014 1.4K Sep 24 16:52 77.filtered.tagged.Log.progress.out
3.0M -rw-r--r-- 1 bghoshal ltri2014 2.8M Sep 24 16:52 77.filtered.tagged.SJ.out.tab
   0 -rw-r--r-- 1 bghoshal ltri2014 1.3K Sep 24 16:39 77.postmap.yaml
   0 -rw-r--r-- 1 bghoshal ltri2014  640 Sep 24 12:26 sample_0077.BCstats.txt
2.7G -rw-r--r-- 1 bghoshal ltri2014 2.7G Sep 24 12:39 sample_0077.filtered.tagged.Aligned.out.bam
2.4G -rw-r--r-- 1 bghoshal ltri2014 2.4G Sep 24 12:44 sample_0077.filtered.tagged.Aligned.out.bam.ex.featureCounts.bam
2.4G -rw-r--r-- 1 bghoshal ltri2014 2.4G Sep 24 12:44 sample_0077.filtered.tagged.Aligned.out.bam.in.featureCounts.bam
1.8G -rw-r--r-- 1 bghoshal ltri2014 1.8G Sep 24 12:26 sample_0077.filtered.tagged.bam
   0 -rw-r--r-- 1 bghoshal ltri2014 1.9K Sep 24 12:39 sample_0077.filtered.tagged.Log.final.out
 27M -rw-r--r-- 1 bghoshal ltri2014  27M Sep 24 12:39 sample_0077.filtered.tagged.Log.out
   0 -rw-r--r-- 1 bghoshal ltri2014 1.4K Sep 24 12:39 sample_0077.filtered.tagged.Log.progress.out
3.0M -rw-r--r-- 1 bghoshal ltri2014 2.8M Sep 24 12:39 sample_0077.filtered.tagged.SJ.out.tab
   0 -rw-r--r-- 1 bghoshal ltri2014 1.3K Sep 24 12:26 sample_0077.postmap.yaml
   0 -rw-r--r-- 1 bghoshal ltri2014  280 Sep 24 16:35 zUMIs_runlog.txt

77.filtered.tagged._STARgenome:
total 56M
   0 drwx--S--- 2 bghoshal ltri2014 4.0K Sep 24 16:40 .
   0 drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
 21M -rw-r--r-- 1 bghoshal ltri2014  21M Sep 24 16:40 exonGeTrInfo.tab
8.5M -rw-r--r-- 1 bghoshal ltri2014 8.5M Sep 24 16:40 exonInfo.tab
1.0M -rw-r--r-- 1 bghoshal ltri2014 711K Sep 24 16:40 geneInfo.tab
8.0M -rw-r--r-- 1 bghoshal ltri2014 8.0M Sep 24 16:46 sjdbInfo.txt
5.5M -rw-r--r-- 1 bghoshal ltri2014 5.1M Sep 24 16:40 sjdbList.fromGTF.out.tab
6.5M -rw-r--r-- 1 bghoshal ltri2014 6.2M Sep 24 16:46 sjdbList.out.tab
5.5M -rw-r--r-- 1 bghoshal ltri2014 5.5M Sep 24 16:40 transcriptInfo.tab

77.filtered.tagged._STARpass1:
total 3.5M
   0 drwx--S--- 2 bghoshal ltri2014 4.0K Sep 24 16:46 .
   0 drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
   0 -rw-r--r-- 1 bghoshal ltri2014 1.9K Sep 24 16:46 Log.final.out
3.5M -rw-r--r-- 1 bghoshal ltri2014 3.1M Sep 24 16:46 SJ.out.tab

sample_0077.filtered.tagged._STARgenome:
total 56M
   0 drwx--S--- 2 bghoshal ltri2014 4.0K Sep 24 12:27 .
   0 drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
 21M -rw-r--r-- 1 bghoshal ltri2014  21M Sep 24 12:27 exonGeTrInfo.tab
8.5M -rw-r--r-- 1 bghoshal ltri2014 8.5M Sep 24 12:27 exonInfo.tab
1.0M -rw-r--r-- 1 bghoshal ltri2014 711K Sep 24 12:27 geneInfo.tab
8.0M -rw-r--r-- 1 bghoshal ltri2014 8.0M Sep 24 12:33 sjdbInfo.txt
5.5M -rw-r--r-- 1 bghoshal ltri2014 5.1M Sep 24 12:27 sjdbList.fromGTF.out.tab
6.5M -rw-r--r-- 1 bghoshal ltri2014 6.2M Sep 24 12:33 sjdbList.out.tab
5.5M -rw-r--r-- 1 bghoshal ltri2014 5.5M Sep 24 12:27 transcriptInfo.tab

sample_0077.filtered.tagged._STARpass1:
total 3.5M
   0 drwx--S--- 2 bghoshal ltri2014 4.0K Sep 24 12:33 .
   0 drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
   0 -rw-r--r-- 1 bghoshal ltri2014 1.9K Sep 24 12:33 Log.final.out
3.5M -rw-r--r-- 1 bghoshal ltri2014 3.1M Sep 24 12:33 SJ.out.tab

zUMIs_output:
total 17M
   0 drwxr-sr-x 4 bghoshal ltri2014 4.0K Sep 24 16:54 .
   0 drwxr-sr-x 7 bghoshal ltri2014 4.0K Sep 24 17:25 ..
9.5M -rw-r--r-- 1 bghoshal ltri2014 9.1M Sep 24 16:54 77kept_barcodes.txt
7.0M -rw-r--r-- 1 bghoshal ltri2014 6.6M Sep 24 17:21 .currentRGgroup.txt
   0 drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:31 expression
   0 -rw-r--r-- 1 bghoshal ltri2014   27 Sep 24 12:39 sample_0077kept_barcodes.txt
   0 drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:21 stats

bghoshal@nia-login05:/project/l/ltri2014/bghoshal/September_2018/Seda/samples/sample_0077$ ls -lhsa zUMIs_output/*
9.5M -rw-r--r-- 1 bghoshal ltri2014 9.1M Sep 24 16:54 zUMIs_output/77kept_barcodes.txt
   0 -rw-r--r-- 1 bghoshal ltri2014   27 Sep 24 12:39 zUMIs_output/sample_0077kept_barcodes.txt
zUMIs_output/expression:
total 28M
  0 drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:31 .
  0 drwxr-sr-x 4 bghoshal ltri2014 4.0K Sep 24 16:54 ..
28M -rw-r--r-- 1 bghoshal ltri2014  28M Sep 24 17:31 77.dgecounts.rds

zUMIs_output/stats:
total 1.0M
   0 drwxr-sr-x 2 bghoshal ltri2014 4.0K Sep 24 17:21 .
   0 drwxr-sr-x 4 bghoshal ltri2014 4.0K Sep 24 16:54 ..
512K -rw-r--r-- 1 bghoshal ltri2014 134K Sep 24 17:21 77.downsampling_thresholds.pdf
512K -rw-r--r-- 1 bghoshal ltri2014 4.3K Sep 24 12:44 sample_0077.downsampling_thresholds.pdf

**Comment by cziegenhain** [comment]
Hey Bibaswan,

Honestly I have not seen this error message before. could you explain why your folder contains some files with the prefix `sample_0077` and some just `77`? 
I ran the test reads you had sent a while back and the plotting worked for me.

**Comment by ghoshal** [comment]
I am using R 3.5.1. Do you think that might be the problem?

**Comment by cziegenhain** [comment]
No, I'm also using this R version.

**Comment by ghoshal** [comment]
It got sorted. I had to uninstall and install the data table library in R. Thanks for all the help.
