### ISSUE TITLE
how to understand collapse UMI and downsampling in zUMI

### ISSUE THREAD

**Issue by 2236529177** [sdparekh/zUMIs#75]
Dear professor,
Thanks for your great tool zUMI.
I am reading your paper "Counting absolute numbers of molecules using unique molecular identifiers".
 I have there major questions

Q1： Features of available UMI pipelines for the quantifcation of gene expression data in your table 1. Is it convenient for you to depict the meaning of collapse UMI and to concrete meaning of methods like 'Hamming distance' or  'Identity only'

Q2 : nother unique feature of zUMIs is that it allows for downsampling of reads before collapsing UMIs, thus enabling the user to assess whether a library was sequenced to saturation or whether deeper sequencing is necessary to depict the full mRNA complexity.  I understand the downsampling concept as a noun in Communication (The digital to digital process, downsampling point, is used at the receiving end to reduce the complexity of the receiver.). so how to undestand it in your zUMI

Q3 In figure 2 of D picture , Violin plots of gene-wise dispersion estimates with different quality fltering and UMI collapsing methods but the legend depict 1 base lower than phread17, not many different qulity filter

thanks a lot

**Comment by cziegenhain** [comment]
Hey,

Thank you for your interest in zUMIs. The GitHub issues are for bug reports, questions & suggestions related to the actual software implementation of our tool. Unfortunately this is not the right place for questions on the general concepts and background. I'm sure you'll find plenty of material in the literature to explain hamming distance and downsampling, etc.

Thank you for your understanding,
Christoph
