### ISSUE TITLE
Error in cell barcode detection

### ISSUE THREAD

**Issue by ghoshal** [sdparekh/zUMIs#76]
Hi,

I am using zUMIs on another split-seq dataset with 542 million sequences. I am using the same yaml files that I used for the previous data that ran well. However, I am getting a weird error before the mapping stage begins. It is completing the mapping stage successfully but can't find a barcode.
Please help!!

 You provided these parameters:
 YAML file:	zUMIs_SS1.yaml
 zUMIs directory:		/gpfs/fs0/scratch/w/wrana/bghoshal/software/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   null
 zUMIs version 2.0.7 

Filtering...
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 5
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 6
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 5
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 8
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2[W::sam_parse1] 
empty query name[main_samview] truncated file.

[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] [W::sam_parse1] empty query nameempty query name

[W::sam_read1] [W::sam_read1] Parse error at line 2Parse error at line 2

[main_samview] truncated file.
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 7
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 3
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 4
[main_samview] truncated file.
[W::sam_parse1] empty query name
[W::sam_read1] Parse error at line 6
[main_samview] truncated file.
cat: /scratch/w/wrana/bghoshal/August_2018/Seda/SS1/zUMIs_output/.tmpMerge//SS1.*.BCstats.txt: No such file or directory
Mapping...
Oct 01 10:40:24 ..... started STAR run
Oct 01 10:40:24 ..... loading genome
Oct 01 10:40:33 ..... processing annotations GTF
Oct 01 10:40:37 ..... inserting junctions into the genome indices
Oct 01 10:41:28 ..... started 1st pass mapping
Oct 01 10:41:31 ..... finished 1st pass mapping
Oct 01 10:41:31 ..... inserting junctions into the genome indices
Oct 01 10:42:22 ..... started mapping
Oct 01 10:42:25 ..... finished successfully
Counting...
[1] "2018-10-01 10:42:36 EDT"
Error in data.table::fread(bccount_file) : 
  File is empty: /scratch/w/wrana/bghoshal/August_2018/Seda/SS1/SS1.BCstats.txt
Calls: cellBC -> <Anonymous>
Execution halted
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-10-01 10:42:37 EDT"
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/scratch/w/wrana/bghoshal/August_2018/Seda/SS1/zUMIs_output/SS1kept_barcodes.txt' does not exist; getwd()=='/g
pfs/fs0/scratch/w/wrana/bghoshal/August_2018/Seda/SS1'. Include correct full path, or one or more spaces to consider t
he input a system command.

Thanks,

Bibaswan

**Comment by ghoshal** [comment]
Just to update you. I took a sample 100,000 sequences from this data and ran in the Ubuntu VirtualBox and I encountered the same error. 

Thanks for your help again.

**Comment by sdparekh** [comment]
you could share your yaml and some reads. I have never seen such errors before.

**Comment by ghoshal** [comment]
I have sent you an email with the YAML file, 100000 reads, and the error output.

**Comment by sdparekh** [comment]
Your barcode read is variable in length ranging from 26-94 bases. 
It does not really make sense to have pre-trimmed barcode reads where the definition of cell barcode is BC(11-18,49-56,87-94). I wish you could have let us known in the original post that this was done so that we would not have spend significant amount of time on troubleshooting this issue. 

Variable cDNA length is sensible & can occur and is handled within zUMIs but not the barcode read.

**Comment by ghoshal** [comment]
Sorry for the inconvenience. I thought the program is automatically going to remove the sequences/barcode reads below the defined length of barcode read. Also, the error message did not signify anything about the length of the read. Thanks for your input. I'll remove the sequences with low number of bases and rerun zUMIs.
