### ISSUE TITLE
zUMIs with Smart-seq2

### ISSUE THREAD

**Issue by ghoshal** [sdparekh/zUMIs#77]
Hi,

I have Smart Seq2 data for 384 cells. How can I use zUMIs to process the data? What are the parameters that will be different?

Thanks,

Bibaswan

**Comment by sdparekh** [comment]
Just leave out UMI tag in read definitions in YAML file.

**Comment by ghoshal** [comment]
There are no barcodes in the smart seq2 process. I tried running with both reads as cDNA and started from the Mapping stage but it failed.

**Comment by cziegenhain** [comment]
you should use the nextera i5 and i7 index reads as the barcodes! its not desirable to run zUMIs per cell individually.

**Comment by ghoshal** [comment]
Ok makes sense. We'll try that then.

Thanks a lot.

**Comment by cziegenhain** [comment]
Hope it works well for you.
