### ISSUE TITLE
Alignment/counting without barcodes

### ISSUE THREAD

**Issue by yonatans2** [sdparekh/zUMIs#79]
Perhaps a silly question, but it is possible to use zUMIs on a sample with all barcodes already trimmed?

Thanks,
Yonatan

**Comment by cziegenhain** [comment]
Hey Yonatan,

I'm not sure what you mean by trimmed?
If you have a single demultiplexed file you could simply run STAR and featureCounts...

**Comment by yonatans2** [comment]
I have a bunch of demultiplexed files. zUMIs is nice and easy because it's
just one line to run, so I hoped there's some way to do my simple case with
it.

**Comment by sdparekh** [comment]
The easiest fix would be to go back one step and use multiplexed fastq files. You can refer to this twitter conversation https://twitter.com/ashley99900423/status/1042886428953387008
Let us know if you need further assistance.

**Comment by cziegenhain** [comment]
I am closing this issue for now, feel free to reopen if something comes up.

**Comment by yonatans2** [comment]
OK thanks!
