### ISSUE TITLE
missing fastq.gz files in mapping step

### ISSUE THREAD

**Issue by csoneson** [sdparekh/zUMIs#8]
Hi,
when I run zUMIs (on the example data as well as on my own data), it complains in the mapping step that it can't find gzipped fastq files:

```
Oct 24 11:45:10 ..... started STAR run
Oct 24 11:45:10 ..... loading genome
gzip: ./chr22test.cdnaread.filtered.fastq.gz: No such file or directory
Oct 24 11:45:12 ..... processing annotations GTF
```

The file `./chr22test.cdnaread.filtered.fastq` exists, but it is not gzipped. If I manually gzip it and resume zUMIs from the mapping step, it seems to work.

I am using zUMIs v0.0.2 (downloaded Oct 23) and STAR v.2.5.3a. My call:

```
bash zUMIs/zUMIs-master.sh -f zUMIs/ExampleData/barcoderead_HEK.1mio.fq.gz \
-r zUMIs/ExampleData/cDNAread_HEK.1mio.fq.gz -c 1-6 -m 7-16 -l 50 \
-g reference/hg38_chr22/ -a reference/GRCh38.84.chr22.gtf -n chr22test -p 8 -o .
```

Am I doing something wrong, or is there a missing compression step after the filtering? 

Thanks

**Comment by csoneson** [comment]
Sorry, I just realized that the issue was due to a problem finding pigz. With pigz reachable, the gzipped files are generated as expected.

**Comment by cziegenhain** [comment]
Hi Charlotte,

Thanks for using zUMIs and good to hear that the problem solved. 
We could implement a user-defined custom path to pigz if that would be helpful?

Let us know if you encounter any other issues.

Best,
Christoph

**Comment by csoneson** [comment]
That might indeed be helpful! In fact, the same may be true for a custom path to R/Rscript. 
Thanks for a nice piece of software.
Charlotte

**Comment by cziegenhain** [comment]
Great, thanks for the feedback!
We just pushed the possibility to give custom pigz ("-P ") and custom Rscript ("-V ") paths.
Best,
Christoph

**Comment by csoneson** [comment]
Great, thanks!
