### ISSUE TITLE
Error in count table generation using example data

### ISSUE THREAD

**Issue by lxhuang7** [sdparekh/zUMIs#81]
Dear authors of zUMIs,

I am trying the pipeline for the first time on a HPC and have some trouble to run through the whole workflow using the example data provided in the package. First error comes as follows:

Filtering...
samtools view: writing to standard output failed: Broken pipe
samtools view: error closing standard output: -1
Mapping...
Oct 10 17:53:19 ..... started STAR run
Oct 10 17:53:19 ..... loading genome
Oct 10 17:53:20 ..... processing annotations GTF
Oct 10 17:53:21 ..... inserting junctions into the genome indices
Oct 10 17:53:31 ..... started mapping
Oct 10 17:55:12 ..... finished successfully
Counting...
[1] "2018-10-10 17:55:25 CDT"
[1] "78 barcodes detected."
[1] "8279 reads were assigned to barcodes that do not correspond to intact cells."
[1] "9e+07 Reads per chunk"
[1] "Loading reference annotation from:"
[1] "/data/reference/GRCh38/GRCh38.84.chr22.gtf"
[1] "Annotation loaded!"
[1] "Assigning reads to features (ex)"

It doesn't seem to affect the alignment and the subsequent feature assignment though:
......
|| Process BAM file Example.filtered.tagged.Aligned.out.bam...                ||
||    Single-end reads are included.                                          ||
||    Assign reads to features...                                             ||
||    Total reads : 853296                                                    ||
||    Successfully assigned reads : 21725 (2.5%)                              ||
||    Running time : 0.02 minutes                                             ||
||                                                                            ||
||                         Read assignment finished.                          ||
||                                                                            ||
\\===================== http://subread.sourceforge.net/ ======================//

Then I have this error that cause the program stops.

[1] "Here are the detected subsampling options:"
[1] "Automatic downsampling"
[1] "Working on barcode chunk 1 out of 1"
[1] "Processing 78 barcodes in this chunk..."
Error in (function (cl, name, valueClass)  :
  assignment of an object of class “numeric” is not valid for @‘Dim’ in an object of class “dgTMatrix”; is(value, "integer") is not TRUE
Calls: convert2countM -> .makewide -> <Anonymous> -> <Anonymous>
Execution halted
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2018-10-10 17:55:49 CDT"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/data/results/test/zUMIs_output/expression/Example.dgecounts.rds', probable reason 'No such file or directory'
Execution halted

Information about the R program is as follows:
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.7 (Santiago)

Matrix products: default
BLAS: /gpfs/apps/haswell/software/gcc-6.2.0/R/3.5.0/lib64/R/lib/libRblas.so
LAPACK: /gpfs/apps/haswell/software/gcc-6.2.0/R/3.5.0/lib64/R/lib/libRlapack.so

Any help would be greatly appreciated!

Best regards,
Lei

**Comment by lxhuang7** [comment]
Hi Christoph,

Thanks much for your prompt reply! With your suggestion, I traced the error back to the R script zUMIs-dge2.R and UMIstuffFUN.R. I found out when calling function reads2genes(), the return data frame from data.table::fread() contains some unicode around the first column, something like:

\[\e[0;33m\]GCCTGC\[\e[0m\]

Then I realized I have the customized terminal color setting in my .bash_profile.  Once I removed that setting, the pipeline runs successfully as expected. Still puzzled by how the unicode got into the results, but at least I can run the pipeline on my own data for now.

Thanks again for your help!

Best,
Lei

**Comment by lxhuang7** [comment]
Hi Christoph,

Thanks much for your prompt reply! With your suggestion, I traced the error back to the R script zUMIs-dge2.R and UMIstuffFUN.R. I found out when calling function reads2genes(), the return data frame from data.table::fread() contains some unicode around the first column, something like:

[\e[0;33m]GCCTGC[\e[0m]

Then I realized I have the customized terminal color setting in my .bash_profile. Once I removed that setting, the pipeline runs successfully as expected. Still puzzled by how the unicode got into the results, but at least I can run the pipeline on my own data for now.

Thanks again for your help!

Best,
Lei

**Comment by cziegenhain** [comment]
Hey Lei,
Oh wow I would not have expected that! Good that you found the issue. I'll note this and see if we can make zUMIs more robust to this sort of issue in the future. 

Let us know if you encounter further issues. 

Best,
Christoph
