### ISSUE TITLE
SplitSeq running error 

### ISSUE THREAD

**Issue by mgood2** [sdparekh/zUMIs#82]
Hi,

I got this error msg:
```
EXITING because of fatal PARAMETERS error: pGe.sjdbOverhang <=0 while junctions are inserted on the fly with --sjdbFileChrStartEnd or/and --sjdbGTFfile
SOLUTION: specify pGe.sjdbOverhang>0, ideally readmateLength-1
```
I tried STAR 2.5.4a, STAR 2.6.0a. I made STAR reference using the following command:
`STAR --runThreadN 4 --runMode genomeGenerate --genomeDir 'STAR' --genomeFastaFiles 'Homo_sapiens.GRCh38.dna.primary_assembly.fa'`
with/ without gtf tried both.

I have used your Splitseq_example.txt setting from #63 .
But I still get the error msg.

Could you help me with this problem?

Many thanks,
Eunmin

**Comment by cziegenhain** [comment]
Hey Eunmin,

sorry that you are encountering troubles with zUMIs.
That seems confusing! In zUMIs, we detect the read length automatically to set the correct `sjdbOverhang` parameter. 
I am thinking if maybe something went already wrong when extracting the cDNA reads before mapping.

Could you please post:

- zUMIs version
- The exact YAML file that you used
- contents of your output directory (eg `ls -sha` output )
- if you got a `*.filtered.tagged.bam` file, can we see the first few lines of that?

Hope we will get to this quickly.

Best,
Christoph

**Comment by mgood2** [comment]
I didn't put cDNA(1-151). 
Thank you so much. 
Eunmin

**Comment by sdparekh** [comment]
Hi Eunmin, I am glad that your problem is solved. I will close this issue for now but feel free to re-open if you need any further help.
