### ISSUE TITLE
Problems running example file 

### ISSUE THREAD

**Issue by mb3188** [sdparekh/zUMIs#83]
HI, 
I am using zUMIs doe the first time and tried with your example file, however I am having trouble making it work . There must be some beginner mistakes here, but I'd really appreciate your input. 

Thanks, 
Martina

#Innitiating the run:
../zUMIs-master.sh -y ZUMI_RUN_TEST_RUN.yaml -s /data/MB998/SOFTWARE/STAR/source/STAR -t /programs/bin/samtools/samtools -p /usr/bin/pigz -r /data/MB998/LUNG_CANCER/zUMIs -d /data/MB998/LUNG_CANCER/zUMIs

#YAML FILE I AM USING:

project: My_ZUMI_RUN
sequence_files:
  file1:
    name: /data/MB998/LUNG_CANCER/zUMIs/ZUMI_RUN_TES_RUN/barcoderead_HEK.1mio.fq.gz
    base_definition:
    - cDNA(1-88)
    - BC(1-16)
    - UMI(10)
  file2:
    name: /data/MB998/LUNG_CANCER/zUMIs/ZUMI_RUN_TES_RUN/cDNAread_HEK.1mio.fq.gz
    base_definition:
    - cDNA(1-88)
    - BC(0)
    - UMI(0)
reference:
  STAR_index: /data/MB998/LUNG_CANCER/zUMIs/ZUMI_RUN_TES_RUN/reference/hg38_chr22
  GTF_file: /data/MB998/LUNG_CANCER/zUMIs/ZUMI_RUN_TES_RUN/reference/GRCh38.84.chr22.gtf
  additional_STAR_params:
  additional_files: ~
out_dir: /data/MB998/LUNG_CANCER/zUMIs/ZUMI_RUN_TES_RUN
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering
samtools_exec: /programs/bin/samtools/samtools
pigz_exec: /usr/bin/pigz
STAR_exec: /data/MB998/SOFTWARE/STAR/source/STAR
zUMIs_directory: /data/MB998/LUNG_CANCER/zUMIs
read_layout: PE

#ERROR OUTPUT:
 You provided these parameters:
 YAML file:    ZUMI_RUN_TEST_RUN.yaml
 zUMIs directory:        /data/MB998/LUNG_CANCER/zUMIs
 STAR executable        /data/MB998/SOFTWARE/STAR/source/STAR
 samtools executable        /programs/bin/samtools/samtools
 pigz executable        /usr/bin/pigz
 Rscript executable        /data/MB998/LUNG_CANCER/zUMIs
 RAM limit:   0
 zUMIs version 2.1.1

Filtering...
../zUMIs-master.sh: line 157: /home/mb998/bin/perl: Input/output error
../zUMIs-master.sh: line 157: /home/mb998/bin/perl: Input/output error
sh: /programs/bin/samtools/samtools: Input/output error
Mapping...
../zUMIs-master.sh: line 171: /data/MB998/LUNG_CANCER/zUMIs: Is a directory
Counting...
../zUMIs-master.sh: line 181: /data/MB998/LUNG_CANCER/zUMIs: Is a directory
Descriptive statistics...
../zUMIs-master.sh: line 193: /data/MB998/LUNG_CANCER/zUMIs: Is a directory

**Comment by cziegenhain** [comment]
Hey Martina,

You have specified the ranges of cDNA sequence, BC and UMI wrong. 
Check that again carefully compared to the included example YAML in our repository.
Some pointers:
- ranges can not overlap (eg a base can not be both cDNA and BC)
- every type needs to be a range, so you giving  UMI(10) will not work
- if there is no BC or UMI in a read, don't give any of those definitions (don't do BC(0))

Best,
Christoph

**Comment by mb3188** [comment]
Thank you Christoph.
yes, that was definitely an issue and I corrected that. Now I think that portion works and I get BCstats.txt file. However I still can't make it work due to the issues below. It seems like it can;t read those R scripts that it needs for Mapping, Counting and Filtering. The folder I provide is the one in which all the zumi scripts are, but it not producing any results. 
 zUMIs_directory: /data/MB998/LUNG_CANCER/zUMIs


RUN log: 
Filtering...
Mapping...
../zUMIs-master.sh: line 171: /data/MB998/LUNG_CANCER/zUMIs: Is a directory
Counting...
../zUMIs-master.sh: line 181: /data/MB998/LUNG_CANCER/zUMIs: Is a directory
Descriptive statistics...
../zUMIs-master.sh: line 193: /data/MB998/LUNG_CANCER/zUMIs: Is a directory


Thanks, 
Martina

**Comment by cziegenhain** [comment]
Hey Martina,

Oh sorry I didn't see that issue right away:
It seems like you are giving a folder instead of the Rscript binary! The "-r" option should point the Rscript binary in your R installation folder.

**Comment by mb3188** [comment]
HI Christoph, 

I have now progressed to successfully running test files and getting all the outputs. However when I run my data and doing only mapping to chr 22 for test (so I use your reference in gtf). I successfully progress to creating  all the files but no files are created for dge in expression folder and I only My_ZUMI_RUN.detected_cells.pdf plot in stats folder. However I did not see any errors in any of the log files. What might be the issue? 

Thanks and sorry to ask so many questions.

**Comment by cziegenhain** [comment]
Hey,

That is odd. I could imagine if no reads map to chr22 that things break.
Would be nice if you could send the full log of standard out / standard error along with the YAML and the folder contents `ls -sha`.

**Comment by mb3188** [comment]
These are the folder contents and I attached the compressed folder of the files


[mb998@cbsumezey01 TEST_ZUMI]$ ls -sha
total 2.9G
4.0K .                                                                 0 My_ZUMI_RUN.filtered.tagged._STARpass1
4.0K ..                                                             4.0K My_ZUMI_RUN.postmap.yaml
 22M My_ZUMI_RUN.BCstats.txt                                        4.0K My_ZUMI_RUN.yaml
1.5G My_ZUMI_RUN.filtered.tagged.Aligned.out.bam                    4.0K My_ZUMI_RUN.yaml~
1.4G My_ZUMI_RUN.filtered.tagged.Aligned.out.bam.featureCounts.bam     0 out
4.0K My_ZUMI_RUN.filtered.tagged.Log.final.out                      4.0K Rplots.pdf
 76K My_ZUMI_RUN.filtered.tagged.Log.out                            4.0K .Rsubread_featureCounts_pid20853.summary
 12K My_ZUMI_RUN.filtered.tagged.Log.progress.out                   1.1M .Rsubread_UserProvidedAnnotation_pid20853
7.7M My_ZUMI_RUN.filtered.tagged.SJ.out.tab                            0 zUMIs_output
   0 My_ZUMI_RUN.filtered.tagged._STARgenome                        4.0K zUMIs_runlog.txt


[mb998@cbsumezey01 TEST_ZUMI]$ cd zUMIs_output/
[mb998@cbsumezey01 zUMIs_output]$ ls -sha
total 360K
   0 .  4.0K ..     0 expression  356K My_ZUMI_RUNkept_barcodes.txt     0 stats     0 .tmpMerge





[My_ZUMI_RUN.zip](https://github.com/sdparekh/zUMIs/files/2479207/My_ZUMI_RUN.zip)

**Comment by sdparekh** [comment]
Hi Martina,
By standard out/error Christoph meant what gets printed as verbose while zUMIs is running. Another thing you could send is `samtools view My_ZUMI_RUN.filtered.tagged.Aligned.out.bam.featureCounts.bam` .

What is your Rsubread version?

**Comment by mb3188** [comment]
Ok, I have to re-run with standard err/out and it seems that it is complaining about fastq files are corrupted and incomplete, as well as not in the same order, yet bam file still gets produced.  I attached those 2 files. I am using Rsubread_1.30.9. 

[Std_err_std_out.zip](https://github.com/sdparekh/zUMIs/files/2484317/Std_err_std_out.zip)

**Comment by sdparekh** [comment]
Are you using pre-filtered or pre-trimmed fastq files? BAM file could also get produced if some of your reads in the same order. This totally looks like you need to revisit your raw data. Let us know if you still have issues after sorting out your raw data. May I see some of your readids? `gunzip -c read1.fastq.gz | head`

**Comment by sdparekh** [comment]
Hi Martina, I am closing this issue for now but feel free to re-open if you need further help.
