### ISSUE TITLE
fatal error while mapping

### ISSUE THREAD

**Issue by mbassalbioinformatics** [sdparekh/zUMIs#85]
Hi Chris

Thanks for the update for processing ddSeq datasets.  The new update processes the filtering step with no issues unlike before.  When it moves onto mapping zUMIs will throw an error

EXITING because of fatal PARAMETERS error: present --sjdbOverhang=74 is not equal to the value at the genome generation step =0
SOLUTION:

I initially had generated a genome with 100bp overhangs, that didnt work. I then i regenerated an index as per the example given in https://github.com/sdparekh/zUMIs/wiki/Usage with no overhang and got the error above.  Im sure I must be missing something very simple to get this running.  Any help appreciated!

**Comment by sdparekh** [comment]
Hi,
Just make sure that the STAR versions are the same for indexing and mapping. you can check it from the Log.out files of STAR. If you face the same issue again, you can just get another STAR version like 2.5.4a and try the same. Let us know if you have the same trouble again. You can refer to the similar issue with STAR https://github.com/alexdobin/STAR/issues/470
