### ISSUE TITLE
R-3.5.1 issue GenomicFeatures

### ISSUE THREAD

**Issue by mgood2** [sdparekh/zUMIs#86]
```
Error in loadNamespace(name) :
  there is no package called ‘GenomicFeatures’
Calls: .makeSAF
Execution halted
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/output/zUMIs_output/expression/10xF6.dgecounts.rds', probable reason 'No such file or directory'
Execution halted
```
I have noticed that GenomicFeatures package is not available in R-3.5.1.

**Comment by cziegenhain** [comment]
Sorry I'll directly close this issue as it is not related to zUMIs but rather your installation.
GenomicFeatures is definitely available for R3.5.1. 
Just use the installation instructions. 

https://github.com/sdparekh/zUMIs/wiki/Installation#r
