### ISSUE TITLE
relative path for output directory

### ISSUE THREAD

**Issue by csoneson** [sdparekh/zUMIs#9]
Hi again,

I just ran into another issue, now in the counting step, which I believe may be linked to the `setwd(dirname(abamfile))` command on line 134 of `zUMIs-dge.R`. Basically, if I provide my output directory as a relative path (which is not the current directory) when I call `zUMIs`, the `saveRDS` command on line 187 will try to save an object to a directory that doesn't exist. If I specify the absolute path of the output directory it works fine. If the change of directory is necessary, perhaps this could be clarified.

Thanks
Charlotte

**Comment by cziegenhain** [comment]
Hey,

you are again right. We had encountered this bug 2 weeks ago but turns out our fix had a mistake in itself. zUMIs should now detect relative paths automatically and convert them in absolute paths.

Thanks,
Christoph

**Comment by csoneson** [comment]
Thanks for the quick fix!
Charlotte
