### ISSUE TITLE
Bus error

### ISSUE THREAD

**Issue by hmassalha** [sdparekh/zUMIs#92]
Hi, 
I am using the same bash code that worked for me in the past with zUMIs. However, now I am not getting the dgcounts.rds files, although I got a 'Successfully completed' message. 
When looked deeply in the output files I see two things: 
1. 
`Raw reads: 27276018 
Filtered reads: 12754354 

Make sure you have approximately 13778 Mb RAM availableNov 22 17:19:33 ..... started STAR run
Nov 22 17:19:33 ..... loading genome
**/home/labs/shalev/hassanm/NGS/zUMI/zUMI006/zUMIs-noslurm.sh: line 91: 287599 Bus error               (core dumped) $starexc --genomeDir $g --runThreadN $t --readFilesCommand zcat --sjdbGTFfile $gtf --outFileNamePrefix $o/$sn. --outSAMtype BAM Unsorted --outSAMmultNmax 1 --outFilterMultimapNmax 50 --outSAMunmapped Within --sjdbOverhang $rl --twopassMode Basic --readFilesIn $o/$sn.cdnaread.filtered.fastq.gz $x**
[bam_sort_core] merging from 0 files and 16 in-memory blocks...
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-11-22 17:20:49 IST"
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-11-22 17:21:01 IST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-11-22 17:22:01 IST"`

2. 
`**Error in data.table::fread(paste("cut -f4 ", abamfile[2], ".featureCounts",  : 
  File is empty: /dev/shm/file4fe366000b61d**
Calls: makeGEprofile -> <Anonymous>
Execution halted
[1] "I am loading useful packages for plotting..."
[1] "2018-11-22 17:22:06 IST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '/home/labs/shalev/kerenb/NGS/181121_NB501465_0409_AHVLG7BGX7_Acinar_Telocytes_Hassan_output/Mouse_Telocytes/zUMI_strandS1/zUMIs_output/expression/F3_big_p1.dgecounts.rds', probable reason 'No such file or directory'
Execution halted`

in the folder of the zUMIs_output I see that Aligned.out.bam, aligned.sorted.bam, ex.featureCounts and in.featureCounts files are 0 bits. hope this can give a hit to what happned..

Thanks, HM

**Comment by cziegenhain** [comment]
Hey,

For me it looks like things start to go wrong while STAR is loading the reference genome. 
Could you make sure that you are giving the correct path & have sufficient memory for loading available?
The other error messages are just downstream problems of no useful mapped file being present.

Apart from that, I see that you are using a quite old version. I can recommend to update to our newest zUMIs release [for many new features and even faster processing](https://github.com/sdparekh/zUMIs#zumis20-released) :)

Best,
Christoph

**Comment by hmassalha** [comment]
Hi, 
Thanks for your reply. I did check the paths and the files that I am using for this analysis. They are OK. 
I looked into the log.out file and find the following: 
`EXITING because of fatal PARAMETERS error: present --sjdbOverhang=65 is not equal to the value at the genome generation step =100
SOLUTION: 

Nov 25 06:47:21 ...... FATAL ERROR, exiting`

hope this note will give more hits to solve the problem. 
Thanks, HM

**Comment by hmassalha** [comment]
Hi, 
I managed to find the problem and solve it. Since I am using an old bash code that worked for me, the problem was from the cluster of the institute. Solved and everything working as expected. 
Again thanks for your help, and will update my zUMIs :) 

Best, HM

**Comment by cziegenhain** [comment]
Hey HM,

alright great! Was just about to answer here to check the STAR version but you managed to solve it already. Hope everything goes smooth for you now.

Best,

Christoph

**Comment by cziegenhain** [comment]
Hey,

Since you do get output from some of the jobs, I would assume the problem lies with the files that break. Couple of suggestions:

- I would recommend to double check that for all iterations, the paths to the input fastq files are correct and that you have the correct permissions!
- Are some of your input fastq files preprocessed, eg. trimmed? Variable read length could throw older versions of zUMIs off.  
- Are just the STAR bam files empty or also the filtered fastq and barcode .sam files? if those have content, can you show us a couple of lines for a job that breaks?

Best,
Christoph

**Comment by hmassalha** [comment]
Hi Christoph, 
I did what you suggested and I do get dgecounts.rds files for most of my libraries. I have two pools of 6 samples each, and for them, I am getting the following message: 'TERM_RUNLIMIT: job killed after reaching LSF run time limit.' What would you suggest for me to do? 

Thanks again for your help, 
HM

**Comment by hmassalha** [comment]
Hey, 
You are correct, I do have a high number of reads for my samples. 

I will be happy if you can give me more details with regard to use the Illumina barcode directly into the zUMI. Sure it will be much faster, this is because zUMI has to load the genome-related files only once. Could you please share with me the relevant bcl2fastq and the zUMIs command? 

Thanks, HM

**Comment by cziegenhain** [comment]
Of course, I'd be happy to!

- In bcl2fastq, make sure to add the flag `--create-fastq-for-index-reads`. 
- If the same pool of libraries was sequenced on all lanes of the flow cell (eg. NextSeq500), also add `--no-lane-splitting`.
- In the SampleSheet, only list the libraries that should NOT be run in zUMIs. If all libraries should go through zUMIs, you don't even need a SampleSheet! The fastq files you will put into zUMIs are then the Undetermined_*_.fastq.gz!
- Since I think you are using the older release of zUMIs, you would add the illumina index fastq file as plate barcode (`-T Undetermined_I1.fastq.gz`) and give the appropriate base range (`-U 1-8`).

Best,
Christoph

**Comment by hmassalha** [comment]
Dear Christoph, 
I just downloaded the new zUMI to our cluster in the lab. I bulit the yaml file based on the instructions that you have in github. Unfortunalty I keep getting the following message: 

'Job <human_zonation> was submitted from host <access2.wexac.weizmann.ac.il> by user <hassanm> in cluster <wexac> at Fri Jan 11 12:38:42 2019
Job was executed on host(s) <12*cn472.wexac.weizmann.ac.il>, in queue <new-short>, as user <hassanm> in cluster <wexac> at Fri Jan 11 12:38:37 2019
</home/labs/shalev/hassanm> was used as the home directory.
</home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output> was used as the working directory.
Started at Fri Jan 11 12:38:37 2019
Terminated at Fri Jan 11 12:38:38 2019
Results reported at Fri Jan 11 12:38:38 2019

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
bash zUMIs-master.sh -y /home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output/yaml.yaml
------------------------------------------------------------

Successfully completed.

Resource usage summary:

    CPU time :                                   0.19 sec.
    Max Memory :                                 2 MB
    Average Memory :                             2.00 MB
    Total Requested Memory :                     24000.00 MB
    Delta Memory :                               23998.00 MB
    Max Swap :                                   -
    Max Processes :                              4
    Max Threads :                                5
    Run time :                                   7 sec.
    Turnaround time :                            0 sec.

The output (if any) follows:

tee: '/home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output'
/zUMIs_runlog.txt: No such file or directory


 You provided these parameters:
 YAML file:      /home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output/yaml.yaml
 zUMIs directory:                /home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output
 STAR executable         STAR
 samtools executable             samtools
 pigz executable         pigz
 Rscript executable              Rscript
 RAM limit:   2
 zUMIs version 2.2.2b 


mkdir: cannot create directory ‘'/home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output'\r/zUMIs_output/’: No such file or directory
mkdir: cannot create directory ‘'/home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output'\r/zUMIs_output/expression’: No such file or directory
mkdir: cannot create directory ‘'/home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output'\r/zUMIs_output/stats’: No such file or directory
mkdir: cannot create directory ‘'/home/labs/shalev/hassanm/NGS/190109_NB501465_0443_AHJ2WYBGX9_human_zonation_zUMI181029_output'\r/zUMIs_output/.tmpMerge’: No such file or directory'

Any suggestions, please? I check the paths and they are OK. Just a small reminder, I would like to make the Illumina demultiplexing using zUMI and not bcl2fastq, and the -U flag is not useful anymore with the latest version of zUMI. 

Thanks in advance, 
HM

**Comment by sdparekh** [comment]
Hi HM,

It looks like you have special characters like "\r" in your path. Please check the encoding of your script and yaml files. 

For your second question, you can provide illumina index reads as file3 and use the range BC(1-8) or however long your read is. That way the sample barcode becomes illumina index + Sample BC.

I hope this helps.

Good luck
Best,
Swati

**Comment by hmassalha** [comment]
Hi Swati, 
Sorry for my late reply, I was busy with another project. 
I tried to understand why I have this "\r", I don't have in my line in code neither the ymal that includes this hidden character '\r'. Do you have any suggestion how I can go around this issue? 

Thanks, HM
