### ISSUE TITLE
counting error

### ISSUE THREAD

**Issue by heyfastos** [sdparekh/zUMIs#93]
dear zUmi authors.
While running zUmi, an error occurred that i could not understand. This is not the first time i use zUMI and in the past it ran without a problem, so i am unsure what it is that i am doing wrong... Here is the command i used:

...zUMIs-master.sh -f $READ2.fastq.gz -r $READ1.fastq.gz -n nov_LCMseq -g .../GRCm38.84_STAR_zumi/ -a .../GRCm38.84/Mus_musculus.GRCm38.84.gtf -c 1-6 -m 7-16 -l 50 -s 1 -b $BARCODE_FILE.txt -p 1 -o zUmi_test2/

Below i pasted the error msg and some of the output i got. Do you think you can tell me where is the problem?  do you need any additional information? (the barcode file for example, contains only one column that includes all barcodes used in the experiment, each barcode in a new row)

thanks!
Dan.

Nov 25 18:00:32 ..... started STAR run
Nov 25 18:00:32 ..... loading genome
Nov 25 18:00:55 ..... processing annotations GTF
Nov 25 18:01:05 ..... inserting junctions into the genome indices
Nov 25 18:05:09 ..... started 1st pass mapping
Nov 25 18:41:10 ..... finished 1st pass mapping
Nov 25 18:41:11 ..... inserting junctions into the genome indices
Nov 25 18:42:31 ..... started mapping
Nov 25 19:20:14 ..... finished successfully
[bam_sort_core] merging from 2 files and 1 in-memory blocks...
**[E::hts_open_format] Failed to open file tmp.nov_LCMseq.0000.bam**
**samtools sort: failed to create temporary file "tmp.nov_LCMseq.0000.bam": File exists**
Loading required package: optparse
[1] "I am loading useful packages..."
[1] "2018-11-25 19:27:09 IST"
[1] "I am making annotations in SAF... This will take less than 3 minutes..."
[1] "2018-11-25 19:27:23 IST"
Import genomic features from the file as a GRanges object ... OK
Prepare the 'metadata' data frame ... OK
Make the TxDb object ... OK
**Warning message:
In .get_cds_IDX(type, phase) :
  The "phase" metadata column contains non-NA values for features of type
  stop_codon. This information was ignored.**
'select()' returned 1:many mapping between keys and columns
[1] "I am making count tables...This will take a while!!"
[1] "2018-11-25 19:28:32 IST"
.......
Read 94.4% of 33363498 rows
Read 33363498 rows and 1 (of 1) columns from 2.072 GB file in 00:00:40
**Error: Columns `XC`, `XM` must be length 1 or 38585130, not 33363498, 33363498
Execution halted**
[1] "I am loading useful packages for plotting..."
[1] "2018-11-25 19:32:30 IST"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  **cannot open compressed file '/home/labs/shalev/millerd/myData/Sequencing/LCM-scrbSeq/november_2018/zUmi_out_Dan2//zUMIs_output/expression/nov_LCMseq.dgecounts.rds', probable reason 'No such file or directory'**
Execution halted

**Comment by sdparekh** [comment]
Hi Dan,

Can you list the versions of zUMIs, STAR, samtools and Rsubread pacakge? It would also be useful to see what you got so far as an output `ls -lha zUmi_test2/*`. If you don't mind, you could paste a couple of lines of the aligned bam file. It looks like samtools sort is not working but unless I see the version and the content of the bam file, it would be difficult to troubleshoot.

Best,
Swati

**Comment by heyfastos** [comment]
Thank you Swati:
STAR version: 2.5.3a
zUMIs version: 0.0.6
samtools Version: 1.8 (using htslib 1.8)
R version: 3.4.3
Rsubread: 1.28.1 
pigz: 2.3.4
mysql: 5.7.16

the output folder contains the following files (last three lines are folders):

-rwxr-x--- 1 millerd shalev-wx-grp 809M Nov 25 20:47 nov_LCMseq.aligned.sorted.bam
-rwxr-x--- 1 millerd shalev-wx-grp 2.2G Nov 25 20:53 nov_LCMseq.aligned.sorted.bam.ex.featureCounts
-rwxr-x--- 1 millerd shalev-wx-grp 2.2G Nov 25 20:52 nov_LCMseq.aligned.sorted.bam.in.featureCounts
-rwxr-x--- 1 millerd shalev-wx-grp 1.9K Nov 25 20:41 nov_LCMseq.Log.final.out
-rwxr-x--- 1 millerd shalev-wx-grp 206K Nov 25 20:41 nov_LCMseq.Log.out
-rwxr-x--- 1 millerd shalev-wx-grp 5.4K Nov 25 20:41 nov_LCMseq.Log.progress.out
-rwxr-x--- 1 millerd shalev-wx-grp 299K Nov 25 20:41 nov_LCMseq.SJ.out.tab
drwxr-x--- 2 millerd shalev-wx-grp 4.0K Nov 25 19:48 nov_LCMseq._STARgenome
drwxr-x--- 2 millerd shalev-wx-grp 4.0K Nov 25 20:15 nov_LCMseq._STARpass1
drwxr-x--- 5 millerd shalev-wx-grp 4.0K Nov 25 15:20 zUMIs_output


i used samtool  view to read the bam file. it starts with:
NB501465:406:HVLH5BGX7:1:11101:1123:12472       0       7       81094342        1       15M     *       0       0       ACAGTGACGGGGCAC AA<AAEEEEEEEEEE NH:i:3  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1128:18002       0       1       69689106        0       1S15M   *       0       0       CGATGTGGTCCTTGCA        AA<AAEEEEEEEEEEE        NH:i:15 HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1130:6509        16      15      88933953        255     6M999N10M       *       0       0       ACCAACCATCACATCG        EEEEEEEEEEEAAAAA        NH:i:1  HI:i:1  AS:i:16 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1130:16960       0       3       30769481        3       1S15M   *       0       0       CGATGTAATTTCGTGG        AAAAAEEEEEEEEEEE        NH:i:2  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1138:15599       0       2       17937451        0       15M     *       0       0       TGACCATCTTCTTTT AAAAAEEEEEEEEEE NH:i:15 HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1147:15809       0       3       124167932       255     16M     *       0       0       TGACCAGATTATTTAT        AAAAAEEEEEEEEEEE        NH:i:1  HI:i:1  AS:i:15 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1148:4921        0       5       135391752       255     15M     *       0       0       ACAGTGTTGTATCGA AA/AAEEEEEEEEEE NH:i:1  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1159:2218        0       5       78126388        0       15M     *       0       0       ACAGTGAGGTGGCTA AA/6AEEEEEEEEEE NH:i:11 HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1159:5918        16      2       181292656       0       14M     *       0       0       CGACCATCTGGTCA  EEEEEEEEEAAAAA  NH:i:5  HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1160:3346        0       15      80607327        3       1S15M   *       0       0       TTAGGCGGGGGGCGGG        AAAAAEEEEEEEEEEE        NH:i:2  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1166:4017        0       17      65958075        0       16M     *       0       0       TGACCATAGCTCTGTG        AAAAAEEEEEEEEEEE        NH:i:11 HI:i:1  AS:i:15 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1176:7953        16      2       127271340       0       1S15M   *       0       0       CCGGACAGCCCACTGT        EEEEEEEEEEEAA<AA        NH:i:7  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1188:4384        0       5       92582030        0       15M1S   *       0       0       CGATGTGTTCAAAGGG        AAAAAEEEEEEEEEEE        NH:i:10 HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1190:5172        0       18      64765926        0       15M     *       0       0       TGACCAAGCTGGGTT AAAAAEEEEEEEAEE NH:i:6  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1191:19972       0       17      15137987        0       15M1S   *       0       0       TGACCACTGGTTGACA        A/AAAEEEEEEEEEEE        NH:i:9  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1201:14037       0       15      56722824        0       3S13M   *       0       0       CGATGTCGGATCGAAT        AAAAAEEEEEEEEEEE        NH:i:5  HI:i:1  AS:i:12 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1204:2041        16      15      96863044        0       1S13M   *       0       0       CATTACCTACATCG  EEEEEEEEEAAAAA  NH:i:11 HI:i:1  AS:i:12 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1211:13644       16      11      104823886       3       15M     *       0       0       GGCAAATCGTGGTCA EEEEEEEEEEAAAAA NH:i:2  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1219:5897        16      8       72047348        255     14M2S   *       0       0       AATCGCGAGTCACTGT        EEEEEEEEEEEAA<AA        NH:i:1  HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1219:8639        16      1       113943233       0       1S14M   *       0       0       ACCCCCCATGCCTAA EEEEEEEEEEAAAAA NH:i:16 HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1222:9290        16      11      4937175 0       2S14M   *       0       0       TGGGTGACCGCCCTAA        EEEEEEEEEEEAAAAA        NH:i:8  HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1227:16383       16      5       68818424        255     16M     *       0       0       TCAAACCACCTGGTCA        EEEEEEEEEEEAAAAA        NH:i:1  HI:i:1  AS:i:15 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1237:6110        0       2       54190201        3       16M     *       0       0       CAATGTGGATCATTAT        AA/AAEAEAEAEEEEE        NH:i:2  HI:i:1  AS:i:15 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1240:14365       0       11      75992455        0       14M1S   *       0       0       CGATGTCCAAAAAGT AA<//EEEEEE<EEE NH:i:23 HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1242:3891        16      14      90877538        0       15M     *       0       0       TAGTTACCACACTGT EEEEEEEEEEAAAAA NH:i:5  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1249:18819       16      2       106689833       3       1S15M   *       0       0       CACATGCTAGACATCG        EEEEEEEEEEEAA6AA        NH:i:2  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1258:9083        0       7       104283781       3       15M     *       0       0       CGATGTTTACTAGTT AAAAAEEEEEEEEEE NH:i:2  HI:i:1  AS:i:14 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1258:11615       0       4       54875786        0       14M     *       0       0       TGACCACCCAGACA  A/AAAEEEEEEEEE  NH:i:28 HI:i:1  AS:i:13 nM:i:0
NB501465:406:HVLH5BGX7:1:11101:1261:18002       16      3       106933413       1       16M     *       0       0       CACATCTGTTTGGTCA        EEEEEEEEEEEAAAAA        NH:i:4  HI:i:1  AS:i:15 nM:i:0


I hope this helps you helping me :) :) 
all the best,
Dan

**Comment by sdparekh** [comment]
Hi Dan,

Are you sure you gave the correct barcode and cDNA read? To me it looks like they are swapped by mistake. 

-f should be barcode read
-r should be cDNA read

**Comment by heyfastos** [comment]
True... how silly. 
I would highly appreciate it if you could shortly comment on how you came up with this conclusion, so that i will not have to bother you in such cases in the future.
thank you very much!

**Comment by sdparekh** [comment]
No worries ;) Always happy to help! These minor or silly mistakes are always the mean ones to find. I will close this issue for now but feel free to open it again if you face any other issues.
