### ISSUE TITLE
Serialize Error

### ISSUE THREAD

**Issue by tylerchen7** [sdparekh/zUMIs#95]
Hello zUMIs Team!

I've been running zUMIs 2.2.1 on libraries generated with a modified version of mcSCRB-seq and it appears to run fine when my input fastqs are pre-subsampled to 7M reads. When running on paired fastqs with 24M reads from the same dataset, however, I run into the issue below. 

> Error in serialize(data, node$con) : ignoring SIGPIPE signal

I am running from filtering with R1: 1-8 BC, 9-18 UMI and R2: 1-50 cDNA, with the requirement to find only the top 7 barcodes from the dataset, and hamming distance of 1 for UMI collapse, using a STAR index built without sjdbOverhang as recommended. The node I'm running on has 64GB RAM and 20 cores, so I attempted to set a RAM limit of 48GB and run on 18 cores in my .yaml file (this was likely unnecessary), which didn't solve the issue. 

I wasn't sure if it was an issue with my setup, the cluster I'm running on, or zUMIs, so I thought I'd see if you had any suggestions!

> [tylerchen@n0132 zUMIs]$ bash zUMIs-master.sh -y TC011A_24M.yaml
> 
> 
>  You provided these parameters:
>  YAML file:     TC011A_24M.yaml
>  zUMIs directory:               /clusterfs/rosalind/groups/streetslab/tylerchen/zUMIs
>  STAR executable                STAR
>  samtools executable            samtools
>  pigz executable                pigz
>  Rscript executable             Rscript
>  RAM limit:   48
>  zUMIs version 2.2.1
> 
> 
> Filtering...
> Mapping...
> Dec 20 01:24:51 ..... started STAR run
> Dec 20 01:24:52 ..... loading genome
> Dec 20 01:29:08 ..... processing annotations GTF
> Dec 20 01:29:33 ..... inserting junctions into the genome indices
> Dec 20 01:31:47 ..... started 1st pass mapping
> Dec 20 01:32:44 ..... finished 1st pass mapping
> Dec 20 01:32:44 ..... inserting junctions into the genome indices
> Dec 20 01:34:59 ..... started mapping
> Dec 20 01:36:36 ..... finished successfully
> Counting...
> [1] "2018-12-20 01:37:03 PST"
> [1] "1060994 reads were assigned to barcodes that do not correspond to intact cells."
> [1] "2.16e+08 Reads per chunk"
> [1] "Loading reference annotation from:"
> [1] "/clusterfs/rosalind/groups/streetslab/tylerchen/STAR-2.5.4b/reference/GRCh38/annotation/Homo_sapiens.GRCh38.91.gtf"
> [1] "Annotation loaded!"
> [1] "Assigning reads to features (ex)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 18                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid71625 ...       ||
> ||    Features : 1199851                                                      ||
> ||    Meta-features : 49614                                                   ||
> ||    Chromosomes/contigs : 47                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 20376622                                                  ||
> ||    Successfully assigned reads : 12346383 (60.6%)                          ||
> ||    Running time : 1.18 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [1] "Assigning reads to features (in)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 18                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid71625 ...       ||
> ||    Features : 275949                                                       ||
> ||    Meta-features : 28257                                                   ||
> ||    Chromosomes/contigs : 36                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 20376622                                                  ||
> ||    Successfully assigned reads : 4318449 (21.2%)                           ||
> ||    Running time : 1.11 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [bam_sort_core] merging from 0 files and 9 in-memory blocks...
> [bam_sort_core] merging from 0 files and 9 in-memory blocks...
> [1] "Here are the detected subsampling options:"
>  [1] "1500000"  " 1250000" "1000000"  " 900000"  " 800000"  " 700000"
>  [7] " 600000"  " 500000"  " 400000"  " 300000"  " 200000"  " 100000"
> [13] " 50000"   " 40000"   " 30000"   " 20000"   " 10000"   " 7500"
> [19] " 5000"    " 2500"    " 1000"
> [1] "Working on barcode chunk 1 out of 1"
> [1] "Processing 7 barcodes in this chunk..."
> Initialising 18 core cluster.
> Error in serialize(data, node$con) : ignoring SIGPIPE signal
> Calls: collectCounts ... postNode -> sendData -> sendData.SOCKnode -> serialize
> In addition: Warning message:
> group_indices_.grouped_df ignores extra arguments
> Execution halted
> Descriptive statistics...
> [1] "I am loading useful packages for plotting..."
> [1] "2018-12-20 01:48:47 PST"
> Error in gzfile(file, "rb") : cannot open the connection
> Calls: readRDS -> gzfile
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/clusterfs/rosalind/groups/streetslab/tylerchen/out/TC011A_24M/zUMIs_output/expression/TC011A_24M.dgecounts.rds', probable reason 'No such file or directory'
> Execution halted

Thanks very much for your help!

**Comment by cziegenhain** [comment]
Hey Tyler,

Hmm this seems to be a problem when the multicore implementation of dplyr (multidplyr) is starting to run the hamming distance calculations.
 
Did you observe that the RAM was running full when the instance crashed? It's a bit hard to anticipate how much data gets copied explicitly to each worker job, so there is a chance the RAM limit you gave was exceeded.

Can you try some of the following:
- run without hamming distance collapsing (only the hamming distance calculations suffer from this issue)
- try giving less cores (eg. 4, less data being copied to worker cores). For the counting step in zUMIs, the number of cores is anyway not all too critical.

Let me know if that helps.

Best,
Christoph

PS: Also super interesting to hear how mcSCRB-seq is working for you!

**Comment by tylerchen7** [comment]
Hi Christoph,

Thanks a ton for the reply! Just ran it without the Hamming distance option (all other parameters identical to my knowledge) and ran into the following issue, one I haven't seen before. 

> [tylerchen@n0065 zUMIs]$ bash zUMIs-master.sh -y TC011A_24M_noHamming.yaml
> 
> 
>  You provided these parameters:
>  YAML file:     TC011A_24M_noHamming.yaml
>  zUMIs directory:               /clusterfs/rosalind/groups/streetslab/tylerchen/zUMIs
>  STAR executable                STAR
>  samtools executable            samtools
>  pigz executable                pigz
>  Rscript executable             Rscript
>  RAM limit:   48
>  zUMIs version 2.2.1
> 
> 
> Filtering...
> Mapping...
> Dec 20 15:52:47 ..... started STAR run
> Dec 20 15:52:48 ..... loading genome
> Dec 20 15:57:00 ..... processing annotations GTF
> Dec 20 15:57:25 ..... inserting junctions into the genome indices
> Dec 20 15:59:40 ..... started 1st pass mapping
> Dec 20 16:00:37 ..... finished 1st pass mapping
> Dec 20 16:00:38 ..... inserting junctions into the genome indices
> Dec 20 16:03:03 ..... started mapping
> Dec 20 16:04:39 ..... finished successfully
> Counting...
> [1] "2018-12-20 16:05:10 PST"
> [1] "1060994 reads were assigned to barcodes that do not correspond to intact cells."
> [1] "2.16e+08 Reads per chunk"
> [1] "Loading reference annotation from:"
> [1] "/clusterfs/rosalind/groups/streetslab/tylerchen/STAR-2.5.4b/reference/GRCh38/annotation/Homo_sapiens.GRCh38.91.gtf"
> [1] "Annotation loaded!"
> [1] "Assigning reads to features (ex)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 18                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid16040 ...       ||
> ||    Features : 1199851                                                      ||
> ||    Meta-features : 49614                                                   ||
> ||    Chromosomes/contigs : 47                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 20376622                                                  ||
> ||    Successfully assigned reads : 12346383 (60.6%)                          ||
> ||    Running time : 2.12 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [1] "Assigning reads to features (in)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 18                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid16040 ...       ||
> ||    Features : 275949                                                       ||
> ||    Meta-features : 28257                                                   ||
> ||    Chromosomes/contigs : 36                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 20376622                                                  ||
> ||    Successfully assigned reads : 4318449 (21.2%)                           ||
> ||    Running time : 2.88 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [bam_sort_core] merging from 0 files and 9 in-memory blocks...
> [bam_sort_core] merging from 0 files and 9 in-memory blocks...
> [1] "Here are the detected subsampling options:"
>  [1] "1500000"  " 1250000" "1000000"  " 900000"  " 800000"  " 700000"
>  [7] " 600000"  " 500000"  " 400000"  " 300000"  " 200000"  " 100000"
> [13] " 50000"   " 40000"   " 30000"   " 20000"   " 10000"   " 7500"
> [19] " 5000"    " 2500"    " 1000"
> [1] "Working on barcode chunk 1 out of 1"
> [1] "Processing 7 barcodes in this chunk..."
> Error in umiFUNs[[umiFUN]](reads = reads, bccount = bccount, ftype = tt,  :
>   attempt to apply non-function
> Calls: collectCounts -> lapply -> lapply -> FUN
> Execution halted
> Descriptive statistics...
> [1] "I am loading useful packages for plotting..."
> [1] "2018-12-20 16:14:38 PST"
> Error in gzfile(file, "rb") : cannot open the connection
> Calls: readRDS -> gzfile
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/clusterfs/rosalind/groups/streetslab/tylerchen/out/TC011A_24M_noHamming/zUMIs_output/expression/TC011A_24M_noHamming.dgecounts.rds', probable reason 'No such file or directory'
> Execution halted

Any thoughts? I'll attempt a run with UMI hamming distance of 1 enabled and 4 cores in the meantime.

**Comment by cziegenhain** [comment]
Hey,

Sorry I think I didn't say precisely what I meant: Please set `Ham_Dist: 0` in the yaml file to switch off the hamming distance collapsing. The error you got looks like you removed that line completely and hence zUMIs didn't know whether to use sequence identity or hamming distance collapsing of UMIs.

I find it actually a bit confusing why this would run out of memory, you have really few reads so things should be very smooth. I'll check with @sdparekh while you rerun and we get back to you!

**Comment by cziegenhain** [comment]
Hey Tyler,

good that it works fine without hamming distance.

For the error that you are facing, I am unsure if we can fix this multidplyr issue, its more of a black box for me. It could be that you have very few cells in there and the partitioning over several cores thus breaks. 
Anyways I have coded up a workaround: zUMIs will now first try to use the faster multidplyr processing, but if that fails will use regular linear processing of your data. It would be slower but hopefully more failsafe!

So please update zUMIs and try again! 

Fingers crossed,

Christoph

**Comment by cziegenhain** [comment]
Hey Tyler,

I just committed a second trial to fix this with an explicit closing of the multicore cluster.
Thanks for your patience and trying!

Another thing that came up on a closer look: It seems like your downsampling options are beginning with space - there should be no spaces between the commas in your YAML file! Can you double check this?

Best,

Christoph

**Comment by tylerchen7** [comment]
Hey Christoph,

Hmmm... Fixed the downsampling spaces issue and attempted again with the same result. I've tried this version with no RAM limit listed in my parameters and it still fails; UMI hamming distance = 0 still works. It appears that it is somehow still attempting to run serialize after the multidplyr error is caught. 

> [tylerchen@n0112 zUMIs]$ bash zUMIs-master.sh -y TC011A.yaml
> 
> 
>  You provided these parameters:
>  YAML file:     TC011A.yaml
>  zUMIs directory:               /clusterfs/rosalind/groups/streetslab/tylerchen/zUMIs
>  STAR executable                STAR
>  samtools executable            samtools
>  pigz executable                pigz
>  Rscript executable             Rscript
>  RAM limit:   54
>  zUMIs version 2.2.2b
> 
> 
> Filtering...
> Mapping...
> Dec 25 14:55:27 ..... started STAR run
> Dec 25 14:55:28 ..... loading genome
> Dec 25 14:59:39 ..... processing annotations GTF
> Dec 25 15:00:03 ..... inserting junctions into the genome indices
> Dec 25 15:02:11 ..... started 1st pass mapping
> Dec 25 15:04:16 ..... finished 1st pass mapping
> Dec 25 15:04:17 ..... inserting junctions into the genome indices
> Dec 25 15:06:26 ..... started mapping
> Dec 25 15:09:30 ..... finished successfully
> Counting...
> [1] "2018-12-25 15:09:48 PST"
> [1] "3108854 reads were assigned to barcodes that do not correspond to intact cells."
> [1] "2.43e+08 Reads per chunk"
> [1] "Loading reference annotation from:"
> [1] "/clusterfs/rosalind/groups/streetslab/tylerchen/STAR-2.5.4b/reference/GRCh38/annotation/Homo_sapiens.GRCh38.91.gtf"
> [1] "Annotation loaded!"
> [1] "Assigning reads to features (ex)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 20                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid46755 ...       ||
> ||    Features : 1199851                                                      ||
> ||    Meta-features : 49614                                                   ||
> ||    Chromosomes/contigs : 47                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 47360876                                                  ||
> ||    Successfully assigned reads : 28718758 (60.6%)                          ||
> ||    Running time : 4.70 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [1] "Assigning reads to features (in)"
> 
>         ==========     _____ _    _ ____  _____  ______          _____
>         =====         / ____| |  | |  _ \|  __ \|  ____|   /\   |  __ \
>           =====      | (___ | |  | | |_) | |__) | |__     /  \  | |  | |
>             ====      \___ \| |  | |  _ <|  _  /|  __|   / /\ \ | |  | |
>               ====    ____) | |__| | |_) | | \ \| |____ / ____ \| |__| |
>         ==========   |_____/ \____/|____/|_|  \_\______/_/    \_\_____/
>        Rsubread 1.28.1
> 
> //========================== featureCounts setting ===========================\\
> ||                                                                            ||
> ||             Input files : 1 BAM file                                       ||
> ||                           S /clusterfs/rosalind/groups/streetslab/tyle ... ||
> ||                                                                            ||
> ||      Dir for temp files : .                                                ||
> ||                 Threads : 20                                               ||
> ||                   Level : meta-feature level                               ||
> ||              Paired-end : yes                                              ||
> ||         Strand specific : no                                               ||
> ||      Multimapping reads : primary only                                     ||
> || Multi-overlapping reads : not counted                                      ||
> ||   Min overlapping bases : 1                                                ||
> ||                                                                            ||
> ||          Chimeric reads : not counted                                      ||
> ||        Both ends mapped : not required                                     ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> //================================= Running ==================================\\
> ||                                                                            ||
> || Load annotation file ./.Rsubread_UserProvidedAnnotation_pid46755 ...       ||
> ||    Features : 275949                                                       ||
> ||    Meta-features : 28257                                                   ||
> ||    Chromosomes/contigs : 36                                                ||
> ||                                                                            ||
> || Process BAM file /clusterfs/rosalind/groups/streetslab/tylerchen/out/T ... ||
> ||    Single-end reads are included.                                          ||
> ||    Assign reads to features...                                             ||
> ||    Total reads : 47360876                                                  ||
> ||    Successfully assigned reads : 10071521 (21.3%)                          ||
> ||    Running time : 3.97 minutes                                             ||
> ||                                                                            ||
> ||                         Read assignment finished.                          ||
> ||                                                                            ||
> \\===================== http://subread.sourceforge.net/ ======================//
> 
> [bam_sort_core] merging from 10 files and 10 in-memory blocks...
> [bam_sort_core] merging from 10 files and 10 in-memory blocks...
> [1] "Here are the detected subsampling options:"
>  [1] "2000000" "1500000" "1000000" "900000"  "800000"  "700000"  "600000"
>  [8] "500000"  "400000"  "300000"  "200000"  "100000"  "50000"   "40000"
> [15] "30000"   "20000"   "10000"   "7500"    "5000"    "2500"    "1000"
> [1] "Working on barcode chunk 1 out of 1"
> [1] "Processing 7 barcodes in this chunk..."
> Initialising 20 core cluster.
> Error in serialize(data, node$con) : ignoring SIGPIPE signal
> In addition: Warning message:
> group_indices_.grouped_df ignores extra arguments
> [1] "Caught an error during multidplyr, trying linearly..."
> Error in serialize(data, node$con) : error writing to connection
> Calls: collectCounts ... postNode -> sendData -> sendData.SOCKnode -> serialize
> Execution halted
> Descriptive statistics...
> [1] "I am loading useful packages for plotting..."
> [1] "2018-12-25 15:37:14 PST"
> Error in gzfile(file, "rb") : cannot open the connection
> Calls: readRDS -> gzfile
> In addition: Warning message:
> In gzfile(file, "rb") :
>   cannot open compressed file '/clusterfs/rosalind/groups/streetslab/tylerchen/out/TC011A/zUMIs_output/expression/TC011A.dgecounts.rds', probable reason 'No such file or directory'
> Execution halted

**Comment by cziegenhain** [comment]
Hey,

Thanks for the checks and information.
The Inf vs some integer in the verbose is expected when setting a RAM limit.

For further troubleshooting, I think it would be easiest if you could share some of your data and I will see what's going on. Maybe if you can send a million reads & your YAML via [mail](https://github.com/sdparekh/zUMIs/blob/master/zUMIs-master.sh#L5) ?

Hope we get to this issue soon.

**Comment by tylerchen7** [comment]
Apologies for the delay; been doing a bit of debugging on my own and was wondering, how many calls do you expect to be made to umiCollapseHam over the course of the run?

**Comment by cziegenhain** [comment]
Hi,

that function should start up at least 4 times (exon & exon+intron quantification for each all reads and downsampling)

**Comment by tbeaux18** [comment]
I am unsure if I should begin a new issue, but I am facing the same issue currently when collapsing UMIs with a hamming distance > 0. My data is very low throughput with only 16 cells. I also am threading at 16 cores, but that is to speed up the STAR alignment since I generally start this pipeline from the beginning rather than counting. 

`/usr/local/bin/zUMIs-master.sh: line 221: 21162 Killed                  $Rexc $zumisdir/zUMIs-dge2.R $yaml
Sat Apr  6 19:41:05 CDT 2019
Descriptive statistics...
[1] "I am loading useful packages for plotting..."
[1] "2019-04-06 19:41:10 CDT"
Error in gzfile(file, "rb") : cannot open the connection
Calls: readRDS -> gzfile
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '[omitted]/zcb_trial.dgecounts.rds', probable reason 'No such file or directory'
Execution halted`

I am re-running the counting with umi collapsing ham dist: 0 just to make sure that that is the problem. But just to bump this to say that this multi-threading + ham dist: >0 is still breaking.

**Comment by cziegenhain** [comment]
Hi Tim,

My gut feeling says that this is due to the low throughput data and trying to spread the work over different worker cores, but I could be wrong. 
We have run quite some data in our lab (usually with ~100-200 cells) and the hamming distance collapse seems to work fine.

I changed the function to strictly linear processing for you and attaching the code here. Please replace your UMIstuffFUN.R with the attached one and try!

Sorry that we have no more conclusive solution so far...

best,
Christoph
[UMIstuffFUN_trial.R.gz](https://github.com/sdparekh/zUMIs/files/3085232/UMIstuffFUN_trial.R.gz)

**Comment by tbeaux18** [comment]
Hey Chris!

I ran the pipeline through with the single thread counting script and it appears to have worked well. Thanks very much for the script. Just for clarity so I can make my pipeline more general, would you say that "high throughput" for cells to work with the multi-threading by ~100 cells as you mentioned above?

**Comment by cziegenhain** [comment]
Hey,

Thats excellent news, happy to hear it ran!
For the question of when the multi-threading (we use multidplyr for this step) works: The number of cells available vs the number of cores given was only a hypothesis from me as I have seen it work in our lab! 
I will make this more robust by automatically falling to single-threaded processing in the code, of course subject to change as soon as we know more in detail what exactly are the conditions that cause the failures.

Thanks for testing & reporting!

**Comment by cziegenhain** [comment]
Hi @tbeaux18 & @tylerchen7 ,

I recoded the call to hamming distance filtering.
It now uses a completely different parallelization strategy and should thus get rid of these weird serialization errors!
Please make sure you have the `parallel` package installed.
Would be great to hear feedback if it now runs directly with datasets that were problematic before.

Thanks a lot for your patience,
Christoph
