### ISSUE TITLE
Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by yxiao832** [sdparekh/zUMIs#96]
Dear zUMI, 

I can run the example data without problem with zUMI. Then I used my a small subset of my real fastq data. I used fastq_pair to pair my read1 and read2 and took a small subset of the real data to run zUMI. 
The error looks like this: 

Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed
Calls: cellBC ... .FindBCcut -> <Anonymous> -> eval -> eval -> mclustBIC
Execution halted
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/Splitseq_zUMI_test12212018kept_barcodes.txt' does not exist; getwd()=='/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test'. Include correct full path, or one or more spaces to consider the input a system command.
Execution halted

Thank you!
Yang

**Comment by yxiao832** [comment]
Just adding more info to the above thread  
the output is like this 

 You provided these parameters:
 YAML file:	/home/yxiao832/softwares/Splitseq_zUMI_test12212018.yaml
 zUMIs directory:		/home/yxiao832/softwares/zUMIs
 STAR executable		STAR
 samtools executable		samtools
 pigz executable		pigz
 Rscript executable		Rscript
 RAM limit:   0
 zUMIs version 2.2.1 


Filtering...
Mapping...
Dec 21 13:51:18 ..... started STAR run
Dec 21 13:51:18 ..... loading genome
Terminated

**Comment by cziegenhain** [comment]
Hey Yang,

Thanks for posting the second piece of information! The more messages we see the better we can help troubleshoot.

I am not really familiar with fastq_pair so not sure what you did in that step but assume that the output is clean & properly paired fastq files.
Anyway, it seems like the STAR mapping crashed during the loading of the genome.

Could you please make sure that you use a correctly created STAR index and have enough RAM available for the loading?
Maybe you can look into / post the STAR log that should have been created in the run folder to nail this issue down!

Best,
Christoph

**Comment by yxiao832** [comment]
Hi Christoph, 
Thanks for your reply!
This is a split-seq run.  I created several STAR indexes with or without GTF plus with specifying overhang 65 or without overhang. 

This is my yaml file. 

project: Splitseq_zUMI_test12212018
sequence_files:
  file1:
    name: /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/SplitseqWT_R1_test.fastq.paired.fq.gz
    base_definition: cDNA(1-66)
  file2:
    name: /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/SplitseqWT_R2_test.fastq.paired.fq.gz
    base_definition:
    - BC(11-18,49-56,87-94)
    - UMI(1-10)
reference:
  STAR_index: /project/lazarlab/chunjie/AlignerIndex2/mm10.66/
  GTF_file: /project/lazarlab/chunjie/ReferenceGenome2/mm10/Mus_musculus.GRCm38.94.gtf
  additional_STAR_params: ''
  additional_files: ~
out_dir: /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test
num_threads: 8
mem_limit: 0
filter_cutoffs:
  BC_filter:
    num_bases: 1
    phred: 20
  UMI_filter:
    num_bases: 1
    phred: 20
barcodes:
  barcode_num: ~
  barcode_file: ~
  BarcodeBinning: 0
  nReadsperCell: 100
counting_opts:
  introns: yes
  downsampling: '0'
  strand: 0
  Ham_Dist: 0
  velocyto: no
  primaryHit: yes
  twoPass: yes
make_stats: yes
which_Stage: Filtering

Anyway, I will look into the STAR index. Thanks a lot!
Best,
Yang

**Comment by cziegenhain** [comment]
Hey Yang,

Okay I think your YAML looks good.
The STAR index should be one that was generated without GTF and without specific overhang.
Can you add the STAR log when you run zUMIs with that STAR index? It should be called `Splitseq_zUMI_test12212018.filtered.tagged.Log.out` in your case!

**Comment by yxiao832** [comment]
Hi Christoph,
Thanks again!

I redid the STAR index again without GTF and without specific overhang. 

Here is the STAR log info: 
###### All USER parameters from Command Line:
readFilesCommand              samtools   view   -@2        ~RE-DEFINED
outSAMmultNmax                1     ~RE-DEFINED
outFilterMultimapNmax         50     ~RE-DEFINED
outSAMunmapped                Within        ~RE-DEFINED
outSAMtype                    BAM   Unsorted        ~RE-DEFINED
genomeDir                     /home/yxiao832/index/STAR_index/mm10_STAR_index12222018     ~RE-DEFINED
sjdbGTFfile                   /project/lazarlab/chunjie/ReferenceGenome2/mm10/Mus_musculus.GRCm38.94.gtf     ~RE-DEFINED
runThreadN                    8     ~RE-DEFINED
readFilesIn                   /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam        ~RE-DEFINED
outFileNamePrefix             /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/Splitseq_zUMI_test12212018.filtered.tagged.     ~RE-DEFINED
sjdbOverhang                  65     ~RE-DEFINED
readFilesType                 SAM   SE        ~RE-DEFINED
twopassMode                   Basic     ~RE-DEFINED
##### Finished reading parameters from all sources

##### Final user re-defined parameters-----------------:
runThreadN                        8
genomeDir                         /home/yxiao832/index/STAR_index/mm10_STAR_index12222018
readFilesType                     SAM   SE   
readFilesIn                       /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam   
readFilesCommand                  samtools   view   -@2   
outFileNamePrefix                 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/Splitseq_zUMI_test12212018.filtered.tagged.
outSAMtype                        BAM   Unsorted   
outSAMunmapped                    Within   
outSAMmultNmax                    1
outFilterMultimapNmax             50
sjdbGTFfile                       /project/lazarlab/chunjie/ReferenceGenome2/mm10/Mus_musculus.GRCm38.94.gtf
sjdbOverhang                      65
twopassMode                       Basic

-------------------------------
##### Final effective command line:
STAR   --runThreadN 8   --genomeDir /home/yxiao832/index/STAR_index/mm10_STAR_index12222018   --readFilesType SAM   SE      --readFilesIn /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam      --readFilesCommand samtools   view   -@2      --outFileNamePrefix /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/Splitseq_zUMI_test12212018.filtered.tagged.   --outSAMtype BAM   Unsorted      --outSAMunmapped Within      --outSAMmultNmax 1   --outFilterMultimapNmax 50   --sjdbGTFfile /project/lazarlab/chunjie/ReferenceGenome2/mm10/Mus_musculus.GRCm38.94.gtf   --sjdbOverhang 65   --twopassMode Basic

##### Final parameters after user input--------------------------------:
versionSTAR                       20201
versionGenome                     20101   20200   
parametersFiles                   -   
sysShell                          -
runMode                           alignReads
runThreadN                        8
runDirPerm                        User_RWX
runRNGseed                        777
genomeDir                         /home/yxiao832/index/STAR_index/mm10_STAR_index12222018
genomeLoad                        NoSharedMemory
genomeFastaFiles                  -   
genomeChainFiles                  -   
genomeSAindexNbases               14
genomeChrBinNbits                 18
genomeSAsparseD                   1
genomeSuffixLengthMax             18446744073709551615
genomeFileSizes                   0   
genomeConsensusFile               -
readFilesType                     SAM   SE   
readFilesIn                       /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam   
readFilesPrefix                   -
readFilesCommand                  samtools   view   -@2   
readMatesLengthsIn                NotEqual
readMapNumber                     18446744073709551615
readNameSeparator                 /   
inputBAMfile                      -
bamRemoveDuplicatesType           -
bamRemoveDuplicatesMate2basesN    0
limitGenomeGenerateRAM            31000000000
limitIObufferSize                 150000000
limitOutSAMoneReadBytes           100000
limitOutSJcollapsed               1000000
limitOutSJoneRead                 1000
limitBAMsortRAM                   0
limitSjdbInsertNsj                1000000
outFileNamePrefix                 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/Splitseq_zUMI_test12212018.filtered.tagged.
outTmpDir                         -
outTmpKeep                        None
outStd                            Log
outReadsUnmapped                  None
outQSconversionAdd                0
outMultimapperOrder               Old_2.4
outSAMtype                        BAM   Unsorted   
outSAMmode                        Full
outSAMstrandField                 None
outSAMattributes                  Standard   
outSAMunmapped                    Within   
outSAMorder                       Paired
outSAMprimaryFlag                 OneBestScore
outSAMreadID                      Standard
outSAMmapqUnique                  255
outSAMflagOR                      0
outSAMflagAND                     65535
outSAMattrRGline                  -   
outSAMheaderHD                    -   
outSAMheaderPG                    -   
outSAMheaderCommentFile           -
outBAMcompression                 1
outBAMsortingThreadN              0
outSAMfilter                      None   
outSAMmultNmax                    1
outSAMattrIHstart                 1
outSJfilterReads                  All
outSJfilterCountUniqueMin         3   1   1   1   
outSJfilterCountTotalMin          3   1   1   1   
outSJfilterOverhangMin            30   12   12   12   
outSJfilterDistToOtherSJmin       10   0   5   10   
outSJfilterIntronMaxVsReadN       50000   100000   200000   
outWigType                        None   
outWigStrand                      Stranded   
outWigReferencesPrefix            -
outWigNorm                        RPM   
outFilterType                     Normal
outFilterMultimapNmax             50
outFilterMultimapScoreRange       1
outFilterScoreMin                 0
outFilterScoreMinOverLread        0.66
outFilterMatchNmin                0
outFilterMatchNminOverLread       0.66
outFilterMismatchNmax             10
outFilterMismatchNoverLmax        0.3
outFilterMismatchNoverReadLmax    1
outFilterIntronMotifs             None
outFilterIntronStrands            RemoveInconsistentStrands
clip5pNbases                      0   
clip3pNbases                      0   
clip3pAfterAdapterNbases          0   
clip3pAdapterSeq                  -   
clip3pAdapterMMp                  0.1   
winBinNbits                       16
winAnchorDistNbins                9
winFlankNbins                     4
winAnchorMultimapNmax             50
winReadCoverageRelativeMin        0.5
winReadCoverageBasesMin           0
scoreGap                          0
scoreGapNoncan                    -8
scoreGapGCAG                      -4
scoreGapATAC                      -8
scoreStitchSJshift                1
scoreGenomicLengthLog2scale       -0.25
scoreDelBase                      -2
scoreDelOpen                      -2
scoreInsOpen                      -2
scoreInsBase                      -2
seedSearchLmax                    0
seedSearchStartLmax               50
seedSearchStartLmaxOverLread      1
seedPerReadNmax                   1000
seedPerWindowNmax                 50
seedNoneLociPerWindow             10
seedMultimapNmax                  10000
seedSplitMin                      12
alignIntronMin                    21
alignIntronMax                    0
alignMatesGapMax                  0
alignTranscriptsPerReadNmax       10000
alignSJoverhangMin                5
alignSJDBoverhangMin              3
alignSJstitchMismatchNmax         0   -1   0   0   
alignSplicedMateMapLmin           0
alignSplicedMateMapLminOverLmate    0.66
alignWindowsPerReadNmax           10000
alignTranscriptsPerWindowNmax     100
alignEndsType                     Local
alignSoftClipAtReferenceEnds      Yes
alignEndsProtrude                 0   ConcordantPair   
chimSegmentMin                    0
chimScoreMin                      0
chimScoreDropMax                  20
chimScoreSeparation               10
chimScoreJunctionNonGTAG          -1
chimMainSegmentMultNmax           10
chimJunctionOverhangMin           20
chimOutType                       SeparateSAMold   
chimFilter                        banGenomicN   
chimSegmentReadGapMax             0
sjdbFileChrStartEnd               -   
sjdbGTFfile                       /project/lazarlab/chunjie/ReferenceGenome2/mm10/Mus_musculus.GRCm38.94.gtf
sjdbGTFchrPrefix                  -
sjdbGTFfeatureExon                exon
sjdbGTFtagExonParentTranscript    transcript_id
sjdbGTFtagExonParentGene          gene_id
sjdbOverhang                      65
sjdbScore                         2
sjdbInsertSave                    Basic
quantMode                         -   
quantTranscriptomeBAMcompression    1
quantTranscriptomeBan             IndelSoftclipSingleend
twopass1readsN                    18446744073709551615
twopassMode                       Basic
----------------------------------------


   Input read files for mate 1, from input string /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam,/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 12508 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 16926 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 18872 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 18788 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 18884 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 18147 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 17467 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam
-rw-rw-r-- 1 yxiao832 yxiao832 18561 Dec 23 15:05 /home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam

   readsCommandsFile:
exec > "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/Splitseq_zUMI_test12212018.filtered.tagged._STARtmp/tmp.fifo.read1"
echo FILE 0
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.aa.filtered.tagged.bam"
echo FILE 1
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ab.filtered.tagged.bam"
echo FILE 2
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ac.filtered.tagged.bam"
echo FILE 3
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ad.filtered.tagged.bam"
echo FILE 4
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ae.filtered.tagged.bam"
echo FILE 5
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.af.filtered.tagged.bam"
echo FILE 6
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ag.filtered.tagged.bam"
echo FILE 7
samtools   view   -@2      "/home/yxiao832/12152018SplitseqWT_new/zUMI_split_test/zUMIs_output/.tmpMerge//Splitseq_zUMI_test12212018.ah.filtered.tagged.bam"

Finished loading and checking parameters
Reading genome generation parameters:
versionGenome                 20201        ~RE-DEFINED
genomeFastaFiles              /project/lazarlab/chunjie/ReferenceGenome2/mm10/GRCm38_mm10.normalChr.fa        ~RE-DEFINED
genomeSAindexNbases           14     ~RE-DEFINED
genomeChrBinNbits             18     ~RE-DEFINED
genomeSAsparseD               1     ~RE-DEFINED
sjdbOverhang                  0     ~RE-DEFINED
sjdbFileChrStartEnd           -        ~RE-DEFINED
sjdbGTFfile                   -     ~RE-DEFINED
sjdbGTFchrPrefix              -     ~RE-DEFINED
sjdbGTFfeatureExon            exon     ~RE-DEFINED
sjdbGTFtagExonParentTranscripttranscript_id     ~RE-DEFINED
sjdbGTFtagExonParentGene      gene_id     ~RE-DEFINED
sjdbInsertSave                Basic     ~RE-DEFINED
genomeFileSizes               2728656896   21842186276        ~RE-DEFINED
Genome version is compatible with current STAR version
Number of real (reference) chromosomes= 22
1	10	130694993	0
2	11	122082543	130809856
3	12	120129022	252968960
4	13	120421639	373293056
5	14	124902244	493879296
6	15	104043685	618921984
7	16	98207768	722993152
8	17	94987271	821297152
9	18	90702639	916455424
10	19	61431566	1007419392
11	1	195471971	1069023232
12	2	182113224	1264582656
13	3	160039680	1446772736
14	4	156508116	1606942720
15	5	151834684	1763704832
16	6	149736546	1915748352
17	7	145441459	2065694720
18	8	129401213	2211184640
19	9	124595110	2340683776
20	MT	16299	2465464320
21	X	171031299	2465726464
22	Y	91744698	2636906496
Started loading the genome: Sun Dec 23 15:06:00 2018

Genome: size given as a parameter = 2728656896
SA: size given as a parameter = 21842186276
/SAindex: size given as a parameter = 1
Read from SAindex: genomeSAindexNbases=14  nSAi=357913940
nGenome=2728656896;  nSAbyte=21842186276
GstrandBit=32   SA number of indices=5295075460
Shared memory is not used for genomes. Allocated a private copy of the genome.
Genome file size: 2728656896 bytes; state: good=1 eof=0 fail=0 bad=0
Loading Genome ... done! state: good=1 eof=0 fail=0 bad=0; loaded 2728656896 bytes
SA file size: 21842186276 bytes; state: good=1 eof=0 fail=0 bad=0



Yang

**Comment by cziegenhain** [comment]
Hey Yang,

It seems like your STAR breaks when loading the suffix array (SA) file of your reference index.
I would assume that this means you either run out of RAM or more likely your reference index is defective.
Did you check the log of the index creation or did it complete successfully?

**Comment by yxiao832** [comment]
Hi Christoph, 

I did check the log and it completed successfully. I attached it here. 
[generatingSTARindex_NOGTF_splitseq.txt](https://github.com/sdparekh/zUMIs/files/2716156/generatingSTARindex_NOGTF_splitseq.txt)

I did some tests for my files.  Since I was able to run the example files, I used your example fastq and my own index, which works well. I also used my own fastq and your example index and this gave me error. And my own fastq and my own index showed the same error. 
Based on the above result, it looks like something with my fastq preparation? I attached my subset fastq file here. 
[SplitseqWT_R1_test.fastq.paired.fq.gz](https://github.com/sdparekh/zUMIs/files/2716158/SplitseqWT_R1_test.fastq.paired.fq.gz)
[SplitseqWT_R2_test.fastq.paired.fq.gz](https://github.com/sdparekh/zUMIs/files/2716159/SplitseqWT_R2_test.fastq.paired.fq.gz)


Fastq was created by illumina basespace, and I used fastqpair to reorder fastq file according to the instruction of issue #40  https://github.com/sdparekh/zUMIs/issues/40   since the previous run had the error of "fastq files are not in the same order". 


Again the error is like this 

Error in if (G[1] == 1) { : missing value where TRUE/FALSE needed
Calls: cellBC ... .FindBCcut -> <Anonymous> -> eval -> eval -> mclustBIC
Execution halted
Error in data.table::fread(paste0(opt$out_dir, "/zUMIs_output/", opt$project,  : 
  File '/home/yxiao832/zUMItest/zUMIs_output/zUMI_run_test_fq12272018kept_barcodes.txt' does not exist; getwd()=='/home/yxiao832/zUMItest'. Include correct full path, or one or more spaces to consider the input a system command.
Execution halted

I also attached my output files here and STAR logs. 

[Splitseq_zUMI_test12262018.filtered.tagged.Log.out.txt](https://github.com/sdparekh/zUMIs/files/2716157/Splitseq_zUMI_test12262018.filtered.tagged.Log.out.txt)

<img width="793" alt="screen shot 2018-12-29 at 3 31 47 pm" src="https://user-images.githubusercontent.com/46054827/50535125-7b5eae00-0b81-11e9-8d99-f14397b18717.png">

Best and happy holidays!
Yang

**Comment by yxiao832** [comment]
Hi Christoph, 

I tried my complete fastq files without trimming read2 to 94 bases first. Interestingly, zUMI is able to give me some results. So, maybe subsetting data cause some issues in my previous run.

Here below is the output file and error files. I am not sure what the errors mean. 

[zUMI_12312018.o.txt](https://github.com/sdparekh/zUMIs/files/2719359/zUMI_12312018.o.txt)
[zUMI_12312018.e.txt](https://github.com/sdparekh/zUMIs/files/2719360/zUMI_12312018.e.txt)


The final output is a bit weird too. I think my run shouldn't give me this few number of cells and the feature file showed huge amount of unused BC.  I wonder whether changing the BC collapsing strategy would work? 

[zUMI_run_12292018.detected_cells.pdf](https://github.com/sdparekh/zUMIs/files/2719362/zUMI_run_12292018.detected_cells.pdf)
[zUMI_run_12292018.features.pdf](https://github.com/sdparekh/zUMIs/files/2719363/zUMI_run_12292018.features.pdf)

I am trying the fastq file with read2 trimming to 94bp. Will update with you later. 

Thanks a lot! I really appreciate your help!
Yang

**Comment by cziegenhain** [comment]
Hey Yang,

Don't mind those warnings, the plots for statistics are just abit out of the expectation!
I think your zUMIs run worked nicely this time around!

For the number of detected barcodes:
What's your expected number? It could be that only the doublets were selected here by the automatic algorithm. I would recommend to rerun the counting step with the number of cells you expect. Looking at the distribution, did you plan on 5000 - 10000 cells?

Note: for zUMIs it should make no difference between full fastq files or trimmed to exactly 94 bases as long as each read has the barcode bases covered that you are trying to extract.

**Comment by yxiao832** [comment]
Hi Christoph,

Thank you so much for walking me through zUMI step by step and got this work!

Indeed, my expected cell number is 5000 - 10000 cells. 

I looked up zUMI old thread and found the info of rerunning counting steps. I'd like to double check with you about the command line: 

bash DIRECTORY TO zUMIs-master.sh -y DIRECTORY TO yaml file  -w (expected cell number)

or I should also add some parameters in the yaml file? 

Thanks again!
Yang

**Comment by yxiao832** [comment]
I have another following question is that how the blue line is generated in the detected cell PDF file. 
My understanding is that the blue line is based on the setting of nReadsperCell, which I set at 100, but I still see the line was drawn around log10 3-4. Probably I didn't understand this correctly or some other parameters are also taken into consideration?  
Thanks a lot!
Yang

**Comment by cziegenhain** [comment]
Hey Yang,

The -w flag does not exist. Familiarize yourself with the options in our wiki: https://github.com/sdparekh/zUMIs/wiki/Usage
All barcode related things are controlled in the YAML file. `which_Stage: Counting` sounds good, so you dont need to repeat the filtering and mapping steps.

For the cell detection: The nReadsperCell just discards all barcodes with less than n, followed by the detection of relevant cell barcods. you should read up on the algorithm in our paper.

Best,
Christoph
