### ISSUE TITLE
help the sequence type ?

### ISSUE THREAD

**Issue by haiyun0799** [sdparekh/zUMIs#97]
I try to analysis the data set from the paper "Single-Cell RNA-Seq Analysis Maps Development of Human Germline Cells and Gonadal Niche Interactions".
I do not know how can I use zUMIs to analysis these datasets.
It is base on Smart-seq2 but with cell barcode and UMI.

the following is how the data produce:

Single-cell RNA-Seq Library Preparation and Sequencing
A modified Smart-seq2 protocol was applied for single-cell RNA-seq (Kannanayakal and Eberwine, 2005, Picelli et al., 2013, Picelli et al., 2014, Spaethling et al., 2016). Briefly, after MACS and FACS purification, a single FGC or gonadal somatic cell was placed into the lysis buffer by mouth pipette. The reverse transcription reaction was performed with 25 nt oligo(dT) primer anchored with an 8 nt cell-specific barcode (Table S2) and 8 nt unique molecular identifiers (UMIs) (Hashimshony et al., 2012, Islam et al., 2012, Islam et al., 2014, Klein et al., 2015). After the first-strand synthesis, the second-strand cDNAs were synthesized, and the cDNAs were amplified by 17 cycles of PCR. The amplified cDNAs of the single cells were then pooled together for the following steps. Biotinylated pre-indexed primers were used to further amplify the PCR product by an additional 4 cycles of PCR to introduce biotin tags to the 3′ ends of the amplified cDNAs. Approximately 300 ng cDNA was sheared to approximately 300 bp by Covaris S2, and the 3′ terminal of the cDNA was captured by Dynabeads® MyOne Streptavidin C1 beads (Thermo Fisher). The RNA-seq library was constructed using a Kapa Hyper Prep Kit (Kapa Biosystems) and subjected to 150 bp paired-end sequencing on an Illumina HiSeq 4000 platform (sequenced by Novogene).

Processing of Single-cell RNA-seq Data
Raw reads were first separated by specific cell barcode information attached in read 2 of the pair-ended reads. UMI information was aligned to the corresponding read 1, which was then trimmed to remove the template switch oligo (TSO) sequence and polyA tail sequence. Subsequently, we also removed reads with adaptor contaminants and low-quality bases (N > 10%). Next, the clean reads were aligned to the hg19 human transcriptome (UCSC) using TopHat (version 2.0.12) (Trapnell et al., 2009).

**Comment by cziegenhain** [comment]
Hi,

From the description you posted I don't know where exactly barcode and UMI is encoded in the reads.
You need to find out the precise base positions of BC and UMI in the read pairs and then list them accordingly into the YAML config file for zUMIs.

Best,
Christoph
