### ISSUE TITLE
Library barcodes?

### ISSUE THREAD

**Issue by SHR456** [sdparekh/zUMIs#99]
Hi,

Not sure if I missed it in the wiki, but was wondering how zUMIs deals with library barcodes? I have indrops v3 data with several libraries pooled and sequenced in the same run. Thanks.

**Comment by cziegenhain** [comment]
Hi,

Yes you can input your pooled libraries directly into zUMIs. 

Just add the library barcode in the fastq definition as such:
https://github.com/sdparekh/zUMIs/wiki/Protocol-specific-setup#indrops

**Comment by SHR456** [comment]
Great, thanks.
